import { l } from '../data.js'
import { buildExam } from './exam-factory.js'

// Docker course — bilingual (English / Bangla), deeper build:
// 8 modules, 38 topics, command tables, hands-on code examples, and guided labs.

export const dockerModules = [
  { id: 'dk-foundations', number: '01', title: l('Docker foundations', 'ডকার ভিত্তি'), description: l('Containers vs VMs, images vs containers, and how the Docker engine fits together.', 'কন্টেইনার বনাম VM, ইমেজ বনাম কন্টেইনার, এবং ডকার ইঞ্জিন কীভাবে কাজ করে।'), color: '#0284c7' },
  { id: 'dk-images', number: '02', title: l('Working with images', 'ইমেজ নিয়ে কাজ'), description: l('Pull and run images, understand layers, tags, and registries like Docker Hub.', 'ইমেজ পুল ও রান করুন, লেয়ার, ট্যাগ ও Docker Hub-এর মতো রেজিস্ট্রি বুঝুন।'), color: '#0f9f78' },
  { id: 'dk-dockerfile', number: '03', title: l('Building with Dockerfiles', 'Dockerfile দিয়ে বিল্ড'), description: l('Write Dockerfiles, use the build cache, multi-stage builds, and image best practices.', 'Dockerfile লিখুন, বিল্ড ক্যাশ, মাল্টি-স্টেজ বিল্ড ও ইমেজ বেস্ট প্র্যাকটিস ব্যবহার করুন।'), color: '#6c5ce7' },
  { id: 'dk-containers', number: '04', title: l('Running containers', 'কন্টেইনার চালানো'), description: l('Run flags, the container lifecycle, exec and logs, environment, restarts, and limits.', 'রান ফ্ল্যাগ, কন্টেইনার লাইফসাইকেল, exec ও logs, এনভায়রনমেন্ট, রিস্টার্ট ও লিমিট।'), color: '#d97706' },
  { id: 'dk-data', number: '05', title: l('Data & storage', 'ডেটা ও স্টোরেজ'), description: l('Persist data with volumes and bind mounts, share it, and back it up.', 'ভলিউম ও বাইন্ড মাউন্ট দিয়ে ডেটা স্থায়ী করুন, শেয়ার ও ব্যাকআপ করুন।'), color: '#e34b87' },
  { id: 'dk-networking', number: '06', title: l('Networking', 'নেটওয়ার্কিং'), description: l('How containers talk: bridge networks, publishing ports, and service discovery.', 'কন্টেইনার কীভাবে কথা বলে: ব্রিজ নেটওয়ার্ক, পোর্ট পাবলিশ ও সার্ভিস ডিসকভারি।'), color: '#0891b2' },
  { id: 'dk-compose', number: '07', title: l('Docker Compose', 'ডকার কম্পোজ'), description: l('Define and run multi-container apps from a single compose file.', 'একটি compose ফাইল থেকে মাল্টি-কন্টেইনার অ্যাপ সংজ্ঞায়িত ও চালান।'), color: '#7c3aed' },
  { id: 'dk-production', number: '08', title: l('Production & operations', 'প্রোডাকশন ও অপারেশন'), description: l('Optimize and secure images, add healthchecks and logging, and ship through CI.', 'ইমেজ অপটিমাইজ ও নিরাপদ করুন, হেলথচেক ও লগিং যোগ করুন, ও CI দিয়ে শিপ করুন।'), color: '#188cbd' },
]

const rawTopics = [
  // ── Foundations ───────────────────────────────────────────────────────────
  ['dk-what', 'dk-foundations', 'What is Docker?', 'ডকার কী?', 'Beginner', 11, 'dk-layers',
    'Docker packages an application with everything it needs into a container that runs the same way anywhere.', 'ডকার একটি অ্যাপ্লিকেশনকে তার সব প্রয়োজনসহ একটি কন্টেইনারে প্যাকেজ করে, যা সর্বত্র একইভাবে চলে।',
    'A shipping container: the same sealed box loads onto any truck, ship, or crane without repacking.', 'একটি শিপিং কন্টেইনার: একই সিল করা বাক্স যেকোনো ট্রাক, জাহাজ বা ক্রেনে ওঠে, পুনরায় প্যাক ছাড়াই।',
    'Package your app and its dependencies into an image, then run that image as a container anywhere.', 'আপনার অ্যাপ ও নির্ভরতা একটি ইমেজে প্যাকেজ করুন, তারপর সেই ইমেজ যেকোনো জায়গায় কন্টেইনার হিসেবে চালান।',
    'Containers give consistent, portable environments, but they add a build step and a new layer of tooling to learn.', 'কন্টেইনার সামঞ্জস্যপূর্ণ, পোর্টেবল এনভায়রনমেন্ট দেয়, তবে একটি বিল্ড ধাপ ও শেখার নতুন টুলিং যোগ করে।',
    'Thinking a container is a lightweight VM; it shares the host kernel and is not a full machine.', 'কন্টেইনারকে হালকা VM ভাবা; এটি হোস্ট কার্নেল শেয়ার করে ও পূর্ণ মেশিন নয়।'],
  ['dk-vs-vm', 'dk-foundations', 'Containers vs virtual machines', 'কন্টেইনার বনাম ভার্চুয়াল মেশিন', 'Beginner', 12, 'dk-lifecycle',
    'A VM virtualizes whole hardware and runs its own OS; a container shares the host kernel and isolates just the process.', 'VM পুরো হার্ডওয়্যার ভার্চুয়ালাইজ করে ও নিজের OS চালায়; কন্টেইনার হোস্ট কার্নেল শেয়ার করে ও শুধু প্রসেস আলাদা করে।',
    'A VM is a whole separate house; a container is a locked room in a shared building—far lighter to add.', 'VM হলো একটি আলাদা পুরো বাড়ি; কন্টেইনার হলো একটি শেয়ার্ড ভবনের একটি তালাবদ্ধ ঘর—যোগ করা অনেক হালকা।',
    'Use containers for fast, dense, portable app packaging; use VMs when you need full OS isolation.', 'দ্রুত, ঘন, পোর্টেবল অ্যাপ প্যাকেজিংয়ে কন্টেইনার নিন; পূর্ণ OS আইসোলেশন দরকার হলে VM নিন।',
    'Containers start in seconds and use far less memory, but they share the kernel, so isolation is weaker than a VM.', 'কন্টেইনার সেকেন্ডে চালু হয় ও অনেক কম মেমরি নেয়, তবে কার্নেল শেয়ার করে বলে VM-এর চেয়ে আইসোলেশন দুর্বল।',
    'Assuming containers isolate as strongly as VMs; a kernel exploit can cross the container boundary.', 'কন্টেইনার VM-এর মতো শক্ত আইসোলেশন দেয় ধরে নেওয়া; একটি কার্নেল এক্সপ্লয়েট কন্টেইনার সীমানা পার করতে পারে।'],
  ['dk-images-containers', 'dk-foundations', 'Images vs containers', 'ইমেজ বনাম কন্টেইনার', 'Beginner', 11, 'dk-layers',
    'An image is a read-only template; a container is a running instance of that image with a writable layer on top.', 'ইমেজ হলো একটি রিড-অনলি টেমপ্লেট; কন্টেইনার হলো সেই ইমেজের একটি চলমান ইনস্ট্যান্স, ওপরে একটি লেখনযোগ্য লেয়ারসহ।',
    'An image is a class; a container is an object—one blueprint, many running instances.', 'ইমেজ হলো একটি ক্লাস; কন্টেইনার হলো একটি অবজেক্ট—এক ব্লুপ্রিন্ট, অনেক চলমান ইনস্ট্যান্স।',
    'Build or pull an image once, then run many containers from it; each container gets its own writable layer.', 'একবার ইমেজ বিল্ড বা পুল করুন, তারপর তা থেকে অনেক কন্টেইনার চালান; প্রতিটি কন্টেইনার নিজের লেখনযোগ্য লেয়ার পায়।',
    'The shared read-only image saves space across containers, but data written inside a container is lost when it is removed.', 'শেয়ার্ড রিড-অনলি ইমেজ কন্টেইনারজুড়ে জায়গা বাঁচায়, তবে কন্টেইনারের ভেতরে লেখা ডেটা রিমুভ করলে হারায়।',
    'Storing important data in a container’s writable layer instead of a volume, then losing it on removal.', 'গুরুত্বপূর্ণ ডেটা ভলিউমের বদলে কন্টেইনারের লেখনযোগ্য লেয়ারে রাখা, তারপর রিমুভে হারানো।'],
  ['dk-engine', 'dk-foundations', 'The Docker engine & CLI', 'ডকার ইঞ্জিন ও CLI', 'Beginner', 11, 'dk-build',
    'The Docker daemon builds and runs containers; the docker CLI sends it commands over an API.', 'ডকার ডেমন কন্টেইনার বিল্ড ও রান করে; docker CLI একটি API দিয়ে তাকে কমান্ড পাঠায়।',
    'A kitchen: you (the CLI) hand orders to the chef (the daemon) who actually cooks and plates the food.', 'একটি রান্নাঘর: আপনি (CLI) শেফকে (ডেমন) অর্ডার দেন, যিনি আসলে রাঁধেন ও পরিবেশন করেন।',
    'Run docker commands from the CLI; remember a daemon must be running to build, pull, or start anything.', 'CLI থেকে docker কমান্ড চালান; মনে রাখুন বিল্ড, পুল বা শুরু করতে একটি ডেমন চলমান থাকতে হবে।',
    'The client/daemon split lets you control remote engines, but it means the daemon runs with high privileges you must secure.', 'ক্লায়েন্ট/ডেমন বিভাজন রিমোট ইঞ্জিন নিয়ন্ত্রণ করতে দেয়, তবে ডেমন উঁচু সুবিধায় চলে যা আপনাকে নিরাপদ করতে হয়।',
    'Adding a user to the docker group without realizing it is effectively root-level access on the host.', 'একজন ব্যবহারকারীকে docker গ্রুপে যোগ করা, না বুঝে যে এটি কার্যত হোস্টে root-স্তরের অ্যাক্সেস।'],

  // ── Working with images ───────────────────────────────────────────────────
  ['dk-pull-run', 'dk-images', 'Pulling & running images', 'ইমেজ পুল ও রান', 'Beginner', 12, 'dk-build',
    'docker pull downloads an image from a registry; docker run creates and starts a container from it.', 'docker pull একটি রেজিস্ট্রি থেকে ইমেজ নামায়; docker run তা থেকে কন্টেইনার তৈরি ও চালু করে।',
    'pull is buying the ingredients; run is actually cooking a dish from them.', 'pull হলো উপকরণ কেনা; run হলো তা থেকে আসলে একটি ডিশ রাঁধা।',
    'Use docker run image, which pulls automatically if the image is missing; add -d to run it in the background.', 'docker run image ব্যবহার করুন, যা ইমেজ না থাকলে স্বয়ংক্রিয় পুল করে; ব্যাকগ্রাউন্ডে চালাতে -d যোগ করুন।',
    'run makes starting software one command, but each run creates a new container—old ones pile up unless removed.', 'run সফটওয়্যার চালানো এক কমান্ড করে, তবে প্রতিটি run নতুন কন্টেইনার বানায়—রিমুভ না করলে পুরনোগুলো জমে।',
    'Running many containers without cleanup, leaving stopped containers and images filling the disk.', 'পরিষ্কার ছাড়া অনেক কন্টেইনার চালানো, থামানো কন্টেইনার ও ইমেজ ডিস্ক ভরে ফেলা।'],
  ['dk-layers', 'dk-images', 'Image layers & the union filesystem', 'ইমেজ লেয়ার ও ইউনিয়ন ফাইলসিস্টেম', 'Intermediate', 14, 'dk-layers',
    'An image is a stack of read-only layers; each Dockerfile instruction adds one, and layers are cached and shared.', 'ইমেজ হলো রিড-অনলি লেয়ারের স্তূপ; প্রতিটি Dockerfile নির্দেশ একটি যোগ করে, এবং লেয়ার ক্যাশড ও শেয়ার্ড।',
    'Transparent sheets stacked into one picture—shared base sheets are reused across many images.', 'একটি ছবিতে স্তূপীকৃত স্বচ্ছ শিট—শেয়ার্ড বেস শিট অনেক ইমেজে পুনঃব্যবহৃত হয়।',
    'Order Dockerfile steps so rarely-changing layers come first, letting the cache reuse them on every rebuild.', 'Dockerfile ধাপ এমনভাবে সাজান যাতে কম-বদলানো লেয়ার আগে আসে, প্রতিটি রিবিল্ডে ক্যাশ পুনঃব্যবহার করে।',
    'Shared layers save huge amounts of space and build time, but a change low in the stack invalidates everything above it.', 'শেয়ার্ড লেয়ার প্রচুর জায়গা ও বিল্ড টাইম বাঁচায়, তবে স্তূপের নিচে একটি পরিবর্তন তার ওপরের সব বাতিল করে।',
    'Putting frequently-changing steps early in the Dockerfile, busting the cache for every layer after them.', 'ঘন-বদলানো ধাপ Dockerfile-এর শুরুতে রাখা, তার পরের প্রতিটি লেয়ারের ক্যাশ নষ্ট করা।'],
  ['dk-tags', 'dk-images', 'Image tags & versions', 'ইমেজ ট্যাগ ও ভার্সন', 'Beginner', 11, 'dk-build',
    'A tag names a specific version of an image (nginx:1.25); the default latest is just a movable label, not "newest".', 'একটি ট্যাগ একটি ইমেজের নির্দিষ্ট সংস্করণ নাম দেয় (nginx:1.25); ডিফল্ট latest শুধু একটি সরানো-যোগ্য লেবেল, "সর্বশেষ" নয়।',
    'Version stickers on jars: "v1.25" is exact; "latest" is whichever jar someone last put the sticker on.', 'জারে ভার্সন স্টিকার: "v1.25" নির্দিষ্ট; "latest" হলো যে জারে কেউ শেষবার স্টিকার লাগিয়েছে।',
    'Pin explicit tags (image:1.25) in production so builds are reproducible instead of silently changing.', 'প্রোডাকশনে স্পষ্ট ট্যাগ (image:1.25) পিন করুন যাতে বিল্ড নীরবে না বদলে পুনরুৎপাদনযোগ্য হয়।',
    'Tags make versions explicit and repeatable, but relying on latest means your image can change under you without warning.', 'ট্যাগ ভার্সন স্পষ্ট ও পুনরাবৃত্তিযোগ্য করে, তবে latest-এ নির্ভর করলে ইমেজ সতর্কতা ছাড়াই বদলাতে পারে।',
    'Deploying image:latest and getting a different, untested version on the next pull.', 'image:latest ডিপ্লয় করে পরের পুলে একটি ভিন্ন, অপরীক্ষিত সংস্করণ পাওয়া।'],
  ['dk-registry', 'dk-images', 'Registries & Docker Hub', 'রেজিস্ট্রি ও Docker Hub', 'Beginner', 12, 'dk-registry',
    'A registry stores and distributes images; docker push uploads yours and docker pull downloads others.', 'রেজিস্ট্রি ইমেজ সংরক্ষণ ও বিতরণ করে; docker push আপনারটি তোলে ও docker pull অন্যেরটি নামায়।',
    'An app store for images: publish yours for others to install, and install theirs with one command.', 'ইমেজের জন্য একটি অ্যাপ স্টোর: অন্যদের ইনস্টলের জন্য আপনারটি প্রকাশ করুন, ও এক কমান্ডে তাদেরটি ইনস্টল করুন।',
    'Tag an image with your registry name, then docker push it; use private registries for proprietary images.', 'আপনার রেজিস্ট্রি নাম দিয়ে ইমেজ ট্যাগ করুন, তারপর docker push করুন; মালিকানা ইমেজে প্রাইভেট রেজিস্ট্রি নিন।',
    'Public registries make sharing effortless, but pulling untrusted images can bring in vulnerabilities or malware.', 'পাবলিক রেজিস্ট্রি শেয়ার সহজ করে, তবে অবিশ্বস্ত ইমেজ পুল করলে দুর্বলতা বা ম্যালওয়্যার আসতে পারে।',
    'Pulling a random unofficial image and running it with full access without ever checking its contents.', 'একটি এলোমেলো অনানুষ্ঠানিক ইমেজ পুল করে বিষয়বস্তু না দেখেই পূর্ণ অ্যাক্সেসে চালানো।'],
  ['dk-inspect', 'dk-images', 'Inspecting & cleaning up images', 'ইমেজ পরিদর্শন ও পরিষ্কার', 'Beginner', 11, 'dk-registry',
    'docker images lists what you have, docker inspect shows details, and docker image prune reclaims disk space.', 'docker images আপনার কাছে যা আছে তালিকা করে, docker inspect বিস্তারিত দেখায়, ও docker image prune ডিস্ক জায়গা ফিরিয়ে আনে।',
    'A pantry audit: see what is on the shelves, read each label, and throw out what is expired or unused.', 'একটি প্যান্ট্রি অডিট: তাকে কী আছে দেখুন, প্রতিটি লেবেল পড়ুন, ও মেয়াদোত্তীর্ণ বা অব্যবহৃত ফেলে দিন।',
    'Run docker system df to see usage, then prune dangling images and stopped containers to free space.', 'ব্যবহার দেখতে docker system df চালান, তারপর জায়গা মুক্ত করতে ড্যাংলিং ইমেজ ও থামানো কন্টেইনার prune করুন।',
    'Pruning reclaims disk quickly, but an aggressive prune -a can delete images you still need and force slow re-pulls.', 'prune দ্রুত ডিস্ক ফেরায়, তবে আক্রমণাত্মক prune -a এখনো দরকারি ইমেজ মুছে ধীর রি-পুল ঘটাতে পারে।',
    'Running docker system prune -a on a busy host and deleting base images every build depended on.', 'একটি ব্যস্ত হোস্টে docker system prune -a চালিয়ে প্রতিটি বিল্ড যেসব বেস ইমেজে নির্ভর করত তা মোছা।'],

  // ── Building with Dockerfiles ─────────────────────────────────────────────
  ['dk-dockerfile', 'dk-dockerfile', 'Anatomy of a Dockerfile', 'Dockerfile-এর গঠন', 'Beginner', 13, 'dk-build',
    'A Dockerfile is a recipe: an ordered list of instructions that Docker executes to build an image.', 'Dockerfile হলো একটি রেসিপি: নির্দেশের একটি ক্রমিক তালিকা যা ডকার একটি ইমেজ বিল্ড করতে চালায়।',
    'A step-by-step recipe card—start from a base, add ingredients, set the default action, and you have a dish (image).', 'একটি ধাপে-ধাপে রেসিপি কার্ড—একটি বেস থেকে শুরু, উপকরণ যোগ, ডিফল্ট ক্রিয়া সেট, আর একটি ডিশ (ইমেজ) হলো।',
    'Start FROM a base image, COPY your code in, RUN build steps, and set the default CMD to launch the app.', 'একটি বেস ইমেজ FROM দিয়ে শুরু, কোড COPY করুন, বিল্ড ধাপ RUN করুন, ও অ্যাপ চালাতে ডিফল্ট CMD সেট করুন।',
    'A Dockerfile makes builds reproducible and reviewable, but each instruction adds a layer, so order and size matter.', 'Dockerfile বিল্ডকে পুনরুৎপাদনযোগ্য ও রিভিউযোগ্য করে, তবে প্রতিটি নির্দেশ একটি লেয়ার যোগ করে, তাই ক্রম ও সাইজ গুরুত্বপূর্ণ।',
    'Writing one giant RUN with everything, making the image hard to cache, read, and debug.', 'সবকিছু নিয়ে একটি বিশাল RUN লেখা, ইমেজকে ক্যাশ, পড়া ও ডিবাগ করা কঠিন করা।'],
  ['dk-instructions', 'dk-dockerfile', 'Key Dockerfile instructions', 'মূল Dockerfile নির্দেশ', 'Intermediate', 15, 'dk-build',
    'FROM sets the base, RUN executes build commands, COPY adds files, WORKDIR sets the directory, and CMD/ENTRYPOINT define what runs.', 'FROM বেস সেট করে, RUN বিল্ড কমান্ড চালায়, COPY ফাইল যোগ করে, WORKDIR ডিরেক্টরি সেট করে, ও CMD/ENTRYPOINT কী চলবে ঠিক করে।',
    'Each instruction is a verb in the recipe: base from, do this, copy that, then run this by default.', 'প্রতিটি নির্দেশ রেসিপির একটি ক্রিয়া: এই বেস থেকে, এটি করো, ওটা কপি করো, তারপর ডিফল্টে এটি চালাও।',
    'Use ENTRYPOINT for the fixed executable and CMD for default arguments you may override at run time.', 'নির্দিষ্ট এক্সিকিউটেবলে ENTRYPOINT ও রান-টাইমে ওভাররাইড-যোগ্য ডিফল্ট আর্গুমেন্টে CMD ব্যবহার করুন।',
    'These instructions are simple, but RUN vs CMD and CMD vs ENTRYPOINT are easy to confuse and behave very differently.', 'এই নির্দেশ সরল, তবে RUN বনাম CMD ও CMD বনাম ENTRYPOINT সহজে গুলিয়ে যায় ও খুব ভিন্নভাবে আচরণ করে।',
    'Using RUN (build time) when you meant CMD (run time), baking a one-off command into the image.', 'CMD (রান টাইম) বোঝাতে RUN (বিল্ড টাইম) ব্যবহার করা, একটি এককালীন কমান্ড ইমেজে বেক করা।'],
  ['dk-build-cache', 'dk-dockerfile', 'Build cache & layer ordering', 'বিল্ড ক্যাশ ও লেয়ার ক্রম', 'Intermediate', 14, 'dk-build',
    'Docker caches each layer and reuses it until an instruction (or its inputs) changes, then rebuilds everything after.', 'ডকার প্রতিটি লেয়ার ক্যাশ করে ও একটি নির্দেশ (বা তার ইনপুট) না বদলানো পর্যন্ত পুনঃব্যবহার করে, তারপর পরের সব রিবিল্ড করে।',
    'A checkpoint save in a game—unchanged early steps load instantly; a change forces replaying from that point on.', 'একটি গেমে চেকপয়েন্ট সেভ—অপরিবর্তিত শুরুর ধাপ তাৎক্ষণিক লোড হয়; একটি পরিবর্তন সেখান থেকে রিপ্লে করায়।',
    'Copy dependency files and install them before copying your source, so code changes do not bust the dependency cache.', 'সোর্স কপির আগে ডিপেন্ডেন্সি ফাইল কপি করে ইনস্টল করুন, যাতে কোড পরিবর্তন ডিপেন্ডেন্সি ক্যাশ না ভাঙে।',
    'Cache ordering can cut builds from minutes to seconds, but a poorly ordered Dockerfile reinstalls dependencies every time.', 'ক্যাশ ক্রম বিল্ড মিনিট থেকে সেকেন্ডে নামাতে পারে, তবে খারাপভাবে সাজানো Dockerfile প্রতিবার ডিপেন্ডেন্সি রি-ইনস্টল করে।',
    'Running COPY . . before installing dependencies, so any code edit reinstalls everything from scratch.', 'ডিপেন্ডেন্সি ইনস্টলের আগে COPY . . চালানো, ফলে যেকোনো কোড এডিট সব নতুন করে ইনস্টল করে।'],
  ['dk-multistage', 'dk-dockerfile', 'Multi-stage builds', 'মাল্টি-স্টেজ বিল্ড', 'Advanced', 16, 'dk-layers',
    'A multi-stage build uses one stage to compile and a second, minimal stage that copies only the final artifact.', 'মাল্টি-স্টেজ বিল্ড একটি স্টেজে কম্পাইল করে ও দ্বিতীয় ন্যূনতম স্টেজে শুধু চূড়ান্ত আর্টিফ্যাক্ট কপি করে।',
    'Cook in a full kitchen, then send only the finished dish to the dining room—leave the pots and mess behind.', 'একটি পূর্ণ রান্নাঘরে রাঁধুন, তারপর শুধু তৈরি ডিশটি ডাইনিং রুমে পাঠান—হাঁড়ি ও অগোছালো রেখে দিন।',
    'Build with the full toolchain in stage one, then COPY --from that stage into a slim runtime image.', 'স্টেজ ওয়ানে পূর্ণ টুলচেইন দিয়ে বিল্ড করুন, তারপর সেই স্টেজ থেকে COPY --from দিয়ে একটি স্লিম রানটাইম ইমেজে নিন।',
    'Multi-stage builds shrink final images dramatically, but they add complexity and can be tricky to cache and debug.', 'মাল্টি-স্টেজ বিল্ড চূড়ান্ত ইমেজ ব্যাপকভাবে ছোট করে, তবে জটিলতা যোগ করে ও ক্যাশ ও ডিবাগ করা কঠিন হতে পারে।',
    'Shipping the whole build toolchain in the final image, making it huge and widening the attack surface.', 'পুরো বিল্ড টুলচেইন চূড়ান্ত ইমেজে পাঠানো, একে বিশাল করা ও আক্রমণ-পৃষ্ঠ বাড়ানো।'],
  ['dk-dockerignore', 'dk-dockerfile', '.dockerignore & build context', '.dockerignore ও বিল্ড কনটেক্সট', 'Intermediate', 12, 'dk-build',
    'The build context is the files sent to the daemon; a .dockerignore keeps junk (node_modules, .git, secrets) out of it.', 'বিল্ড কনটেক্সট হলো ডেমনে পাঠানো ফাইল; .dockerignore এতে আবর্জনা (node_modules, .git, সিক্রেট) ঢুকতে দেয় না।',
    'A "do not pack" list before shipping—leave out the clutter so the box stays small and clean.', 'শিপিংয়ের আগে "প্যাক করবেন না" তালিকা—অগোছালো বাদ দিন যাতে বাক্স ছোট ও পরিষ্কার থাকে।',
    'Add a .dockerignore for node_modules, .git, and secrets to speed builds and avoid leaking files into the image.', 'বিল্ড দ্রুত করতে ও ইমেজে ফাইল ফাঁস এড়াতে node_modules, .git ও সিক্রেটের জন্য একটি .dockerignore যোগ করুন।',
    'A good .dockerignore shrinks the context and improves caching, but forgetting it can send gigabytes and leak secrets.', 'একটি ভালো .dockerignore কনটেক্সট ছোট করে ও ক্যাশিং উন্নত করে, তবে ভুলে গেলে গিগাবাইট পাঠাতে ও সিক্রেট ফাঁস করতে পারে।',
    'Leaving out .dockerignore, so a huge context (and a stray .env) gets copied into the image.', '.dockerignore বাদ দেওয়া, ফলে একটি বিশাল কনটেক্সট (ও একটি ভুল .env) ইমেজে কপি হয়।'],
  ['dk-image-best', 'dk-dockerfile', 'Image best practices', 'ইমেজ বেস্ট প্র্যাকটিস', 'Advanced', 15, 'dk-layers',
    'Good images are small, pinned, and run as a non-root user, with few layers and only what runtime needs.', 'ভালো ইমেজ ছোট, পিন করা ও নন-রুট ব্যবহারকারী হিসেবে চলে, কম লেয়ারে ও শুধু রানটাইমের প্রয়োজন নিয়ে।',
    'Packing a travel bag: take the small essentials, label them, and lock it—not the whole wardrobe.', 'একটি ভ্রমণ ব্যাগ প্যাক: ছোট প্রয়োজনীয় জিনিস নিন, লেবেল দিন, ও তালা দিন—পুরো আলমারি নয়।',
    'Start from a slim/alpine base, combine RUN steps, pin versions, and add a USER so the app is not root.', 'একটি স্লিম/alpine বেস থেকে শুরু, RUN ধাপ একত্র করুন, ভার্সন পিন করুন, ও একটি USER যোগ করুন যাতে অ্যাপ root না হয়।',
    'Smaller, hardened images pull and start faster and are safer, but a too-minimal base can miss libraries your app needs.', 'ছোট, কঠোর ইমেজ দ্রুত পুল ও চালু হয় ও নিরাপদ, তবে অতি-ন্যূনতম বেস আপনার অ্যাপের দরকারি লাইব্রেরি মিস করতে পারে।',
    'Running the container as root by default, so a compromise inside grants root on shared resources.', 'ডিফল্টে কন্টেইনার root হিসেবে চালানো, ফলে ভেতরের একটি আপস শেয়ার্ড রিসোর্সে root দেয়।'],

  // ── Running containers ────────────────────────────────────────────────────
  ['dk-run-flags', 'dk-containers', 'docker run flags', 'docker run ফ্ল্যাগ', 'Beginner', 13, 'dk-lifecycle',
    'Common run flags: -d (background), -p (publish a port), -e (set an env var), --name (name it), -v (mount data).', 'সাধারণ run ফ্ল্যাগ: -d (ব্যাকগ্রাউন্ড), -p (পোর্ট পাবলিশ), -e (env সেট), --name (নাম), -v (ডেটা মাউন্ট)।',
    'Dials on a machine: run in the background, expose an output port, feed in settings, and label it.', 'একটি মেশিনের ডায়াল: ব্যাকগ্রাউন্ডে চালান, একটি আউটপুট পোর্ট খুলুন, সেটিং দিন, ও লেবেল দিন।',
    'Combine flags: docker run -d -p 8080:80 --name web nginx to run nginx detached on port 8080.', 'ফ্ল্যাগ মেলান: docker run -d -p 8080:80 --name web nginx দিয়ে nginx পোর্ট 8080-এ ডিটাচড চালান।',
    'Flags make one command highly configurable, but a long unreadable run line is easy to get subtly wrong.', 'ফ্ল্যাগ এক কমান্ডকে অত্যন্ত কনফিগারযোগ্য করে, তবে একটি লম্বা অপাঠ্য run লাইন সূক্ষ্মভাবে ভুল হওয়া সহজ।',
    'Forgetting -d and blocking your terminal, or reversing -p host:container and publishing the wrong port.', '-d ভুলে টার্মিনাল আটকানো, বা -p host:container উল্টে ভুল পোর্ট পাবলিশ করা।'],
  ['dk-lifecycle', 'dk-containers', 'The container lifecycle', 'কন্টেইনার লাইফসাইকেল', 'Beginner', 12, 'dk-lifecycle',
    'A container is created, then runs, can be stopped and started again, and finally removed with docker rm.', 'একটি কন্টেইনার তৈরি হয়, তারপর চলে, থামানো ও আবার চালু করা যায়, শেষে docker rm দিয়ে মুছে ফেলা হয়।',
    'A machine you power on, pause, power on again, and eventually unplug and haul away.', 'একটি মেশিন যা চালু করেন, থামান, আবার চালু করেন, শেষে খুলে সরিয়ে ফেলেন।',
    'Use docker ps to see running ones, docker ps -a for all, docker stop/start to control, and docker rm to delete.', 'চলমান দেখতে docker ps, সব দেখতে docker ps -a, নিয়ন্ত্রণে docker stop/start, ও মুছতে docker rm ব্যবহার করুন।',
    'Stopped containers keep their state and logs for debugging, but they also keep consuming disk until removed.', 'থামানো কন্টেইনার ডিবাগের জন্য স্টেট ও লগ রাখে, তবে রিমুভ না করা পর্যন্ত ডিস্কও খরচ করতে থাকে।',
    'Only using docker ps (running) and not realizing stopped containers still exist and hold names and disk.', 'শুধু docker ps (চলমান) ব্যবহার করা আর না বোঝা যে থামানো কন্টেইনার এখনো আছে ও নাম ও ডিস্ক ধরে রাখে।'],
  ['dk-exec-logs', 'dk-containers', 'Exec & logs', 'exec ও logs', 'Beginner', 12, 'dk-lifecycle',
    'docker logs shows a container’s output; docker exec runs a command (like a shell) inside a running container.', 'docker logs একটি কন্টেইনারের আউটপুট দেখায়; docker exec একটি চলমান কন্টেইনারের ভেতরে একটি কমান্ড (যেমন শেল) চালায়।',
    'logs is reading the machine’s printout; exec is opening the panel and reaching inside while it runs.', 'logs হলো মেশিনের প্রিন্টআউট পড়া; exec হলো চলা অবস্থায় প্যানেল খুলে ভেতরে হাত দেওয়া।',
    'Debug with docker logs -f to follow output and docker exec -it name sh to get a shell inside.', 'ডিবাগে docker logs -f দিয়ে আউটপুট follow ও docker exec -it name sh দিয়ে ভেতরে একটি শেল নিন।',
    'exec is invaluable for debugging, but changes you make inside a running container vanish when it is recreated.', 'exec ডিবাগে অমূল্য, তবে একটি চলমান কন্টেইনারের ভেতরে করা পরিবর্তন পুনঃতৈরিতে হারায়।',
    'Fixing a problem by editing files inside a running container instead of the image, so the fix is lost on redeploy.', 'ইমেজের বদলে চলমান কন্টেইনারের ভেতরে ফাইল এডিট করে সমস্যা ঠিক করা, ফলে রিডিপ্লয়ে ফিক্স হারায়।'],
  ['dk-env-config', 'dk-containers', 'Environment & configuration', 'এনভায়রনমেন্ট ও কনফিগারেশন', 'Intermediate', 13, 'dk-lifecycle',
    'Pass configuration into containers with environment variables (-e or --env-file) instead of baking it into the image.', 'ইমেজে বেক না করে এনভায়রনমেন্ট ভ্যারিয়েবল (-e বা --env-file) দিয়ে কন্টেইনারে কনফিগারেশন দিন।',
    'The same appliance shipped worldwide, configured by the plug and dial settings at each location, not rebuilt.', 'একই যন্ত্র বিশ্বজুড়ে পাঠানো, প্রতিটি জায়গায় প্লাগ ও ডায়াল সেটিং দিয়ে কনফিগার, পুনর্নির্মাণ নয়।',
    'Read config from env vars in your app, and supply them per environment with -e or an --env-file.', 'আপনার অ্যাপে env ভ্যার থেকে কনফিগ পড়ুন, ও প্রতি এনভায়রনমেন্টে -e বা একটি --env-file দিয়ে দিন।',
    'Env-based config makes one image work in dev, staging, and prod, but secrets in env vars can leak via logs or inspect.', 'env-ভিত্তিক কনফিগ এক ইমেজকে dev, staging ও prod-এ চালায়, তবে env ভ্যারে সিক্রেট logs বা inspect দিয়ে ফাঁস হতে পারে।',
    'Baking environment-specific config or secrets into the image, so you need a new build for every environment.', 'এনভায়রনমেন্ট-নির্দিষ্ট কনফিগ বা সিক্রেট ইমেজে বেক করা, ফলে প্রতি এনভায়রনমেন্টে নতুন বিল্ড লাগে।'],
  ['dk-restart', 'dk-containers', 'Restart policies & healthchecks', 'রিস্টার্ট পলিসি ও হেলথচেক', 'Intermediate', 13, 'dk-lifecycle',
    'A restart policy tells Docker to relaunch a container after it exits or the host reboots; a healthcheck reports if it is actually healthy.', 'রিস্টার্ট পলিসি ডকারকে বলে কন্টেইনার বেরোলে বা হোস্ট রিবুট করলে একে আবার চালাতে; হেলথচেক বলে এটি আসলে সুস্থ কি না।',
    'A pilot light that relights the burner automatically, plus a sensor confirming the flame is truly on.', 'একটি পাইলট লাইট যা বার্নার স্বয়ংক্রিয় জ্বালায়, সঙ্গে একটি সেন্সর নিশ্চিত করে শিখা সত্যিই জ্বলছে।',
    'Set --restart unless-stopped for long-running services, and add a HEALTHCHECK so orchestrators know real status.', 'দীর্ঘ-চলমান সার্ভিসে --restart unless-stopped সেট করুন, ও একটি HEALTHCHECK যোগ করুন যাতে অর্কেস্ট্রেটর আসল স্ট্যাটাস জানে।',
    'Restart policies keep services up, but a crash-looping container with a broken image will restart forever, hiding the real error.', 'রিস্টার্ট পলিসি সার্ভিস সচল রাখে, তবে ভাঙা ইমেজসহ ক্র্যাশ-লুপিং কন্টেইনার চিরকাল রিস্টার্ট করে আসল এরর লুকায়।',
    'Relying on "running" status when the app inside is actually broken, because there is no healthcheck.', 'হেলথচেক না থাকায় ভেতরের অ্যাপ আসলে ভাঙা হলেও "running" স্ট্যাটাসে ভরসা করা।'],
  ['dk-resources', 'dk-containers', 'Resource limits (CPU, memory)', 'রিসোর্স লিমিট (CPU, মেমরি)', 'Intermediate', 13, 'dk-lifecycle',
    'By default a container can use all host resources; --memory and --cpus cap how much it may consume.', 'ডিফল্টে একটি কন্টেইনার সব হোস্ট রিসোর্স ব্যবহার করতে পারে; --memory ও --cpus কতটা নিতে পারবে তা সীমিত করে।',
    'A fuse and a speed limiter—one appliance cannot draw all the power or run away with the whole engine.', 'একটি ফিউজ ও একটি স্পিড লিমিটার—একটি যন্ত্র সব শক্তি টানতে বা পুরো ইঞ্জিন নিয়ে ছুটতে পারে না।',
    'Set --memory and --cpus so one noisy container cannot starve the others on a shared host.', '--memory ও --cpus সেট করুন যাতে একটি হইচই কন্টেইনার শেয়ার্ড হোস্টে অন্যদের অভুক্ত না করে।',
    'Limits protect neighbors and improve stability, but set too low they trigger out-of-memory kills or throttling.', 'লিমিট প্রতিবেশীদের রক্ষা করে ও স্থিতিশীলতা বাড়ায়, তবে খুব কম হলে out-of-memory kill বা থ্রটলিং ঘটায়।',
    'Running unbounded containers, so one memory leak takes down every service on the host.', 'সীমাহীন কন্টেইনার চালানো, ফলে একটি মেমরি লিক হোস্টের প্রতিটি সার্ভিস ফেলে দেয়।'],

  // ── Data & storage ────────────────────────────────────────────────────────
  ['dk-volumes', 'dk-data', 'Named volumes', 'নেমড ভলিউম', 'Beginner', 13, 'dk-volume',
    'A named volume is Docker-managed storage that lives outside the container, so data survives restarts and removal.', 'একটি নেমড ভলিউম হলো ডকার-পরিচালিত স্টোরেজ যা কন্টেইনারের বাইরে থাকে, তাই ডেটা রিস্টার্ট ও রিমুভে টিকে থাকে।',
    'An external hard drive you plug into any machine—the data stays even after the machine is scrapped.', 'একটি বাহ্যিক হার্ড ড্রাইভ যা যেকোনো মেশিনে যুক্ত করেন—মেশিন বাতিল হলেও ডেটা থাকে।',
    'Mount a volume with -v name:/path for databases and any data you must keep between container runs.', 'ডেটাবেস ও কন্টেইনার রানের মধ্যে রাখতে হওয়া যেকোনো ডেটায় -v name:/path দিয়ে ভলিউম মাউন্ট করুন।',
    'Volumes cleanly separate data from the container, but they persist after docker rm and can quietly pile up.', 'ভলিউম ডেটাকে কন্টেইনার থেকে পরিষ্কারভাবে আলাদা করে, তবে docker rm-এর পরও থাকে ও নীরবে জমতে পারে।',
    'Storing database data in the container instead of a volume, then losing everything when the container is replaced.', 'ভলিউমের বদলে কন্টেইনারে ডেটাবেস ডেটা রাখা, তারপর কন্টেইনার বদলালে সব হারানো।'],
  ['dk-bind-mounts', 'dk-data', 'Bind mounts', 'বাইন্ড মাউন্ট', 'Intermediate', 13, 'dk-volume',
    'A bind mount maps a host directory straight into the container, so both see the same live files.', 'একটি বাইন্ড মাউন্ট একটি হোস্ট ডিরেক্টরি সরাসরি কন্টেইনারে ম্যাপ করে, তাই দুজনই একই লাইভ ফাইল দেখে।',
    'A shared folder between two computers—edit on one side and it changes instantly on the other.', 'দুটি কম্পিউটারের মধ্যে একটি শেয়ার্ড ফোল্ডার—এক পাশে এডিট করলে অন্য পাশে সঙ্গে সঙ্গে বদলায়।',
    'Use a bind mount in development to live-edit code on the host while it runs inside the container.', 'ডেভেলপমেন্টে একটি বাইন্ড মাউন্ট ব্যবহার করুন যাতে কন্টেইনারে চলা অবস্থায় হোস্টে কোড লাইভ-এডিট করা যায়।',
    'Bind mounts are great for local development, but they depend on host paths and are less portable than named volumes.', 'বাইন্ড মাউন্ট লোকাল ডেভেলপমেন্টে চমৎকার, তবে হোস্ট পাথের ওপর নির্ভর করে ও নেমড ভলিউমের চেয়ে কম পোর্টেবল।',
    'Bind-mounting a host directory over the app’s code in production, exposing or breaking the running image.', 'প্রোডাকশনে অ্যাপের কোডের ওপর একটি হোস্ট ডিরেক্টরি বাইন্ড-মাউন্ট করা, চলমান ইমেজ ফাঁস বা ভাঙা।'],
  ['dk-persistence', 'dk-data', 'Persisting & sharing data', 'ডেটা স্থায়ী ও শেয়ার', 'Intermediate', 12, 'dk-volume',
    'Containers are ephemeral; anything you must keep or share between containers belongs in a volume, not the container.', 'কন্টেইনার ক্ষণস্থায়ী; যা রাখতে বা কন্টেইনারের মধ্যে শেয়ার করতে হবে তা কন্টেইনারে নয়, ভলিউমে থাকে।',
    'Hotel rooms are cleaned between guests—keep your valuables in the safe (volume), not the room (container).', 'অতিথিদের মধ্যে হোটেল রুম পরিষ্কার হয়—মূল্যবান জিনিস রুমে (কন্টেইনার) নয়, সেফে (ভলিউম) রাখুন।',
    'Design apps to write state to a volume, and mount the same volume in multiple containers to share it.', 'অ্যাপ এমনভাবে ডিজাইন করুন যাতে স্টেট ভলিউমে লেখে, ও শেয়ার করতে একই ভলিউম একাধিক কন্টেইনারে মাউন্ট করুন।',
    'Volumes make containers safely disposable, but shared writable volumes need care to avoid concurrent-write corruption.', 'ভলিউম কন্টেইনারকে নিরাপদে ফেলে-দেওয়া-যোগ্য করে, তবে শেয়ার্ড লেখনযোগ্য ভলিউমে একসঙ্গে-লেখা নষ্ট এড়াতে যত্ন লাগে।',
    'Treating a container as permanent storage, then losing all state the first time it must be recreated.', 'একটি কন্টেইনারকে স্থায়ী স্টোরেজ ভাবা, তারপর প্রথমবার পুনঃতৈরির সময় সব স্টেট হারানো।'],
  ['dk-backup', 'dk-data', 'Backing up volume data', 'ভলিউম ডেটা ব্যাকআপ', 'Advanced', 13, 'dk-volume',
    'To back up a volume, run a temporary container that mounts it and archives its contents to a file on the host.', 'একটি ভলিউম ব্যাকআপ করতে, একটি অস্থায়ী কন্টেইনার চালান যা তা মাউন্ট করে ও বিষয়বস্তু হোস্টের একটি ফাইলে আর্কাইভ করে।',
    'Copying the contents of a safe into a labeled box you store off-site, so you can restore it later.', 'একটি সেফের বিষয়বস্তু একটি লেবেলযুক্ত বাক্সে কপি করে অফ-সাইটে রাখা, যাতে পরে পুনরুদ্ধার করা যায়।',
    'Use a helper container (like alpine) with tar to archive the volume, and reverse the process to restore.', 'ভলিউম আর্কাইভ করতে tar-সহ একটি হেল্পার কন্টেইনার (যেমন alpine) ব্যবহার করুন, ও পুনরুদ্ধারে উল্টো করুন।',
    'This approach is portable and scriptable, but backups are only useful if you test that a restore actually works.', 'এই পদ্ধতি পোর্টেবল ও স্ক্রিপ্টযোগ্য, তবে ব্যাকআপ তখনই কাজের যখন রিস্টোর সত্যিই কাজ করে তা পরীক্ষা করেন।',
    'Assuming a volume is automatically backed up, then discovering there is no recovery after a disk failure.', 'ধরে নেওয়া একটি ভলিউম স্বয়ংক্রিয় ব্যাকআপ হয়, তারপর ডিস্ক ব্যর্থতার পর কোনো পুনরুদ্ধার নেই আবিষ্কার করা।'],

  // ── Networking ────────────────────────────────────────────────────────────
  ['dk-network-basics', 'dk-networking', 'Container networking basics', 'কন্টেইনার নেটওয়ার্কিং বেসিক', 'Intermediate', 14, 'dk-compose',
    'By default containers join a bridge network where they get private IPs and can reach each other and the internet.', 'ডিফল্টে কন্টেইনার একটি ব্রিজ নেটওয়ার্কে যোগ দেয় যেখানে প্রাইভেট IP পায় ও একে অপরকে ও ইন্টারনেটে পৌঁছাতে পারে।',
    'An internal office network—everyone gets an extension and can call each other without going through the outside line.', 'একটি অভ্যন্তরীণ অফিস নেটওয়ার্ক—সবাই একটি এক্সটেনশন পায় ও বাইরের লাইন ছাড়াই একে অপরকে কল করতে পারে।',
    'Let containers on the same network talk directly; only publish ports you actually need to expose to the host.', 'একই নেটওয়ার্কের কন্টেইনারকে সরাসরি কথা বলতে দিন; শুধু যে পোর্ট হোস্টে খোলা দরকার তা পাবলিশ করুন।',
    'The default bridge is convenient, but containers on it can reach each other, so isolation needs separate networks.', 'ডিফল্ট ব্রিজ সুবিধাজনক, তবে এর কন্টেইনার একে অপরকে পৌঁছাতে পারে, তাই আইসোলেশনে আলাদা নেটওয়ার্ক লাগে।',
    'Publishing a database port to the host when only the app container needs it, exposing it to the whole network.', 'শুধু অ্যাপ কন্টেইনারের দরকার হলেও একটি ডেটাবেস পোর্ট হোস্টে পাবলিশ করা, পুরো নেটওয়ার্কে খোলা।'],
  ['dk-ports', 'dk-networking', 'Publishing ports', 'পোর্ট পাবলিশিং', 'Beginner', 12, 'dk-volume',
    'Publishing maps a host port to a container port with -p host:container, letting outside traffic reach the container.', 'পাবলিশিং -p host:container দিয়ে একটি হোস্ট পোর্টকে কন্টেইনার পোর্টে ম্যাপ করে, বাইরের ট্রাফিককে কন্টেইনারে পৌঁছাতে দেয়।',
    'A forwarding number: dial the host’s public number and it rings the container’s internal extension.', 'একটি ফরওয়ার্ডিং নম্বর: হোস্টের পাবলিক নম্বরে ডায়াল করলে কন্টেইনারের অভ্যন্তরীণ এক্সটেনশন বাজে।',
    'Use -p 8080:80 to expose the container’s port 80 on the host’s 8080; read it as host:container.', 'কন্টেইনারের পোর্ট 80 হোস্টের 8080-এ খুলতে -p 8080:80 ব্যবহার করুন; এটি host:container হিসেবে পড়ুন।',
    'Publishing makes a service reachable, but every published port is an opening that must be firewalled and justified.', 'পাবলিশিং একটি সার্ভিস পৌঁছানোযোগ্য করে, তবে প্রতিটি পাবলিশড পোর্ট একটি ছিদ্র যা ফায়ারওয়াল ও যুক্তিসঙ্গত হতে হবে।',
    'Reversing the mapping (-p 80:8080) and wondering why the service is unreachable on the expected port.', 'ম্যাপিং উল্টানো (-p 80:8080) আর অবাক হওয়া কেন সার্ভিস প্রত্যাশিত পোর্টে পৌঁছানো যায় না।'],
  ['dk-custom-networks', 'dk-networking', 'Custom networks & service discovery', 'কাস্টম নেটওয়ার্ক ও সার্ভিস ডিসকভারি', 'Intermediate', 14, 'dk-compose',
    'A user-defined network isolates a group of containers and gives them DNS, so they can reach each other by name.', 'একটি ইউজার-ডিফাইনড নেটওয়ার্ক একদল কন্টেইনারকে আলাদা করে ও DNS দেয়, তাই তারা নাম দিয়ে একে অপরকে পৌঁছাতে পারে।',
    'A private team channel with a directory—call "database" by name instead of memorizing its number.', 'একটি ডিরেক্টরিসহ ব্যক্তিগত টিম চ্যানেল—নম্বর মুখস্থ না করে নাম দিয়ে "database" কল করুন।',
    'Create a custom network and attach related containers, then connect using the container/service name as the hostname.', 'একটি কাস্টম নেটওয়ার্ক বানিয়ে সম্পর্কিত কন্টেইনার যুক্ত করুন, তারপর হোস্টনাম হিসেবে কন্টেইনার/সার্ভিস নাম দিয়ে সংযোগ করুন।',
    'Custom networks give clean isolation and name-based discovery, but the legacy default bridge lacks DNS between containers.', 'কাস্টম নেটওয়ার্ক পরিষ্কার আইসোলেশন ও নাম-ভিত্তিক ডিসকভারি দেয়, তবে লিগ্যাসি ডিফল্ট ব্রিজে কন্টেইনারের মধ্যে DNS নেই।',
    'Hard-coding a container IP instead of its name, then breaking when Docker assigns a different IP on restart.', 'নামের বদলে একটি কন্টেইনার IP হার্ড-কোড করা, তারপর রিস্টার্টে ডকার ভিন্ন IP দিলে ভাঙা।'],

  // ── Docker Compose ────────────────────────────────────────────────────────
  ['dk-compose-intro', 'dk-compose', 'What is Docker Compose?', 'ডকার কম্পোজ কী?', 'Beginner', 12, 'dk-compose',
    'Compose defines a multi-container app in one YAML file, so you start the whole stack with a single command.', 'Compose একটি YAML ফাইলে একটি মাল্টি-কন্টেইনার অ্যাপ সংজ্ঞায়িত করে, তাই এক কমান্ডে পুরো স্ট্যাক চালু করেন।',
    'A single "start the band" button that powers on the drummer, guitarist, and singer together, in tune.', 'একটি "ব্যান্ড শুরু" বোতাম যা ড্রামার, গিটারিস্ট ও গায়ককে একসঙ্গে, সুরে চালু করে।',
    'Describe each service in compose.yaml, then run docker compose up to build and start them all together.', 'compose.yaml-এ প্রতিটি সার্ভিস বর্ণনা করুন, তারপর docker compose up দিয়ে সব একসঙ্গে বিল্ড ও চালু করুন।',
    'Compose makes local multi-service setups reproducible, but it is single-host—production scaling needs an orchestrator.', 'Compose লোকাল মাল্টি-সার্ভিস সেটআপ পুনরুৎপাদনযোগ্য করে, তবে এটি সিঙ্গল-হোস্ট—প্রোডাকশন স্কেলিংয়ে অর্কেস্ট্রেটর লাগে।',
    'Treating Compose as a production orchestrator across many machines, which it is not designed to be.', 'Compose-কে অনেক মেশিনজুড়ে প্রোডাকশন অর্কেস্ট্রেটর ভাবা, যার জন্য এটি ডিজাইন করা নয়।'],
  ['dk-compose-file', 'dk-compose', 'The compose file', 'কম্পোজ ফাইল', 'Beginner', 14, 'dk-compose',
    'A compose file lists services, each with an image (or build), ports, environment, volumes, and dependencies.', 'একটি compose ফাইল সার্ভিস তালিকা করে, প্রতিটির একটি image (বা build), ports, environment, volumes ও নির্ভরতাসহ।',
    'A cast list for a play: each actor (service) has a role, costume, and cues defined in one script.', 'একটি নাটকের কাস্ট তালিকা: প্রতিটি অভিনেতা (সার্ভিস)-এর ভূমিকা, পোশাক ও কিউ এক স্ক্রিপ্টে সংজ্ঞায়িত।',
    'Under services, give each a name and either image: to pull or build: to build from a Dockerfile.', 'services-এর অধীনে প্রতিটিকে একটি নাম দিন এবং পুল করতে image: বা Dockerfile থেকে বিল্ড করতে build: দিন।',
    'One declarative file captures the whole stack, but like all YAML it is whitespace-sensitive and easy to misindent.', 'একটি ডিক্লারেটিভ ফাইল পুরো স্ট্যাক ধরে, তবে সব YAML-এর মতো এটি হোয়াইটস্পেস-সংবেদনশীল ও সহজে ভুল ইনডেন্ট হয়।',
    'Mixing tabs and spaces or misindenting, so Compose reads the file completely differently than you intended.', 'ট্যাব ও স্পেস মেশানো বা ভুল ইনডেন্ট, ফলে Compose ফাইলটি আপনার উদ্দেশ্যের চেয়ে পুরো ভিন্নভাবে পড়ে।'],
  ['dk-compose-multi', 'dk-compose', 'Multi-container apps', 'মাল্টি-কন্টেইনার অ্যাপ', 'Intermediate', 15, 'dk-compose',
    'Compose puts services on a shared network so they reach each other by service name, and depends_on sets start order.', 'Compose সার্ভিসগুলোকে একটি শেয়ার্ড নেটওয়ার্কে রাখে যাতে তারা সার্ভিস নাম দিয়ে একে অপরকে পৌঁছায়, ও depends_on শুরুর ক্রম সেট করে।',
    'An assembly line where each station knows the next by name and waits for the previous to be ready.', 'একটি অ্যাসেম্বলি লাইন যেখানে প্রতিটি স্টেশন পরেরটিকে নামে চেনে ও আগেরটি প্রস্তুত হওয়া পর্যন্ত অপেক্ষা করে।',
    'Reference other services by their compose name (e.g., host "db"), and use depends_on to order startup.', 'অন্য সার্ভিসকে তাদের compose নামে (যেমন হোস্ট "db") রেফার করুন, ও শুরুর ক্রমে depends_on ব্যবহার করুন।',
    'Compose wires networking and order for you, but depends_on waits for start, not readiness—you still need healthchecks.', 'Compose আপনার জন্য নেটওয়ার্কিং ও ক্রম যুক্ত করে, তবে depends_on শুরুর জন্য অপেক্ষা করে, প্রস্তুতির জন্য নয়—হেলথচেক লাগে।',
    'Assuming depends_on waits until a database is ready to accept connections, when it only waits for the container to start.', 'ধরে নেওয়া depends_on ডেটাবেস সংযোগ নিতে প্রস্তুত হওয়া পর্যন্ত অপেক্ষা করে, যখন এটি শুধু কন্টেইনার চালু হওয়ার জন্য অপেক্ষা করে।'],
  ['dk-compose-env', 'dk-compose', 'Env & config in Compose', 'Compose-এ env ও কনফিগ', 'Intermediate', 12, 'dk-compose',
    'Compose reads a .env file and lets each service set environment and env_file, keeping config out of the image.', 'Compose একটি .env ফাইল পড়ে ও প্রতিটি সার্ভিসকে environment ও env_file সেট করতে দেয়, কনফিগ ইমেজের বাইরে রাখে।',
    'A settings panel per service, plus one shared settings file the whole app reads from.', 'প্রতি সার্ভিসে একটি সেটিংস প্যানেল, সঙ্গে একটি শেয়ার্ড সেটিংস ফাইল যা পুরো অ্যাপ পড়ে।',
    'Keep secrets and per-environment values in a .env or secrets, and reference them from the compose file.', 'সিক্রেট ও প্রতি-এনভায়রনমেন্ট মান একটি .env বা secrets-এ রাখুন, ও compose ফাইল থেকে রেফার করুন।',
    'Externalized config makes the same compose file work across environments, but a committed .env leaks secrets to the repo.', 'বাহ্যিক কনফিগ একই compose ফাইলকে এনভায়রনমেন্টজুড়ে চালায়, তবে কমিট করা .env রিপোতে সিক্রেট ফাঁস করে।',
    'Committing a .env full of production secrets to version control, exposing them to everyone with repo access.', 'প্রোডাকশন সিক্রেটে ভরা একটি .env ভার্সন কন্ট্রোলে কমিট করা, রিপো অ্যাক্সেস থাকা সবার কাছে ফাঁস।'],
  ['dk-compose-scale', 'dk-compose', 'Scaling & lifecycle', 'স্কেলিং ও লাইফসাইকেল', 'Intermediate', 12, 'dk-compose',
    'docker compose up starts the stack, down stops and removes it, and --scale runs multiple replicas of a service.', 'docker compose up স্ট্যাক চালু করে, down থামিয়ে মুছে ফেলে, ও --scale একটি সার্ভিসের একাধিক রেপ্লিকা চালায়।',
    'A master switch for the whole stack, plus a dial to add more copies of any one worker.', 'পুরো স্ট্যাকের জন্য একটি মাস্টার সুইচ, সঙ্গে যেকোনো একটি ওয়ার্কারের বেশি কপি যোগ করার ডায়াল।',
    'Use compose up -d to run detached, compose logs to watch, and compose down -v to also remove volumes.', 'ডিটাচড চালাতে compose up -d, দেখতে compose logs, ও ভলিউমসহ মুছতে compose down -v ব্যবহার করুন।',
    'Compose makes the stack easy to bring up and tear down, but down -v deletes volumes and the data inside them.', 'Compose স্ট্যাক চালু ও বন্ধ করা সহজ করে, তবে down -v ভলিউম ও ভেতরের ডেটা মুছে ফেলে।',
    'Running compose down -v in the wrong environment and wiping the database volume you needed.', 'ভুল এনভায়রনমেন্টে compose down -v চালিয়ে দরকারি ডেটাবেস ভলিউম মুছে ফেলা।'],

  // ── Production & operations ───────────────────────────────────────────────
  ['dk-optimize', 'dk-production', 'Optimizing images for production', 'প্রোডাকশনে ইমেজ অপটিমাইজ', 'Advanced', 15, 'dk-compose',
    'Production images should be small and fast: use slim bases, multi-stage builds, and drop build tools and caches.', 'প্রোডাকশন ইমেজ ছোট ও দ্রুত হওয়া উচিত: স্লিম বেস, মাল্টি-স্টেজ বিল্ড ব্যবহার করুন, ও বিল্ড টুল ও ক্যাশ বাদ দিন।',
    'Shipping only the finished product in minimal packaging—no factory equipment, no packing peanuts.', 'শুধু তৈরি পণ্য ন্যূনতম প্যাকেজিংয়ে পাঠানো—কোনো কারখানার যন্ত্র নয়, কোনো প্যাকিং উপকরণ নয়।',
    'Combine multi-stage builds, a slim base, and a .dockerignore; verify the final image size with docker images.', 'মাল্টি-স্টেজ বিল্ড, একটি স্লিম বেস ও একটি .dockerignore মেলান; docker images দিয়ে চূড়ান্ত ইমেজ সাইজ যাচাই করুন।',
    'Smaller images deploy faster and have a smaller attack surface, but over-trimming can remove libraries the app needs at runtime.', 'ছোট ইমেজ দ্রুত ডিপ্লয় হয় ও কম আক্রমণ-পৃষ্ঠ, তবে অতি-ছাঁটাই রানটাইমে অ্যাপের দরকারি লাইব্রেরি সরাতে পারে।',
    'Shipping a multi-gigabyte image full of build tools, slowing every deploy and pull.', 'বিল্ড টুলে ভরা একটি মাল্টি-গিগাবাইট ইমেজ পাঠানো, প্রতিটি ডিপ্লয় ও পুল ধীর করা।'],
  ['dk-security', 'dk-production', 'Container security', 'কন্টেইনার নিরাপত্তা', 'Advanced', 16, 'dk-compose',
    'Harden containers by running as non-root, using trusted minimal images, scanning for vulnerabilities, and keeping secrets out of images.', 'নন-রুট হিসেবে চালিয়ে, বিশ্বস্ত ন্যূনতম ইমেজ ব্যবহার করে, দুর্বলতা স্ক্যান করে ও ইমেজ থেকে সিক্রেট দূরে রেখে কন্টেইনার কঠোর করুন।',
    'Locking a shipping container: minimal contents, a verified seal, an inspection, and no keys taped inside.', 'একটি শিপিং কন্টেইনার তালা দেওয়া: ন্যূনতম বিষয়বস্তু, যাচাই করা সিল, একটি পরিদর্শন, ও ভেতরে কোনো চাবি টেপ করা নয়।',
    'Add a non-root USER, pin and scan base images, and inject secrets at runtime instead of baking them in.', 'একটি নন-রুট USER যোগ করুন, বেস ইমেজ পিন ও স্ক্যান করুন, ও সিক্রেট বেক না করে রানটাইমে দিন।',
    'Layered hardening greatly reduces risk, but security is ongoing—a base image that is safe today can have a CVE tomorrow.', 'স্তরিত কঠোরতা ঝুঁকি অনেক কমায়, তবে নিরাপত্তা চলমান—আজ নিরাপদ একটি বেস ইমেজে কাল CVE থাকতে পারে।',
    'Running every container as root with baked-in secrets, so one breakout compromises the whole host.', 'বেক-ইন সিক্রেটসহ প্রতিটি কন্টেইনার root হিসেবে চালানো, ফলে একটি ব্রেকআউট পুরো হোস্ট আপস করে।'],
  ['dk-healthcheck-logs', 'dk-production', 'Healthchecks & logging', 'হেলথচেক ও লগিং', 'Intermediate', 13, 'dk-compose',
    'Containers log to stdout/stderr for the engine to collect; a HEALTHCHECK lets the platform detect an unhealthy container and act.', 'কন্টেইনার ইঞ্জিনের সংগ্রহের জন্য stdout/stderr-এ লগ করে; একটি HEALTHCHECK প্ল্যাটফর্মকে অসুস্থ কন্টেইনার শনাক্ত ও ব্যবস্থা নিতে দেয়।',
    'A dashboard light and a diagnostic port—the system reports its own status and streams a running record.', 'একটি ড্যাশবোর্ড লাইট ও একটি ডায়াগনস্টিক পোর্ট—সিস্টেম নিজের স্ট্যাটাস জানায় ও একটি চলমান রেকর্ড স্ট্রিম করে।',
    'Write logs to stdout (not files inside the container), and define a HEALTHCHECK that probes a real endpoint.', 'লগ stdout-এ লিখুন (কন্টেইনারের ভেতরে ফাইলে নয়), ও একটি HEALTHCHECK সংজ্ঞায়িত করুন যা একটি আসল এন্ডপয়েন্ট প্রোব করে।',
    'Standard logging and healthchecks make containers observable and self-healing, but noisy logs and slow probes cost resources.', 'প্রমিত লগিং ও হেলথচেক কন্টেইনারকে অবজার্ভেবল ও স্ব-নিরাময়ী করে, তবে হইচই লগ ও ধীর প্রোব রিসোর্স খরচ করে।',
    'Writing logs to a file inside the container, so they disappear with the container and are missed by the platform.', 'কন্টেইনারের ভেতরে একটি ফাইলে লগ লেখা, ফলে কন্টেইনারের সঙ্গে হারায় ও প্ল্যাটফর্ম মিস করে।'],
  ['dk-registry-ci', 'dk-production', 'Registries & CI/CD', 'রেজিস্ট্রি ও CI/CD', 'Advanced', 14, 'dk-registry',
    'In CI, you build an image, tag it (often with the commit), push it to a registry, and deploy that exact tag.', 'CI-তে আপনি একটি ইমেজ বিল্ড করেন, ট্যাগ দেন (প্রায়ই কমিট দিয়ে), একটি রেজিস্ট্রিতে পুশ করেন, ও ঠিক সেই ট্যাগ ডিপ্লয় করেন।',
    'A factory line that stamps each batch with a serial number, stores it in the warehouse, and ships that exact batch.', 'একটি কারখানা লাইন যা প্রতিটি ব্যাচে একটি সিরিয়াল নম্বর দেয়, গুদামে রাখে, ও ঠিক সেই ব্যাচ শিপ করে।',
    'Build and push in CI with an immutable tag, then deploy by digest or tag so what you tested is exactly what runs.', 'CI-তে একটি ইমিউটেবল ট্যাগ দিয়ে বিল্ড ও পুশ করুন, তারপর ডাইজেস্ট বা ট্যাগে ডিপ্লয় করুন যাতে যা টেস্ট করলেন তাই চলে।',
    'A registry-driven pipeline makes deploys reproducible and rollback-able, but it adds infrastructure and credentials to secure.', 'রেজিস্ট্রি-চালিত পাইপলাইন ডিপ্লয়কে পুনরুৎপাদনযোগ্য ও রোলব্যাক-যোগ্য করে, তবে সুরক্ষিত করার অবকাঠামো ও ক্রেডেনশিয়াল যোগ করে।',
    'Building the image on the production host at deploy time instead of pulling a tested one from a registry.', 'রেজিস্ট্রি থেকে একটি টেস্টেড ইমেজ পুল না করে ডিপ্লয়ের সময় প্রোডাকশন হোস্টে ইমেজ বিল্ড করা।'],
  ['dk-orchestration', 'dk-production', 'Beyond Docker: orchestration', 'ডকারের বাইরে: অর্কেস্ট্রেশন', 'Advanced', 14, 'dk-registry',
    'Orchestrators like Kubernetes run containers across many machines, handling scheduling, scaling, healing, and networking.', 'কুবারনেটিসের মতো অর্কেস্ট্রেটর অনেক মেশিনজুড়ে কন্টেইনার চালায়, শিডিউলিং, স্কেলিং, নিরাময় ও নেটওয়ার্কিং সামলায়।',
    'Docker builds and runs one container; an orchestrator is the air-traffic control for a whole fleet of them.', 'ডকার একটি কন্টেইনার বিল্ড ও রান করে; অর্কেস্ট্রেটর হলো তাদের পুরো বহরের এয়ার-ট্রাফিক কন্ট্রোল।',
    'Master containers with Docker first; move to Kubernetes when you need multi-host scaling, self-healing, and rollouts.', 'আগে ডকার দিয়ে কন্টেইনার আয়ত্ত করুন; মাল্টি-হোস্ট স্কেলিং, স্ব-নিরাময় ও রোলআউট দরকার হলে কুবারনেটিসে যান।',
    'Orchestrators unlock resilient scale, but they add major operational complexity that many small apps do not need.', 'অর্কেস্ট্রেটর স্থিতিস্থাপক স্কেল খোলে, তবে বড় অপারেশনাল জটিলতা যোগ করে যা অনেক ছোট অ্যাপের দরকার নেই।',
    'Reaching for Kubernetes for a simple single-server app, taking on huge complexity for no real benefit.', 'একটি সরল সিঙ্গল-সার্ভার অ্যাপে কুবারনেটিস ব্যবহার করা, বিনা লাভে বিশাল জটিলতা নেওয়া।'],
]

// Command / instruction reference tables (op = intent, value = command) with 4+ homogeneous rows.
const commands = {
  'dk-pull-run': [['Download an image', 'ইমেজ নামান', 'docker pull nginx'], ['Run a container', 'কন্টেইনার চালান', 'docker run nginx'], ['Run in background', 'ব্যাকগ্রাউন্ডে চালান', 'docker run -d nginx'], ['List running containers', 'চলমান কন্টেইনার', 'docker ps']],
  'dk-tags': [['Tag an image', 'ইমেজ ট্যাগ', 'docker tag app app:1.0'], ['Run a pinned version', 'পিন করা সংস্করণ', 'docker run nginx:1.25'], ['List local images', 'লোকাল ইমেজ', 'docker images'], ['Remove an image', 'ইমেজ রিমুভ', 'docker rmi app:1.0']],
  'dk-inspect': [['List images', 'ইমেজ তালিকা', 'docker images'], ['Show usage', 'ব্যবহার দেখুন', 'docker system df'], ['Inspect details', 'বিস্তারিত দেখুন', 'docker inspect app'], ['Reclaim disk', 'ডিস্ক ফেরান', 'docker image prune']],
  'dk-instructions': [['Set the base image', 'বেস ইমেজ সেট', 'FROM'], ['Run a build command', 'বিল্ড কমান্ড', 'RUN'], ['Copy files in', 'ফাইল কপি', 'COPY'], ['Default run command', 'ডিফল্ট রান কমান্ড', 'CMD'], ['Fixed entry executable', 'নির্দিষ্ট এন্ট্রি', 'ENTRYPOINT']],
  'dk-run-flags': [['Run detached', 'ডিটাচড', '-d'], ['Publish a port', 'পোর্ট পাবলিশ', '-p 8080:80'], ['Set an env var', 'env সেট', '-e KEY=val'], ['Name the container', 'নাম দিন', '--name web'], ['Mount a volume', 'ভলিউম মাউন্ট', '-v vol:/data']],
  'dk-lifecycle': [['List all containers', 'সব কন্টেইনার', 'docker ps -a'], ['Stop a container', 'কন্টেইনার থামান', 'docker stop web'], ['Start it again', 'আবার চালু', 'docker start web'], ['Remove a container', 'কন্টেইনার রিমুভ', 'docker rm web']],
  'dk-exec-logs': [['View logs', 'লগ দেখুন', 'docker logs web'], ['Follow logs', 'লগ follow', 'docker logs -f web'], ['Open a shell inside', 'ভেতরে শেল', 'docker exec -it web sh'], ['Run one command', 'এক কমান্ড', 'docker exec web ls']],
  'dk-volumes': [['Create a volume', 'ভলিউম তৈরি', 'docker volume create data'], ['Mount it', 'মাউন্ট করুন', '-v data:/var/lib'], ['List volumes', 'ভলিউম তালিকা', 'docker volume ls'], ['Remove a volume', 'ভলিউম রিমুভ', 'docker volume rm data']],
  'dk-network-basics': [['List networks', 'নেটওয়ার্ক তালিকা', 'docker network ls'], ['Create a network', 'নেটওয়ার্ক তৈরি', 'docker network create app'], ['Connect a container', 'কন্টেইনার যুক্ত', 'docker network connect app web'], ['Inspect a network', 'নেটওয়ার্ক দেখুন', 'docker network inspect app']],
  'dk-compose-scale': [['Start the stack', 'স্ট্যাক চালু', 'docker compose up -d'], ['Stop and remove', 'থামিয়ে রিমুভ', 'docker compose down'], ['View logs', 'লগ দেখুন', 'docker compose logs -f'], ['Scale a service', 'সার্ভিস স্কেল', 'docker compose up --scale web=3']],
}

// Hands-on code examples (deep dive): title bilingual, lang is a label, code is literal, note bilingual.
const examples = {
  'dk-pull-run': { title: l('Run nginx and open it on port 8080', 'nginx চালিয়ে পোর্ট 8080-এ খুলুন'), lang: 'bash', code: '# pull is automatic on first run\ndocker run -d -p 8080:80 --name web nginx\n\n# check it is running, then open http://localhost:8080\ndocker ps', note: l('-d runs it in the background; -p maps host 8080 to the container’s port 80.', '-d একে ব্যাকগ্রাউন্ডে চালায়; -p হোস্ট 8080-কে কন্টেইনারের পোর্ট 80-এ ম্যাপ করে।') },
  'dk-dockerfile': { title: l('A minimal Node app Dockerfile', 'একটি ন্যূনতম Node অ্যাপ Dockerfile'), lang: 'Dockerfile', code: 'FROM node:20-slim\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nEXPOSE 3000\nCMD ["node", "server.js"]', note: l('Dependencies are copied and installed before the source, so code edits keep the npm cache.', 'সোর্সের আগে ডিপেন্ডেন্সি কপি ও ইনস্টল হয়, তাই কোড এডিটে npm ক্যাশ থাকে।') },
  'dk-build-cache': { title: l('Cache-friendly instruction order', 'ক্যাশ-বান্ধব নির্দেশ ক্রম'), lang: 'Dockerfile', code: '# 1. copy only dependency manifests first\nCOPY package*.json ./\nRUN npm ci\n\n# 2. copy the rest of the source last\nCOPY . .', note: l('Because source is copied last, editing code does not invalidate the cached npm ci layer.', 'সোর্স শেষে কপি হওয়ায় কোড এডিট ক্যাশড npm ci লেয়ার বাতিল করে না।') },
  'dk-multistage': { title: l('Multi-stage build for a tiny final image', 'ছোট চূড়ান্ত ইমেজে মাল্টি-স্টেজ বিল্ড'), lang: 'Dockerfile', code: '# build stage: full toolchain\nFROM node:20 AS build\nWORKDIR /app\nCOPY . .\nRUN npm ci && npm run build\n\n# runtime stage: only the output\nFROM nginx:alpine\nCOPY --from=build /app/dist /usr/share/nginx/html', note: l('The heavy build tools stay in the first stage; only the built files land in the final image.', 'ভারী বিল্ড টুল প্রথম স্টেজে থাকে; শুধু বিল্ড করা ফাইল চূড়ান্ত ইমেজে যায়।') },
  'dk-dockerignore': { title: l('A typical .dockerignore', 'একটি সাধারণ .dockerignore'), lang: 'dockerignore', code: 'node_modules\n.git\n.env\nDockerfile\n*.log\ndist', note: l('Keeping these out of the build context speeds builds and avoids leaking secrets into the image.', 'এগুলো বিল্ড কনটেক্সটের বাইরে রাখা বিল্ড দ্রুত করে ও ইমেজে সিক্রেট ফাঁস এড়ায়।') },
  'dk-image-best': { title: l('Run as a non-root user', 'নন-রুট ব্যবহারকারী হিসেবে চালান'), lang: 'Dockerfile', code: 'FROM node:20-slim\nWORKDIR /app\nCOPY --chown=node:node . .\nRUN npm ci --omit=dev\nUSER node\nCMD ["node", "server.js"]', note: l('USER node drops root, so a compromise inside the container is far less dangerous.', 'USER node root ছাড়ে, তাই কন্টেইনারের ভেতরে একটি আপস অনেক কম বিপজ্জনক।') },
  'dk-run-flags': { title: l('A fully configured run command', 'একটি সম্পূর্ণ কনফিগার করা run কমান্ড'), lang: 'bash', code: 'docker run -d \\\n  --name api \\\n  -p 8080:3000 \\\n  -e NODE_ENV=production \\\n  -v api-data:/app/data \\\n  --restart unless-stopped \\\n  myorg/api:1.4', note: l('Detached, named, port-mapped, configured by env, with a persistent volume and a restart policy.', 'ডিটাচড, নামযুক্ত, পোর্ট-ম্যাপড, env দিয়ে কনফিগার, একটি স্থায়ী ভলিউম ও রিস্টার্ট পলিসিসহ।') },
  'dk-volumes': { title: l('Persist database data in a named volume', 'নেমড ভলিউমে ডেটাবেস ডেটা স্থায়ী করুন'), lang: 'bash', code: 'docker volume create pgdata\n\ndocker run -d --name db \\\n  -e POSTGRES_PASSWORD=secret \\\n  -v pgdata:/var/lib/postgresql/data \\\n  postgres:16', note: l('The data lives in pgdata, so removing and recreating the db container keeps every row.', 'ডেটা pgdata-তে থাকে, তাই db কন্টেইনার রিমুভ ও পুনঃতৈরি করলেও প্রতিটি রো থাকে।') },
  'dk-bind-mounts': { title: l('Live-edit code with a bind mount', 'বাইন্ড মাউন্ট দিয়ে লাইভ কোড এডিট'), lang: 'bash', code: '# changes on the host appear instantly inside the container\ndocker run -d --name dev \\\n  -p 3000:3000 \\\n  -v "$PWD":/app \\\n  -w /app \\\n  node:20 npm run dev', note: l('The current host directory is mounted at /app, so saving a file triggers the app to reload.', 'বর্তমান হোস্ট ডিরেক্টরি /app-এ মাউন্ট, তাই একটি ফাইল সেভ করলে অ্যাপ রিলোড হয়।') },
  'dk-compose-file': { title: l('A two-service compose file', 'দুই-সার্ভিসের compose ফাইল'), lang: 'yaml', code: 'services:\n  web:\n    build: .\n    ports:\n      - "8080:3000"\n    environment:\n      - NODE_ENV=production\n    depends_on:\n      - db\n  db:\n    image: postgres:16\n    environment:\n      - POSTGRES_PASSWORD=secret\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n\nvolumes:\n  pgdata:', note: l('web builds from the Dockerfile and reaches the database at the hostname "db".', 'web Dockerfile থেকে বিল্ড হয় ও "db" হোস্টনামে ডেটাবেসে পৌঁছায়।') },
  'dk-compose-multi': { title: l('Reach another service by name', 'নাম দিয়ে অন্য সার্ভিসে পৌঁছান'), lang: 'bash', code: '# from inside the web container, the db is just "db"\n# e.g. a connection string:\npostgres://user:secret@db:5432/app\n\n# bring the whole stack up\ndocker compose up -d', note: l('Compose puts both services on one network, so "db" resolves to the database container.', 'Compose দুই সার্ভিসকে এক নেটওয়ার্কে রাখে, তাই "db" ডেটাবেস কন্টেইনারে রিজলভ করে।') },
  'dk-compose-scale': { title: l('Common Compose lifecycle commands', 'সাধারণ Compose লাইফসাইকেল কমান্ড'), lang: 'bash', code: 'docker compose up -d          # start in the background\ndocker compose logs -f        # follow all logs\ndocker compose up --scale web=3   # run 3 web replicas\ndocker compose down           # stop and remove (keeps volumes)', note: l('down stops everything but keeps named volumes; add -v only when you truly want the data gone.', 'down সব থামায় কিন্তু নেমড ভলিউম রাখে; ডেটা সত্যিই মুছতে চাইলে তবেই -v দিন।') },
  'dk-backup': { title: l('Back up a volume to a tar file', 'ভলিউম একটি tar ফাইলে ব্যাকআপ'), lang: 'bash', code: '# archive the pgdata volume into the current host directory\ndocker run --rm \\\n  -v pgdata:/data \\\n  -v "$PWD":/backup \\\n  alpine tar czf /backup/pgdata.tar.gz -C /data .', note: l('A throwaway alpine container mounts the volume and writes a compressed archive to the host.', 'একটি ফেলে-দেওয়া alpine কন্টেইনার ভলিউম মাউন্ট করে ও হোস্টে একটি কম্প্রেসড আর্কাইভ লেখে।') },
  'dk-restart': { title: l('A Dockerfile HEALTHCHECK', 'একটি Dockerfile HEALTHCHECK'), lang: 'Dockerfile', code: 'HEALTHCHECK --interval=30s --timeout=3s \\\n  CMD curl -f http://localhost:3000/health || exit 1', note: l('Docker marks the container "unhealthy" if the probe fails, so platforms can restart or route around it.', 'প্রোব ব্যর্থ হলে ডকার কন্টেইনারকে "unhealthy" চিহ্নিত করে, যাতে প্ল্যাটফর্ম রিস্টার্ট বা এড়িয়ে যেতে পারে।') },
  'dk-registry-ci': { title: l('Build, tag, and push in CI', 'CI-তে বিল্ড, ট্যাগ ও পুশ'), lang: 'bash', code: 'docker build -t myorg/api:$GIT_SHA .\ndocker push myorg/api:$GIT_SHA\n\n# deploy the exact tag you just tested\ndocker run -d myorg/api:$GIT_SHA', note: l('Tagging by commit SHA makes every deploy traceable and easy to roll back to a known image.', 'কমিট SHA দিয়ে ট্যাগ করলে প্রতিটি ডিপ্লয় ট্রেসযোগ্য ও একটি জানা ইমেজে রোলব্যাক করা সহজ।') },
}

// Docker-flavoured distractors for generated exams (each is a clearly bad practice).
const distractors = [
  l('Store your database data inside the container’s writable layer.', 'কন্টেইনারের লেখনযোগ্য লেয়ারে আপনার ডেটাবেস ডেটা রাখুন।'),
  l('Always deploy image:latest so it silently changes under you.', 'সবসময় image:latest ডিপ্লয় করুন যাতে এটি নীরবে বদলায়।'),
  l('Run every container as root with secrets baked into the image.', 'সিক্রেট ইমেজে বেক করে প্রতিটি কন্টেইনার root হিসেবে চালান।'),
  l('Copy all source before installing deps so the cache never helps.', 'ডিপেন্ডেন্সির আগে সব সোর্স কপি করুন যাতে ক্যাশ কখনো সাহায্য না করে।'),
  l('Ship the whole build toolchain in the final production image.', 'পুরো বিল্ড টুলচেইন চূড়ান্ত প্রোডাকশন ইমেজে পাঠান।'),
  l('Publish every internal port to the host, firewall be damned.', 'প্রতিটি অভ্যন্তরীণ পোর্ট হোস্টে পাবলিশ করুন, ফায়ারওয়াল যাক।'),
  l('Edit files inside a running container instead of the image.', 'ইমেজের বদলে একটি চলমান কন্টেইনারের ভেতরে ফাইল এডিট করুন।'),
  l('Commit your production .env full of secrets to the repo.', 'সিক্রেটে ভরা প্রোডাকশন .env রিপোতে কমিট করুন।'),
]

export const dockerTopics = rawTopics.map((row, index) => {
  const [id, moduleId, en, bn, difficulty, minutes, diagram, insightEn, insightBn, analogyEn, analogyBn, actionEn, actionBn, tradeoffEn, tradeoffBn, mistakeEn, mistakeBn] = row
  const topic = {
    id, order: index + 1, moduleId, title: l(en, bn), difficulty, minutes, diagram, deepDive: null,
    insight: l(insightEn, insightBn), analogy: l(analogyEn, analogyBn), action: l(actionEn, actionBn), tradeoff: l(tradeoffEn, tradeoffBn), mistake: l(mistakeEn, mistakeBn),
    complexity: (commands[id] || []).map(([opEn, opBn, value]) => ({ op: l(opEn, opBn), value })),
    example: examples[id] || null,
    objectives: [
      l(`Explain ${en} in plain language.`, `সহজ ভাষায় ${bn} ব্যাখ্যা করতে পারবেন।`),
      l('Recognize when to reach for this in a real Docker workflow.', 'বাস্তব ডকার ওয়ার্কফ্লোতে কখন এটি নিতে হবে তা বুঝতে পারবেন।'),
      l('Run the key commands and know what the important flags do.', 'মূল কমান্ড চালাতে ও গুরুত্বপূর্ণ ফ্ল্যাগগুলো কী করে তা জানতে পারবেন।'),
    ],
    advantages: l(`Understanding ${en.toLowerCase()} makes your containers smaller, safer, and more reproducible.`, `${bn} বোঝা আপনার কন্টেইনারকে ছোট, নিরাপদ ও বেশি পুনরুৎপাদনযোগ্য করে।`),
    interview: l(`Show the command or config for ${en.toLowerCase()}, explain what it does, and name a trade-off or pitfall.`, `${bn}-এর কমান্ড বা কনফিগ দেখান, কী করে ব্যাখ্যা করুন, ও একটি ট্রেড-অফ বা ঝুঁকি বলুন।`),
    glossary: [
      { term: l('Image', 'ইমেজ'), definition: l('A read-only template of layers that a container runs from.', 'লেয়ারের একটি রিড-অনলি টেমপ্লেট যা থেকে কন্টেইনার চলে।') },
      { term: l('Container', 'কন্টেইনার'), definition: l('A running instance of an image with its own writable layer.', 'একটি ইমেজের চলমান ইনস্ট্যান্স, নিজের লেখনযোগ্য লেয়ারসহ।') },
    ],
  }
  topic.exam = buildExam(topic, { distractors, subject: 'docker' })
  return topic
})

// ── Guided labs (bilingual) ─────────────────────────────────────────────────
export const dockerLabs = [
  {
    id: 'dk-run-lab', icon: '▶', title: l('Run Your First Container', 'প্রথম কন্টেইনার চালান ল্যাব'), subtitle: l('Pick the right command for each step.', 'প্রতিটি ধাপে সঠিক কমান্ড বাছুন।'),
    stages: [
      ['Start it', 'চালু করুন', 'You want nginx running in the background. Which command?', 'আপনি nginx ব্যাকগ্রাউন্ডে চালাতে চান। কোন কমান্ড?', ['docker run -d nginx', 'docker build nginx'], ['docker run -d nginx', 'docker build nginx'], 0, 'run starts a container; -d detaches it. build makes an image from a Dockerfile.', 'run কন্টেইনার চালু করে; -d ডিটাচ করে। build Dockerfile থেকে ইমেজ বানায়।'],
      ['Expose it', 'খুলুন', 'You must reach it on host port 8080. What do you add?', 'হোস্ট পোর্ট 8080-এ পৌঁছাতে হবে। কী যোগ করবেন?', ['-p 8080:80', '-e 8080:80'], ['-p 8080:80', '-e 8080:80'], 0, '-p publishes host:container ports; -e sets environment variables.', '-p host:container পোর্ট পাবলিশ করে; -e env ভ্যারিয়েবল সেট করে।'],
      ['See it', 'দেখুন', 'You want to confirm it is running. Which command?', 'এটি চলছে নিশ্চিত করতে চান। কোন কমান্ড?', ['docker ps', 'docker images'], ['docker ps', 'docker images'], 0, 'docker ps lists running containers; docker images lists images.', 'docker ps চলমান কন্টেইনার; docker images ইমেজ তালিকা করে।'],
      ['Clean up', 'পরিষ্কার', 'You are done and want to remove the stopped container. Which?', 'শেষ, থামানো কন্টেইনার রিমুভ করতে চান। কোনটি?', ['docker rm web', 'docker stop web'], ['docker rm web', 'docker stop web'], 0, 'stop halts it; rm deletes it. Remove to reclaim the name and disk.', 'stop থামায়; rm মোছে। নাম ও ডিস্ক ফেরাতে রিমুভ করুন।'],
    ],
  },
  {
    id: 'dk-dockerfile-lab', icon: '⌂', title: l('Write a Good Dockerfile', 'ভালো Dockerfile লেখা ল্যাব'), subtitle: l('Make cache-friendly, small-image choices.', 'ক্যাশ-বান্ধব, ছোট-ইমেজ সিদ্ধান্ত নিন।'),
    stages: [
      ['Order for cache', 'ক্যাশের ক্রম', 'For fast rebuilds, what should you COPY and install first?', 'দ্রুত রিবিল্ডে প্রথমে কী COPY ও ইনস্টল করবেন?', ['Dependency files (package.json)', 'The entire source tree'], ['ডিপেন্ডেন্সি ফাইল (package.json)', 'পুরো সোর্স ট্রি'], 0, 'Installing deps before copying source keeps the dependency cache across code edits.', 'সোর্স কপির আগে ডিপ ইনস্টল কোড এডিটেও ডিপেন্ডেন্সি ক্যাশ রাখে।'],
      ['Smaller image', 'ছোট ইমেজ', 'To ship a tiny production image, which technique fits best?', 'একটি ছোট প্রোডাকশন ইমেজ পাঠাতে কোন কৌশল সবচেয়ে মানানসই?', ['A multi-stage build', 'One giant single stage with build tools'], ['একটি মাল্টি-স্টেজ বিল্ড', 'বিল্ড টুলসহ একটি বিশাল সিঙ্গল স্টেজ'], 0, 'Multi-stage builds leave the toolchain behind and ship only the artifact.', 'মাল্টি-স্টেজ বিল্ড টুলচেইন রেখে শুধু আর্টিফ্যাক্ট পাঠায়।'],
      ['Keep it clean', 'পরিষ্কার রাখুন', 'What keeps node_modules and .env out of the build context?', 'node_modules ও .env বিল্ড কনটেক্সটের বাইরে কী রাখে?', ['A .dockerignore file', 'A bigger base image'], ['একটি .dockerignore ফাইল', 'একটি বড় বেস ইমেজ'], 0, '.dockerignore excludes files from the context, speeding builds and avoiding leaks.', '.dockerignore কনটেক্সট থেকে ফাইল বাদ দেয়, বিল্ড দ্রুত করে ও ফাঁস এড়ায়।'],
      ['Run safely', 'নিরাপদে চালান', 'How should the container run for better security?', 'ভালো নিরাপত্তায় কন্টেইনার কীভাবে চলা উচিত?', ['As a non-root USER', 'As root, always'], ['একটি নন-রুট USER হিসেবে', 'সবসময় root হিসেবে'], 0, 'A non-root USER limits the damage of a compromise inside the container.', 'একটি নন-রুট USER কন্টেইনারের ভেতরে আপসের ক্ষতি সীমিত করে।'],
    ],
  },
  {
    id: 'dk-data-lab', icon: '⛁', title: l('Keep the Data', 'ডেটা রাখা ল্যাব'), subtitle: l('Choose storage that survives the container.', 'কন্টেইনারের পরও টিকে থাকা স্টোরেজ বাছুন।'),
    stages: [
      ['Persist a database', 'ডেটাবেস স্থায়ী', 'Your database must keep data across restarts. What do you use?', 'আপনার ডেটাবেস রিস্টার্টেও ডেটা রাখতে হবে। কী ব্যবহার করবেন?', ['A named volume', 'The container’s writable layer'], ['একটি নেমড ভলিউম', 'কন্টেইনারের লেখনযোগ্য লেয়ার'], 0, 'A volume lives outside the container, so data survives removal.', 'ভলিউম কন্টেইনারের বাইরে থাকে, তাই রিমুভেও ডেটা টিকে।'],
      ['Live-edit code', 'লাইভ কোড এডিট', 'In development you want host code edits to appear inside the container. What fits?', 'ডেভেলপমেন্টে হোস্ট কোড এডিট কন্টেইনারে দেখাতে চান। কী মানানসই?', ['A bind mount', 'A named volume'], ['একটি বাইন্ড মাউন্ট', 'একটি নেমড ভলিউম'], 0, 'A bind mount maps a host directory straight into the container.', 'বাইন্ড মাউন্ট হোস্ট ডিরেক্টরি সরাসরি কন্টেইনারে ম্যাপ করে।'],
      ['Danger command', 'বিপজ্জনক কমান্ড', 'Which command can delete your data volumes?', 'কোন কমান্ড আপনার ডেটা ভলিউম মুছতে পারে?', ['docker compose down -v', 'docker compose down'], ['docker compose down -v', 'docker compose down'], 0, 'The -v flag also removes named volumes and the data inside.', '-v ফ্ল্যাগ নেমড ভলিউম ও ভেতরের ডেটাও মোছে।'],
      ['Back it up', 'ব্যাকআপ নিন', 'How do you back up a volume’s contents?', 'একটি ভলিউমের বিষয়বস্তু কীভাবে ব্যাকআপ করবেন?', ['A temp container that tars the volume', 'Copy the container’s ID'], ['ভলিউম tar করা একটি অস্থায়ী কন্টেইনার', 'কন্টেইনারের ID কপি করা'], 0, 'Mount the volume in a helper container and archive it to the host.', 'একটি হেল্পার কন্টেইনারে ভলিউম মাউন্ট করে হোস্টে আর্কাইভ করুন।'],
    ],
  },
  {
    id: 'dk-compose-lab', icon: '❏', title: l('Compose a Stack', 'স্ট্যাক কম্পোজ ল্যাব'), subtitle: l('Wire a web app to its database.', 'একটি ওয়েব অ্যাপকে তার ডেটাবেসে যুক্ত করুন।'),
    stages: [
      ['One command', 'এক কমান্ড', 'You want to start web + db together. Which command?', 'আপনি web + db একসঙ্গে চালাতে চান। কোন কমান্ড?', ['docker compose up -d', 'docker run web db'], ['docker compose up -d', 'docker run web db'], 0, 'Compose reads the file and starts every service defined in it.', 'Compose ফাইল পড়ে ও এতে সংজ্ঞায়িত প্রতিটি সার্ভিস চালু করে।'],
      ['Reach the db', 'db-তে পৌঁছান', 'How does the web service connect to the database?', 'web সার্ভিস কীভাবে ডেটাবেসে সংযোগ করে?', ['By the service name (host "db")', 'By a hard-coded IP'], ['সার্ভিস নাম দিয়ে (হোস্ট "db")', 'একটি হার্ড-কোড করা IP দিয়ে'], 0, 'Compose gives services DNS, so "db" resolves to the database container.', 'Compose সার্ভিসকে DNS দেয়, তাই "db" ডেটাবেস কন্টেইনারে রিজলভ করে।'],
      ['Start order', 'শুরুর ক্রম', 'You want db to start before web. What do you add to web?', 'আপনি চান db, web-এর আগে চালু হোক। web-এ কী যোগ করবেন?', ['depends_on: [db]', 'restart: always'], ['depends_on: [db]', 'restart: always'], 0, 'depends_on orders startup (though it waits for start, not readiness).', 'depends_on শুরুর ক্রম ঠিক করে (তবে প্রস্তুতি নয়, শুরুর জন্য অপেক্ষা করে)।'],
      ['Keep secrets safe', 'সিক্রেট নিরাপদ', 'Where should production secrets live?', 'প্রোডাকশন সিক্রেট কোথায় থাকা উচিত?', ['In an uncommitted .env / secrets', 'Committed in compose.yaml'], ['আন-কমিটেড .env / secrets-এ', 'compose.yaml-এ কমিট করা'], 0, 'Keep secrets out of version control; reference them from the compose file.', 'সিক্রেট ভার্সন কন্ট্রোলের বাইরে রাখুন; compose ফাইল থেকে রেফার করুন।'],
    ],
  },
  {
    id: 'dk-lifecycle-lab', icon: '↻', title: l('Debug a Container', 'কন্টেইনার ডিবাগ ল্যাব'), subtitle: l('Inspect and fix a misbehaving container.', 'একটি ভুল-আচরণকারী কন্টেইনার পরিদর্শন ও ঠিক করুন।'),
    stages: [
      ['Read the output', 'আউটপুট পড়ুন', 'A container keeps exiting. Where do you look first?', 'একটি কন্টেইনার বারবার বেরিয়ে যায়। প্রথমে কোথায় দেখবেন?', ['docker logs web', 'docker images'], ['docker logs web', 'docker images'], 0, 'The logs usually show the error that caused the exit.', 'লগ সাধারণত বেরিয়ে যাওয়ার কারণ এররটি দেখায়।'],
      ['Look inside', 'ভেতরে দেখুন', 'You need a shell inside a running container. Which command?', 'একটি চলমান কন্টেইনারের ভেতরে শেল দরকার। কোন কমান্ড?', ['docker exec -it web sh', 'docker run web sh'], ['docker exec -it web sh', 'docker run web sh'], 0, 'exec runs a command in an existing container; run would start a new one.', 'exec বিদ্যমান কন্টেইনারে কমান্ড চালায়; run নতুন একটি শুরু করত।'],
      ['Persist the fix', 'ফিক্স স্থায়ী', 'You fixed a file inside the container. How do you make it permanent?', 'কন্টেইনারের ভেতরে একটি ফাইল ঠিক করেছেন। স্থায়ী করবেন কীভাবে?', ['Change the Dockerfile and rebuild', 'Leave it in the running container'], ['Dockerfile বদলে রিবিল্ড করুন', 'চলমান কন্টেইনারে রেখে দিন'], 0, 'Edits inside a container vanish on recreate; fix the image instead.', 'কন্টেইনারের ভেতরের এডিট পুনঃতৈরিতে হারায়; বরং ইমেজ ঠিক করুন।'],
      ['Auto-recover', 'স্ব-পুনরুদ্ধার', 'You want it to restart automatically if it crashes. What do you set?', 'ক্র্যাশ করলে স্বয়ংক্রিয় রিস্টার্ট চান। কী সেট করবেন?', ['--restart unless-stopped', 'Nothing — it restarts itself'], ['--restart unless-stopped', 'কিছু না — এটি নিজে রিস্টার্ট করে'], 0, 'A restart policy relaunches the container after a crash or reboot.', 'একটি রিস্টার্ট পলিসি ক্র্যাশ বা রিবুটের পর কন্টেইনার আবার চালায়।'],
    ],
  },
  {
    id: 'dk-production-lab', icon: '☁', title: l('Ship to Production', 'প্রোডাকশনে শিপ ল্যাব'), subtitle: l('Make production-safe image and deploy choices.', 'প্রোডাকশন-নিরাপদ ইমেজ ও ডিপ্লয় সিদ্ধান্ত নিন।'),
    stages: [
      ['Tag it right', 'সঠিক ট্যাগ', 'For a reproducible deploy, how should you tag the image?', 'পুনরুৎপাদনযোগ্য ডিপ্লয়ে ইমেজ কীভাবে ট্যাগ করবেন?', ['With an immutable tag (commit SHA)', 'Always as :latest'], ['একটি ইমিউটেবল ট্যাগ (commit SHA)', 'সবসময় :latest হিসেবে'], 0, 'A fixed tag makes deploys traceable and rollbacks reliable.', 'একটি নির্দিষ্ট ট্যাগ ডিপ্লয় ট্রেসযোগ্য ও রোলব্যাক নির্ভরযোগ্য করে।'],
      ['Where to build', 'কোথায় বিল্ড', 'When should the image be built?', 'ইমেজ কখন বিল্ড হওয়া উচিত?', ['In CI, then pushed to a registry', 'On the prod host at deploy time'], ['CI-তে, তারপর রেজিস্ট্রিতে পুশ', 'ডিপ্লয়ের সময় prod হোস্টে'], 0, 'Build and test once in CI; deploy the exact tested image.', 'CI-তে একবার বিল্ড ও টেস্ট করুন; ঠিক টেস্টেড ইমেজ ডিপ্লয় করুন।'],
      ['Know it is healthy', 'সুস্থতা জানুন', 'How does the platform know the app inside is actually working?', 'ভেতরের অ্যাপ আসলে কাজ করছে প্ল্যাটফর্ম কীভাবে জানে?', ['A HEALTHCHECK probe', 'The container is "running"'], ['একটি HEALTHCHECK প্রোব', 'কন্টেইনার "running"'], 0, '"running" only means the process started; a healthcheck confirms it actually works.', '"running" মানে শুধু প্রসেস শুরু হয়েছে; হেলথচেক নিশ্চিত করে এটি আসলে কাজ করে।'],
      ['Handle logs', 'লগ সামলান', 'Where should the app write its logs?', 'অ্যাপ তার লগ কোথায় লিখবে?', ['To stdout/stderr', 'To a file inside the container'], ['stdout/stderr-এ', 'কন্টেইনারের ভেতরে একটি ফাইলে'], 0, 'Logging to stdout lets the engine and platform collect and ship logs.', 'stdout-এ লগ করলে ইঞ্জিন ও প্ল্যাটফর্ম লগ সংগ্রহ ও শিপ করতে পারে।'],
    ],
  },
].map((lab) => ({ ...lab, stages: lab.stages.map((s, i) => ({ id: `${lab.id}-${i}`, title: l(s[0], s[1]), question: l(s[2], s[3]), options: s[4].map((en, x) => l(en, s[5][x])), correct: s[6], feedback: l(s[7], s[8]) })) }))
