import { l } from '../data.js'
import { buildExam } from './exam-factory.js'
import { k8sGuides } from '../guides/kubernetes-guides.js'

// Kubernetes course — bilingual (English / Bangla), deep build:
// 8 modules, 38 topics, kubectl reference tables, hands-on YAML examples, and guided labs.

export const k8sModules = [
  { id: 'k8s-foundations', number: '01', title: l('Kubernetes foundations', 'কুবারনেটিস ভিত্তি'), description: l('What Kubernetes is, why orchestration, cluster architecture, and the declarative model.', 'কুবারনেটিস কী, কেন অর্কেস্ট্রেশন, ক্লাস্টার আর্কিটেকচার ও ডিক্লারেটিভ মডেল।'), color: '#7c3aed' },
  { id: 'k8s-pods', number: '02', title: l('Pods & workloads', 'পড ও ওয়ার্কলোড'), description: l('Pods, multi-container patterns, labels and selectors, namespaces, and the pod lifecycle.', 'পড, মাল্টি-কন্টেইনার প্যাটার্ন, লেবেল ও সিলেক্টর, নেমস্পেস ও পড লাইফসাইকেল।'), color: '#0284c7' },
  { id: 'k8s-controllers', number: '03', title: l('Controllers', 'কন্ট্রোলার'), description: l('ReplicaSets, Deployments, rolling updates, DaemonSets, StatefulSets, and Jobs.', 'ReplicaSet, Deployment, রোলিং আপডেট, DaemonSet, StatefulSet ও Job।'), color: '#0f9f78' },
  { id: 'k8s-networking', number: '04', title: l('Networking & services', 'নেটওয়ার্কিং ও সার্ভিস'), description: l('Services, service types, cluster DNS, Ingress, and network policies.', 'Service, সার্ভিস টাইপ, ক্লাস্টার DNS, Ingress ও নেটওয়ার্ক পলিসি।'), color: '#0891b2' },
  { id: 'k8s-config', number: '05', title: l('Configuration', 'কনফিগারেশন'), description: l('ConfigMaps, Secrets, config injection, resource requests/limits, and probes.', 'ConfigMap, Secret, কনফিগ ইনজেকশন, রিসোর্স request/limit ও প্রোব।'), color: '#d97706' },
  { id: 'k8s-storage', number: '06', title: l('Storage', 'স্টোরেজ'), description: l('Volumes, PersistentVolumes and Claims, and dynamic provisioning with StorageClasses.', 'ভলিউম, PersistentVolume ও Claim, এবং StorageClass দিয়ে ডায়নামিক প্রভিশনিং।'), color: '#e34b87' },
  { id: 'k8s-operations', number: '07', title: l('Operations & scaling', 'অপারেশন ও স্কেলিং'), description: l('Scaling, autoscaling, debugging pods, and RBAC access control.', 'স্কেলিং, অটোস্কেলিং, পড ডিবাগিং ও RBAC অ্যাক্সেস নিয়ন্ত্রণ।'), color: '#6c5ce7' },
  { id: 'k8s-production', number: '08', title: l('Production & ecosystem', 'প্রোডাকশন ও ইকোসিস্টেম'), description: l('Helm, observability, cluster security, GitOps, and managed Kubernetes.', 'Helm, অবজার্ভেবিলিটি, ক্লাস্টার নিরাপত্তা, GitOps ও ম্যানেজড কুবারনেটিস।'), color: '#188cbd' },
]

const rawTopics = [
  // ── Foundations ───────────────────────────────────────────────────────────
  ['k8s-what', 'k8s-foundations', 'What is Kubernetes?', 'কুবারনেটিস কী?', 'Beginner', 11, 'k8s-cluster',
    'Kubernetes is a container orchestrator that runs and manages containers across a cluster of machines automatically.', 'কুবারনেটিস একটি কন্টেইনার অর্কেস্ট্রেটর যা একটি মেশিন ক্লাস্টারজুড়ে কন্টেইনার স্বয়ংক্রিয়ভাবে চালায় ও পরিচালনা করে।',
    'An air-traffic controller for containers—deciding where each runs, restarting crashes, and balancing the load.', 'কন্টেইনারের জন্য একজন এয়ার-ট্রাফিক কন্ট্রোলার—কোনটি কোথায় চলবে, ক্র্যাশ রিস্টার্ট ও লোড ভারসাম্য ঠিক করে।',
    'Describe the state you want in YAML and let Kubernetes create, place, and heal the containers to match.', 'YAML-এ কাঙ্ক্ষিত অবস্থা বর্ণনা করুন এবং কুবারনেটিসকে মেলাতে কন্টেইনার তৈরি, স্থাপন ও নিরাময় করতে দিন।',
    'Kubernetes gives resilient, scalable automation, but it adds significant complexity you must learn and operate.', 'কুবারনেটিস স্থিতিস্থাপক, স্কেলযোগ্য অটোমেশন দেয়, তবে শেখা ও পরিচালনার উল্লেখযোগ্য জটিলতা যোগ করে।',
    'Adopting Kubernetes for a tiny app that a single Docker host would run just fine.', 'একটি ছোট অ্যাপে কুবারনেটিস নেওয়া যা একটি একক ডকার হোস্টেই ভালো চলত।'],
  ['k8s-why', 'k8s-foundations', 'Why orchestration?', 'কেন অর্কেস্ট্রেশন?', 'Beginner', 11, 'k8s-cluster',
    'Plain Docker runs containers on one host; Kubernetes adds scheduling, scaling, self-healing, and networking across many hosts.', 'সাধারণ ডকার এক হোস্টে কন্টেইনার চালায়; কুবারনেটিস অনেক হোস্টজুড়ে শিডিউলিং, স্কেলিং, স্ব-নিরাময় ও নেটওয়ার্কিং যোগ করে।',
    'One chef (Docker) cooks one kitchen; Kubernetes is the restaurant chain managing many kitchens at once.', 'একজন শেফ (ডকার) এক রান্নাঘর সামলায়; কুবারনেটিস অনেক রান্নাঘর একসঙ্গে পরিচালনার রেস্তোরাঁ চেইন।',
    'Move to Kubernetes when you need multi-host scale, automatic failover, and zero-downtime rollouts.', 'মাল্টি-হোস্ট স্কেল, স্বয়ংক্রিয় ফেলওভার ও জিরো-ডাউনটাইম রোলআউট দরকার হলে কুবারনেটিসে যান।',
    'Orchestration unlocks resilience at scale, but running a cluster costs real operational and cognitive overhead.', 'অর্কেস্ট্রেশন স্কেলে স্থিতিস্থাপকতা খোলে, তবে একটি ক্লাস্টার চালানো বাস্তব অপারেশনাল ও জ্ঞানীয় ওভারহেড খরচ করে।',
    'Expecting Kubernetes to fix a bad app; it orchestrates containers, it does not fix broken code.', 'কুবারনেটিস একটি খারাপ অ্যাপ ঠিক করবে আশা করা; এটি কন্টেইনার অর্কেস্ট্রেট করে, ভাঙা কোড ঠিক করে না।'],
  ['k8s-architecture', 'k8s-foundations', 'Cluster architecture', 'ক্লাস্টার আর্কিটেকচার', 'Intermediate', 13, 'k8s-cluster',
    'A cluster has a control plane (API server, scheduler, etcd) that makes decisions and worker nodes that run the pods.', 'একটি ক্লাস্টারে একটি কন্ট্রোল প্লেন (API সার্ভার, শিডিউলার, etcd) থাকে যা সিদ্ধান্ত নেয় ও ওয়ার্কার নোড যা পড চালায়।',
    'The control plane is the head office giving orders; nodes are the branches doing the actual work.', 'কন্ট্রোল প্লেন হলো আদেশ দেওয়া প্রধান অফিস; নোড হলো আসল কাজ করা শাখা।',
    'Send all requests to the API server (via kubectl); let the scheduler place pods and nodes run them.', 'সব অনুরোধ API সার্ভারে (kubectl দিয়ে) পাঠান; শিডিউলারকে পড স্থাপন ও নোডকে চালাতে দিন।',
    'The split design is highly scalable and resilient, but etcd and the control plane are critical and need protection.', 'বিভক্ত ডিজাইন অত্যন্ত স্কেলযোগ্য ও স্থিতিস্থাপক, তবে etcd ও কন্ট্রোল প্লেন সংকটপূর্ণ ও রক্ষা দরকার।',
    'Running workloads on the control-plane nodes, risking the brain of the cluster under app load.', 'কন্ট্রোল-প্লেন নোডে ওয়ার্কলোড চালানো, অ্যাপ লোডে ক্লাস্টারের মস্তিষ্ক ঝুঁকিতে ফেলা।'],
  ['k8s-objects', 'k8s-foundations', 'Objects & the declarative model', 'অবজেক্ট ও ডিক্লারেটিভ মডেল', 'Beginner', 12, 'k8s-desired',
    'You declare objects (Pods, Deployments, Services) as desired state; controllers continuously work to make reality match.', 'আপনি অবজেক্ট (Pod, Deployment, Service) কাঙ্ক্ষিত অবস্থা হিসেবে ঘোষণা করেন; কন্ট্রোলার অবিরত বাস্তবকে মেলাতে কাজ করে।',
    'A thermostat: you set the target temperature and it constantly adjusts to reach and hold it.', 'একটি থার্মোস্ট্যাট: আপনি লক্ষ্য তাপমাত্রা সেট করেন আর এটি অবিরত তা পৌঁছাতে ও ধরে রাখতে সমন্বয় করে।',
    'Write declarative YAML for what you want, apply it, and let controllers reconcile the cluster to that state.', 'যা চান তার ডিক্লারেটিভ YAML লিখুন, অ্যাপ্লাই করুন, ও কন্ট্রোলারকে ক্লাস্টার সেই অবস্থায় মেলাতে দিন।',
    'Declarative state makes systems self-healing and reproducible, but you must think in terms of end state, not steps.', 'ডিক্লারেটিভ স্টেট সিস্টেমকে স্ব-নিরাময়ী ও পুনরুৎপাদনযোগ্য করে, তবে ধাপ নয়, শেষ-অবস্থায় ভাবতে হয়।',
    'Imperatively patching live objects by hand, so the next apply reverts your change and confuses everyone.', 'হাতে লাইভ অবজেক্ট ইম্পারেটিভলি প্যাচ করা, ফলে পরের apply আপনার পরিবর্তন ফিরিয়ে দেয় ও সবাইকে বিভ্রান্ত করে।'],
  ['k8s-kubectl', 'k8s-foundations', 'kubectl: the CLI', 'kubectl: CLI', 'Beginner', 12, 'k8s-desired',
    'kubectl is the CLI that talks to the API server to create, inspect, update, and delete cluster objects.', 'kubectl হলো CLI যা ক্লাস্টার অবজেক্ট তৈরি, পরিদর্শন, আপডেট ও ডিলিট করতে API সার্ভারের সঙ্গে কথা বলে।',
    'The remote control for your cluster—every button sends a request to the control plane.', 'আপনার ক্লাস্টারের রিমোট কন্ট্রোল—প্রতিটি বোতাম কন্ট্রোল প্লেনে একটি অনুরোধ পাঠায়।',
    'Use kubectl apply -f for declarative changes, and get/describe/logs to inspect what is happening.', 'ডিক্লারেটিভ পরিবর্তনে kubectl apply -f, ও কী ঘটছে দেখতে get/describe/logs ব্যবহার করুন।',
    'kubectl is powerful and scriptable, but imperative one-off commands drift from your version-controlled manifests.', 'kubectl শক্তিশালী ও স্ক্রিপ্টযোগ্য, তবে ইম্পারেটিভ এককালীন কমান্ড আপনার ভার্সন-কন্ট্রোলড ম্যানিফেস্ট থেকে সরে যায়।',
    'Making quick imperative edits with kubectl edit and never reflecting them back into your YAML in git.', 'kubectl edit দিয়ে দ্রুত ইম্পারেটিভ এডিট করা আর কখনো git-এর YAML-এ তা না ফেরানো।'],

  // ── Pods & workloads ──────────────────────────────────────────────────────
  ['k8s-pods', 'k8s-pods', 'Pods: the smallest unit', 'পড: ক্ষুদ্রতম একক', 'Beginner', 12, 'k8s-pod',
    'A pod is the smallest deployable unit—one or more containers that share a network address and storage.', 'একটি পড হলো ক্ষুদ্রতম ডিপ্লয়যোগ্য একক—এক বা একাধিক কন্টেইনার যারা একটি নেটওয়ার্ক ঠিকানা ও স্টোরেজ শেয়ার করে।',
    'A pod is a shared apartment: the containers inside are roommates sharing one address and utilities.', 'একটি পড হলো একটি শেয়ার্ড অ্যাপার্টমেন্ট: ভেতরের কন্টেইনার হলো একটি ঠিকানা ও ইউটিলিটি শেয়ার করা রুমমেট।',
    'Usually run one container per pod; Kubernetes schedules, restarts, and replaces pods as whole units.', 'সাধারণত প্রতি পডে একটি কন্টেইনার চালান; কুবারনেটিস পডকে সম্পূর্ণ একক হিসেবে শিডিউল, রিস্টার্ট ও প্রতিস্থাপন করে।',
    'Pods give a simple shared context, but they are ephemeral—their IP changes and they are replaced, not repaired.', 'পড একটি সরল শেয়ার্ড কনটেক্সট দেয়, তবে ক্ষণস্থায়ী—তাদের IP বদলায় ও এদের মেরামত নয়, প্রতিস্থাপন করা হয়।',
    'Connecting to a pod by its IP, then breaking when the pod is rescheduled with a new address.', 'একটি পডে তার IP দিয়ে সংযোগ করা, তারপর পডটি নতুন ঠিকানায় পুনঃশিডিউল হলে ভাঙা।'],
  ['k8s-multicontainer', 'k8s-pods', 'Multi-container pods & sidecars', 'মাল্টি-কন্টেইনার পড ও সাইডকার', 'Intermediate', 13, 'k8s-pod',
    'A pod can hold multiple containers (like an app plus a sidecar) that cooperate over shared localhost and volumes.', 'একটি পড একাধিক কন্টেইনার (যেমন একটি অ্যাপ ও একটি সাইডকার) রাখতে পারে যারা শেয়ার্ড localhost ও ভলিউমে সহযোগিতা করে।',
    'A main worker with a helper at the same desk—sharing the same phone line and filing cabinet.', 'একই ডেস্কে একজন প্রধান কর্মী ও একজন সহায়ক—একই ফোন লাইন ও ফাইলিং ক্যাবিনেট শেয়ার করে।',
    'Use a sidecar for cross-cutting tasks (logging, proxy) that must live beside the main container.', 'ক্রস-কাটিং কাজে (লগিং, প্রক্সি) সাইডকার ব্যবহার করুন যা মূল কন্টেইনারের পাশে থাকতে হবে।',
    'Sidecars keep concerns separate yet co-located, but they share the pod’s fate—if the pod dies, all containers go.', 'সাইডকার বিষয়গুলো আলাদা তবু একত্র রাখে, তবে পডের ভাগ্য শেয়ার করে—পড মরলে সব কন্টেইনার যায়।',
    'Cramming unrelated services into one pod, coupling their scaling and lifecycle unnecessarily.', 'অসম্পর্কিত সার্ভিস এক পডে ঠাসা, অপ্রয়োজনে তাদের স্কেলিং ও লাইফসাইকেল যুক্ত করা।'],
  ['k8s-labels', 'k8s-pods', 'Labels & selectors', 'লেবেল ও সিলেক্টর', 'Beginner', 12, 'k8s-pod',
    'Labels are key-value tags on objects; selectors use them to group and target sets of pods.', 'লেবেল হলো অবজেক্টে কী-ভ্যালু ট্যাগ; সিলেক্টর এগুলো দিয়ে পডের সেট দলবদ্ধ ও টার্গেট করে।',
    'Colored stickers on files—"find all the red ones" instantly selects a whole group.', 'ফাইলে রঙিন স্টিকার—"সব লাল খুঁজুন" তাৎক্ষণিক একটি পুরো দল বাছে।',
    'Label pods consistently (app, tier, env) and use selectors so Services and Deployments find the right pods.', 'পডে ধারাবাহিকভাবে লেবেল দিন (app, tier, env) ও সিলেক্টর ব্যবহার করুন যাতে Service ও Deployment সঠিক পড পায়।',
    'Labels are flexible and decoupled, but a typo in a selector silently matches nothing or the wrong pods.', 'লেবেল নমনীয় ও ডিকাপলড, তবে সিলেক্টরে একটি টাইপো নীরবে কিছুই বা ভুল পড মেলায়।',
    'A Service selector that does not match the pods’ labels, so it routes to zero endpoints.', 'একটি Service সিলেক্টর যা পডের লেবেলের সঙ্গে মেলে না, ফলে শূন্য এন্ডপয়েন্টে রাউট করে।'],
  ['k8s-namespaces', 'k8s-pods', 'Namespaces', 'নেমস্পেস', 'Beginner', 11, 'k8s-pod',
    'Namespaces partition a cluster into virtual sub-clusters, isolating names, quotas, and access for teams or environments.', 'নেমস্পেস একটি ক্লাস্টারকে ভার্চুয়াল সাব-ক্লাস্টারে ভাগ করে, দল বা এনভায়রনমেন্টের জন্য নাম, কোটা ও অ্যাক্সেস আলাদা করে।',
    'Separate floors in one building—each team gets its own space without bumping into the others.', 'এক ভবনে আলাদা তলা—প্রতিটি দল নিজের জায়গা পায়, অন্যদের সঙ্গে ধাক্কা না খেয়ে।',
    'Use namespaces to separate dev/staging/prod or teams, and set the namespace on each command or context.', 'dev/staging/prod বা দল আলাদা করতে নেমস্পেস ব্যবহার করুন, ও প্রতিটি কমান্ড বা কনটেক্সটে নেমস্পেস সেট করুন।',
    'Namespaces give clean isolation and quotas, but they do not isolate nodes—workloads still share the same machines.', 'নেমস্পেস পরিষ্কার আইসোলেশন ও কোটা দেয়, তবে নোড আলাদা করে না—ওয়ার্কলোড এখনো একই মেশিন শেয়ার করে।',
    'Forgetting which namespace you are in and deleting or editing resources in the wrong environment.', 'কোন নেমস্পেসে আছেন ভুলে গিয়ে ভুল এনভায়রনমেন্টে রিসোর্স ডিলিট বা এডিট করা।'],
  ['k8s-pod-lifecycle', 'k8s-pods', 'Pod lifecycle & restarts', 'পড লাইফসাইকেল ও রিস্টার্ট', 'Intermediate', 13, 'k8s-pod',
    'A pod moves through Pending, Running, and then Succeeded or Failed; the kubelet restarts containers per the restart policy.', 'একটি পড Pending, Running, তারপর Succeeded বা Failed-এর মধ্য দিয়ে যায়; kubelet রিস্টার্ট পলিসি অনুযায়ী কন্টেইনার রিস্টার্ট করে।',
    'A task on a board moving from queued to in-progress to done or failed, with automatic retries.', 'একটি বোর্ডে একটি কাজ কিউড থেকে চলমান থেকে সম্পন্ন বা ব্যর্থ-এ সরছে, স্বয়ংক্রিয় রিট্রাইসহ।',
    'Check pod phase and events with kubectl describe when a pod is stuck in Pending or CrashLoopBackOff.', 'একটি পড Pending বা CrashLoopBackOff-এ আটকে গেলে kubectl describe দিয়ে ফেজ ও ইভেন্ট দেখুন।',
    'Automatic restarts keep apps up, but a container that always crashes enters CrashLoopBackOff and hides the root cause.', 'স্বয়ংক্রিয় রিস্টার্ট অ্যাপ সচল রাখে, তবে সবসময় ক্র্যাশ করা কন্টেইনার CrashLoopBackOff-এ ঢোকে ও মূল কারণ লুকায়।',
    'Assuming a Pending pod is a bug when it is often just no node with enough resources to schedule it.', 'একটি Pending পডকে বাগ ভাবা যখন প্রায়ই শিডিউল করার মতো যথেষ্ট রিসোর্সসহ নোড নেই।'],

  // ── Controllers ───────────────────────────────────────────────────────────
  ['k8s-replicaset', 'k8s-controllers', 'ReplicaSets', 'ReplicaSet', 'Intermediate', 12, 'k8s-desired',
    'A ReplicaSet keeps a specified number of identical pods running, recreating any that die.', 'একটি ReplicaSet নির্দিষ্ট সংখ্যক অভিন্ন পড চালু রাখে, মরে যাওয়াগুলো পুনরায় তৈরি করে।',
    'A supervisor who ensures exactly five workers are always on the floor—if one leaves, another is called in.', 'একজন সুপারভাইজার যিনি নিশ্চিত করেন সবসময় ঠিক পাঁচজন কর্মী মেঝেতে—একজন গেলে আরেকজনকে ডাকা হয়।',
    'Rarely create ReplicaSets directly; use a Deployment, which manages ReplicaSets for you.', 'সরাসরি ReplicaSet কমই বানান; একটি Deployment ব্যবহার করুন, যা আপনার জন্য ReplicaSet সামলায়।',
    'ReplicaSets guarantee a pod count and self-heal, but on their own they cannot do rolling updates between versions.', 'ReplicaSet একটি পড সংখ্যা নিশ্চিত করে ও স্ব-নিরাময় করে, তবে একা তারা ভার্সনের মধ্যে রোলিং আপডেট করতে পারে না।',
    'Managing ReplicaSets by hand for updates instead of letting a Deployment orchestrate them.', 'আপডেটে একটি Deployment-কে অর্কেস্ট্রেট করতে না দিয়ে হাতে ReplicaSet সামলানো।'],
  ['k8s-deployment', 'k8s-controllers', 'Deployments', 'Deployment', 'Beginner', 14, 'k8s-desired',
    'A Deployment manages ReplicaSets to run and update a stateless app, handling rollouts and rollbacks declaratively.', 'একটি Deployment একটি স্টেটলেস অ্যাপ চালাতে ও আপডেট করতে ReplicaSet সামলায়, ডিক্লারেটিভভাবে রোলআউট ও রোলব্যাক করে।',
    'A project manager who swaps the team to a new plan gradually, and can revert if the new plan fails.', 'একজন প্রজেক্ট ম্যানেজার যিনি দলকে ধীরে নতুন পরিকল্পনায় বদলান, ও নতুন পরিকল্পনা ব্যর্থ হলে ফিরে যেতে পারেন।',
    'Define a Deployment with a replica count and pod template, and update it by changing the image and re-applying.', 'একটি রেপ্লিকা সংখ্যা ও পড টেমপ্লেটসহ একটি Deployment সংজ্ঞায়িত করুন, ও ইমেজ বদলে পুনরায় apply করে আপডেট করুন।',
    'Deployments make stateless apps easy to scale and update, but they are not meant for stateful, identity-bound workloads.', 'Deployment স্টেটলেস অ্যাপ স্কেল ও আপডেট সহজ করে, তবে স্টেটফুল, পরিচয়-বদ্ধ ওয়ার্কলোডের জন্য নয়।',
    'Using a Deployment for a database that needs stable identity and storage, where a StatefulSet fits.', 'একটি ডেটাবেসে Deployment ব্যবহার যা স্থিতিশীল পরিচয় ও স্টোরেজ চায়, যেখানে StatefulSet মানানসই।'],
  ['k8s-rollout', 'k8s-controllers', 'Rolling updates & rollbacks', 'রোলিং আপডেট ও রোলব্যাক', 'Intermediate', 14, 'k8s-rollout',
    'A rolling update replaces old pods with new ones gradually, keeping the app available and allowing instant rollback.', 'একটি রোলিং আপডেট পুরনো পডকে ধীরে নতুন দিয়ে প্রতিস্থাপন করে, অ্যাপ সচল রাখে ও তাৎক্ষণিক রোলব্যাক দেয়।',
    'Replacing a fleet’s tires one vehicle at a time so deliveries never stop.', 'একটি বহরের টায়ার একবারে একটি গাড়ি করে বদলানো যাতে ডেলিভারি কখনো না থামে।',
    'Update the Deployment’s image and watch kubectl rollout status; use rollout undo to revert instantly.', 'Deployment-এর ইমেজ আপডেট করে kubectl rollout status দেখুন; তাৎক্ষণিক ফিরতে rollout undo ব্যবহার করুন।',
    'Rolling updates give zero-downtime deploys, but during the roll two versions run at once, which your app must tolerate.', 'রোলিং আপডেট জিরো-ডাউনটাইম ডিপ্লয় দেয়, তবে রোলের সময় দুই ভার্সন একসঙ্গে চলে, যা আপনার অ্যাপকে সহ্য করতে হয়।',
    'Rolling out a change that is not backward compatible, breaking clients while both versions run together.', 'ব্যাকওয়ার্ড-সামঞ্জস্যহীন একটি পরিবর্তন রোল করা, দুই ভার্সন একসঙ্গে চলাকালে ক্লায়েন্ট ভাঙা।'],
  ['k8s-daemonset', 'k8s-controllers', 'DaemonSets', 'DaemonSet', 'Intermediate', 12, 'k8s-desired',
    'A DaemonSet runs exactly one copy of a pod on every node, for cluster-wide agents like log or metrics collectors.', 'একটি DaemonSet প্রতিটি নোডে ঠিক একটি পড কপি চালায়, লগ বা মেট্রিক্স কালেক্টরের মতো ক্লাস্টার-ব্যাপী এজেন্টের জন্য।',
    'A security guard posted at every entrance—one per door, automatically, no matter how many doors there are.', 'প্রতিটি প্রবেশপথে একজন নিরাপত্তা রক্ষী—প্রতি দরজায় একটি, স্বয়ংক্রিয়ভাবে, যত দরজাই থাকুক।',
    'Use a DaemonSet for node-level tools (logging, monitoring, networking) that must run on all nodes.', 'নোড-স্তরের টুলে (লগিং, মনিটরিং, নেটওয়ার্কিং) DaemonSet ব্যবহার করুন যা সব নোডে চলতে হবে।',
    'DaemonSets guarantee per-node coverage automatically, but they consume resources on every node, including new ones.', 'DaemonSet স্বয়ংক্রিয়ভাবে প্রতি-নোড কভারেজ নিশ্চিত করে, তবে নতুনসহ প্রতিটি নোডে রিসোর্স খরচ করে।',
    'Using a DaemonSet for a regular app, running needless copies on every node instead of a fixed replica count.', 'একটি সাধারণ অ্যাপে DaemonSet ব্যবহার, নির্দিষ্ট রেপ্লিকার বদলে প্রতি নোডে অপ্রয়োজনীয় কপি চালানো।'],
  ['k8s-statefulset', 'k8s-controllers', 'StatefulSets', 'StatefulSet', 'Advanced', 15, 'k8s-desired',
    'A StatefulSet runs stateful pods with stable names, ordered startup, and each its own persistent storage.', 'একটি StatefulSet স্থিতিশীল নাম, ক্রমিক শুরু ও প্রত্যেকের নিজস্ব স্থায়ী স্টোরেজসহ স্টেটফুল পড চালায়।',
    'Numbered lockers assigned to specific people—person 0 always gets locker 0 with their own belongings.', 'নির্দিষ্ট ব্যক্তিদের বরাদ্দ নম্বরযুক্ত লকার—ব্যক্তি ০ সবসময় নিজের জিনিসসহ লকার ০ পায়।',
    'Use a StatefulSet for databases and clustered systems that need stable identities and per-pod volumes.', 'ডেটাবেস ও ক্লাস্টার্ড সিস্টেমে StatefulSet ব্যবহার করুন যাদের স্থিতিশীল পরিচয় ও প্রতি-পড ভলিউম দরকার।',
    'StatefulSets provide stable identity and storage, but they are more complex to scale and update than Deployments.', 'StatefulSet স্থিতিশীল পরিচয় ও স্টোরেজ দেয়, তবে Deployment-এর চেয়ে স্কেল ও আপডেট করা বেশি জটিল।',
    'Reaching for a StatefulSet when your app is actually stateless and a Deployment would be simpler.', 'অ্যাপ আসলে স্টেটলেস ও Deployment সহজ হতো যেখানে StatefulSet ব্যবহার করা।'],
  ['k8s-jobs', 'k8s-controllers', 'Jobs & CronJobs', 'Job ও CronJob', 'Intermediate', 13, 'k8s-desired',
    'A Job runs a pod to completion for a one-off task; a CronJob runs Jobs on a schedule.', 'একটি Job একটি এককালীন কাজের জন্য একটি পড সম্পূর্ণ হওয়া পর্যন্ত চালায়; একটি CronJob শিডিউলে Job চালায়।',
    'A Job is a one-time errand; a CronJob is a recurring calendar reminder that fires the errand.', 'একটি Job হলো এককালীন কাজ; একটি CronJob হলো একটি পুনরাবৃত্ত ক্যালেন্ডার রিমাইন্ডার যা কাজটি চালায়।',
    'Use a Job for batch tasks (migrations, backups) and a CronJob for scheduled ones, with a schedule in cron format.', 'ব্যাচ কাজে (মাইগ্রেশন, ব্যাকআপ) Job ও শিডিউলড কাজে CronJob ব্যবহার করুন, cron ফরম্যাটে শিডিউলসহ।',
    'Jobs guarantee a task runs to completion with retries, but long or overlapping CronJobs can pile up if one runs slow.', 'Job রিট্রাইসহ একটি কাজ সম্পূর্ণ চালানো নিশ্চিত করে, তবে দীর্ঘ বা ওভারল্যাপিং CronJob একটি ধীর হলে জমতে পারে।',
    'Running a batch task as a long-lived Deployment that never exits instead of a Job that completes.', 'সম্পন্ন হওয়া Job-এর বদলে কখনো না-বেরোনো দীর্ঘজীবী Deployment হিসেবে একটি ব্যাচ কাজ চালানো।'],

  // ── Networking & services ─────────────────────────────────────────────────
  ['k8s-service', 'k8s-networking', 'Services', 'Service', 'Beginner', 14, 'k8s-service',
    'A Service gives a stable virtual IP and DNS name that load-balances traffic across a changing set of pods.', 'একটি Service একটি স্থিতিশীল ভার্চুয়াল IP ও DNS নাম দেয় যা বদলানো পড সেটজুড়ে ট্রাফিক লোড-ব্যালান্স করে।',
    'A front desk phone number that always works, even as the staff behind it change shifts.', 'একটি ফ্রন্ট ডেস্ক ফোন নম্বর যা সবসময় কাজ করে, পেছনের কর্মী শিফট বদলালেও।',
    'Create a Service selecting your pods by label; other pods reach it by its stable name, not pod IPs.', 'লেবেল দিয়ে আপনার পড নির্বাচন করা একটি Service বানান; অন্য পড এটিকে স্থিতিশীল নামে পৌঁছায়, পড IP নয়।',
    'Services decouple clients from ephemeral pods, but the default ClusterIP is only reachable inside the cluster.', 'Service ক্লায়েন্টকে ক্ষণস্থায়ী পড থেকে ডিকাপল করে, তবে ডিফল্ট ClusterIP শুধু ক্লাস্টারের ভেতরে পৌঁছানো যায়।',
    'Expecting a ClusterIP Service to be reachable from outside the cluster, which it is not.', 'একটি ClusterIP Service ক্লাস্টারের বাইরে থেকে পৌঁছানো যাবে আশা করা, যা যায় না।'],
  ['k8s-service-types', 'k8s-networking', 'Service types', 'সার্ভিস টাইপ', 'Intermediate', 13, 'k8s-service',
    'ClusterIP is internal-only, NodePort opens a port on every node, and LoadBalancer provisions an external cloud load balancer.', 'ClusterIP শুধু অভ্যন্তরীণ, NodePort প্রতিটি নোডে একটি পোর্ট খোলে, ও LoadBalancer একটি বাহ্যিক ক্লাউড লোড ব্যালান্সার দেয়।',
    'Internal extension (ClusterIP), a side door with a number (NodePort), or a public street address (LoadBalancer).', 'অভ্যন্তরীণ এক্সটেনশন (ClusterIP), নম্বরযুক্ত একটি পাশের দরজা (NodePort), বা একটি পাবলিক রাস্তার ঠিকানা (LoadBalancer)।',
    'Use ClusterIP for internal traffic, LoadBalancer for public services in the cloud, and Ingress to consolidate HTTP.', 'অভ্যন্তরীণ ট্রাফিকে ClusterIP, ক্লাউডে পাবলিক সার্ভিসে LoadBalancer, ও HTTP একত্র করতে Ingress ব্যবহার করুন।',
    'LoadBalancer is the easy public path, but one per service gets expensive—Ingress shares one entry point across many.', 'LoadBalancer সহজ পাবলিক পথ, তবে প্রতি সার্ভিসে একটি ব্যয়বহুল হয়—Ingress অনেকজুড়ে একটি প্রবেশপথ শেয়ার করে।',
    'Creating a LoadBalancer per microservice and running up a large, unnecessary cloud bill.', 'প্রতি মাইক্রোসার্ভিসে একটি LoadBalancer বানিয়ে একটি বড়, অপ্রয়োজনীয় ক্লাউড বিল তোলা।'],
  ['k8s-dns', 'k8s-networking', 'Cluster DNS & discovery', 'ক্লাস্টার DNS ও ডিসকভারি', 'Intermediate', 12, 'k8s-service',
    'Cluster DNS gives every Service a name (service.namespace.svc) so pods find each other by name, not IP.', 'ক্লাস্টার DNS প্রতিটি Service-কে একটি নাম দেয় (service.namespace.svc) যাতে পড IP নয়, নাম দিয়ে একে অপরকে খুঁজে।',
    'A phone directory for the cluster—dial "database" by name and it connects to the right service.', 'ক্লাস্টারের একটি ফোন ডিরেক্টরি—নাম দিয়ে "database" ডায়াল করুন আর সঠিক সার্ভিসে যুক্ত হয়।',
    'Connect between services using the Service name; use the full name across namespaces (svc.namespace).', 'সার্ভিসের মধ্যে Service নাম দিয়ে সংযোগ করুন; নেমস্পেসজুড়ে পূর্ণ নাম (svc.namespace) ব্যবহার করুন।',
    'DNS-based discovery is stable and simple, but stale DNS caching in apps can delay picking up endpoint changes.', 'DNS-ভিত্তিক ডিসকভারি স্থিতিশীল ও সরল, তবে অ্যাপে পুরনো DNS ক্যাশিং এন্ডপয়েন্ট পরিবর্তন নিতে দেরি করাতে পারে।',
    'Hard-coding a Service’s cluster IP instead of its DNS name, which breaks when the Service is recreated.', 'একটি Service-এর DNS নামের বদলে ক্লাস্টার IP হার্ড-কোড করা, যা Service পুনঃতৈরিতে ভাঙে।'],
  ['k8s-ingress', 'k8s-networking', 'Ingress', 'Ingress', 'Advanced', 15, 'k8s-ingress',
    'An Ingress routes external HTTP/HTTPS traffic to internal Services by host and path, through one entry point.', 'একটি Ingress বাহ্যিক HTTP/HTTPS ট্রাফিক হোস্ট ও পাথ অনুযায়ী অভ্যন্তরীণ Service-এ পাঠায়, একটি প্রবেশপথ দিয়ে।',
    'A building receptionist who directs each visitor to the right department based on who they ask for.', 'একজন ভবন রিসেপশনিস্ট যিনি প্রতিটি দর্শককে তারা কাকে খোঁজে তার ভিত্তিতে সঠিক বিভাগে পাঠান।',
    'Define Ingress rules mapping hostnames/paths to Services, and run an ingress controller to enforce them.', 'হোস্টনাম/পাথকে Service-এ ম্যাপ করা Ingress নিয়ম সংজ্ঞায়িত করুন, ও এদের কার্যকর করতে একটি ingress কন্ট্রোলার চালান।',
    'Ingress consolidates routing and TLS at one point, but it needs a controller and becomes a critical shared component.', 'Ingress রাউটিং ও TLS এক বিন্দুতে একত্র করে, তবে একটি কন্ট্রোলার লাগে ও একটি সংকটপূর্ণ শেয়ার্ড উপাদান হয়।',
    'Creating Ingress rules without deploying an ingress controller, so nothing actually routes the traffic.', 'একটি ingress কন্ট্রোলার ডিপ্লয় না করে Ingress নিয়ম বানানো, ফলে কিছুই আসলে ট্রাফিক রাউট করে না।'],
  ['k8s-networkpolicy', 'k8s-networking', 'Network policies', 'নেটওয়ার্ক পলিসি', 'Advanced', 14, 'k8s-service',
    'By default all pods can talk to each other; a NetworkPolicy restricts which pods may connect, like a firewall.', 'ডিফল্টে সব পড একে অপরের সঙ্গে কথা বলতে পারে; একটি NetworkPolicy কোন পড সংযোগ করতে পারবে তা সীমিত করে, ফায়ারওয়ালের মতো।',
    'Access rules between departments—only the ones you explicitly allow can call each other.', 'বিভাগের মধ্যে অ্যাক্সেস নিয়ম—শুধু যাদের স্পষ্টভাবে অনুমতি দেন তারাই একে অপরকে কল করতে পারে।',
    'Apply NetworkPolicies to allow only required traffic (e.g., web to db) and deny the rest by default.', 'শুধু দরকারি ট্রাফিক (যেমন web থেকে db) অনুমোদন ও বাকিটা ডিফল্টে ডিনাই করতে NetworkPolicy প্রয়োগ করুন।',
    'Network policies greatly reduce lateral movement risk, but they require a supporting CNI plugin and careful rules.', 'নেটওয়ার্ক পলিসি পার্শ্বীয় গতির ঝুঁকি অনেক কমায়, তবে একটি সমর্থক CNI প্লাগইন ও সতর্ক নিয়ম লাগে।',
    'Assuming pods are isolated by default; without a NetworkPolicy every pod can reach every other pod.', 'ধরে নেওয়া পড ডিফল্টে আলাদা; NetworkPolicy ছাড়া প্রতিটি পড প্রতিটি অন্য পডে পৌঁছাতে পারে।'],

  // ── Configuration ─────────────────────────────────────────────────────────
  ['k8s-configmap', 'k8s-config', 'ConfigMaps', 'ConfigMap', 'Beginner', 12, 'k8s-pod',
    'A ConfigMap stores non-secret configuration as key-value data you inject into pods as env vars or files.', 'একটি ConfigMap নন-সিক্রেট কনফিগারেশন কী-ভ্যালু ডেটা হিসেবে রাখে যা env ভ্যার বা ফাইল হিসেবে পডে দেন।',
    'A settings file the app reads at startup—change the settings without rebuilding the app.', 'একটি সেটিংস ফাইল যা অ্যাপ শুরুতে পড়ে—অ্যাপ পুনর্নির্মাণ ছাড়াই সেটিং বদলান।',
    'Put environment-specific, non-sensitive config in a ConfigMap and reference it from the pod spec.', 'এনভায়রনমেন্ট-নির্দিষ্ট, স্পর্শকাতর-নয় কনফিগ একটি ConfigMap-এ রাখুন ও পড স্পেক থেকে রেফার করুন।',
    'ConfigMaps decouple config from images, but they are plain text—never put passwords or keys in them.', 'ConfigMap কনফিগকে ইমেজ থেকে ডিকাপল করে, তবে এগুলো সাধারণ টেক্সট—কখনো পাসওয়ার্ড বা কী রাখবেন না।',
    'Storing secrets in a ConfigMap, exposing them in plain text to anyone who can read the object.', 'একটি ConfigMap-এ সিক্রেট রাখা, অবজেক্ট পড়তে পারা যে কারো কাছে সাধারণ টেক্সটে ফাঁস।'],
  ['k8s-secret', 'k8s-config', 'Secrets', 'Secret', 'Intermediate', 13, 'k8s-pod',
    'A Secret holds sensitive data (passwords, tokens, keys) that Kubernetes injects into pods, kept separate from ConfigMaps.', 'একটি Secret স্পর্শকাতর ডেটা (পাসওয়ার্ড, টোকেন, কী) রাখে যা কুবারনেটিস পডে দেয়, ConfigMap থেকে আলাদা রাখা।',
    'A locked drawer for valuables, handed to the app only when it needs them.', 'মূল্যবান জিনিসের জন্য একটি তালাবদ্ধ ড্রয়ার, শুধু দরকারে অ্যাপকে দেওয়া।',
    'Store credentials in Secrets, reference them as env vars or mounted files, and restrict who can read them via RBAC.', 'ক্রেডেনশিয়াল Secret-এ রাখুন, env ভ্যার বা মাউন্টেড ফাইল হিসেবে রেফার করুন, ও RBAC দিয়ে কে পড়তে পারবে সীমিত করুন।',
    'Secrets separate sensitive data and integrate with pods, but by default they are only base64-encoded, not encrypted at rest.', 'Secret স্পর্শকাতর ডেটা আলাদা করে ও পডে যুক্ত হয়, তবে ডিফল্টে শুধু base64-এনকোডেড, রেস্টে এনক্রিপ্টেড নয়।',
    'Assuming base64 is encryption and committing Secret manifests to git, leaking the credentials.', 'base64-কে এনক্রিপশন ভাবা ও Secret ম্যানিফেস্ট git-এ কমিট করা, ক্রেডেনশিয়াল ফাঁস।'],
  ['k8s-env', 'k8s-config', 'Config injection', 'কনফিগ ইনজেকশন', 'Intermediate', 12, 'k8s-pod',
    'Pods get configuration through environment variables and mounted files, sourced from literals, ConfigMaps, or Secrets.', 'পড এনভায়রনমেন্ট ভ্যারিয়েবল ও মাউন্টেড ফাইল দিয়ে কনফিগারেশন পায়, লিটারাল, ConfigMap বা Secret থেকে।',
    'Dials and a settings card on the machine—set the same appliance differently at each site.', 'মেশিনে ডায়াল ও একটি সেটিংস কার্ড—একই যন্ত্র প্রতিটি সাইটে ভিন্নভাবে সেট।',
    'Inject config with env (from ConfigMaps/Secrets) or mount it as a volume when the app expects a file.', 'env দিয়ে (ConfigMap/Secret থেকে) কনফিগ দিন, বা অ্যাপ একটি ফাইল প্রত্যাশা করলে ভলিউম হিসেবে মাউন্ট করুন।',
    'Externalized config keeps one image reusable everywhere, but too many env vars scattered across specs get hard to track.', 'বাহ্যিক কনফিগ এক ইমেজকে সর্বত্র পুনঃব্যবহারযোগ্য রাখে, তবে স্পেকজুড়ে ছড়ানো অনেক env ভ্যার ট্র্যাক করা কঠিন হয়।',
    'Hard-coding config in the image, so you must rebuild and repush for every environment change.', 'ইমেজে কনফিগ হার্ড-কোড করা, ফলে প্রতিটি এনভায়রনমেন্ট পরিবর্তনে রিবিল্ড ও রিপুশ লাগে।'],
  ['k8s-resources', 'k8s-config', 'Resource requests & limits', 'রিসোর্স request ও limit', 'Intermediate', 14, 'k8s-pod',
    'Requests reserve guaranteed CPU/memory for a pod; limits cap the maximum it can use, guiding scheduling and stability.', 'Request একটি পডের জন্য নিশ্চিত CPU/মেমরি রিজার্ভ করে; limit সর্বোচ্চ ব্যবহার সীমিত করে, শিডিউলিং ও স্থিতিশীলতা নির্দেশ করে।',
    'A reserved table (request) plus a spending cap (limit)—guaranteed a seat, but not the whole restaurant.', 'একটি রিজার্ভড টেবিল (request) ও একটি খরচ সীমা (limit)—একটি আসন নিশ্চিত, তবে পুরো রেস্তোরাঁ নয়।',
    'Set realistic requests so the scheduler places pods well, and limits so one pod cannot starve the node.', 'বাস্তব request সেট করুন যাতে শিডিউলার পড ভালোভাবে রাখে, ও limit যাতে একটি পড নোড অভুক্ত না করে।',
    'Requests and limits improve fairness and packing, but limits set too low cause OOM kills or CPU throttling.', 'Request ও limit ন্যায্যতা ও প্যাকিং উন্নত করে, তবে খুব কম limit OOM kill বা CPU থ্রটলিং ঘটায়।',
    'Running pods with no requests, so the scheduler cannot pack nodes well and one pod can hog everything.', 'request ছাড়া পড চালানো, ফলে শিডিউলার নোড ভালোভাবে প্যাক করতে পারে না ও একটি পড সব দখল করতে পারে।'],
  ['k8s-probes', 'k8s-config', 'Liveness & readiness probes', 'liveness ও readiness প্রোব', 'Intermediate', 13, 'k8s-pod',
    'A liveness probe restarts a hung container; a readiness probe stops sending traffic until the pod is ready to serve.', 'একটি liveness প্রোব একটি ঝুলে থাকা কন্টেইনার রিস্টার্ট করে; একটি readiness প্রোব পড পরিবেশনের জন্য প্রস্তুত না হওয়া পর্যন্ত ট্রাফিক পাঠানো থামায়।',
    'A pulse check (liveness) and an "open for business" sign (readiness)—restart if dead, route only when ready.', 'একটি পালস চেক (liveness) ও একটি "খোলা" সাইন (readiness)—মরলে রিস্টার্ট, প্রস্তুত হলেই রাউট।',
    'Add readiness and liveness probes to real endpoints so Kubernetes routes and restarts based on true health.', 'আসল এন্ডপয়েন্টে readiness ও liveness প্রোব যোগ করুন যাতে কুবারনেটিস সত্যিকার সুস্থতার ভিত্তিতে রাউট ও রিস্টার্ট করে।',
    'Probes make services self-healing and safe to roll, but a too-aggressive liveness probe can restart healthy pods under load.', 'প্রোব সার্ভিসকে স্ব-নিরাময়ী ও রোল-নিরাপদ করে, তবে অতি-আক্রমণাত্মক liveness প্রোব লোডে সুস্থ পড রিস্টার্ট করতে পারে।',
    'Pointing a liveness probe at a slow endpoint, so heavy load triggers needless restarts and a crash loop.', 'একটি liveness প্রোব একটি ধীর এন্ডপয়েন্টে নির্দেশ করা, ফলে ভারী লোড অপ্রয়োজনীয় রিস্টার্ট ও ক্র্যাশ লুপ ঘটায়।'],

  // ── Storage ───────────────────────────────────────────────────────────────
  ['k8s-volumes', 'k8s-storage', 'Volumes', 'ভলিউম', 'Intermediate', 12, 'k8s-pod',
    'A volume gives a pod storage that outlives its containers’ restarts, mounted into the containers at a path.', 'একটি ভলিউম একটি পডকে স্টোরেজ দেয় যা তার কন্টেইনারের রিস্টার্টের চেয়ে বেশি টেকে, একটি পাথে কন্টেইনারে মাউন্ট করা।',
    'A shared scratch pad in the pod that survives a container restart but not the pod being deleted.', 'পডে একটি শেয়ার্ড স্ক্র্যাচ প্যাড যা কন্টেইনার রিস্টার্ট টেকে কিন্তু পড ডিলিট নয়।',
    'Use an emptyDir volume for scratch space shared between a pod’s containers, and PVCs for durable data.', 'একটি পডের কন্টেইনারের মধ্যে শেয়ার্ড স্ক্র্যাচ স্পেসে emptyDir ভলিউম, ও টেকসই ডেটায় PVC ব্যবহার করুন।',
    'Pod volumes are simple, but most volume types die with the pod—durable data needs a PersistentVolume.', 'পড ভলিউম সরল, তবে বেশিরভাগ ভলিউম টাইপ পডের সঙ্গে মরে—টেকসই ডেটায় PersistentVolume লাগে।',
    'Using an emptyDir for data you must keep, then losing it the moment the pod is rescheduled.', 'রাখতে-হওয়া ডেটায় emptyDir ব্যবহার, তারপর পড পুনঃশিডিউল হওয়ার মুহূর্তে তা হারানো।'],
  ['k8s-pv-pvc', 'k8s-storage', 'PersistentVolumes & Claims', 'PersistentVolume ও Claim', 'Advanced', 15, 'k8s-pod',
    'A PersistentVolume is a piece of cluster storage; a PersistentVolumeClaim is a pod’s request to use some of it.', 'একটি PersistentVolume হলো ক্লাস্টার স্টোরেজের একটি অংশ; একটি PersistentVolumeClaim হলো তার কিছু ব্যবহারের পডের অনুরোধ।',
    'A warehouse of storage units (PVs); a claim (PVC) is you renting one unit for your stuff.', 'স্টোরেজ ইউনিটের একটি গুদাম (PV); একটি ক্লেইম (PVC) হলো আপনার জিনিসের জন্য একটি ইউনিট ভাড়া নেওয়া।',
    'Have pods reference a PVC; the PVC binds to a PV so data persists independently of any pod.', 'পডকে একটি PVC রেফার করান; PVC একটি PV-তে বাঁধে যাতে ডেটা যেকোনো পড থেকে স্বাধীনভাবে টেকে।',
    'PV/PVC cleanly separate storage from pods, but reclaim policies decide whether data is kept or deleted when a claim is released.', 'PV/PVC স্টোরেজকে পড থেকে পরিষ্কারভাবে আলাদা করে, তবে রিক্লেইম পলিসি ঠিক করে ক্লেইম ছাড়লে ডেটা রাখা না মোছা হবে।',
    'Using a Delete reclaim policy on important data, so releasing the claim wipes the underlying volume.', 'গুরুত্বপূর্ণ ডেটায় Delete রিক্লেইম পলিসি ব্যবহার, ফলে ক্লেইম ছাড়লে অন্তর্নিহিত ভলিউম মোছে।'],
  ['k8s-storageclass', 'k8s-storage', 'StorageClasses & provisioning', 'StorageClass ও প্রভিশনিং', 'Advanced', 13, 'k8s-pod',
    'A StorageClass defines a type of storage and lets Kubernetes provision PersistentVolumes on demand automatically.', 'একটি StorageClass এক ধরনের স্টোরেজ সংজ্ঞায়িত করে ও কুবারনেটিসকে চাহিদা অনুযায়ী স্বয়ংক্রিয়ভাবে PersistentVolume প্রভিশন করতে দেয়।',
    'Choosing "standard" or "express" shipping—the class picks the tier and the system provisions it for you.', '"স্ট্যান্ডার্ড" বা "এক্সপ্রেস" শিপিং বাছা—ক্লাস টিয়ার বাছে ও সিস্টেম আপনার জন্য প্রভিশন করে।',
    'Reference a StorageClass in a PVC to get dynamically provisioned storage of the right performance tier.', 'একটি PVC-তে একটি StorageClass রেফার করুন যাতে সঠিক পারফরম্যান্স টিয়ারের ডায়নামিকভাবে প্রভিশনড স্টোরেজ পান।',
    'Dynamic provisioning removes manual PV creation, but the wrong class can be slow or costly for the workload.', 'ডায়নামিক প্রভিশনিং ম্যানুয়াল PV তৈরি সরায়, তবে ভুল ক্লাস ওয়ার্কলোডের জন্য ধীর বা ব্যয়বহুল হতে পারে।',
    'Leaving storage on a slow default class for a database that needs fast SSD-backed volumes.', 'দ্রুত SSD-সমর্থিত ভলিউম দরকার এমন ডেটাবেসে ধীর ডিফল্ট ক্লাসে স্টোরেজ রাখা।'],

  // ── Operations & scaling ──────────────────────────────────────────────────
  ['k8s-scaling', 'k8s-operations', 'Scaling deployments', 'ডিপ্লয়মেন্ট স্কেলিং', 'Beginner', 12, 'k8s-desired',
    'Scaling changes how many pod replicas run; more replicas share load and add redundancy.', 'স্কেলিং কতটি পড রেপ্লিকা চলে তা বদলায়; বেশি রেপ্লিকা লোড ভাগ করে ও রিডানডেন্সি যোগ করে।',
    'Opening more checkout lanes when the queue grows, and closing them when it shrinks.', 'কিউ বাড়লে বেশি চেকআউট লেন খোলা, ও কমলে বন্ধ করা।',
    'Scale with kubectl scale or by changing replicas in the Deployment and re-applying the manifest.', 'kubectl scale দিয়ে বা Deployment-এ replicas বদলে ম্যানিফেস্ট পুনরায় apply করে স্কেল করুন।',
    'More replicas add throughput and resilience, but only if the app is stateless and the cluster has spare capacity.', 'বেশি রেপ্লিকা থ্রুপুট ও স্থিতিস্থাপকতা যোগ করে, তবে শুধু অ্যাপ স্টেটলেস ও ক্লাস্টারে অতিরিক্ত ক্ষমতা থাকলে।',
    'Scaling up a stateful app that assumes a single instance, causing data races or duplicate work.', 'একক ইনস্ট্যান্স ধরে নেওয়া একটি স্টেটফুল অ্যাপ স্কেল করা, ডেটা রেস বা ডুপ্লিকেট কাজ ঘটানো।'],
  ['k8s-hpa', 'k8s-operations', 'Horizontal Pod Autoscaler', 'হরাইজন্টাল পড অটোস্কেলার', 'Advanced', 14, 'k8s-desired',
    'The Horizontal Pod Autoscaler adds or removes replicas automatically based on metrics like CPU or memory usage.', 'হরাইজন্টাল পড অটোস্কেলার CPU বা মেমরি ব্যবহারের মতো মেট্রিকের ভিত্তিতে স্বয়ংক্রিয়ভাবে রেপ্লিকা যোগ বা সরায়।',
    'A thermostat for capacity—more heat (load) automatically brings more radiators (pods) online.', 'ক্ষমতার জন্য একটি থার্মোস্ট্যাট—বেশি তাপ (লোড) স্বয়ংক্রিয়ভাবে বেশি রেডিয়েটর (পড) আনে।',
    'Define an HPA with a target metric and min/max replicas; ensure pods have resource requests for CPU-based scaling.', 'একটি টার্গেট মেট্রিক ও min/max রেপ্লিকাসহ একটি HPA সংজ্ঞায়িত করুন; CPU-ভিত্তিক স্কেলিংয়ে পডে রিসোর্স request নিশ্চিত করুন।',
    'Autoscaling matches capacity to demand, but it reacts with a lag and cannot help if the cluster has no room to grow.', 'অটোস্কেলিং ক্ষমতাকে চাহিদার সঙ্গে মেলায়, তবে দেরিতে সাড়া দেয় ও ক্লাস্টারে বাড়ার জায়গা না থাকলে সাহায্য করতে পারে না।',
    'Configuring an HPA without resource requests, so it has no CPU baseline to scale against and does nothing.', 'রিসোর্স request ছাড়া HPA কনফিগার করা, ফলে স্কেল করার CPU বেসলাইন নেই ও কিছু করে না।'],
  ['k8s-debug', 'k8s-operations', 'Debugging pods', 'পড ডিবাগিং', 'Intermediate', 13, 'k8s-pod',
    'Debug pods with logs (output), describe (events and state), and exec (a shell inside a running container).', 'পড ডিবাগ করুন logs (আউটপুট), describe (ইভেন্ট ও স্টেট), ও exec (একটি চলমান কন্টেইনারে শেল) দিয়ে।',
    'A doctor’s workflow—read the chart (logs), check vitals and history (describe), then examine directly (exec).', 'একজন ডাক্তারের ওয়ার্কফ্লো—চার্ট পড়া (logs), ভাইটাল ও ইতিহাস দেখা (describe), তারপর সরাসরি পরীক্ষা (exec)।',
    'Start with kubectl describe pod for events, then kubectl logs, and kubectl exec -it to inspect from inside.', 'ইভেন্টে kubectl describe pod দিয়ে শুরু, তারপর kubectl logs, ও ভেতর থেকে দেখতে kubectl exec -it।',
    'These tools localize most problems fast, but exec changes are lost on restart—fix the manifest, not the live pod.', 'এই টুল বেশিরভাগ সমস্যা দ্রুত স্থানীয় করে, তবে exec পরিবর্তন রিস্টার্টে হারায়—লাইভ পড নয়, ম্যানিফেস্ট ঠিক করুন।',
    'Ignoring the Events section of kubectl describe, which usually explains why a pod will not schedule or start.', 'kubectl describe-এর Events অংশ উপেক্ষা করা, যা সাধারণত পড কেন শিডিউল বা চালু হয় না ব্যাখ্যা করে।'],
  ['k8s-rbac', 'k8s-operations', 'RBAC & access control', 'RBAC ও অ্যাক্সেস নিয়ন্ত্রণ', 'Advanced', 14, 'k8s-cluster',
    'RBAC controls who can do what: Roles grant permissions, and RoleBindings attach them to users or service accounts.', 'RBAC নিয়ন্ত্রণ করে কে কী করতে পারে: Role পারমিশন দেয়, ও RoleBinding তা ব্যবহারকারী বা সার্ভিস অ্যাকাউন্টে যুক্ত করে।',
    'Keycards with access levels—each role opens only the doors that role is allowed through.', 'অ্যাক্সেস-স্তরসহ কীকার্ড—প্রতিটি রোল শুধু সেই দরজা খোলে যা সেই রোলের অনুমোদিত।',
    'Grant least privilege: scope Roles to a namespace and bind only the permissions each user or app truly needs.', 'ন্যূনতম অধিকার দিন: Role-কে একটি নেমস্পেসে সীমিত করুন ও প্রতিটি ব্যবহারকারী বা অ্যাপের সত্যিকার দরকারি পারমিশনই বাঁধুন।',
    'RBAC enforces strong access control, but overly broad cluster-admin bindings quietly hand over the whole cluster.', 'RBAC শক্ত অ্যাক্সেস নিয়ন্ত্রণ প্রয়োগ করে, তবে অতি-প্রশস্ত cluster-admin বাইন্ডিং নীরবে পুরো ক্লাস্টার তুলে দেয়।',
    'Granting cluster-admin to an app’s service account for convenience, massively widening the blast radius.', 'সুবিধার জন্য একটি অ্যাপের সার্ভিস অ্যাকাউন্টে cluster-admin দেওয়া, ক্ষতির পরিধি ব্যাপকভাবে বাড়ানো।'],

  // ── Production & ecosystem ────────────────────────────────────────────────
  ['k8s-helm', 'k8s-production', 'Helm: package manager', 'Helm: প্যাকেজ ম্যানেজার', 'Advanced', 14, 'k8s-rollout',
    'Helm is a package manager for Kubernetes: charts bundle templated manifests you install and upgrade as one unit.', 'Helm হলো কুবারনেটিসের একটি প্যাকেজ ম্যানেজার: চার্ট টেমপ্লেটেড ম্যানিফেস্ট বান্ডেল করে যা আপনি এক এককে ইনস্টল ও আপগ্রেড করেন।',
    'An app installer for the cluster—one command sets up a whole application with its config filled in.', 'ক্লাস্টারের জন্য একটি অ্যাপ ইনস্টলার—এক কমান্ড একটি পুরো অ্যাপ্লিকেশন তার কনফিগসহ সেট করে।',
    'Use Helm charts to install complex apps, override values per environment, and upgrade or roll back releases.', 'জটিল অ্যাপ ইনস্টল, প্রতি এনভায়রনমেন্টে ভ্যালু ওভাররাইড, ও রিলিজ আপগ্রেড বা রোলব্যাকে Helm চার্ট ব্যবহার করুন।',
    'Helm makes complex deploys repeatable and configurable, but templated YAML adds indirection that can obscure what deploys.', 'Helm জটিল ডিপ্লয় পুনরাবৃত্তিযোগ্য ও কনফিগারযোগ্য করে, তবে টেমপ্লেটেড YAML একটি ইনডাইরেকশন যোগ করে যা কী ডিপ্লয় হয় অস্পষ্ট করতে পারে।',
    'Installing a third-party chart with default values in production without reviewing what it actually creates.', 'এটি আসলে কী বানায় না দেখে প্রোডাকশনে ডিফল্ট ভ্যালুসহ একটি থার্ড-পার্টি চার্ট ইনস্টল করা।'],
  ['k8s-observability', 'k8s-production', 'Monitoring & observability', 'মনিটরিং ও অবজার্ভেবিলিটি', 'Intermediate', 13, 'k8s-cluster',
    'Observe a cluster with metrics (Prometheus), dashboards (Grafana), centralized logs, and traces to see what is happening.', 'একটি ক্লাস্টার মেট্রিক (Prometheus), ড্যাশবোর্ড (Grafana), কেন্দ্রীভূত লগ ও ট্রেস দিয়ে পর্যবেক্ষণ করুন যাতে কী ঘটছে দেখা যায়।',
    'A cockpit of gauges and recorders—you cannot safely fly a fleet you cannot see.', 'গজ ও রেকর্ডারের একটি ককপিট—যে বহর দেখতে পান না তা নিরাপদে ওড়াতে পারেন না।',
    'Collect pod and node metrics, ship logs centrally, and alert on symptoms like error rate and saturation.', 'পড ও নোড মেট্রিক সংগ্রহ করুন, লগ কেন্দ্রীয়ভাবে পাঠান, ও এরর রেট ও স্যাচুরেশনের মতো উপসর্গে অ্যালার্ট দিন।',
    'Good observability makes incidents fast to diagnose, but collecting everything costs storage, compute, and tuning.', 'ভালো অবজার্ভেবিলিটি ঘটনা দ্রুত নির্ণয় করে, তবে সবকিছু সংগ্রহ স্টোরেজ, কম্পিউট ও টিউনিং খরচ করে।',
    'Only adding monitoring after an outage, so the incident you needed to understand went unrecorded.', 'আউটেজের পরই শুধু মনিটরিং যোগ করা, ফলে যে ঘটনা বুঝতে দরকার ছিল তা রেকর্ড হয়নি।'],
  ['k8s-security', 'k8s-production', 'Cluster security', 'ক্লাস্টার নিরাপত্তা', 'Advanced', 15, 'k8s-cluster',
    'Secure a cluster with RBAC, least-privilege pods (non-root, dropped capabilities), network policies, and scanned images.', 'একটি ক্লাস্টার RBAC, ন্যূনতম-অধিকার পড (নন-রুট, বাদ দেওয়া ক্ষমতা), নেটওয়ার্ক পলিসি ও স্ক্যান করা ইমেজ দিয়ে নিরাপদ করুন।',
    'Defense in depth for a building—ID badges, locked rooms, restricted hallways, and inspected deliveries.', 'একটি ভবনে গভীর প্রতিরক্ষা—আইডি ব্যাজ, তালাবদ্ধ ঘর, সীমিত করিডোর ও পরিদর্শিত ডেলিভারি।',
    'Run pods as non-root with minimal privileges, restrict traffic with NetworkPolicies, and scope RBAC tightly.', 'পড নন-রুট ন্যূনতম সুবিধায় চালান, NetworkPolicy দিয়ে ট্রাফিক সীমিত করুন, ও RBAC কড়াভাবে স্কোপ করুন।',
    'Layered hardening greatly cuts risk, but each control adds configuration and can block legitimate workloads if misapplied.', 'স্তরিত কঠোরতা ঝুঁকি অনেক কমায়, তবে প্রতিটি নিয়ন্ত্রণ কনফিগারেশন যোগ করে ও ভুল প্রয়োগে বৈধ ওয়ার্কলোড ব্লক করতে পারে।',
    'Running everything as root cluster-admin for convenience, so one compromised pod owns the whole cluster.', 'সুবিধার জন্য সবকিছু root cluster-admin হিসেবে চালানো, ফলে একটি আপসকৃত পড পুরো ক্লাস্টার দখল করে।'],
  ['k8s-gitops', 'k8s-production', 'GitOps & declarative deploys', 'GitOps ও ডিক্লারেটিভ ডিপ্লয়', 'Advanced', 14, 'k8s-desired',
    'GitOps makes a git repository the single source of truth; a tool continuously syncs the cluster to match the committed manifests.', 'GitOps একটি git রিপোজিটরিকে সত্যের একক উৎস করে; একটি টুল অবিরত ক্লাস্টারকে কমিট করা ম্যানিফেস্টের সঙ্গে সিংক করে।',
    'A self-correcting autopilot that always flies the route written in the flight plan (git), correcting any drift.', 'একটি স্ব-সংশোধনী অটোপাইলট যা সবসময় ফ্লাইট প্ল্যানে (git) লেখা রুটে ওড়ে, যেকোনো drift সংশোধন করে।',
    'Store all manifests in git and let a GitOps tool (Argo CD, Flux) apply and reconcile them automatically.', 'সব ম্যানিফেস্ট git-এ রাখুন ও একটি GitOps টুল (Argo CD, Flux)-কে স্বয়ংক্রিয়ভাবে apply ও reconcile করতে দিন।',
    'GitOps gives auditable, reversible deploys, but it requires discipline—out-of-band kubectl changes get reverted by the sync.', 'GitOps অডিটযোগ্য, রিভার্সিবল ডিপ্লয় দেয়, তবে শৃঙ্খলা লাগে—আউট-অফ-ব্যান্ড kubectl পরিবর্তন সিংক ফিরিয়ে দেয়।',
    'Mixing manual kubectl edits with GitOps, then being confused when the tool reverts your live changes.', 'GitOps-এর সঙ্গে ম্যানুয়াল kubectl এডিট মেশানো, তারপর টুল আপনার লাইভ পরিবর্তন ফেরালে বিভ্রান্ত হওয়া।'],
  ['k8s-managed', 'k8s-production', 'Managed Kubernetes', 'ম্যানেজড কুবারনেটিস', 'Intermediate', 13, 'k8s-cluster',
    'Managed Kubernetes (EKS, GKE, AKS) runs the control plane for you, so you only manage worker nodes and workloads.', 'ম্যানেজড কুবারনেটিস (EKS, GKE, AKS) আপনার জন্য কন্ট্রোল প্লেন চালায়, তাই আপনি শুধু ওয়ার্কার নোড ও ওয়ার্কলোড সামলান।',
    'Renting a fully staffed venue instead of building and running the whole building yourself.', 'পুরো ভবন নিজে বানিয়ে চালানোর বদলে একটি সম্পূর্ণ-স্টাফড ভেন্যু ভাড়া নেওয়া।',
    'Use a managed service to skip control-plane upgrades and etcd operations, and focus on your apps.', 'কন্ট্রোল-প্লেন আপগ্রেড ও etcd অপারেশন এড়াতে ও অ্যাপে মনোযোগ দিতে একটি ম্যানেজড সার্ভিস ব্যবহার করুন।',
    'Managed clusters remove huge operational burden, but you trade some control and pay the provider’s premium.', 'ম্যানেজড ক্লাস্টার বিশাল অপারেশনাল বোঝা সরায়, তবে কিছু নিয়ন্ত্রণ ছাড়েন ও প্রদানকারীর প্রিমিয়াম দেন।',
    'Assuming managed means hands-off; you still own node sizing, workload upgrades, security, and cost.', 'ধরে নেওয়া ম্যানেজড মানে হাত-ছাড়া; আপনি এখনো নোড সাইজিং, ওয়ার্কলোড আপগ্রেড, নিরাপত্তা ও খরচের মালিক।'],
]

// kubectl / helm reference tables (op = intent, value = command) with 4+ homogeneous rows.
const commands = {
  'k8s-kubectl': [['Show cluster nodes', 'নোড দেখুন', 'kubectl get nodes'], ['List pods', 'পড তালিকা', 'kubectl get pods'], ['Describe a resource', 'রিসোর্স বর্ণনা', 'kubectl describe pod x'], ['Apply a manifest', 'ম্যানিফেস্ট অ্যাপ্লাই', 'kubectl apply -f app.yaml']],
  'k8s-pods': [['List pods', 'পড তালিকা', 'kubectl get pods'], ['Pod details', 'পড বিস্তারিত', 'kubectl describe pod x'], ['Pod logs', 'পড লগ', 'kubectl logs x'], ['Delete a pod', 'পড ডিলিট', 'kubectl delete pod x']],
  'k8s-namespaces': [['List namespaces', 'নেমস্পেস তালিকা', 'kubectl get ns'], ['Create a namespace', 'নেমস্পেস তৈরি', 'kubectl create ns dev'], ['List across all', 'সবজুড়ে তালিকা', 'kubectl get pods -A'], ['Set default namespace', 'ডিফল্ট নেমস্পেস', 'kubectl config set-context --current --namespace=dev']],
  'k8s-deployment': [['Create a deployment', 'ডিপ্লয়মেন্ট তৈরি', 'kubectl create deploy web --image=nginx'], ['List deployments', 'ডিপ্লয়মেন্ট তালিকা', 'kubectl get deploy'], ['Scale it', 'স্কেল', 'kubectl scale deploy web --replicas=3'], ['Apply a manifest', 'ম্যানিফেস্ট অ্যাপ্লাই', 'kubectl apply -f deploy.yaml']],
  'k8s-rollout': [['Check rollout status', 'রোলআউট স্ট্যাটাস', 'kubectl rollout status deploy/web'], ['Roll back', 'রোলব্যাক', 'kubectl rollout undo deploy/web'], ['Restart pods', 'পড রিস্টার্ট', 'kubectl rollout restart deploy/web'], ['Update the image', 'ইমেজ আপডেট', 'kubectl set image deploy/web nginx=nginx:1.25']],
  'k8s-jobs': [['Create a job', 'জব তৈরি', 'kubectl create job pi --image=busybox'], ['List jobs', 'জব তালিকা', 'kubectl get jobs'], ['List cron jobs', 'ক্রন জব তালিকা', 'kubectl get cronjobs'], ['Job logs', 'জব লগ', 'kubectl logs job/pi']],
  'k8s-service': [['Expose a deployment', 'ডিপ্লয়মেন্ট এক্সপোজ', 'kubectl expose deploy web --port=80'], ['List services', 'সার্ভিস তালিকা', 'kubectl get svc'], ['Service details', 'সার্ভিস বিস্তারিত', 'kubectl describe svc web'], ['Port-forward locally', 'লোকাল পোর্ট-ফরোয়ার্ড', 'kubectl port-forward svc/web 8080:80']],
  'k8s-configmap': [['Create from literals', 'লিটারাল থেকে তৈরি', 'kubectl create cm app --from-literal=KEY=val'], ['List config maps', 'কনফিগম্যাপ তালিকা', 'kubectl get cm'], ['View a config map', 'কনফিগম্যাপ দেখুন', 'kubectl describe cm app'], ['Apply a manifest', 'ম্যানিফেস্ট অ্যাপ্লাই', 'kubectl apply -f cm.yaml']],
  'k8s-secret': [['Create a secret', 'সিক্রেট তৈরি', 'kubectl create secret generic db --from-literal=pw=secret'], ['List secrets', 'সিক্রেট তালিকা', 'kubectl get secrets'], ['View a secret', 'সিক্রেট দেখুন', 'kubectl describe secret db'], ['Apply a manifest', 'ম্যানিফেস্ট অ্যাপ্লাই', 'kubectl apply -f secret.yaml']],
  'k8s-scaling': [['Scale a deployment', 'ডিপ্লয়মেন্ট স্কেল', 'kubectl scale deploy web --replicas=5'], ['Check replicas', 'রেপ্লিকা দেখুন', 'kubectl get deploy web'], ['Autoscale it', 'অটোস্কেল', 'kubectl autoscale deploy web --min=2 --max=10'], ['Watch pods', 'পড ওয়াচ', 'kubectl get pods -w']],
  'k8s-pv-pvc': [['List volumes', 'ভলিউম তালিকা', 'kubectl get pv'], ['List claims', 'ক্লেইম তালিকা', 'kubectl get pvc'], ['Describe a claim', 'ক্লেইম বর্ণনা', 'kubectl describe pvc data'], ['Apply a claim', 'ক্লেইম অ্যাপ্লাই', 'kubectl apply -f pvc.yaml']],
  'k8s-debug': [['Pod logs', 'পড লগ', 'kubectl logs x'], ['Follow logs', 'লগ follow', 'kubectl logs -f x'], ['Exec into a pod', 'পডে exec', 'kubectl exec -it x -- sh'], ['Describe for events', 'ইভেন্টে describe', 'kubectl describe pod x']],
  'k8s-rbac': [['List roles', 'রোল তালিকা', 'kubectl get roles'], ['List bindings', 'বাইন্ডিং তালিকা', 'kubectl get rolebindings'], ['Check a permission', 'পারমিশন চেক', 'kubectl auth can-i create pods'], ['Describe a role', 'রোল বর্ণনা', 'kubectl describe role dev']],
  'k8s-helm': [['Add a repo', 'রেপো যোগ', 'helm repo add repo <url>'], ['Install a chart', 'চার্ট ইনস্টল', 'helm install web repo/nginx'], ['List releases', 'রিলিজ তালিকা', 'helm list'], ['Upgrade a release', 'রিলিজ আপগ্রেড', 'helm upgrade web repo/nginx']],
}

// Hands-on YAML / kubectl examples (deep dive).
const examples = {
  'k8s-kubectl': { title: l('The everyday kubectl loop', 'প্রতিদিনের kubectl লুপ'), lang: 'bash', code: 'kubectl apply -f app.yaml     # create or update from a manifest\nkubectl get pods              # see what is running\nkubectl describe pod web-xyz  # events and current state\nkubectl logs -f web-xyz       # follow the container output', note: l('apply is declarative — run it again after editing the file and Kubernetes reconciles the difference.', 'apply ডিক্লারেটিভ — ফাইল এডিটের পর আবার চালান, কুবারনেটিস পার্থক্য মেলায়।') },
  'k8s-pods': { title: l('A minimal Pod manifest', 'একটি ন্যূনতম Pod ম্যানিফেস্ট'), lang: 'yaml', code: 'apiVersion: v1\nkind: Pod\nmetadata:\n  name: web\n  labels:\n    app: web\nspec:\n  containers:\n    - name: nginx\n      image: nginx:1.25\n      ports:\n        - containerPort: 80', note: l('In practice you rarely create bare Pods — a Deployment manages them for you.', 'বাস্তবে খালি Pod কমই বানান — একটি Deployment আপনার জন্য এদের সামলায়।') },
  'k8s-multicontainer': { title: l('App container plus a logging sidecar', 'অ্যাপ কন্টেইনার ও একটি লগিং সাইডকার'), lang: 'yaml', code: 'spec:\n  containers:\n    - name: app\n      image: myorg/app:1.0\n    - name: log-shipper\n      image: fluent/fluent-bit\n      # both share the pod network and can mount the same volume', note: l('The two containers share localhost and volumes, so the sidecar can read the app’s logs.', 'দুই কন্টেইনার localhost ও ভলিউম শেয়ার করে, তাই সাইডকার অ্যাপের লগ পড়তে পারে।') },
  'k8s-namespaces': { title: l('Create and use a namespace', 'একটি নেমস্পেস তৈরি ও ব্যবহার'), lang: 'bash', code: 'kubectl create namespace dev\nkubectl apply -f app.yaml -n dev\nkubectl get pods -n dev\n\n# make dev the default for this context\nkubectl config set-context --current --namespace=dev', note: l('Setting the default namespace saves typing -n on every command in this environment.', 'ডিফল্ট নেমস্পেস সেট করলে এই এনভায়রনমেন্টে প্রতিটি কমান্ডে -n টাইপ করা বাঁচে।') },
  'k8s-deployment': { title: l('A Deployment with three replicas', 'তিন রেপ্লিকার একটি Deployment'), lang: 'yaml', code: 'apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: web\n  template:\n    metadata:\n      labels:\n        app: web\n    spec:\n      containers:\n        - name: web\n          image: nginx:1.25', note: l('The selector must match the pod template labels, or the Deployment manages zero pods.', 'সিলেক্টর পড টেমপ্লেট লেবেলের সঙ্গে মিলতে হবে, না হলে Deployment শূন্য পড সামলায়।') },
  'k8s-rollout': { title: l('Update and roll back a Deployment', 'একটি Deployment আপডেট ও রোলব্যাক'), lang: 'bash', code: 'kubectl set image deploy/web web=nginx:1.26\nkubectl rollout status deploy/web    # watch the rollout\n\n# something broke? revert instantly\nkubectl rollout undo deploy/web', note: l('Kubernetes replaces pods gradually and keeps the previous ReplicaSet so undo is instant.', 'কুবারনেটিস ধীরে পড বদলায় ও আগের ReplicaSet রাখে, তাই undo তাৎক্ষণিক।') },
  'k8s-jobs': { title: l('A CronJob that runs every night', 'প্রতি রাতে চলা একটি CronJob'), lang: 'yaml', code: 'apiVersion: batch/v1\nkind: CronJob\nmetadata:\n  name: nightly-backup\nspec:\n  schedule: "0 2 * * *"\n  jobTemplate:\n    spec:\n      template:\n        spec:\n          restartPolicy: OnFailure\n          containers:\n            - name: backup\n              image: myorg/backup:1.0', note: l('The schedule uses standard cron syntax — here, 02:00 every day.', 'শিডিউল প্রমিত cron সিনট্যাক্স ব্যবহার করে — এখানে প্রতিদিন ০২:০০।') },
  'k8s-service': { title: l('A ClusterIP Service for the web pods', 'web পডের জন্য একটি ClusterIP Service'), lang: 'yaml', code: 'apiVersion: v1\nkind: Service\nmetadata:\n  name: web\nspec:\n  selector:\n    app: web\n  ports:\n    - port: 80\n      targetPort: 80', note: l('The selector app: web makes this Service load-balance across every pod with that label.', 'সিলেক্টর app: web এই Service-কে সেই লেবেলের প্রতিটি পডে লোড-ব্যালান্স করায়।') },
  'k8s-ingress': { title: l('An Ingress routing by path', 'পাথ অনুযায়ী রাউট করা একটি Ingress'), lang: 'yaml', code: 'apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: site\nspec:\n  rules:\n    - host: example.com\n      http:\n        paths:\n          - path: /api\n            pathType: Prefix\n            backend:\n              service:\n                name: api\n                port:\n                  number: 80', note: l('You also need an ingress controller (like nginx-ingress) running for these rules to take effect.', 'এই নিয়ম কার্যকর হতে একটি ingress কন্ট্রোলার (যেমন nginx-ingress) চলাও দরকার।') },
  'k8s-configmap': { title: l('A ConfigMap injected as env vars', 'env ভ্যার হিসেবে দেওয়া একটি ConfigMap'), lang: 'yaml', code: 'apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: app-config\ndata:\n  LOG_LEVEL: info\n  FEATURE_X: "true"\n---\n# in the pod spec:\nenvFrom:\n  - configMapRef:\n      name: app-config', note: l('envFrom turns every key in the ConfigMap into an environment variable in the container.', 'envFrom ConfigMap-এর প্রতিটি কী-কে কন্টেইনারে একটি এনভায়রনমেন্ট ভ্যারিয়েবল করে।') },
  'k8s-secret': { title: l('A Secret referenced as an env var', 'env ভ্যার হিসেবে রেফার করা একটি Secret'), lang: 'yaml', code: 'env:\n  - name: DB_PASSWORD\n    valueFrom:\n      secretKeyRef:\n        name: db\n        key: pw', note: l('The pod reads the value at runtime; the raw secret never has to appear in the pod manifest.', 'পড রানটাইমে মান পড়ে; কাঁচা সিক্রেট পড ম্যানিফেস্টে কখনো দেখাতে হয় না।') },
  'k8s-resources': { title: l('Requests and limits on a container', 'একটি কন্টেইনারে request ও limit'), lang: 'yaml', code: 'resources:\n  requests:\n    cpu: "250m"\n    memory: "256Mi"\n  limits:\n    cpu: "500m"\n    memory: "512Mi"', note: l('requests guide scheduling; limits cap usage. 250m means a quarter of one CPU core.', 'requests শিডিউলিং নির্দেশ করে; limits ব্যবহার সীমিত করে। 250m মানে এক CPU কোরের এক-চতুর্থাংশ।') },
  'k8s-probes': { title: l('Liveness and readiness probes', 'liveness ও readiness প্রোব'), lang: 'yaml', code: 'readinessProbe:\n  httpGet:\n    path: /ready\n    port: 8080\n  initialDelaySeconds: 5\nlivenessProbe:\n  httpGet:\n    path: /health\n    port: 8080\n  periodSeconds: 10', note: l('Readiness gates traffic until the app is up; liveness restarts it if it later hangs.', 'readiness অ্যাপ চালু না হওয়া পর্যন্ত ট্রাফিক আটকায়; liveness পরে ঝুলে গেলে রিস্টার্ট করে।') },
  'k8s-pv-pvc': { title: l('A PersistentVolumeClaim', 'একটি PersistentVolumeClaim'), lang: 'yaml', code: 'apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: data\nspec:\n  accessModes:\n    - ReadWriteOnce\n  resources:\n    requests:\n      storage: 10Gi', note: l('A pod mounts this claim; the PVC binds to a matching PV so the data outlives the pod.', 'একটি পড এই ক্লেইম মাউন্ট করে; PVC একটি মেলা PV-তে বাঁধে যাতে ডেটা পডের চেয়ে বেশি টেকে।') },
  'k8s-hpa': { title: l('A Horizontal Pod Autoscaler', 'একটি হরাইজন্টাল পড অটোস্কেলার'), lang: 'yaml', code: 'apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: web\nspec:\n  scaleTargetRef:\n    apiVersion: apps/v1\n    kind: Deployment\n    name: web\n  minReplicas: 2\n  maxReplicas: 10\n  metrics:\n    - type: Resource\n      resource:\n        name: cpu\n        target:\n          type: Utilization\n          averageUtilization: 70', note: l('The HPA keeps average CPU near 70%, adding pods under load and removing them when idle. It needs CPU requests set.', 'HPA গড় CPU ৭০%-এর কাছে রাখে, লোডে পড যোগ ও অলস হলে সরায়। এতে CPU request সেট থাকা লাগে।') },
}

// Kubernetes-flavoured distractors for generated exams (each is a clearly bad practice).
const distractors = [
  l('Adopt Kubernetes for a tiny app a single Docker host would run fine.', 'একটি ছোট অ্যাপে কুবারনেটিস নিন যা একক ডকার হোস্টেই চলত।'),
  l('Connect to pods by their IP addresses, which change on every restart.', 'পডে তাদের IP ঠিকানা দিয়ে সংযোগ করুন, যা প্রতি রিস্টার্টে বদলায়।'),
  l('Store passwords in a ConfigMap in plain text for everyone to read.', 'পাসওয়ার্ড ConfigMap-এ সাধারণ টেক্সটে রাখুন যাতে সবাই পড়তে পারে।'),
  l('Grant cluster-admin to every app service account for convenience.', 'সুবিধার জন্য প্রতিটি অ্যাপ সার্ভিস অ্যাকাউন্টে cluster-admin দিন।'),
  l('Run workloads on the control-plane nodes to save a few machines.', 'কয়েকটি মেশিন বাঁচাতে কন্ট্রোল-প্লেন নোডে ওয়ার্কলোড চালান।'),
  l('Patch live objects by hand and never update the YAML in git.', 'হাতে লাইভ অবজেক্ট প্যাচ করুন আর git-এর YAML কখনো আপডেট করবেন না।'),
  l('Skip resource requests so the scheduler cannot pack nodes well.', 'রিসোর্স request বাদ দিন যাতে শিডিউলার নোড ভালোভাবে প্যাক করতে না পারে।'),
  l('Create a LoadBalancer per microservice and ignore the cloud bill.', 'প্রতি মাইক্রোসার্ভিসে একটি LoadBalancer বানান ও ক্লাউড বিল উপেক্ষা করুন।'),
]

export const k8sTopics = rawTopics.map((row, index) => {
  const [id, moduleId, en, bn, difficulty, minutes, diagram, insightEn, insightBn, analogyEn, analogyBn, actionEn, actionBn, tradeoffEn, tradeoffBn, mistakeEn, mistakeBn] = row
  const topic = {
    id, order: index + 1, moduleId, title: l(en, bn), difficulty, minutes, diagram, deepDive: null,
    insight: l(insightEn, insightBn), analogy: l(analogyEn, analogyBn), action: l(actionEn, actionBn), tradeoff: l(tradeoffEn, tradeoffBn), mistake: l(mistakeEn, mistakeBn),
    complexity: (commands[id] || []).map(([opEn, opBn, value]) => ({ op: l(opEn, opBn), value })),
    example: examples[id] || null,
    guide: k8sGuides[id] || null,
    objectives: [
      l(`Explain ${en} in plain language.`, `সহজ ভাষায় ${bn} ব্যাখ্যা করতে পারবেন।`),
      l('Recognize when to reach for this in a real cluster.', 'বাস্তব ক্লাস্টারে কখন এটি নিতে হবে তা বুঝতে পারবেন।'),
      l('Run the key kubectl commands and read the manifest fields.', 'মূল kubectl কমান্ড চালাতে ও ম্যানিফেস্ট ফিল্ড পড়তে পারবেন।'),
    ],
    advantages: l(`Understanding ${en.toLowerCase()} lets you run resilient, self-healing workloads at scale.`, `${bn} বোঝা আপনাকে স্কেলে স্থিতিস্থাপক, স্ব-নিরাময়ী ওয়ার্কলোড চালাতে দেয়।`),
    interview: l(`Show the manifest or kubectl command for ${en.toLowerCase()}, explain what it does, and name a trade-off or pitfall.`, `${bn}-এর ম্যানিফেস্ট বা kubectl কমান্ড দেখান, কী করে ব্যাখ্যা করুন, ও একটি ট্রেড-অফ বা ঝুঁকি বলুন।`),
    glossary: [
      { term: l('Pod', 'পড'), definition: l('The smallest deployable unit — one or more containers sharing network and storage.', 'ক্ষুদ্রতম ডিপ্লয়যোগ্য একক—নেটওয়ার্ক ও স্টোরেজ শেয়ার করা এক বা একাধিক কন্টেইনার।') },
      { term: l('Controller', 'কন্ট্রোলার'), definition: l('A loop that keeps actual cluster state matching the declared desired state.', 'একটি লুপ যা ক্লাস্টারের বর্তমান অবস্থাকে ঘোষিত কাঙ্ক্ষিত অবস্থার সঙ্গে মেলায়।') },
    ],
  }
  topic.exam = buildExam(topic, { distractors, subject: 'kubernetes' })
  return topic
})

// ── Guided labs (bilingual) ─────────────────────────────────────────────────
export const k8sLabs = [
  {
    id: 'k8s-deploy-lab', icon: '⎈', title: l('Deploy an App', 'অ্যাপ ডিপ্লয় ল্যাব'), subtitle: l('Get a stateless app running with the right objects.', 'সঠিক অবজেক্ট দিয়ে একটি স্টেটলেস অ্যাপ চালু করুন।'),
    stages: [
      ['Run replicas', 'রেপ্লিকা চালান', 'You want 3 identical, self-healing pods of a stateless app. Which object?', 'একটি স্টেটলেস অ্যাপের ৩টি অভিন্ন, স্ব-নিরাময়ী পড চান। কোন অবজেক্ট?', ['A Deployment', 'A bare Pod'], ['একটি Deployment', 'একটি খালি Pod'], 0, 'A Deployment manages replicas and self-healing; a bare Pod does neither.', 'Deployment রেপ্লিকা ও স্ব-নিরাময় সামলায়; খালি Pod কোনোটিই নয়।'],
      ['Apply it', 'অ্যাপ্লাই করুন', 'How do you create it from a YAML file, the declarative way?', 'ডিক্লারেটিভভাবে একটি YAML ফাইল থেকে কীভাবে বানাবেন?', ['kubectl apply -f deploy.yaml', 'kubectl edit deployment'], ['kubectl apply -f deploy.yaml', 'kubectl edit deployment'], 0, 'apply -f creates or updates from a file you keep in git.', 'apply -f git-এ রাখা একটি ফাইল থেকে তৈরি বা আপডেট করে।'],
      ['Reach it', 'পৌঁছান', 'Other pods must reach it by a stable name. What do you add?', 'অন্য পড এটিকে স্থিতিশীল নামে পৌঁছাতে হবে। কী যোগ করবেন?', ['A Service', 'A second Deployment'], ['একটি Service', 'দ্বিতীয় একটি Deployment'], 0, 'A Service gives a stable name and load-balances across the pods.', 'Service একটি স্থিতিশীল নাম দেয় ও পডজুড়ে লোড-ব্যালান্স করে।'],
      ['Update safely', 'নিরাপদে আপডেট', 'You push a new image and want zero downtime. What happens by default?', 'নতুন ইমেজ পুশ করেন ও জিরো-ডাউনটাইম চান। ডিফল্টে কী হয়?', ['A rolling update', 'All pods restart at once'], ['একটি রোলিং আপডেট', 'সব পড একসঙ্গে রিস্টার্ট'], 0, 'Deployments replace pods gradually, keeping the app available.', 'Deployment ধীরে পড বদলায়, অ্যাপ সচল রাখে।'],
    ],
  },
  {
    id: 'k8s-networking-lab', icon: '⇄', title: l('Wire Up Networking', 'নেটওয়ার্কিং যুক্ত ল্যাব'), subtitle: l('Expose services inside and outside the cluster.', 'ক্লাস্টারের ভেতরে ও বাইরে সার্ভিস এক্সপোজ করুন।'),
    stages: [
      ['Internal only', 'শুধু অভ্যন্তরীণ', 'Which Service type is reachable only inside the cluster?', 'কোন Service টাইপ শুধু ক্লাস্টারের ভেতরে পৌঁছানো যায়?', ['ClusterIP', 'LoadBalancer'], ['ClusterIP', 'LoadBalancer'], 0, 'ClusterIP is the default, internal-only Service type.', 'ClusterIP হলো ডিফল্ট, শুধু-অভ্যন্তরীণ Service টাইপ।'],
      ['Find by name', 'নামে খুঁজুন', 'How should the web pod connect to the database Service?', 'web পড কীভাবে ডেটাবেস Service-এ সংযোগ করবে?', ['By the Service DNS name', 'By the pod IP'], ['Service DNS নাম দিয়ে', 'পড IP দিয়ে'], 0, 'Cluster DNS resolves the Service name to a stable virtual IP.', 'ক্লাস্টার DNS Service নামকে একটি স্থিতিশীল ভার্চুয়াল IP-তে রিজলভ করে।'],
      ['One entry point', 'এক প্রবেশপথ', 'You have many HTTP services and want one external entry point. What fits?', 'অনেক HTTP সার্ভিস আছে ও একটি বাহ্যিক প্রবেশপথ চান। কী মানানসই?', ['An Ingress', 'A LoadBalancer per service'], ['একটি Ingress', 'প্রতি সার্ভিসে একটি LoadBalancer'], 0, 'Ingress consolidates HTTP routing behind one entry point.', 'Ingress এক প্রবেশপথের পেছনে HTTP রাউটিং একত্র করে।'],
      ['Restrict traffic', 'ট্রাফিক সীমিত', 'By default pods can reach any other pod. What locks that down?', 'ডিফল্টে পড যেকোনো পডে পৌঁছাতে পারে। কী তা আটকায়?', ['A NetworkPolicy', 'A ConfigMap'], ['একটি NetworkPolicy', 'একটি ConfigMap'], 0, 'A NetworkPolicy allows only the traffic you explicitly permit.', 'NetworkPolicy শুধু আপনার স্পষ্ট অনুমোদিত ট্রাফিক দেয়।'],
    ],
  },
  {
    id: 'k8s-config-lab', icon: '⚙', title: l('Configure & Secure', 'কনফিগার ও নিরাপদ ল্যাব'), subtitle: l('Inject config and secrets the right way.', 'সঠিকভাবে কনফিগ ও সিক্রেট দিন।'),
    stages: [
      ['Non-secret config', 'নন-সিক্রেট কনফিগ', 'Where do plain, non-sensitive settings belong?', 'সাধারণ, স্পর্শকাতর-নয় সেটিং কোথায় থাকে?', ['A ConfigMap', 'The container image'], ['একটি ConfigMap', 'কন্টেইনার ইমেজ'], 0, 'A ConfigMap keeps config out of the image and easy to change.', 'ConfigMap কনফিগকে ইমেজের বাইরে ও বদলানো সহজ রাখে।'],
      ['Sensitive data', 'স্পর্শকাতর ডেটা', 'Where should a database password live?', 'একটি ডেটাবেস পাসওয়ার্ড কোথায় থাকা উচিত?', ['A Secret', 'A ConfigMap'], ['একটি Secret', 'একটি ConfigMap'], 0, 'Secrets are meant for sensitive data and can be tightly access-controlled.', 'Secret স্পর্শকাতর ডেটার জন্য ও কড়া অ্যাক্সেস-নিয়ন্ত্রিত হতে পারে।'],
      ['Right-size it', 'সঠিক মাপ', 'What lets the scheduler place pods well and cap their usage?', 'কী শিডিউলারকে পড ভালোভাবে রাখতে ও ব্যবহার সীমিত করতে দেয়?', ['requests and limits', 'A bigger node only'], ['requests ও limits', 'শুধু একটি বড় নোড'], 0, 'requests reserve capacity; limits cap it, guiding scheduling and stability.', 'requests ক্ষমতা রিজার্ভ করে; limits সীমিত করে, শিডিউলিং ও স্থিতিশীলতা নির্দেশ করে।'],
      ['Least privilege', 'ন্যূনতম অধিকার', 'How should you grant an app’s service account permissions?', 'একটি অ্যাপের সার্ভিস অ্যাকাউন্টে কীভাবে পারমিশন দেবেন?', ['Only what it needs (scoped RBAC)', 'cluster-admin, to be safe'], ['শুধু যা দরকার (স্কোপড RBAC)', 'নিরাপদ থাকতে cluster-admin'], 0, 'Least-privilege RBAC limits the damage if the app is compromised.', 'ন্যূনতম-অধিকার RBAC অ্যাপ আপস হলে ক্ষতি সীমিত করে।'],
    ],
  },
  {
    id: 'k8s-storage-lab', icon: '⛁', title: l('Persist State', 'স্টেট স্থায়ী ল্যাব'), subtitle: l('Keep data safe across pod restarts.', 'পড রিস্টার্টেও ডেটা নিরাপদ রাখুন।'),
    stages: [
      ['Durable data', 'টেকসই ডেটা', 'A pod must keep data even if it is deleted and recreated. What do you use?', 'পড ডিলিট ও পুনঃতৈরি হলেও ডেটা রাখতে হবে। কী ব্যবহার করবেন?', ['A PersistentVolumeClaim', 'An emptyDir volume'], ['একটি PersistentVolumeClaim', 'একটি emptyDir ভলিউম'], 0, 'A PVC binds to a PersistentVolume that outlives the pod.', 'PVC একটি PersistentVolume-এ বাঁধে যা পডের চেয়ে বেশি টেকে।'],
      ['Auto-provision', 'অটো-প্রভিশন', 'You want storage created on demand at the right tier. What enables that?', 'সঠিক টিয়ারে চাহিদায় স্টোরেজ তৈরি চান। কী তা সম্ভব করে?', ['A StorageClass', 'A NodePort'], ['একটি StorageClass', 'একটি NodePort'], 0, 'A StorageClass dynamically provisions PVs of the chosen type.', 'StorageClass বাছাই টাইপের PV ডায়নামিকভাবে প্রভিশন করে।'],
      ['Stateful app', 'স্টেটফুল অ্যাপ', 'A database needs stable identity and its own volume per pod. Which controller?', 'একটি ডেটাবেসের স্থিতিশীল পরিচয় ও প্রতি পডে নিজের ভলিউম দরকার। কোন কন্ট্রোলার?', ['A StatefulSet', 'A Deployment'], ['একটি StatefulSet', 'একটি Deployment'], 0, 'StatefulSets give stable names and per-pod persistent storage.', 'StatefulSet স্থিতিশীল নাম ও প্রতি-পড স্থায়ী স্টোরেজ দেয়।'],
      ['Protect the data', 'ডেটা রক্ষা', 'Which reclaim policy risks wiping data when a claim is released?', 'কোন রিক্লেইম পলিসি ক্লেইম ছাড়লে ডেটা মোছার ঝুঁকি রাখে?', ['Delete', 'Retain'], ['Delete', 'Retain'], 0, 'Delete removes the underlying volume; Retain keeps it for safety.', 'Delete অন্তর্নিহিত ভলিউম মোছে; Retain নিরাপত্তায় রাখে।'],
    ],
  },
  {
    id: 'k8s-debug-lab', icon: '↻', title: l('Debug a Pod', 'পড ডিবাগ ল্যাব'), subtitle: l('Find why a pod will not run.', 'একটি পড কেন চলছে না খুঁজুন।'),
    stages: [
      ['Read events', 'ইভেন্ট পড়ুন', 'A pod is stuck in Pending. Where do you look first?', 'একটি পড Pending-এ আটকে। প্রথমে কোথায় দেখবেন?', ['kubectl describe pod (Events)', 'kubectl get nodes'], ['kubectl describe pod (Events)', 'kubectl get nodes'], 0, 'The Events section usually says why it cannot schedule (e.g., no resources).', 'Events অংশ সাধারণত কেন শিডিউল হয় না বলে (যেমন রিসোর্স নেই)।'],
      ['Read output', 'আউটপুট পড়ুন', 'A pod is CrashLoopBackOff. What shows the crash reason?', 'একটি পড CrashLoopBackOff। কী ক্র্যাশের কারণ দেখায়?', ['kubectl logs', 'kubectl get svc'], ['kubectl logs', 'kubectl get svc'], 0, 'The logs usually contain the error that kills the container.', 'লগ সাধারণত কন্টেইনার মারা এররটি ধারণ করে।'],
      ['Look inside', 'ভেতরে দেখুন', 'You need a shell in a running pod to inspect it. Which command?', 'পরিদর্শনে একটি চলমান পডে শেল দরকার। কোন কমান্ড?', ['kubectl exec -it pod -- sh', 'kubectl apply -f pod'], ['kubectl exec -it pod -- sh', 'kubectl apply -f pod'], 0, 'exec runs a command (like a shell) inside an existing pod.', 'exec একটি বিদ্যমান পডের ভেতরে একটি কমান্ড (যেমন শেল) চালায়।'],
      ['Persist the fix', 'ফিক্স স্থায়ী', 'You found a bad setting. Where do you fix it permanently?', 'একটি খারাপ সেটিং পেলেন। স্থায়ীভাবে কোথায় ঠিক করবেন?', ['In the manifest, then apply', 'By editing the live pod'], ['ম্যানিফেস্টে, তারপর apply', 'লাইভ পড এডিট করে'], 0, 'Live edits vanish on restart; fix the YAML and re-apply.', 'লাইভ এডিট রিস্টার্টে হারায়; YAML ঠিক করে পুনরায় apply করুন।'],
    ],
  },
  {
    id: 'k8s-scale-lab', icon: '☁', title: l('Scale & Operate', 'স্কেল ও পরিচালনা ল্যাব'), subtitle: l('Handle load and run in production.', 'লোড সামলান ও প্রোডাকশনে চালান।'),
    stages: [
      ['Manual scale', 'ম্যানুয়াল স্কেল', 'Traffic doubled. How do you quickly add replicas?', 'ট্রাফিক দ্বিগুণ। দ্রুত রেপ্লিকা কীভাবে যোগ করবেন?', ['kubectl scale deploy web --replicas=6', 'Restart the node'], ['kubectl scale deploy web --replicas=6', 'নোড রিস্টার্ট'], 0, 'scale changes the replica count immediately.', 'scale সঙ্গে সঙ্গে রেপ্লিকা সংখ্যা বদলায়।'],
      ['Auto scale', 'অটো স্কেল', 'You want replicas to follow CPU automatically. What do you add?', 'রেপ্লিকা স্বয়ংক্রিয়ভাবে CPU অনুসরণ করুক চান। কী যোগ করবেন?', ['A HorizontalPodAutoscaler', 'A bigger image'], ['একটি HorizontalPodAutoscaler', 'একটি বড় ইমেজ'], 0, 'An HPA adds/removes pods based on metrics — and needs resource requests.', 'HPA মেট্রিকের ভিত্তিতে পড যোগ/সরায়—ও রিসোর্স request লাগে।'],
      ['Package it', 'প্যাকেজ', 'You want to install a complex app with one configurable command. What helps?', 'এক কনফিগারযোগ্য কমান্ডে একটি জটিল অ্যাপ ইনস্টল চান। কী সাহায্য করে?', ['A Helm chart', 'Copy-pasting YAML by hand'], ['একটি Helm চার্ট', 'হাতে YAML কপি-পেস্ট'], 0, 'Helm packages templated manifests you install and upgrade as one unit.', 'Helm টেমপ্লেটেড ম্যানিফেস্ট প্যাকেজ করে যা এক এককে ইনস্টল ও আপগ্রেড করেন।'],
      ['Source of truth', 'সত্যের উৎস', 'For auditable, reversible deploys, what should drive the cluster?', 'অডিটযোগ্য, রিভার্সিবল ডিপ্লয়ে ক্লাস্টার কী চালানো উচিত?', ['Git (GitOps)', 'Ad-hoc kubectl edits'], ['Git (GitOps)', 'অ্যাড-হক kubectl এডিট'], 0, 'GitOps makes git the source of truth and syncs the cluster to it.', 'GitOps git-কে সত্যের উৎস করে ও ক্লাস্টার তার সঙ্গে সিংক করে।'],
    ],
  },
].map((lab) => ({ ...lab, stages: lab.stages.map((s, i) => ({ id: `${lab.id}-${i}`, title: l(s[0], s[1]), question: l(s[2], s[3]), options: s[4].map((en, x) => l(en, s[5][x])), correct: s[6], feedback: l(s[7], s[8]) })) }))
