import { l } from '../data.js'
import { buildExam } from './exam-factory.js'

// Linux Fundamentals course — bilingual (English / Bangla).
// Mirrors the DSA / Git / Networking course shape so lesson rendering stays data-driven.

export const linuxModules = [
  { id: 'lx-foundations', number: '01', title: l('Linux foundations', 'লিনাক্স ভিত্তি'), description: l('What Linux is, the shell, the filesystem tree, and the "everything is a file" idea.', 'লিনাক্স কী, শেল, ফাইলসিস্টেম গাছ ও "সবকিছুই একটি ফাইল" ধারণা।'), color: '#d97706' },
  { id: 'lx-files', number: '02', title: l('Files & navigation', 'ফাইল ও নেভিগেশন'), description: l('Move around the filesystem and create, copy, move, find, and match files.', 'ফাইলসিস্টেমে চলুন এবং ফাইল তৈরি, কপি, সরানো, খোঁজা ও ম্যাচ করুন।'), color: '#0284c7' },
  { id: 'lx-text', number: '03', title: l('Text & streams', 'টেক্সট ও স্ট্রিম'), description: l('View files, redirect and pipe streams, and search and transform text.', 'ফাইল দেখুন, স্ট্রিম রিডাইরেক্ট ও পাইপ করুন, এবং টেক্সট খুঁজুন ও রূপান্তর করুন।'), color: '#0f9f78' },
  { id: 'lx-permissions', number: '04', title: l('Users & permissions', 'ইউজার ও পারমিশন'), description: l('Users and groups, read/write/execute permissions, ownership, and sudo.', 'ইউজার ও গ্রুপ, রিড/রাইট/এক্সিকিউট পারমিশন, মালিকানা ও sudo।'), color: '#e34b87' },
  { id: 'lx-processes', number: '05', title: l('Processes & services', 'প্রসেস ও সার্ভিস'), description: l('Processes, signals, background jobs, systemd services, and cron scheduling.', 'প্রসেস, সিগন্যাল, ব্যাকগ্রাউন্ড জব, systemd সার্ভিস ও cron শিডিউলিং।'), color: '#6c5ce7' },
  { id: 'lx-packages', number: '06', title: l('Packages & environment', 'প্যাকেজ ও এনভায়রনমেন্ট'), description: l('Package managers, environment variables, shell config, and SSH.', 'প্যাকেজ ম্যানেজার, এনভায়রনমেন্ট ভ্যারিয়েবল, শেল কনফিগ ও SSH।'), color: '#0891b2' },
  { id: 'lx-storage', number: '07', title: l('Storage & scripting', 'স্টোরেজ ও স্ক্রিপ্টিং'), description: l('Disks and mounts, disk usage, bash scripting, and log troubleshooting.', 'ডিস্ক ও মাউন্ট, ডিস্ক ব্যবহার, bash স্ক্রিপ্টিং ও লগ ট্রাবলশুটিং।'), color: '#7c3aed' },
]

const rawTopics = [
  // ── Foundations ───────────────────────────────────────────────────────────
  ['lx-what', 'lx-foundations', 'What is Linux?', 'লিনাক্স কী?', 'Beginner', 10, 'lx-prompt',
    'Linux is an open-source operating system kernel; distributions like Ubuntu bundle it with tools into a full system.', 'লিনাক্স একটি ওপেন-সোর্স অপারেটিং সিস্টেম কার্নেল; উবুন্টুর মতো ডিস্ট্রিবিউশন একে টুলসহ একটি পূর্ণ সিস্টেমে বান্ডেল করে।',
    'The kernel is the engine; a distro is the whole car built around it with seats, dashboard, and controls.', 'কার্নেল হলো ইঞ্জিন; ডিস্ট্রো হলো তার চারপাশে গড়া সিট, ড্যাশবোর্ড ও নিয়ন্ত্রণসহ পুরো গাড়ি।',
    'Pick a distribution for your need (Ubuntu/Debian for servers) and learn the shared core tools.', 'প্রয়োজন অনুযায়ী ডিস্ট্রিবিউশন বাছুন (সার্ভারে উবুন্টু/ডেবিয়ান) এবং সাধারণ মূল টুল শিখুন।',
    'Linux is free, flexible, and everywhere on servers, but its power comes with a steeper command-line learning curve.', 'লিনাক্স ফ্রি, নমনীয় ও সার্ভারে সর্বত্র, তবে এর শক্তির সঙ্গে আসে কঠিন কমান্ড-লাইন শেখার বক্ররেখা।',
    'Assuming every distro is totally different; most share the same kernel, shell, and core commands.', 'ধরে নেওয়া প্রতিটি ডিস্ট্রো একদম আলাদা; বেশিরভাগ একই কার্নেল, শেল ও মূল কমান্ড শেয়ার করে।'],
  ['lx-shell', 'lx-foundations', 'The shell & terminal', 'শেল ও টার্মিনাল', 'Beginner', 12, 'lx-prompt',
    'The shell is a program that reads your typed commands and asks the kernel to run them; bash is the most common.', 'শেল একটি প্রোগ্রাম যা আপনার টাইপ করা কমান্ড পড়ে ও কার্নেলকে চালাতে বলে; bash সবচেয়ে প্রচলিত।',
    'A translator between you and the machine—you speak commands, it relays them to the operating system.', 'আপনার ও মেশিনের মধ্যে একজন অনুবাদক—আপনি কমান্ড বলেন, এটি অপারেটিং সিস্টেমে পৌঁছায়।',
    'Learn the prompt, tab-completion, and the arrow keys for history to move fast in the shell.', 'শেলে দ্রুত চলতে প্রম্পট, ট্যাব-কমপ্লিশন ও ইতিহাসের অ্যারো কী শিখুন।',
    'The shell is fast and scriptable for experts, but it is unforgiving—there is no undo for a wrong command.', 'শেল বিশেষজ্ঞদের জন্য দ্রুত ও স্ক্রিপ্টযোগ্য, তবে ক্ষমাহীন—ভুল কমান্ডের কোনো আনডু নেই।',
    'Running a powerful command (like rm) without reading it, because the shell does exactly what you said.', 'একটি শক্তিশালী কমান্ড (যেমন rm) না পড়ে চালানো, কারণ শেল ঠিক যা বলেন তাই করে।'],
  ['lx-filesystem', 'lx-foundations', 'The filesystem hierarchy', 'ফাইলসিস্টেম হায়ারার্কি', 'Beginner', 13, 'lx-tree',
    'Linux organizes everything under a single root /, with standard directories like /home, /etc, /var, and /usr.', 'লিনাক্স সবকিছু একটি একক রুট /-এর নিচে সাজায়, /home, /etc, /var ও /usr-এর মতো প্রমিত ডিরেক্টরিসহ।',
    'One filing cabinet where every drawer has a fixed purpose—personal files, settings, logs, programs.', 'একটি ফাইলিং ক্যাবিনেট যেখানে প্রতিটি ড্রয়ারের নির্দিষ্ট উদ্দেশ্য—ব্যক্তিগত ফাইল, সেটিং, লগ, প্রোগ্রাম।',
    'Learn the key directories: /home (users), /etc (config), /var/log (logs), /usr/bin (programs).', 'মূল ডিরেক্টরি শিখুন: /home (ব্যবহারকারী), /etc (কনফিগ), /var/log (লগ), /usr/bin (প্রোগ্রাম)।',
    'A single tree makes everything findable and scriptable, but one wrong path can touch a critical system file.', 'একটি গাছ সবকিছু খুঁজে-পাওয়া ও স্ক্রিপ্টযোগ্য করে, তবে একটি ভুল পাথ একটি সংকটপূর্ণ সিস্টেম ফাইল স্পর্শ করতে পারে।',
    'Editing files under /etc or /var without a backup, then breaking a service with no easy way back.', 'ব্যাকআপ ছাড়া /etc বা /var-এর ফাইল এডিট করা, তারপর সহজ ফেরার পথ ছাড়াই একটি সার্ভিস ভাঙা।'],
  ['lx-everything-file', 'lx-foundations', 'Everything is a file', 'সবকিছুই একটি ফাইল', 'Intermediate', 12, 'lx-prompt',
    'In Linux almost everything is a file—documents, directories, devices, and even running processes appear as files.', 'লিনাক্সে প্রায় সবকিছুই একটি ফাইল—ডকুমেন্ট, ডিরেক্টরি, ডিভাইস, এমনকি চলমান প্রসেসও ফাইল হিসেবে দেখা যায়।',
    'A universal socket: because everything plugs in the same way (as a file), the same tools work on all of it.', 'একটি সর্বজনীন সকেট: সবকিছু একইভাবে (ফাইল হিসেবে) যুক্ত হয় বলে একই টুল সবকিছুতে কাজ করে।',
    'Use the same read/write tools on devices and pseudo-files (/dev, /proc) as you do on ordinary files.', 'সাধারণ ফাইলের মতো ডিভাইস ও সিউডো-ফাইলেও (/dev, /proc) একই পড়া/লেখা টুল ব্যবহার করুন।',
    'The everything-is-a-file model is elegant and uniform, but writing to the wrong device file can corrupt a disk.', 'সবকিছু-ফাইল মডেল মার্জিত ও অভিন্ন, তবে ভুল ডিভাইস ফাইলে লেখা একটি ডিস্ক নষ্ট করতে পারে।',
    'Treating a device file like a text file and writing to it carelessly, damaging real hardware or data.', 'একটি ডিভাইস ফাইলকে টেক্সট ফাইলের মতো ধরে অসাবধানে লেখা, আসল হার্ডওয়্যার বা ডেটা ক্ষতি করা।'],

  // ── Files & navigation ────────────────────────────────────────────────────
  ['lx-navigation', 'lx-files', 'Navigating: pwd, cd, ls', 'নেভিগেশন: pwd, cd, ls', 'Beginner', 12, 'lx-tree',
    'pwd shows where you are, ls lists what is here, and cd moves you between directories.', 'pwd দেখায় আপনি কোথায়, ls দেখায় এখানে কী আছে, আর cd আপনাকে ডিরেক্টরির মধ্যে সরায়।',
    'Walking a building: pwd is "which room am I in?", ls is "what is in this room?", cd is "walk to another room".', 'একটি ভবনে হাঁটা: pwd হলো "কোন ঘরে আছি?", ls হলো "এই ঘরে কী?", cd হলো "অন্য ঘরে যান"।',
    'Use ls -la to see hidden files and details, and cd with tab-completion to move quickly.', 'লুকানো ফাইল ও বিস্তারিত দেখতে ls -la, আর দ্রুত সরতে ট্যাব-কমপ্লিশনসহ cd ব্যবহার করুন।',
    'These commands are simple and instant, but ls output can overwhelm on huge directories without filters.', 'এই কমান্ড সরল ও তাৎক্ষণিক, তবে ফিল্টার ছাড়া বিশাল ডিরেক্টরিতে ls আউটপুট বিভ্রান্ত করতে পারে।',
    'Losing track of your current directory and running a destructive command in the wrong place.', 'বর্তমান ডিরেক্টরির হিসাব হারিয়ে ভুল জায়গায় একটি ধ্বংসাত্মক কমান্ড চালানো।'],
  ['lx-paths', 'lx-files', 'Absolute vs relative paths', 'অ্যাবসোলিউট বনাম রিলেটিভ পাথ', 'Beginner', 11, 'lx-tree',
    'An absolute path starts from root (/home/user); a relative path starts from where you are now (./docs).', 'অ্যাবসোলিউট পাথ রুট থেকে শুরু (/home/user); রিলেটিভ পাথ আপনি এখন যেখানে সেখান থেকে (./docs)।',
    'An absolute address is the full postal address; a relative one is "two doors down from here".', 'অ্যাবসোলিউট ঠিকানা হলো পুরো ডাক ঠিকানা; রিলেটিভ হলো "এখান থেকে দুই দরজা পরে"।',
    'Use . for current, .. for parent, and ~ for your home; prefer absolute paths in scripts for safety.', 'বর্তমানে ., প্যারেন্টে .., হোমে ~ ব্যবহার করুন; নিরাপত্তায় স্ক্রিপ্টে অ্যাবসোলিউট পাথ নিন।',
    'Relative paths are short and portable, but they depend on your current directory, which scripts can get wrong.', 'রিলেটিভ পাথ ছোট ও পোর্টেবল, তবে বর্তমান ডিরেক্টরির ওপর নির্ভর করে, যা স্ক্রিপ্ট ভুল করতে পারে।',
    'Using a relative path in a cron job or script, so it breaks when run from a different directory.', 'ক্রন জব বা স্ক্রিপ্টে রিলেটিভ পাথ ব্যবহার, ফলে অন্য ডিরেক্টরি থেকে চালালে ভাঙে।'],
  ['lx-file-ops', 'lx-files', 'Creating & managing files', 'ফাইল তৈরি ও ব্যবস্থাপনা', 'Beginner', 13, 'lx-tree',
    'touch creates files, mkdir makes directories, cp copies, mv moves or renames, and rm deletes.', 'touch ফাইল তৈরি করে, mkdir ডিরেক্টরি বানায়, cp কপি করে, mv সরায় বা নাম বদলায়, আর rm মুছে ফেলে।',
    'The basic verbs of housekeeping your files: make, copy, move, and throw away.', 'আপনার ফাইল গোছানোর মৌলিক ক্রিয়া: বানানো, কপি, সরানো ও ফেলে দেওয়া।',
    'Use mkdir -p to create nested paths and cp -r to copy directories; double-check before rm.', 'নেস্টেড পাথ বানাতে mkdir -p ও ডিরেক্টরি কপিতে cp -r নিন; rm-এর আগে দুবার যাচাই করুন।',
    'These commands are quick and powerful, but rm has no trash can—deleted files are gone immediately.', 'এই কমান্ড দ্রুত ও শক্তিশালী, তবে rm-এর কোনো রিসাইকেল বিন নেই—মোছা ফাইল সঙ্গে সঙ্গে হারায়।',
    'Running rm -rf on the wrong path and permanently deleting data with no recovery.', 'ভুল পাথে rm -rf চালিয়ে পুনরুদ্ধার ছাড়াই স্থায়ীভাবে ডেটা মোছা।'],
  ['lx-find', 'lx-files', 'Finding files', 'ফাইল খোঁজা', 'Intermediate', 13, 'lx-tree',
    'find searches the tree live by name, size, or time; locate uses a fast prebuilt index; which finds a command.', 'find গাছে নাম, সাইজ বা সময় দিয়ে লাইভ খোঁজে; locate দ্রুত প্রি-বিল্ট ইনডেক্স ব্যবহার করে; which একটি কমান্ড খুঁজে।',
    'find is searching every room by hand; locate is checking a pre-made catalog; which asks "where is this tool kept?".', 'find হলো প্রতিটি ঘর হাতে খোঁজা; locate হলো আগে-বানানো ক্যাটালগ দেখা; which জিজ্ঞাসা করে "এই টুল কোথায় রাখা?"।',
    'Use find . -name "*.log" for precise live searches, and locate for instant results on indexed paths.', 'নিখুঁত লাইভ সার্চে find . -name "*.log", আর ইনডেক্সড পাথে তাৎক্ষণিক ফলে locate ব্যবহার করুন।',
    'find is precise and up to date but slow on big trees; locate is instant but can be stale until reindexed.', 'find নিখুঁত ও হালনাগাদ কিন্তু বড় গাছে ধীর; locate তাৎক্ষণিক কিন্তু রি-ইনডেক্স না হওয়া পর্যন্ত পুরনো হতে পারে।',
    'Trusting locate for a file created seconds ago before its index has been updated.', 'ইনডেক্স আপডেটের আগে সেকেন্ড আগে তৈরি ফাইলের জন্য locate-এ ভরসা করা।'],
  ['lx-wildcards', 'lx-files', 'Wildcards & globbing', 'ওয়াইল্ডকার্ড ও গ্লবিং', 'Intermediate', 12, 'lx-tree',
    'The shell expands wildcards before running a command: * matches any characters, ? one character, [abc] a set.', 'শেল কমান্ড চালানোর আগে ওয়াইল্ডকার্ড প্রসারিত করে: * যেকোনো অক্ষর, ? একটি অক্ষর, [abc] একটি সেট মেলায়।',
    'A search filter: "*.jpg" means "every name ending in .jpg", filled in before the command even sees it.', 'একটি সার্চ ফিল্টার: "*.jpg" মানে ".jpg-তে শেষ হওয়া প্রতিটি নাম", কমান্ড দেখার আগেই ভরা।',
    'Use * and ? to act on many files at once, and quote patterns when you want a command (not the shell) to expand them.', 'একসঙ্গে অনেক ফাইলে কাজ করতে * ও ? ব্যবহার করুন, আর কমান্ডকে (শেলকে নয়) প্রসারণ করাতে চাইলে প্যাটার্ন কোট করুন।',
    'Wildcards save huge amounts of typing, but a broad pattern with rm can hit far more files than you meant.', 'ওয়াইল্ডকার্ড বিপুল টাইপিং বাঁচায়, তবে rm-সহ একটি প্রশস্ত প্যাটার্ন উদ্দেশ্যের চেয়ে অনেক বেশি ফাইলে লাগতে পারে।',
    'Running rm * in the wrong directory and deleting everything the glob expanded to.', 'ভুল ডিরেক্টরিতে rm * চালিয়ে গ্লব যা প্রসারিত করল তার সব মোছা।'],

  // ── Text & streams ────────────────────────────────────────────────────────
  ['lx-view', 'lx-text', 'Viewing files', 'ফাইল দেখা', 'Beginner', 12, 'lx-pipe',
    'cat dumps a whole file, less pages through it interactively, head shows the top, and tail shows or follows the end.', 'cat পুরো ফাইল ঢালে, less ইন্টারেক্টিভভাবে পৃষ্ঠা ধরে দেখায়, head ওপর দেখায়, আর tail শেষ দেখায় বা follow করে।',
    'Reading a book: cat photocopies it all, less flips pages, head reads the intro, tail watches the latest chapter.', 'একটি বই পড়া: cat পুরোটা ফটোকপি করে, less পৃষ্ঠা ওল্টায়, head ভূমিকা পড়ে, tail সর্বশেষ অধ্যায় দেখে।',
    'Use less for big files and tail -f to watch logs update in real time.', 'বড় ফাইলে less ও লগ রিয়েল-টাইমে আপডেট দেখতে tail -f ব্যবহার করুন।',
    'cat is instant but floods your terminal on large files; less is controlled but interactive, not scriptable.', 'cat তাৎক্ষণিক কিন্তু বড় ফাইলে টার্মিনাল প্লাবিত করে; less নিয়ন্ত্রিত কিন্তু ইন্টারেক্টিভ, স্ক্রিপ্টযোগ্য নয়।',
    'Running cat on a huge or binary file and freezing or garbling your terminal.', 'একটি বিশাল বা বাইনারি ফাইলে cat চালিয়ে টার্মিনাল জমিয়ে বা এলোমেলো করা।'],
  ['lx-redirection', 'lx-text', 'Redirection & pipes', 'রিডাইরেকশন ও পাইপ', 'Intermediate', 15, 'lx-pipe',
    'Redirection sends output to a file (>, >>) or a file into a command (<); a pipe (|) feeds one command’s output into the next.', 'রিডাইরেকশন আউটপুট ফাইলে (>, >>) বা ফাইল কমান্ডে (<) পাঠায়; পাইপ (|) এক কমান্ডের আউটপুট পরেরটিতে দেয়।',
    'Plumbing: a pipe connects one tool’s output hose to the next tool’s input; > pours it into a bucket instead.', 'পাইপলাইন: পাইপ এক টুলের আউটপুট নলকে পরের টুলের ইনপুটে যুক্ত করে; > বদলে একটি বালতিতে ঢালে।',
    'Chain small tools with pipes, use > to save output, and use >> to append instead of overwriting.', 'ছোট টুল পাইপ দিয়ে যুক্ত করুন, আউটপুট সেভে > নিন, ওভাররাইট না করে যোগ করতে >> নিন।',
    'Pipes make tiny tools combine into powerful workflows, but > silently overwrites an existing file.', 'পাইপ ছোট টুলকে শক্তিশালী ওয়ার্কফ্লোতে মেলায়, তবে > বিদ্যমান ফাইল নীরবে ওভাররাইট করে।',
    'Using > when you meant >> and wiping out a file you intended to append to.', '>>-এর বদলে > ব্যবহার করে যে ফাইলে যোগ করার কথা ছিল তা মুছে ফেলা।'],
  ['lx-grep', 'lx-text', 'Searching text with grep', 'grep দিয়ে টেক্সট খোঁজা', 'Beginner', 13, 'lx-pipe',
    'grep searches text for lines matching a pattern, filtering files or the output of other commands.', 'grep একটি প্যাটার্নের সঙ্গে মেলা লাইনের জন্য টেক্সট খোঁজে, ফাইল বা অন্য কমান্ডের আউটপুট ফিল্টার করে।',
    'A highlighter that keeps only the lines you care about and hides the rest.', 'একটি হাইলাইটার যা শুধু আপনার দরকারি লাইন রাখে ও বাকিটা লুকায়।',
    'Pipe logs through grep to find errors; use -i to ignore case, -r to recurse, and -v to invert.', 'এরর খুঁজতে লগ grep-এ পাইপ করুন; কেস উপেক্ষায় -i, রিকার্সে -r, উল্টাতে -v ব্যবহার করুন।',
    'grep is fast and composable, but a loose pattern matches too much and a strict one can miss variants.', 'grep দ্রুত ও কম্পোজেবল, তবে ঢিলা প্যাটার্ন বেশি মেলায় ও কঠোরটি ভ্যারিয়েন্ট মিস করতে পারে।',
    'Forgetting to quote a pattern with special characters, so the shell expands it before grep sees it.', 'বিশেষ অক্ষরসহ প্যাটার্ন কোট করতে ভুলে যাওয়া, ফলে grep দেখার আগেই শেল একে প্রসারিত করে।'],
  ['lx-sed-awk', 'lx-text', 'Transforming text: sed & awk', 'টেক্সট রূপান্তর: sed ও awk', 'Advanced', 16, 'lx-pipe',
    'sed edits text streams line by line (find and replace); awk processes text as columns for filtering and reports.', 'sed টেক্সট স্ট্রিম লাইন-ধরে এডিট করে (খোঁজা ও বদল); awk টেক্সটকে কলাম হিসেবে প্রসেস করে ফিল্টার ও রিপোর্টে।',
    'sed is find-and-replace on a conveyor belt; awk is a spreadsheet that reads columns and computes.', 'sed হলো কনভেয়র বেল্টে খোঁজা-ও-বদল; awk হলো একটি স্প্রেডশিট যা কলাম পড়ে ও হিসাব করে।',
    'Use sed for substitutions and awk to pull out and compute on columns from structured text.', 'প্রতিস্থাপনে sed ও কাঠামোবদ্ধ টেক্সট থেকে কলাম টেনে হিসাব করতে awk ব্যবহার করুন।',
    'sed and awk are extremely powerful one-liners, but their terse syntax is easy to get wrong on complex data.', 'sed ও awk অত্যন্ত শক্তিশালী ওয়ান-লাইনার, তবে জটিল ডেটায় এদের সংক্ষিপ্ত সিনট্যাক্স সহজে ভুল হয়।',
    'Reaching for a fragile sed/awk pipeline where a real parser is needed for structured formats like JSON.', 'JSON-এর মতো কাঠামোবদ্ধ ফরম্যাটে যেখানে আসল পার্সার দরকার সেখানে ভঙ্গুর sed/awk পাইপলাইন ব্যবহার করা।'],
  ['lx-sort-uniq', 'lx-text', 'Sorting & counting', 'সাজানো ও গণনা', 'Intermediate', 13, 'lx-pipe',
    'sort orders lines, uniq collapses adjacent duplicates (often with a count), wc counts, and cut selects columns.', 'sort লাইন সাজায়, uniq পাশাপাশি ডুপ্লিকেট মেলায় (প্রায়ই গণনাসহ), wc গোনে, আর cut কলাম বাছে।',
    'A tidy-up crew: line them up (sort), merge duplicates (uniq), count them (wc), keep chosen fields (cut).', 'একটি গোছানো দল: সারিবদ্ধ করুন (sort), ডুপ্লিকেট মেলান (uniq), গুনুন (wc), বাছাই ফিল্ড রাখুন (cut)।',
    'Remember uniq needs sorted input; a common combo is sort | uniq -c | sort -rn for top counts.', 'মনে রাখুন uniq-এর সাজানো ইনপুট লাগে; টপ গণনায় প্রচলিত কম্বো sort | uniq -c | sort -rn।',
    'These tiny tools compose into powerful analysis, but each does only one thing—you must chain them correctly.', 'এই ছোট টুল শক্তিশালী বিশ্লেষণে মেলে, তবে প্রতিটি একটিই কাজ করে—সঠিকভাবে চেইন করতে হয়।',
    'Running uniq on unsorted input and missing duplicates that are not next to each other.', 'অসাজানো ইনপুটে uniq চালিয়ে পাশাপাশি না থাকা ডুপ্লিকেট মিস করা।'],

  // ── Users & permissions ───────────────────────────────────────────────────
  ['lx-users', 'lx-permissions', 'Users & groups', 'ইউজার ও গ্রুপ', 'Beginner', 12, 'lx-perms',
    'Linux is multi-user: every file and process belongs to a user and a group, and root is the all-powerful admin.', 'লিনাক্স মাল্টি-ইউজার: প্রতিটি ফাইল ও প্রসেস একজন ব্যবহারকারী ও একটি গ্রুপের, আর root হলো সর্বশক্তিমান অ্যাডমিন।',
    'An office building with keycards: each person accesses their own areas; the manager (root) can open every door.', 'কীকার্ডসহ একটি অফিস: প্রত্যেকে নিজের এলাকায় অ্যাক্সেস; ম্যানেজার (root) প্রতিটি দরজা খুলতে পারে।',
    'Use groups to grant shared access, and run day-to-day work as a normal user, not as root.', 'শেয়ার্ড অ্যাক্সেস দিতে গ্রুপ ব্যবহার করুন, আর প্রতিদিনের কাজ root নয়, সাধারণ ব্যবহারকারী হিসেবে করুন।',
    'The user model isolates and protects the system, but managing many users and groups adds administrative work.', 'ইউজার মডেল সিস্টেম আলাদা ও রক্ষা করে, তবে অনেক ব্যবহারকারী ও গ্রুপ সামলানো প্রশাসনিক কাজ বাড়ায়।',
    'Doing everything as root, so a single typo can damage the entire system.', 'সবকিছু root হিসেবে করা, ফলে একটি টাইপো পুরো সিস্টেম ক্ষতি করতে পারে।'],
  ['lx-permissions', 'lx-permissions', 'File permissions (rwx, chmod)', 'ফাইল পারমিশন (rwx, chmod)', 'Intermediate', 15, 'lx-perms',
    'Each file has read, write, and execute permissions for its owner, its group, and everyone else.', 'প্রতিটি ফাইলের মালিক, তার গ্রুপ ও বাকি সবার জন্য পড়া, লেখা ও চালানোর পারমিশন আছে।',
    'Three sets of door locks—one for you, one for your team, one for the public—each allowing look, change, or run.', 'তিন সেট দরজার তালা—একটি আপনার, একটি দলের, একটি জনসাধারণের—প্রতিটি দেখা, বদলানো বা চালানোর অনুমতি দেয়।',
    'Read ls -l output (rwxr-xr--) and set permissions with chmod, using numbers like 644 or 755.', 'ls -l আউটপুট (rwxr-xr--) পড়ুন এবং 644 বা 755-এর মতো সংখ্যা দিয়ে chmod-এ পারমিশন সেট করুন।',
    'Permissions are a simple, powerful guardrail, but overly open bits (like 777) expose files to everyone.', 'পারমিশন একটি সরল, শক্তিশালী রক্ষাকবচ, তবে অতি-খোলা বিট (যেমন 777) ফাইল সবার কাছে উন্মুক্ত করে।',
    'chmod 777 everything to "make it work", quietly opening files to modification by any user.', '"কাজ করানোর" জন্য সবকিছু chmod 777 করা, নীরবে যেকোনো ব্যবহারকারীর পরিবর্তনে ফাইল খোলা।'],
  ['lx-ownership', 'lx-permissions', 'Ownership (chown, chgrp)', 'মালিকানা (chown, chgrp)', 'Intermediate', 12, 'lx-perms',
    'chown changes a file’s owning user and chgrp its group; ownership decides which permission set applies to whom.', 'chown একটি ফাইলের মালিক ব্যবহারকারী ও chgrp তার গ্রুপ বদলায়; মালিকানা ঠিক করে কার জন্য কোন পারমিশন সেট প্রযোজ্য।',
    'Reassigning who holds the keys—changing the owner changes whose "owner" permissions count.', 'কে চাবি রাখে তা পুনর্নির্ধারণ—মালিক বদলালে কার "মালিক" পারমিশন গোনা হবে তা বদলায়।',
    'Use chown user:group file to fix ownership after copying or moving files between accounts.', 'অ্যাকাউন্টের মধ্যে ফাইল কপি/সরানোর পর মালিকানা ঠিক করতে chown user:group file ব্যবহার করুন।',
    'Correct ownership keeps access working, but it needs root and a wrong change can lock a service out of its files.', 'সঠিক মালিকানা অ্যাক্সেস সচল রাখে, তবে এতে root লাগে ও ভুল বদল একটি সার্ভিসকে তার ফাইল থেকে আটকে দিতে পারে।',
    'Recursively chowning a system directory to your user and breaking services that expect root ownership.', 'একটি সিস্টেম ডিরেক্টরি রিকার্সিভলি নিজের ব্যবহারকারীতে chown করে root মালিকানা প্রত্যাশী সার্ভিস ভাঙা।'],
  ['lx-sudo', 'lx-permissions', 'sudo & root', 'sudo ও root', 'Beginner', 11, 'lx-perms',
    'sudo runs a single command with root privileges, so you stay a normal user but can act as admin when needed.', 'sudo একটি একক কমান্ড root সুবিধায় চালায়, তাই আপনি সাধারণ ব্যবহারকারী থাকেন কিন্তু দরকারে অ্যাডমিন হতে পারেন।',
    'Borrowing the manager’s master key for one specific task, then handing it right back.', 'একটি নির্দিষ্ট কাজের জন্য ম্যানেজারের মাস্টার কী ধার নেওয়া, তারপরই ফেরত দেওয়া।',
    'Prefix an admin command with sudo; read the command carefully before running it with elevated power.', 'একটি অ্যাডমিন কমান্ডের আগে sudo দিন; উঁচু ক্ষমতায় চালানোর আগে কমান্ডটি ভালো করে পড়ুন।',
    'sudo limits risk by elevating only per command and logging use, but it still grants full power for that command.', 'sudo শুধু প্রতি কমান্ডে উঁচু করে ও ব্যবহার লগ করে ঝুঁকি কমায়, তবে সেই কমান্ডে পূর্ণ ক্ষমতা দেয়।',
    'Blindly copy-pasting a sudo command from the internet without understanding what it does.', 'এটি কী করে না বুঝে ইন্টারনেট থেকে একটি sudo কমান্ড অন্ধভাবে কপি-পেস্ট করা।'],

  // ── Processes & services ──────────────────────────────────────────────────
  ['lx-processes', 'lx-processes', 'Processes (ps, top)', 'প্রসেস (ps, top)', 'Beginner', 13, 'lx-process',
    'A process is a running program with a unique PID; ps lists them and top shows live CPU and memory use.', 'একটি প্রসেস হলো একটি চলমান প্রোগ্রাম যার ইউনিক PID আছে; ps এদের তালিকা করে ও top লাইভ CPU ও মেমরি ব্যবহার দেখায়।',
    'A control-tower board showing every flight (process) in the air, its number, and how much fuel it burns.', 'একটি কন্ট্রোল টাওয়ার বোর্ড যা আকাশের প্রতিটি ফ্লাইট (প্রসেস), তার নম্বর ও কত জ্বালানি পোড়ায় দেখায়।',
    'Use ps aux to list all processes and top (or htop) to watch which ones use the most resources.', 'সব প্রসেস তালিকায় ps aux ও কোনটি সবচেয়ে বেশি রিসোর্স ব্যবহার করছে দেখতে top (বা htop) ব্যবহার করুন।',
    'These tools give full visibility, but a snapshot can mislead—a process may spike only briefly between samples.', 'এই টুল পূর্ণ দৃশ্যমানতা দেয়, তবে একটি স্ন্যাপশট বিভ্রান্ত করতে পারে—একটি প্রসেস শুধু নমুনার মাঝে ক্ষণিক স্পাইক করতে পারে।',
    'Killing a process by name and accidentally stopping several unrelated ones that share it.', 'নাম দিয়ে একটি প্রসেস kill করে ভুলবশত একই নাম শেয়ার করা কয়েকটি অসম্পর্কিত প্রসেস থামানো।'],
  ['lx-signals', 'lx-processes', 'Signals & killing processes', 'সিগন্যাল ও প্রসেস kill', 'Intermediate', 13, 'lx-process',
    'Signals tell a process what to do; kill sends TERM to ask it to stop gracefully, and KILL (-9) forces it.', 'সিগন্যাল একটি প্রসেসকে কী করতে হবে বলে; kill সুন্দরভাবে থামতে TERM পাঠায়, আর KILL (-9) জোর করে।',
    'A polite "please close up" (TERM) versus pulling the power plug (KILL) when it will not respond.', 'একটি ভদ্র "দয়া করে বন্ধ করুন" (TERM) বনাম সাড়া না দিলে পাওয়ার প্লাগ টানা (KILL)।',
    'Try kill <pid> first to let a process clean up; use kill -9 only when it is truly stuck.', 'প্রসেসকে পরিষ্কার হতে দিতে প্রথমে kill <pid> চেষ্টা করুন; সত্যিই আটকে গেলে তবেই kill -9।',
    'TERM lets a process save state and exit cleanly, but KILL is instant yet can leave corrupt files or locks.', 'TERM প্রসেসকে স্টেট সেভ করে পরিষ্কারভাবে বেরোতে দেয়, তবে KILL তাৎক্ষণিক কিন্তু নষ্ট ফাইল বা লক রেখে যেতে পারে।',
    'Reaching straight for kill -9, skipping the graceful shutdown a process needed to save its data.', 'সরাসরি kill -9 ব্যবহার, প্রসেসের ডেটা সেভের দরকারি সুন্দর শাটডাউন এড়িয়ে যাওয়া।'],
  ['lx-jobs', 'lx-processes', 'Jobs & background', 'জব ও ব্যাকগ্রাউন্ড', 'Intermediate', 12, 'lx-process',
    'Append & to run a command in the background; jobs lists them, fg brings one to the foreground, bg resumes one.', 'ব্যাকগ্রাউন্ডে কমান্ড চালাতে & যোগ করুন; jobs এদের তালিকা করে, fg একটিকে সামনে আনে, bg একটিকে চালায়।',
    'Putting a task on a back burner (&) while you keep cooking up front, then checking or swapping it in later.', 'সামনে রান্না চালিয়ে একটি কাজ পেছনের চুলায় (&) রাখা, তারপর পরে দেখা বা বদলানো।',
    'Use & and nohup to keep long jobs running, and fg/bg to move a job between foreground and background.', 'দীর্ঘ জব চালু রাখতে & ও nohup, আর সামনে-পেছনে সরাতে fg/bg ব্যবহার করুন।',
    'Background jobs free your terminal, but a plain background job dies when you close the shell unless you use nohup.', 'ব্যাকগ্রাউন্ড জব টার্মিনাল মুক্ত করে, তবে nohup ছাড়া শেল বন্ধ করলে সাধারণ ব্যাকগ্রাউন্ড জব মারা যায়।',
    'Starting a long job in the background without nohup, then losing it when the SSH session drops.', 'nohup ছাড়া ব্যাকগ্রাউন্ডে দীর্ঘ জব শুরু করা, তারপর SSH সেশন গেলে তা হারানো।'],
  ['lx-systemd', 'lx-processes', 'Services with systemd', 'systemd দিয়ে সার্ভিস', 'Intermediate', 15, 'lx-process',
    'systemd manages long-running services; systemctl starts, stops, enables at boot, and checks their status.', 'systemd দীর্ঘ-চলমান সার্ভিস সামলায়; systemctl চালু, বন্ধ, বুটে চালু ও স্ট্যাটাস দেখে।',
    'A building manager who starts the lifts each morning, restarts one that breaks, and keeps a status log.', 'একজন ভবন ম্যানেজার যিনি প্রতিদিন লিফট চালু করেন, ভাঙা একটি রিস্টার্ট করেন ও স্ট্যাটাস লগ রাখেন।',
    'Use systemctl start/stop/status and enable a service so it launches automatically on boot.', 'systemctl start/stop/status ব্যবহার করুন এবং একটি সার্ভিস enable করুন যাতে বুটে স্বয়ংক্রিয়ভাবে চালু হয়।',
    'systemd standardizes service management, but its scope is large and its unit files add a learning curve.', 'systemd সার্ভিস ব্যবস্থাপনা প্রমিত করে, তবে এর পরিধি বড় ও ইউনিট ফাইল শেখার বক্ররেখা যোগ করে।',
    'Starting a service manually but forgetting to enable it, so it does not come back after a reboot.', 'একটি সার্ভিস ম্যানুয়ালি চালু করে enable করতে ভুলে যাওয়া, ফলে রিবুটের পর ফিরে আসে না।'],
  ['lx-cron', 'lx-processes', 'Scheduling with cron', 'cron দিয়ে শিডিউলিং', 'Intermediate', 13, 'lx-process',
    'cron runs commands on a schedule defined by five time fields: minute, hour, day, month, and weekday.', 'cron পাঁচটি সময় ফিল্ড দিয়ে সংজ্ঞায়িত শিডিউলে কমান্ড চালায়: মিনিট, ঘণ্টা, দিন, মাস ও সপ্তাহের দিন।',
    'An automatic alarm clock for tasks—"every day at 2am, run the backup".', 'কাজের জন্য একটি স্বয়ংক্রিয় অ্যালার্ম ঘড়ি—"প্রতিদিন রাত ২টায় ব্যাকআপ চালাও"।',
    'Edit your schedule with crontab -e and test the command manually before trusting the cron entry.', 'crontab -e দিয়ে শিডিউল এডিট করুন এবং cron এন্ট্রিতে ভরসার আগে কমান্ডটি ম্যানুয়ালি পরীক্ষা করুন।',
    'cron automates routine work reliably, but jobs run with a minimal environment, so PATH and paths often surprise you.', 'cron রুটিন কাজ নির্ভরযোগ্যভাবে অটোমেট করে, তবে জব ন্যূনতম এনভায়রনমেন্টে চলে, তাই PATH ও পাথ প্রায়ই অবাক করে।',
    'Assuming a cron job has your shell’s environment; it often fails because PATH or variables are not set.', 'ধরে নেওয়া cron জবে আপনার শেলের এনভায়রনমেন্ট আছে; PATH বা ভ্যারিয়েবল সেট না থাকায় প্রায়ই ব্যর্থ হয়।'],

  // ── Packages & environment ────────────────────────────────────────────────
  ['lx-packages', 'lx-packages', 'Package managers', 'প্যাকেজ ম্যানেজার', 'Beginner', 13, 'lx-prompt',
    'A package manager installs, updates, and removes software with its dependencies; apt and dnf are common.', 'প্যাকেজ ম্যানেজার নির্ভরতাসহ সফটওয়্যার ইনস্টল, আপডেট ও রিমুভ করে; apt ও dnf প্রচলিত।',
    'An app store for the command line that also tracks and installs everything a program depends on.', 'কমান্ড লাইনের জন্য একটি অ্যাপ স্টোর যা একটি প্রোগ্রাম যা নির্ভর করে তা-ও ট্র্যাক ও ইনস্টল করে।',
    'Run apt update before apt install so you fetch current package versions, not stale ones.', 'apt install-এর আগে apt update চালান যাতে পুরনো নয়, বর্তমান প্যাকেজ সংস্করণ পান।',
    'Package managers handle dependencies for you, but mixing manual installs with them can break the dependency graph.', 'প্যাকেজ ম্যানেজার আপনার জন্য নির্ভরতা সামলায়, তবে এদের সঙ্গে ম্যানুয়াল ইনস্টল মেশালে নির্ভরতা গ্রাফ ভাঙতে পারে।',
    'Installing software by piping a random script to sudo bash instead of using the package manager.', 'প্যাকেজ ম্যানেজার ব্যবহার না করে একটি এলোমেলো স্ক্রিপ্ট sudo bash-এ পাইপ করে সফটওয়্যার ইনস্টল করা।'],
  ['lx-env', 'lx-packages', 'Environment variables & PATH', 'এনভায়রনমেন্ট ভ্যারিয়েবল ও PATH', 'Intermediate', 13, 'lx-prompt',
    'Environment variables carry settings to programs; PATH lists the directories the shell searches for commands.', 'এনভায়রনমেন্ট ভ্যারিয়েবল প্রোগ্রামে সেটিং বহন করে; PATH-এ শেল যে ডিরেক্টরিগুলোতে কমান্ড খোঁজে তা থাকে।',
    'A shared notepad every program can read—PATH is the list of aisles the shell checks to find a tool.', 'একটি শেয়ার্ড নোটপ্যাড যা প্রতিটি প্রোগ্রাম পড়তে পারে—PATH হলো শেল যে আইলগুলোতে টুল খোঁজে তার তালিকা।',
    'Use export VAR=value to set a variable, and echo $PATH to see where commands are found.', 'একটি ভ্যারিয়েবল সেট করতে export VAR=value, ও কমান্ড কোথায় মেলে দেখতে echo $PATH ব্যবহার করুন।',
    'Env vars configure programs without editing files, but they vanish when the shell closes unless saved in a config file.', 'env ভ্যার ফাইল না এডিট করে প্রোগ্রাম কনফিগার করে, তবে কনফিগ ফাইলে সেভ না করলে শেল বন্ধ হলে হারায়।',
    'Setting a variable in one shell and wondering why another shell or a new session does not see it.', 'এক শেলে একটি ভ্যারিয়েবল সেট করে অবাক হওয়া কেন অন্য শেল বা নতুন সেশন তা দেখে না।'],
  ['lx-shell-config', 'lx-packages', 'Shell config & aliases', 'শেল কনফিগ ও অ্যালিয়াস', 'Intermediate', 12, 'lx-prompt',
    'Shell config files (like ~/.bashrc) run at startup to set your prompt, aliases, environment, and PATH.', 'শেল কনফিগ ফাইল (যেমন ~/.bashrc) শুরুতে চলে আপনার প্রম্পট, অ্যালিয়াস, এনভায়রনমেন্ট ও PATH সেট করতে।',
    'A startup checklist your shell reads every time it opens, arranging your workspace the way you like it.', 'একটি স্টার্টআপ চেকলিস্ট যা আপনার শেল প্রতিবার খোলার সময় পড়ে, আপনার পছন্দমতো কর্মস্থল সাজায়।',
    'Add aliases and exports to ~/.bashrc, then run source ~/.bashrc to apply them without reopening the shell.', 'অ্যালিয়াস ও এক্সপোর্ট ~/.bashrc-এ যোগ করুন, তারপর শেল না খুলে প্রয়োগ করতে source ~/.bashrc চালান।',
    'Config files make your setup persistent and portable, but a broken line can stop new shells from opening properly.', 'কনফিগ ফাইল আপনার সেটআপ স্থায়ী ও পোর্টেবল করে, তবে একটি ভাঙা লাইন নতুন শেল ঠিকমতো খোলা থামাতে পারে।',
    'Breaking ~/.bashrc with a bad edit, then every new terminal opens with errors.', 'একটি খারাপ এডিটে ~/.bashrc ভাঙা, তারপর প্রতিটি নতুন টার্মিনাল এররসহ খোলে।'],
  ['lx-ssh', 'lx-packages', 'SSH & remote access', 'SSH ও রিমোট অ্যাক্সেস', 'Intermediate', 14, 'lx-prompt',
    'SSH gives you an encrypted remote shell on another machine, authenticated by a password or (better) a key pair.', 'SSH আপনাকে অন্য একটি মেশিনে একটি এনক্রিপ্টেড রিমোট শেল দেয়, পাসওয়ার্ড বা (ভালো) কী পেয়ার দিয়ে যাচাই করা।',
    'A secure phone line into a distant computer—everything you type and see is encrypted end to end.', 'একটি দূরের কম্পিউটারে একটি নিরাপদ ফোন লাইন—আপনি যা টাইপ ও দেখেন সব প্রান্ত-থেকে-প্রান্ত এনক্রিপ্টেড।',
    'Connect with ssh user@host; set up key-based auth with ssh-keygen and copy the public key to the server.', 'ssh user@host দিয়ে সংযোগ করুন; ssh-keygen দিয়ে কী-ভিত্তিক auth সেট করে পাবলিক কী সার্ভারে কপি করুন।',
    'Keys are far more secure and convenient than passwords, but a leaked private key hands over full access.', 'কী পাসওয়ার্ডের চেয়ে অনেক নিরাপদ ও সুবিধাজনক, তবে ফাঁস হওয়া প্রাইভেট কী পূর্ণ অ্যাক্সেস তুলে দেয়।',
    'Leaving password login and root SSH enabled on a public server, inviting brute-force attacks.', 'একটি পাবলিক সার্ভারে পাসওয়ার্ড লগইন ও root SSH চালু রাখা, ব্রুট-ফোর্স আক্রমণ ডেকে আনা।'],

  // ── Storage & scripting ───────────────────────────────────────────────────
  ['lx-disks', 'lx-storage', 'Disks & mounting', 'ডিস্ক ও মাউন্টিং', 'Advanced', 15, 'lx-tree',
    'Storage is exposed as block devices (like /dev/sda); you mount a filesystem onto a directory to use it.', 'স্টোরেজ ব্লক ডিভাইস (যেমন /dev/sda) হিসেবে প্রকাশিত; ব্যবহারে একটি ফাইলসিস্টেম একটি ডিরেক্টরিতে মাউন্ট করেন।',
    'Plugging a drive into a spot in the file tree—the mount point is the doorway to that storage.', 'ফাইল-গাছের একটি জায়গায় একটি ড্রাইভ যুক্ত করা—মাউন্ট পয়েন্ট হলো সেই স্টোরেজের দরজা।',
    'Use lsblk to see devices, mount to attach one, and /etc/fstab to mount automatically at boot.', 'ডিভাইস দেখতে lsblk, একটি যুক্ত করতে mount, ও বুটে স্বয়ংক্রিয় মাউন্টে /etc/fstab ব্যবহার করুন।',
    'Mounting is flexible and lets storage live anywhere in the tree, but a bad fstab entry can stop the system from booting.', 'মাউন্টিং নমনীয় ও স্টোরেজকে গাছের যেকোনো জায়গায় রাখতে দেয়, তবে একটি খারাপ fstab এন্ট্রি সিস্টেম বুট হওয়া থামাতে পারে।',
    'Unmounting or unplugging a disk that is still being written to, corrupting its filesystem.', 'এখনো লেখা হচ্ছে এমন একটি ডিস্ক আনমাউন্ট বা খুলে ফেলা, তার ফাইলসিস্টেম নষ্ট করা।'],
  ['lx-diskusage', 'lx-storage', 'Disk usage (df, du)', 'ডিস্ক ব্যবহার (df, du)', 'Beginner', 12, 'lx-pipe',
    'df shows free space per filesystem; du measures how much space files and directories actually use.', 'df প্রতি ফাইলসিস্টেমের ফ্রি স্পেস দেখায়; du ফাইল ও ডিরেক্টরি আসলে কত জায়গা ব্যবহার করে মাপে।',
    'df is the fuel gauge (how full the tank is); du weighs each bag to find what is taking up room.', 'df হলো জ্বালানি গজ (ট্যাংক কতটা পূর্ণ); du প্রতিটি ব্যাগ ওজন করে কী জায়গা নিচ্ছে খুঁজে বের করে।',
    'Run df -h to spot a full disk, then du -sh * to find the biggest directories to clean up.', 'একটি পূর্ণ ডিস্ক ধরতে df -h, তারপর পরিষ্কারে সবচেয়ে বড় ডিরেক্টরি খুঁজতে du -sh * চালান।',
    'df is instant per filesystem, but du must walk the tree, which is slow on directories with millions of files.', 'df প্রতি ফাইলসিস্টেমে তাৎক্ষণিক, তবে du-কে গাছ হাঁটতে হয়, যা লাখো ফাইলের ডিরেক্টরিতে ধীর।',
    'Seeing a full disk in df but deleting the wrong files because you never ran du to find the real culprit.', 'df-তে পূর্ণ ডিস্ক দেখা কিন্তু ভুল ফাইল মোছা কারণ আসল দোষী খুঁজতে du কখনো চালাননি।'],
  ['lx-scripting', 'lx-storage', 'Bash scripting basics', 'bash স্ক্রিপ্টিং বেসিক', 'Advanced', 18, 'lx-prompt',
    'A bash script is a text file of commands with a #!/bin/bash shebang; it automates a sequence you would otherwise type.', 'একটি bash স্ক্রিপ্ট হলো #!/bin/bash শেবাংসহ কমান্ডের একটি টেক্সট ফাইল; এটি যা টাইপ করতেন তা অটোমেট করে।',
    'Writing down a recipe once so anyone (or a schedule) can run the exact same steps every time.', 'একবার একটি রেসিপি লিখে রাখা যাতে যে কেউ (বা একটি শিডিউল) প্রতিবার ঠিক একই ধাপ চালাতে পারে।',
    'Start with #!/bin/bash, make it executable with chmod +x, and use variables, if, and loops to add logic.', '#!/bin/bash দিয়ে শুরু করুন, chmod +x দিয়ে এক্সিকিউটেবল করুন, ও লজিকে ভ্যারিয়েবল, if ও লুপ ব্যবহার করুন।',
    'Scripts make tasks repeatable and shareable, but unquoted variables and missing error checks make them fragile.', 'স্ক্রিপ্ট কাজ পুনরাবৃত্তিযোগ্য ও শেয়ারযোগ্য করে, তবে আন-কোটেড ভ্যারিয়েবল ও অনুপস্থিত এরর চেক এদের ভঙ্গুর করে।',
    'Not quoting variables ("$var"), so a filename with spaces breaks the script in surprising ways.', 'ভ্যারিয়েবল কোট না করা ("$var"), ফলে স্পেসসহ একটি ফাইলনাম স্ক্রিপ্টকে অপ্রত্যাশিতভাবে ভাঙে।'],
  ['lx-troubleshooting', 'lx-storage', 'Logs & troubleshooting', 'লগ ও ট্রাবলশুটিং', 'Intermediate', 14, 'lx-pipe',
    'When something breaks the logs usually explain it: journalctl for systemd services, /var/log for system logs, dmesg for the kernel.', 'কিছু ভাঙলে লগ সাধারণত তা ব্যাখ্যা করে: systemd সার্ভিসে journalctl, সিস্টেম লগে /var/log, কার্নেলে dmesg।',
    'A flight recorder—when something goes wrong, you replay the log to see exactly what happened and when.', 'একটি ফ্লাইট রেকর্ডার—কিছু ভুল হলে লগ রিপ্লে করে ঠিক কী ও কখন ঘটল দেখেন।',
    'Follow a service with journalctl -u name -f, and grep /var/log for the error message and timestamp.', 'একটি সার্ভিস journalctl -u name -f দিয়ে follow করুন, ও এরর বার্তা ও টাইমস্ট্যাম্পে /var/log grep করুন।',
    'Logs hold the answer to most problems, but on a busy system the signal is buried in noise you must filter.', 'লগে বেশিরভাগ সমস্যার উত্তর থাকে, তবে একটি ব্যস্ত সিস্টেমে সংকেত সেই শব্দে চাপা পড়ে যা ফিল্টার করতে হয়।',
    'Guessing at a fix without ever reading the logs, which usually name the exact failing component.', 'কখনো লগ না পড়ে অনুমানে ঠিক করা, যা সাধারণত ঠিক ব্যর্থ উপাদানের নাম বলে।'],
]

// Command reference tables (op = intent, value = command) shown as an extra lesson section.
const commands = {
  'lx-navigation': [['Print working dir', 'বর্তমান ডিরেক্টরি', 'pwd'], ['List files (all, long)', 'ফাইল তালিকা (সব, লং)', 'ls -la'], ['Change directory', 'ডিরেক্টরি বদল', 'cd /path'], ['Go to home', 'হোমে যান', 'cd ~']],
  'lx-file-ops': [['Create empty file', 'খালি ফাইল তৈরি', 'touch file'], ['Make a directory', 'ডিরেক্টরি তৈরি', 'mkdir -p dir'], ['Copy (recursive)', 'কপি (রিকার্সিভ)', 'cp -r a b'], ['Move / rename', 'সরান / নাম বদল', 'mv a b'], ['Delete a file', 'ফাইল মুছুন', 'rm file']],
  'lx-find': [['Find by name', 'নামে খুঁজুন', 'find . -name "*.log"'], ['Find only files', 'শুধু ফাইল খুঁজুন', 'find . -type f'], ['Locate quickly', 'দ্রুত locate', 'locate file'], ['Where is a command', 'কমান্ড কোথায়', 'which ls']],
  'lx-view': [['Show whole file', 'পুরো ফাইল', 'cat file'], ['Page through', 'পৃষ্ঠা ধরে', 'less file'], ['First lines', 'প্রথম লাইন', 'head -n 20'], ['Last lines / follow', 'শেষ লাইন / follow', 'tail -f']],
  'lx-grep': [['Search text', 'টেক্সট খুঁজুন', 'grep pattern file'], ['Ignore case', 'কেস উপেক্ষা', 'grep -i'], ['Search recursively', 'রিকার্সিভ সার্চ', 'grep -r'], ['Invert the match', 'উল্টো ম্যাচ', 'grep -v']],
  'lx-sort-uniq': [['Sort lines', 'লাইন সাজান', 'sort'], ['Unique with counts', 'ইউনিক + গণনা', 'uniq -c'], ['Count lines', 'লাইন গণনা', 'wc -l'], ['Pick a column', 'কলাম বাছুন', 'cut -f1']],
  'lx-permissions': [['Make executable', 'এক্সিকিউটেবল', 'chmod +x file'], ['Owner rwx only', 'শুধু মালিক rwx', 'chmod 700'], ['Standard file', 'সাধারণ ফাইল', 'chmod 644'], ['View permissions', 'পারমিশন দেখুন', 'ls -l']],
  'lx-processes': [['List all processes', 'সব প্রসেস তালিকা', 'ps aux'], ['Live monitor', 'লাইভ মনিটর', 'top'], ['Find PID by name', 'নামে PID খুঁজুন', 'pgrep nginx'], ['Process tree', 'প্রসেস ট্রি', 'pstree']],
  'lx-signals': [['Graceful stop', 'সুন্দরভাবে থামান', 'kill <pid>'], ['Force kill', 'জোর করে kill', 'kill -9 <pid>'], ['Kill by name', 'নামে kill', 'pkill nginx'], ['List signals', 'সিগন্যাল তালিকা', 'kill -l']],
  'lx-systemd': [['Start a service', 'সার্ভিস চালু', 'systemctl start x'], ['Enable at boot', 'বুটে চালু', 'systemctl enable x'], ['Check status', 'স্ট্যাটাস দেখুন', 'systemctl status x'], ['View service logs', 'সার্ভিস লগ দেখুন', 'journalctl -u x']],
  'lx-packages': [['Update the index', 'ইনডেক্স আপডেট', 'apt update'], ['Install a package', 'প্যাকেজ ইনস্টল', 'apt install pkg'], ['Remove a package', 'প্যাকেজ রিমুভ', 'apt remove pkg'], ['Search packages', 'প্যাকেজ খুঁজুন', 'apt search pkg']],
  'lx-env': [['Show all variables', 'সব ভ্যারিয়েবল', 'printenv'], ['Set for one command', 'এক কমান্ডে সেট', 'VAR=1 cmd'], ['Export a variable', 'ভ্যারিয়েবল এক্সপোর্ট', 'export VAR=1'], ['Show the PATH', 'PATH দেখুন', 'echo $PATH']],
  'lx-ssh': [['Connect to a host', 'হোস্টে সংযোগ', 'ssh user@host'], ['Copy a file over', 'ফাইল কপি', 'scp file user@host:'], ['Generate a key', 'কী তৈরি', 'ssh-keygen -t ed25519'], ['Run a remote command', 'রিমোট কমান্ড', 'ssh host "uptime"']],
  'lx-diskusage': [['Free space (human)', 'ফ্রি স্পেস', 'df -h'], ['Directory size', 'ডিরেক্টরি সাইজ', 'du -sh'], ['List block devices', 'ব্লক ডিভাইস', 'lsblk'], ['Biggest subdirectories', 'বড় সাবডিরেক্টরি', 'du -h | sort -h']],
}

// Linux-flavoured distractors for generated exams (each is a clearly bad practice).
const distractors = [
  l('Run every command as root so you never hit a permission error.', 'পারমিশন এরর যাতে না আসে সে জন্য প্রতিটি কমান্ড root হিসেবে চালান।'),
  l('chmod 777 everything until it finally works.', 'কাজ না করা পর্যন্ত সবকিছু chmod 777 করুন।'),
  l('Delete files with rm -rf without reading the path first.', 'পাথ না পড়ে rm -rf দিয়ে ফাইল মুছুন।'),
  l('Pipe a random internet script straight into sudo bash.', 'একটি এলোমেলো ইন্টারনেট স্ক্রিপ্ট সরাসরি sudo bash-এ পাইপ করুন।'),
  l('Edit system config files with no backup and no idea what they do.', 'কী করে না জেনে ও ব্যাকআপ ছাড়াই সিস্টেম কনফিগ ফাইল এডিট করুন।'),
  l('Leave unused ports and password SSH open on a public server.', 'একটি পাবলিক সার্ভারে ব্যবহার-না-করা পোর্ট ও পাসওয়ার্ড SSH খোলা রাখুন।'),
  l('Guess at a fix instead of ever reading the logs.', 'কখনো লগ না পড়ে অনুমানে ঠিক করার চেষ্টা করুন।'),
  l('Use unquoted variables in scripts so spaces break everything.', 'স্ক্রিপ্টে আন-কোটেড ভ্যারিয়েবল ব্যবহার করুন যাতে স্পেস সব ভাঙে।'),
]

export const linuxTopics = rawTopics.map((row, index) => {
  const [id, moduleId, en, bn, difficulty, minutes, diagram, insightEn, insightBn, analogyEn, analogyBn, actionEn, actionBn, tradeoffEn, tradeoffBn, mistakeEn, mistakeBn] = row
  const topic = {
    id, order: index + 1, moduleId, title: l(en, bn), difficulty, minutes, diagram, deepDive: null,
    insight: l(insightEn, insightBn), analogy: l(analogyEn, analogyBn), action: l(actionEn, actionBn), tradeoff: l(tradeoffEn, tradeoffBn), mistake: l(mistakeEn, mistakeBn),
    complexity: (commands[id] || []).map(([opEn, opBn, value]) => ({ op: l(opEn, opBn), value })),
    objectives: [
      l(`Explain ${en} in plain language.`, `সহজ ভাষায় ${bn} ব্যাখ্যা করতে পারবেন।`),
      l('Recognize when to reach for this command or concept.', 'কখন এই কমান্ড বা ধারণা নিতে হবে তা বুঝতে পারবেন।'),
      l('Run the key commands and know what the important flags do.', 'মূল কমান্ড চালাতে ও গুরুত্বপূর্ণ ফ্ল্যাগগুলো কী করে তা জানতে পারবেন।'),
    ],
    advantages: l(`Knowing ${en.toLowerCase()} makes you faster and safer at the Linux command line.`, `${bn} জানা আপনাকে লিনাক্স কমান্ড লাইনে দ্রুত ও নিরাপদ করে।`),
    interview: l(`Show the command for ${en.toLowerCase()}, explain what it does, and mention a flag or risk to watch for.`, `${bn}-এর কমান্ড দেখান, কী করে ব্যাখ্যা করুন, এবং একটি ফ্ল্যাগ বা ঝুঁকির কথা বলুন।`),
    glossary: [
      { term: l('Shell', 'শেল'), definition: l('The program that reads your commands and asks the kernel to run them.', 'যে প্রোগ্রাম আপনার কমান্ড পড়ে ও কার্নেলকে চালাতে বলে।') },
      { term: l('Root', 'রুট'), definition: l('The all-powerful administrator account that can change anything.', 'সর্বশক্তিমান অ্যাডমিন অ্যাকাউন্ট যা যেকোনো কিছু বদলাতে পারে।') },
    ],
  }
  topic.exam = buildExam(topic, { distractors, subject: 'linux' })
  return topic
})

// ── Guided labs (bilingual) ─────────────────────────────────────────────────
export const linuxLabs = [
  {
    id: 'lx-navigate-lab', icon: '❯', title: l('Find Your Way Around', 'পথ খুঁজে বের করা ল্যাব'), subtitle: l('Pick the right command for each move.', 'প্রতিটি পদক্ষেপে সঠিক কমান্ড বাছুন।'),
    stages: [
      ['Where am I', 'আমি কোথায়', 'You need to know your current directory. Which command?', 'আপনার বর্তমান ডিরেক্টরি জানা দরকার। কোন কমান্ড?', ['pwd', 'ls -la'], ['pwd', 'ls -la'], 0, 'pwd prints the working directory.', 'pwd বর্তমান ডিরেক্টরি প্রিন্ট করে।'],
      ['See hidden files', 'লুকানো ফাইল দেখুন', 'You want to list all files, including hidden ones, with details. Which command?', 'বিস্তারিতসহ লুকানো ফাইলসহ সব তালিকা করতে চান। কোন কমান্ড?', ['ls -la', 'cat *'], ['ls -la', 'cat *'], 0, 'ls -la shows all entries (including dotfiles) in long form.', 'ls -la সব এন্ট্রি (dotfile সহ) লং ফর্মে দেখায়।'],
      ['Make nested dirs', 'নেস্টেড ডিরেক্টরি', 'You must create a/b/c in one command. Which command?', 'এক কমান্ডে a/b/c বানাতে হবে। কোন কমান্ড?', ['mkdir -p a/b/c', 'mkdir a b c'], ['mkdir -p a/b/c', 'mkdir a b c'], 0, 'mkdir -p creates the full nested path at once.', 'mkdir -p একসঙ্গে পুরো নেস্টেড পাথ বানায়।'],
      ['Portable path', 'পোর্টেবল পাথ', 'Which path should a reliable script use for /home/user/data?', 'একটি নির্ভরযোগ্য স্ক্রিপ্টে /home/user/data-এর জন্য কোন পাথ?', ['The absolute path', 'A relative path like ./data'], ['অ্যাবসোলিউট পাথ', './data-এর মতো রিলেটিভ পাথ'], 0, 'Absolute paths do not depend on the current directory.', 'অ্যাবসোলিউট পাথ বর্তমান ডিরেক্টরির ওপর নির্ভর করে না।'],
    ],
  },
  {
    id: 'lx-pipe-lab', icon: '⋔', title: l('Build a Pipeline', 'পাইপলাইন তৈরি ল্যাব'), subtitle: l('Combine small tools to answer a question.', 'একটি প্রশ্নের উত্তরে ছোট টুল মেলান।'),
    stages: [
      ['Filter errors', 'এরর ফিল্টার', 'You want only the error lines from app.log. Which command?', 'আপনি app.log থেকে শুধু এরর লাইন চান। কোন কমান্ড?', ['grep error app.log', 'cat app.log'], ['grep error app.log', 'cat app.log'], 0, 'grep keeps only lines matching the pattern.', 'grep শুধু প্যাটার্নে মেলা লাইন রাখে।'],
      ['Save the output', 'আউটপুট সেভ', 'You must save that output to errors.txt without losing the file if it exists. Which?', 'বিদ্যমান ফাইল না হারিয়ে সেই আউটপুট errors.txt-এ সেভ করতে হবে। কোনটি?', ['>> errors.txt', '> errors.txt'], ['>> errors.txt', '> errors.txt'], 0, '>> appends; > would overwrite the file.', '>> যোগ করে; > ফাইল ওভাররাইট করত।'],
      ['Count unique', 'ইউনিক গণনা', 'You want the count of each unique line. Which pipeline?', 'প্রতিটি ইউনিক লাইনের গণনা চান। কোন পাইপলাইন?', ['sort | uniq -c', 'uniq -c'], ['sort | uniq -c', 'uniq -c'], 0, 'uniq needs sorted input, so sort comes first.', 'uniq-এর সাজানো ইনপুট লাগে, তাই আগে sort।'],
      ['Watch it live', 'লাইভ দেখুন', 'You want to watch a log update in real time. Which command?', 'একটি লগ রিয়েল-টাইমে আপডেট দেখতে চান। কোন কমান্ড?', ['tail -f app.log', 'cat app.log'], ['tail -f app.log', 'cat app.log'], 0, 'tail -f follows the file as new lines are written.', 'tail -f নতুন লাইন লেখার সঙ্গে ফাইল follow করে।'],
    ],
  },
  {
    id: 'lx-permissions-lab', icon: '⛨', title: l('Lock It Down', 'নিরাপদ করা ল্যাব'), subtitle: l('Set the right permissions and ownership.', 'সঠিক পারমিশন ও মালিকানা সেট করুন।'),
    stages: [
      ['Least privilege', 'ন্যূনতম অধিকার', 'For your day-to-day work, which account should you use?', 'প্রতিদিনের কাজে কোন অ্যাকাউন্ট ব্যবহার করবেন?', ['A normal user (sudo when needed)', 'The root account'], ['সাধারণ ব্যবহারকারী (দরকারে sudo)', 'root অ্যাকাউন্ট'], 0, 'Work as a normal user; elevate only when necessary.', 'সাধারণ ব্যবহারকারী হিসেবে কাজ করুন; দরকারে তবেই উঁচু করুন।'],
      ['Make a script run', 'স্ক্রিপ্ট চালু', 'Your script will not run. What likely needs setting?', 'আপনার স্ক্রিপ্ট চলছে না। সম্ভবত কী সেট করা দরকার?', ['The execute bit (chmod +x)', 'chmod 777'], ['এক্সিকিউট বিট (chmod +x)', 'chmod 777'], 0, 'chmod +x adds execute without opening it to everyone.', 'chmod +x সবার জন্য না খুলে এক্সিকিউট যোগ করে।'],
      ['Right permissions', 'সঠিক পারমিশন', 'A normal readable file (owner writes, others read) should be…', 'একটি সাধারণ পঠনযোগ্য ফাইল (মালিক লেখে, অন্যরা পড়ে) হওয়া উচিত…', ['644', '777'], ['644', '777'], 0, '644 gives owner read/write and others read-only.', '644 মালিককে রিড/রাইট ও অন্যদের রিড-অনলি দেয়।'],
      ['Fix ownership', 'মালিকানা ঠিক', 'A copied file is owned by the wrong user. What fixes it?', 'একটি কপি করা ফাইল ভুল ব্যবহারকারীর। কী ঠিক করে?', ['chown user:group file', 'rm the file'], ['chown user:group file', 'ফাইলটি rm করুন'], 0, 'chown reassigns the owning user and group.', 'chown মালিক ব্যবহারকারী ও গ্রুপ পুনর্নির্ধারণ করে।'],
    ],
  },
  {
    id: 'lx-service-lab', icon: '⚙', title: l('Run a Service', 'সার্ভিস চালানো ল্যাব'), subtitle: l('Keep a process running and diagnose it.', 'একটি প্রসেস চালু রাখুন ও নির্ণয় করুন।'),
    stages: [
      ['Start it', 'চালু করুন', 'You must start the nginx service now. Which command?', 'এখন nginx সার্ভিস চালু করতে হবে। কোন কমান্ড?', ['systemctl start nginx', 'nginx &'], ['systemctl start nginx', 'nginx &'], 0, 'systemctl manages the service properly under systemd.', 'systemctl systemd-এর অধীনে সার্ভিস ঠিকভাবে সামলায়।'],
      ['Survive reboot', 'রিবুটে টিকে থাকা', 'It must also start automatically after a reboot. What do you run?', 'রিবুটের পরও এটি স্বয়ংক্রিয় চালু হতে হবে। কী চালাবেন?', ['systemctl enable nginx', 'Nothing — start persists'], ['systemctl enable nginx', 'কিছু না — start টিকে থাকে'], 0, 'enable makes it launch on boot; start alone does not.', 'enable বুটে চালু করে; শুধু start করে না।'],
      ['Stuck process', 'আটকে থাকা প্রসেস', 'A process ignores a normal stop. What do you try before forcing it?', 'একটি প্রসেস সাধারণ stop উপেক্ষা করে। জোর করার আগে কী চেষ্টা করবেন?', ['kill <pid> (TERM) first', 'kill -9 immediately'], ['প্রথমে kill <pid> (TERM)', 'সঙ্গে সঙ্গে kill -9'], 0, 'Try a graceful TERM first; use -9 only if it is truly stuck.', 'আগে সুন্দর TERM চেষ্টা করুন; সত্যিই আটকে গেলে তবেই -9।'],
      ['Find the cause', 'কারণ খুঁজুন', 'The service keeps crashing. Where do you look first?', 'সার্ভিসটি বারবার ক্র্যাশ করছে। প্রথমে কোথায় দেখবেন?', ['journalctl -u nginx', 'Reboot and hope'], ['journalctl -u nginx', 'রিবুট করে আশা করা'], 0, 'The service logs usually name the exact failure.', 'সার্ভিস লগ সাধারণত ঠিক ব্যর্থতার নাম বলে।'],
    ],
  },
].map((lab) => ({ ...lab, stages: lab.stages.map((s, i) => ({ id: `${lab.id}-${i}`, title: l(s[0], s[1]), question: l(s[2], s[3]), options: s[4].map((en, x) => l(en, s[5][x])), correct: s[6], feedback: l(s[7], s[8]) })) }))
