import { l } from '../data.js'
import { buildExam } from './exam-factory.js'

// Computer Networking course — bilingual (English / Bangla).
// Mirrors the DSA / Git course shape so lesson rendering stays data-driven.

export const netModules = [
  { id: 'cn-foundations', number: '01', title: l('Networking foundations', 'নেটওয়ার্কিং ভিত্তি'), description: l('What a network is, the layered model, encapsulation, and how speed is measured.', 'নেটওয়ার্ক কী, স্তরভিত্তিক মডেল, এনক্যাপসুলেশন ও গতি কীভাবে মাপা হয়।'), color: '#188cbd' },
  { id: 'cn-link', number: '02', title: l('The link layer', 'লিংক লেয়ার'), description: l('MAC addresses, Ethernet frames, switches, and how devices find each other on a LAN.', 'MAC ঠিকানা, Ethernet ফ্রেম, সুইচ ও LAN-এ ডিভাইস কীভাবে একে অপরকে খুঁজে পায়।'), color: '#0f9f78' },
  { id: 'cn-internet', number: '03', title: l('The internet layer (IP)', 'ইন্টারনেট লেয়ার (IP)'), description: l('IP addresses, subnetting, routing, NAT, and ICMP diagnostics.', 'IP ঠিকানা, সাবনেটিং, রাউটিং, NAT ও ICMP ডায়াগনস্টিক্স।'), color: '#6c5ce7' },
  { id: 'cn-transport', number: '04', title: l('The transport layer', 'ট্রান্সপোর্ট লেয়ার'), description: l('TCP vs UDP, the handshake, ports and sockets, and congestion control.', 'TCP বনাম UDP, হ্যান্ডশেক, পোর্ট ও সকেট, এবং কনজেশন কন্ট্রোল।'), color: '#d97706' },
  { id: 'cn-application', number: '05', title: l('The application layer', 'অ্যাপ্লিকেশন লেয়ার'), description: l('DNS, HTTP, HTTPS/TLS, DHCP, and real-time WebSockets.', 'DNS, HTTP, HTTPS/TLS, DHCP ও রিয়েল-টাইম WebSocket।'), color: '#e34b87' },
  { id: 'cn-infra', number: '06', title: l('Infrastructure & delivery', 'অবকাঠামো ও ডেলিভারি'), description: l('Load balancers, CDNs, proxies, firewalls, and VPN tunnels.', 'লোড ব্যালান্সার, CDN, প্রক্সি, ফায়ারওয়াল ও VPN টানেল।'), color: '#0284c7' },
  { id: 'cn-ops', number: '07', title: l('Security & operations', 'নিরাপত্তা ও অপারেশন'), description: l('TLS certificates, common attacks, troubleshooting tools, and observability.', 'TLS সার্টিফিকেট, সাধারণ আক্রমণ, ট্রাবলশুটিং টুল ও অবজার্ভেবিলিটি।'), color: '#7c3aed' },
]

const rawTopics = [
  // ── Foundations ───────────────────────────────────────────────────────────
  ['cn-what', 'cn-foundations', 'What is a computer network?', 'কম্পিউটার নেটওয়ার্ক কী?', 'Beginner', 10, 'net-stack',
    'A computer network connects devices so they can exchange data using shared rules called protocols.', 'কম্পিউটার নেটওয়ার্ক ডিভাইসগুলোকে যুক্ত করে যাতে তারা প্রোটোকল নামের সাধারণ নিয়ম দিয়ে ডেটা বিনিময় করতে পারে।',
    'A postal system: addresses, envelopes, and delivery rules let anyone send a letter to anyone.', 'একটি ডাক ব্যবস্থা: ঠিকানা, খাম ও ডেলিভারি নিয়ম যে কাউকে যে কারো কাছে চিঠি পাঠাতে দেয়।',
    'Think in terms of who talks to whom, over what medium, using which protocol at each step.', 'ভাবুন কে কার সঙ্গে, কোন মাধ্যমে, প্রতি ধাপে কোন প্রোটোকল দিয়ে কথা বলে।',
    'Networks let distant machines cooperate, but every hop adds latency and a chance of loss or attack.', 'নেটওয়ার্ক দূরের মেশিনকে সহযোগিতা করতে দেয়, তবে প্রতিটি হপ লেটেন্সি এবং হারানো বা আক্রমণের ঝুঁকি যোগ করে।',
    'Assuming the network is invisible and instant, then being surprised by latency and failures.', 'নেটওয়ার্ককে অদৃশ্য ও তাৎক্ষণিক ধরে নেওয়া, তারপর লেটেন্সি ও ব্যর্থতায় অবাক হওয়া।'],
  ['cn-layers', 'cn-foundations', 'The OSI & TCP/IP models', 'OSI ও TCP/IP মডেল', 'Beginner', 14, 'net-stack',
    'Networking is split into layers (OSI has 7, TCP/IP 4); each layer has one job and talks only to the layers next to it.', 'নেটওয়ার্কিং স্তরে ভাগ করা (OSI-তে ৭টি, TCP/IP-তে ৪টি); প্রতিটি স্তরের একটি কাজ এবং শুধু পাশের স্তরের সঙ্গে কথা বলে।',
    'A shipping company: sales, packing, trucking, and roads each handle one job without the others’ details.', 'একটি শিপিং কোম্পানি: বিক্রি, প্যাকিং, ট্রাকিং ও রাস্তা—প্রতিটি একটি কাজ সামলায়, অন্যের বিস্তারিত না জেনেই।',
    'Map any protocol to its layer (HTTP=application, TCP=transport, IP=network, Ethernet=link) to reason about it.', 'যেকোনো প্রোটোকলকে তার স্তরে বসান (HTTP=অ্যাপ্লিকেশন, TCP=ট্রান্সপোর্ট, IP=নেটওয়ার্ক, Ethernet=লিংক) বুঝতে।',
    'Layering keeps each part simple and swappable, but crossing many layers adds overhead per packet.', 'লেয়ারিং প্রতিটি অংশ সরল ও বদলযোগ্য রাখে, তবে অনেক স্তর পার হওয়া প্রতি প্যাকেটে ওভারহেড যোগ করে।',
    'Mixing up the layers—e.g., blaming HTTP for a problem that is really at the TCP or IP layer.', 'স্তর গুলিয়ে ফেলা—যেমন TCP বা IP স্তরের সমস্যার জন্য HTTP-কে দোষ দেওয়া।'],
  ['cn-encapsulation', 'cn-foundations', 'Encapsulation & headers', 'এনক্যাপসুলেশন ও হেডার', 'Intermediate', 13, 'net-stack',
    'As data goes down the stack, each layer wraps it with its own header — application data becomes a segment, packet, then a frame.', 'ডেটা স্ট্যাক ধরে নিচে নামার সময় প্রতিটি স্তর নিজের হেডার দিয়ে মোড়ায়—অ্যাপ্লিকেশন ডেটা সেগমেন্ট, প্যাকেট, তারপর ফ্রেম হয়।',
    'Putting a letter in an envelope, then a bigger envelope, then a mailbag—each adds routing info.', 'একটি চিঠি খামে, তারপর বড় খামে, তারপর ডাকব্যাগে রাখা—প্রতিটি রাউটিং তথ্য যোগ করে।',
    'Remember the wrapping order: HTTP → TCP segment → IP packet → Ethernet frame → bits on the wire.', 'মোড়ানোর ক্রম মনে রাখুন: HTTP → TCP সেগমেন্ট → IP প্যাকেট → Ethernet ফ্রেম → তারে বিট।',
    'Headers make each packet self-describing and routable, but they add bytes of overhead to every message.', 'হেডার প্রতিটি প্যাকেটকে স্ব-বর্ণনামূলক ও রাউটেবল করে, তবে প্রতিটি বার্তায় ওভারহেড বাইট যোগ করে।',
    'Forgetting the receiver unwraps in reverse, so a header set by one layer must be read by the same layer.', 'ভুলে যাওয়া যে গ্রাহক উল্টো ক্রমে খোলে, তাই এক স্তরের সেট করা হেডার একই স্তরকেই পড়তে হয়।'],
  ['cn-performance', 'cn-foundations', 'Bandwidth, latency & throughput', 'ব্যান্ডউইথ, লেটেন্সি ও থ্রুপুট', 'Beginner', 12, 'net-request',
    'Network speed has two parts: bandwidth (how much data per second) and latency (how long one trip takes).', 'নেটওয়ার্ক গতির দুটি অংশ: ব্যান্ডউইথ (প্রতি সেকেন্ডে কত ডেটা) ও লেটেন্সি (একটি যাত্রায় কত সময়)।',
    'A highway: bandwidth is how many lanes, latency is how long the drive takes regardless of lanes.', 'একটি মহাসড়ক: ব্যান্ডউইথ কত লেন, লেটেন্সি লেন যতই হোক গাড়ি চালাতে কত সময়।',
    'For big transfers optimize bandwidth; for chatty request/response, cut round trips to reduce latency.', 'বড় ট্রান্সফারে ব্যান্ডউইথ, আর ঘন ঘন রিকোয়েস্ট/রেসপন্সে রাউন্ড ট্রিপ কমিয়ে লেটেন্সি কমান।',
    'More bandwidth does not fix latency—a far server stays slow to respond no matter how fat the pipe.', 'বেশি ব্যান্ডউইথ লেটেন্সি ঠিক করে না—দূরের সার্ভার পাইপ যতই মোটা হোক, রেসপন্সে ধীরই থাকে।',
    'Buying more bandwidth to fix a latency problem caused by distance or too many round trips.', 'দূরত্ব বা বেশি রাউন্ড ট্রিপজনিত লেটেন্সি ঠিক করতে বেশি ব্যান্ডউইথ কেনা।'],

  // ── Link layer ────────────────────────────────────────────────────────────
  ['cn-mac-ethernet', 'cn-link', 'MAC addresses & Ethernet', 'MAC ঠিকানা ও Ethernet', 'Beginner', 12, 'net-hops',
    'Ethernet moves data as frames on a local network, addressed by unique MAC addresses burned into each device.', 'Ethernet লোকাল নেটওয়ার্কে ডেটা ফ্রেম হিসেবে সরায়, প্রতিটি ডিভাইসে থাকা ইউনিক MAC ঠিকানায় ঠিকানা করা।',
    'A MAC address is like a device’s permanent serial number; the frame is the labeled package on the local belt.', 'MAC ঠিকানা ডিভাইসের স্থায়ী সিরিয়াল নম্বরের মতো; ফ্রেম হলো লোকাল বেল্টের লেবেলযুক্ত প্যাকেজ।',
    'Use MAC addresses to reason about local delivery; they identify devices within one network segment.', 'লোকাল ডেলিভারি বুঝতে MAC ঠিকানা ব্যবহার করুন; এগুলো এক নেটওয়ার্ক সেগমেন্টের ভেতরে ডিভাইস চেনায়।',
    'MAC addresses work only on the local link; crossing networks needs IP addresses on top.', 'MAC ঠিকানা শুধু লোকাল লিংকে কাজ করে; নেটওয়ার্ক পার হতে ওপরে IP ঠিকানা লাগে।',
    'Expecting a MAC address to route across the internet—it never leaves the local network.', 'MAC ঠিকানা ইন্টারনেট জুড়ে রাউট করবে আশা করা—এটি কখনো লোকাল নেটওয়ার্ক ছাড়ে না।'],
  ['cn-switching', 'cn-link', 'Switches & the LAN', 'সুইচ ও LAN', 'Beginner', 12, 'net-hops',
    'A switch connects devices in a LAN and forwards each frame only to the port of its destination MAC.', 'সুইচ একটি LAN-এ ডিভাইস যুক্ত করে এবং প্রতিটি ফ্রেম শুধু গন্তব্য MAC-এর পোর্টে পাঠায়।',
    'A smart mail sorter that learns which desk each person sits at and delivers only there.', 'একটি স্মার্ট মেইল সর্টার যা শেখে কে কোন ডেস্কে বসে এবং শুধু সেখানেই দেয়।',
    'Use a switch (not a hub) so traffic goes only where it belongs, keeping the LAN fast and private.', 'হাব নয়, সুইচ ব্যবহার করুন যাতে ট্রাফিক শুধু যেখানে দরকার সেখানে যায়, LAN দ্রুত ও ব্যক্তিগত থাকে।',
    'Switches make LANs efficient, but they only forward within one network—routers handle between networks.', 'সুইচ LAN-কে দক্ষ করে, তবে শুধু এক নেটওয়ার্কের ভেতরে পাঠায়—নেটওয়ার্কের মধ্যে রাউটার সামলায়।',
    'Confusing a switch (Layer 2, MAC-based) with a router (Layer 3, IP-based).', 'সুইচ (লেয়ার ২, MAC-ভিত্তিক) ও রাউটার (লেয়ার ৩, IP-ভিত্তিক) গুলিয়ে ফেলা।'],
  ['cn-arp', 'cn-link', 'ARP: IP to MAC', 'ARP: IP থেকে MAC', 'Intermediate', 12, 'net-hops',
    'ARP finds the MAC address for a known IP on the local network, so a frame can actually be delivered.', 'ARP লোকাল নেটওয়ার্কে একটি জানা IP-এর MAC ঠিকানা খুঁজে বের করে, যাতে ফ্রেম আসলে ডেলিভার করা যায়।',
    'Shouting "who has address 10.0.0.5?" in a room and the right person raising their hand.', 'একটি ঘরে "১০.০.০.৫ ঠিকানা কার?" বলে চিৎকার, আর সঠিক ব্যক্তির হাত তোলা।',
    'Remember ARP bridges IP (Layer 3) to MAC (Layer 2) before any local frame can be sent.', 'মনে রাখুন কোনো লোকাল ফ্রেম পাঠানোর আগে ARP IP (লেয়ার ৩) থেকে MAC (লেয়ার ২) সংযোগ করে।',
    'ARP is simple and automatic, but it trusts any reply—which enables ARP-spoofing attacks.', 'ARP সরল ও স্বয়ংক্রিয়, তবে যেকোনো উত্তর বিশ্বাস করে—যা ARP-স্পুফিং আক্রমণ সম্ভব করে।',
    'Assuming ARP works across the internet; it only resolves addresses on the local link.', 'ARP ইন্টারনেট জুড়ে কাজ করে ধরে নেওয়া; এটি শুধু লোকাল লিংকে ঠিকানা সমাধান করে।'],

  // ── Internet layer ────────────────────────────────────────────────────────
  ['cn-ip', 'cn-internet', 'IP addresses (IPv4 & IPv6)', 'IP ঠিকানা (IPv4 ও IPv6)', 'Beginner', 15, 'net-hops',
    'An IP address identifies a device on a network and lets packets be routed across the internet toward it.', 'একটি IP ঠিকানা নেটওয়ার্কে একটি ডিভাইস চেনায় এবং প্যাকেটকে ইন্টারনেট জুড়ে তার দিকে রাউট করতে দেয়।',
    'A postal address for your machine—IPv4 is short (32-bit); IPv6 is far longer to fit everyone.', 'আপনার মেশিনের ডাক ঠিকানা—IPv4 ছোট (৩২-বিট); IPv6 সবার জন্য অনেক লম্বা।',
    'Use IPv4 for most cases and IPv6 where address exhaustion matters; know public vs private ranges.', 'বেশিরভাগ ক্ষেত্রে IPv4, আর ঠিকানা ফুরানো গুরুত্বপূর্ণ হলে IPv6 ব্যবহার করুন; পাবলিক বনাম প্রাইভেট রেঞ্জ জানুন।',
    'IPv4 is universal but nearly exhausted; IPv6 solves scarcity but adoption is slow and dual-stack adds work.', 'IPv4 সর্বজনীন কিন্তু প্রায় ফুরিয়ে গেছে; IPv6 অভাব মেটায় কিন্তু গ্রহণ ধীর ও ডুয়াল-স্ট্যাক কাজ বাড়ায়।',
    'Exposing a private IP (like 192.168.x.x) and expecting it to be reachable from the public internet.', 'একটি প্রাইভেট IP (যেমন ১৯২.১৬৮.x.x) প্রকাশ করে পাবলিক ইন্টারনেট থেকে পৌঁছানো যাবে আশা করা।'],
  ['cn-subnetting', 'cn-internet', 'Subnets & CIDR', 'সাবনেট ও CIDR', 'Intermediate', 16, 'net-address',
    'A subnet mask (like /24) splits an IP into a network part and a host part, grouping devices into networks.', 'একটি সাবনেট মাস্ক (যেমন /24) IP-কে নেটওয়ার্ক ও হোস্ট অংশে ভাগ করে, ডিভাইসগুলোকে নেটওয়ার্কে দলবদ্ধ করে।',
    'A street name (network) plus a house number (host)—the mask says how many digits are the street.', 'রাস্তার নাম (নেটওয়ার্ক) আর বাড়ির নম্বর (হোস্ট)—মাস্ক বলে কতটি অঙ্ক রাস্তা।',
    'Read CIDR like /24: the number is how many bits are the network; the rest are host addresses.', '/24-এর মতো CIDR পড়ুন: সংখ্যাটি কত বিট নেটওয়ার্ক; বাকিটা হোস্ট ঠিকানা।',
    'Smaller subnets isolate and secure traffic, but too many tiny subnets waste addresses and add routing complexity.', 'ছোট সাবনেট ট্রাফিক আলাদা ও নিরাপদ করে, তবে অনেক ছোট সাবনেট ঠিকানা অপচয় ও রাউটিং জটিলতা বাড়ায়।',
    'Miscounting host bits—forgetting the network and broadcast addresses are not usable hosts.', 'হোস্ট বিট ভুল গোনা—নেটওয়ার্ক ও ব্রডকাস্ট ঠিকানা ব্যবহারযোগ্য হোস্ট নয় তা ভুলে যাওয়া।'],
  ['cn-routing', 'cn-internet', 'Routing & the default gateway', 'রাউটিং ও ডিফল্ট গেটওয়ে', 'Intermediate', 15, 'net-hops',
    'Routers forward packets between networks, each choosing the next hop toward the destination using a routing table.', 'রাউটার নেটওয়ার্কের মধ্যে প্যাকেট পাঠায়, প্রতিটি রাউটিং টেবিল দিয়ে গন্তব্যের দিকে পরবর্তী হপ বাছে।',
    'A road trip with signposts at each junction—each sign points you one step closer, not the whole way.', 'প্রতিটি মোড়ে সাইনপোস্টসহ একটি রোড ট্রিপ—প্রতিটি সাইন পুরো পথ নয়, এক ধাপ কাছে দেখায়।',
    'Send off-network traffic to your default gateway; let routers handle the hop-by-hop path.', 'অফ-নেটওয়ার্ক ট্রাফিক আপনার ডিফল্ট গেটওয়েতে পাঠান; হপ-বাই-হপ পথ রাউটারকে সামলাতে দিন।',
    'Distributed routing scales the whole internet, but no single router knows the full path—only the next hop.', 'বিতরণকৃত রাউটিং পুরো ইন্টারনেট স্কেল করে, তবে কোনো একটি রাউটার পুরো পথ জানে না—শুধু পরবর্তী হপ।',
    'Assuming a packet takes one fixed path; routes can change per packet as networks shift.', 'একটি প্যাকেট একটি নির্দিষ্ট পথ নেয় ধরে নেওয়া; নেটওয়ার্ক বদলালে প্রতি প্যাকেটে রুট বদলাতে পারে।'],
  ['cn-nat', 'cn-internet', 'NAT & private addresses', 'NAT ও প্রাইভেট ঠিকানা', 'Intermediate', 14, 'net-hops',
    'NAT lets many devices share one public IP by rewriting addresses and ports at the router boundary.', 'NAT রাউটার সীমানায় ঠিকানা ও পোর্ট পুনর্লিখন করে অনেক ডিভাইসকে একটি পাবলিক IP শেয়ার করতে দেয়।',
    'An office with one public phone number; the receptionist maps incoming calls to the right internal extension.', 'একটি অফিসে একটি পাবলিক ফোন নম্বর; রিসেপশনিস্ট আসা কল সঠিক অভ্যন্তরীণ এক্সটেনশনে মেলায়।',
    'Use NAT to conserve public IPv4 addresses; add port forwarding when an inside host must be reachable.', 'পাবলিক IPv4 বাঁচাতে NAT ব্যবহার করুন; ভেতরের হোস্টে পৌঁছাতে হলে পোর্ট ফরওয়ার্ডিং যোগ করুন।',
    'NAT stretches scarce IPv4 addresses, but it breaks direct inbound connections and complicates peer-to-peer apps.', 'NAT দুর্লভ IPv4 ঠিকানা বাড়ায়, তবে সরাসরি ইনবাউন্ড সংযোগ ভাঙে ও পিয়ার-টু-পিয়ার অ্যাপ জটিল করে।',
    'Expecting an inbound connection to reach a device behind NAT without port forwarding.', 'পোর্ট ফরওয়ার্ডিং ছাড়াই NAT-এর পেছনের ডিভাইসে ইনবাউন্ড সংযোগ পৌঁছাবে আশা করা।'],
  ['cn-icmp', 'cn-internet', 'ICMP, ping & traceroute', 'ICMP, ping ও traceroute', 'Intermediate', 13, 'net-hops',
    'ICMP is the network’s messaging protocol for errors and diagnostics; ping and traceroute are built on it.', 'ICMP হলো নেটওয়ার্কের এরর ও ডায়াগনস্টিক বার্তা প্রোটোকল; ping ও traceroute এর ওপর তৈরি।',
    'Delivery status notes—"undeliverable", "address unknown", or "how long did this route take?"', 'ডেলিভারি স্ট্যাটাস নোট—"ডেলিভার করা যায়নি", "ঠিকানা অজানা", বা "এই রুটে কত সময় লাগল?"',
    'Use ping to test reachability and traceroute to see the hops and where latency or loss appears.', 'পৌঁছানো যাচাইয়ে ping ও হপ এবং কোথায় লেটেন্সি/লস তা দেখতে traceroute ব্যবহার করুন।',
    'ICMP is invaluable for diagnosis, but many networks rate-limit or block it, so silence is not proof of failure.', 'ICMP নির্ণয়ে অমূল্য, তবে অনেক নেটওয়ার্ক একে রেট-লিমিট বা ব্লক করে, তাই নীরবতা ব্যর্থতার প্রমাণ নয়।',
    'Concluding a host is down because ping fails, when ICMP may simply be filtered.', 'ping ব্যর্থ হওয়ায় হোস্ট ডাউন ভাবা, যখন ICMP হয়তো শুধু ফিল্টার করা।'],

  // ── Transport layer ───────────────────────────────────────────────────────
  ['cn-tcp', 'cn-transport', 'TCP: reliable delivery', 'TCP: নির্ভরযোগ্য ডেলিভারি', 'Intermediate', 16, 'net-handshake',
    'TCP provides reliable, ordered, error-checked delivery by numbering bytes and re-sending anything lost.', 'TCP বাইট নম্বর দিয়ে ও হারানো কিছু পুনরায় পাঠিয়ে নির্ভরযোগ্য, ক্রমিক, ত্রুটি-যাচাই ডেলিভারি দেয়।',
    'Registered mail with tracking and re-delivery—nothing arrives out of order or silently lost.', 'ট্র্যাকিং ও পুনঃডেলিভারিসহ রেজিস্টার্ড ডাক—কিছুই ক্রমের বাইরে বা নীরবে হারায় না।',
    'Choose TCP when correctness and order matter: web pages, APIs, file transfer, databases.', 'সঠিকতা ও ক্রম দরকার হলে TCP নিন: ওয়েব পেজ, API, ফাইল ট্রান্সফার, ডেটাবেস।',
    'TCP guarantees delivery, but handshakes, acks, and retransmits add latency and overhead versus raw sending.', 'TCP ডেলিভারি নিশ্চিত করে, তবে হ্যান্ডশেক, অ্যাক ও পুনঃপ্রেরণ কাঁচা প্রেরণের চেয়ে লেটেন্সি ও ওভারহেড যোগ করে।',
    'Using TCP for real-time media where a late-but-perfect packet is useless.', 'রিয়েল-টাইম মিডিয়ায় TCP ব্যবহার, যেখানে দেরিতে-আসা নিখুঁত প্যাকেট অকেজো।'],
  ['cn-udp', 'cn-transport', 'UDP: fast & connectionless', 'UDP: দ্রুত ও কানেকশনলেস', 'Intermediate', 14, 'net-request',
    'UDP sends datagrams with no connection, ordering, or delivery guarantee—minimal overhead, maximum speed.', 'UDP সংযোগ, ক্রম বা ডেলিভারি গ্যারান্টি ছাড়া ডেটাগ্রাম পাঠায়—ন্যূনতম ওভারহেড, সর্বোচ্চ গতি।',
    'Shouting a quick message across a room—fast, but you never know if it was heard.', 'ঘর জুড়ে দ্রুত একটি বার্তা বলা—দ্রুত, তবে শোনা গেল কি না কখনো জানেন না।',
    'Choose UDP when speed beats perfection: live video/voice, gaming, DNS queries, telemetry.', 'যখন গতি নিখুঁততার চেয়ে গুরুত্বপূর্ণ তখন UDP নিন: লাইভ ভিডিও/ভয়েস, গেমিং, DNS কুয়েরি, টেলিমেট্রি।',
    'UDP is fast and lightweight, but your application must handle any loss, duplication, or reordering itself.', 'UDP দ্রুত ও হালকা, তবে যেকোনো লস, ডুপ্লিকেশন বা রি-অর্ডার আপনার অ্যাপ্লিকেশনকেই সামলাতে হয়।',
    'Using UDP for a file transfer and getting silently corrupted or missing data.', 'ফাইল ট্রান্সফারে UDP ব্যবহার করে নীরবে নষ্ট বা হারানো ডেটা পাওয়া।'],
  ['cn-handshake', 'cn-transport', 'The TCP three-way handshake', 'TCP তিন-ধাপ হ্যান্ডশেক', 'Intermediate', 14, 'net-handshake',
    'TCP opens a connection with a three-way handshake—SYN, SYN-ACK, ACK—to agree on sequence numbers before data.', 'TCP তিন-ধাপ হ্যান্ডশেকে—SYN, SYN-ACK, ACK—সংযোগ খোলে, ডেটার আগে সিকোয়েন্স নম্বরে সম্মত হতে।',
    'A phone call: "Can you hear me?" — "Yes, can you hear me?" — "Yes." Then you talk.', 'একটি ফোন কল: "শুনতে পাচ্ছেন?" — "হ্যাঁ, আপনি পাচ্ছেন?" — "হ্যাঁ।" তারপর কথা।',
    'Expect one round trip of setup before any TCP data; over TLS, add another for the secure handshake.', 'যেকোনো TCP ডেটার আগে এক রাউন্ড ট্রিপ সেটআপ আশা করুন; TLS-এ নিরাপদ হ্যান্ডশেকে আরেকটি যোগ করুন।',
    'The handshake guarantees both sides are ready, but it costs a round trip before useful data flows.', 'হ্যান্ডশেক দুই পক্ষ প্রস্তুত তা নিশ্চিত করে, তবে দরকারি ডেটার আগে এক রাউন্ড ট্রিপ খরচ করে।',
    'Ignoring handshake cost when opening many short connections instead of reusing one.', 'একটি সংযোগ পুনঃব্যবহার না করে অনেক ছোট সংযোগ খোলার সময় হ্যান্ডশেক খরচ উপেক্ষা করা।'],
  ['cn-ports', 'cn-transport', 'Ports & sockets', 'পোর্ট ও সকেট', 'Beginner', 13, 'net-request',
    'A port number identifies which application on a host a connection belongs to, so one IP can run many services.', 'একটি পোর্ট নম্বর বলে হোস্টের কোন অ্যাপ্লিকেশনের সঙ্গে সংযোগ, তাই একটি IP অনেক সার্ভিস চালাতে পারে।',
    'An apartment building: the IP is the street address, the port is the specific apartment number.', 'একটি অ্যাপার্টমেন্ট ভবন: IP হলো রাস্তার ঠিকানা, পোর্ট নির্দিষ্ট অ্যাপার্টমেন্ট নম্বর।',
    'Learn the well-known ports (80 HTTP, 443 HTTPS, 22 SSH, 53 DNS) and bind services to expected ports.', 'পরিচিত পোর্ট শিখুন (৮০ HTTP, ৪৪৩ HTTPS, ২২ SSH, ৫৩ DNS) এবং সার্ভিস প্রত্যাশিত পোর্টে বাঁধুন।',
    'Ports let one machine host many services, but open ports are also the attack surface a firewall must guard.', 'পোর্ট এক মেশিনে অনেক সার্ভিস দেয়, তবে খোলা পোর্ট সেই আক্রমণ-পৃষ্ঠ যা ফায়ারওয়ালকে পাহারা দিতে হয়।',
    'Leaving unused ports open to the internet, widening the attack surface for no reason.', 'ব্যবহার-না-করা পোর্ট ইন্টারনেটে খোলা রাখা, বিনা কারণে আক্রমণ-পৃষ্ঠ বাড়ানো।'],
  ['cn-congestion', 'cn-transport', 'Flow & congestion control', 'ফ্লো ও কনজেশন কন্ট্রোল', 'Advanced', 15, 'net-request',
    'TCP flow and congestion control adjust the sending rate to match both the receiver and the network’s capacity.', 'TCP ফ্লো ও কনজেশন কন্ট্রোল গ্রাহক ও নেটওয়ার্ক উভয়ের ক্ষমতার সঙ্গে মিলিয়ে প্রেরণ হার সমন্বয় করে।',
    'Merging onto a busy highway: you speed up gradually and back off the moment you see brake lights.', 'ব্যস্ত মহাসড়কে মেশা: ধীরে গতি বাড়ান আর ব্রেক-লাইট দেখলেই কমান।',
    'Let TCP ramp up slowly (slow start) and shrink its window on loss; design for variable throughput.', 'TCP-কে ধীরে বাড়তে দিন (স্লো স্টার্ট) আর লসে উইন্ডো ছোট করতে দিন; পরিবর্তনশীল থ্রুপুটের জন্য ডিজাইন করুন।',
    'Congestion control keeps the network stable and fair, but it deliberately slows you when links get busy.', 'কনজেশন কন্ট্রোল নেটওয়ার্ক স্থিতিশীল ও ন্যায্য রাখে, তবে লিংক ব্যস্ত হলে ইচ্ছাকৃতভাবে আপনাকে ধীর করে।',
    'Blaming the server for slowness that is really packet loss triggering congestion backoff.', 'ধীরগতির জন্য সার্ভারকে দোষ দেওয়া যা আসলে প্যাকেট লস দিয়ে কনজেশন ব্যাকঅফ ঘটাচ্ছে।'],

  // ── Application layer ─────────────────────────────────────────────────────
  ['cn-dns', 'cn-application', 'DNS: names to addresses', 'DNS: নাম থেকে ঠিকানা', 'Beginner', 15, 'net-request',
    'DNS translates human names like example.com into IP addresses, using a hierarchy of servers.', 'DNS example.com-এর মতো মানুষ-পাঠযোগ্য নামকে IP ঠিকানায় অনুবাদ করে, সার্ভারের শ্রেণিবিন্যাস দিয়ে।',
    'A phone book for the internet—you know the name, DNS gives you the number to dial.', 'ইন্টারনেটের একটি ফোন বই—আপনি নাম জানেন, DNS আপনাকে ডায়াল করার নম্বর দেয়।',
    'Rely on DNS caching and TTLs for speed; use the right record types (A, AAAA, CNAME, MX).', 'গতির জন্য DNS ক্যাশিং ও TTL-এ ভরসা করুন; সঠিক রেকর্ড টাইপ ব্যবহার করুন (A, AAAA, CNAME, MX)।',
    'Caching makes DNS fast, but stale caches and long TTLs delay how quickly changes take effect.', 'ক্যাশিং DNS দ্রুত করে, তবে পুরনো ক্যাশ ও লম্বা TTL পরিবর্তন কত দ্রুত কার্যকর হয় তা দেরি করায়।',
    'Blaming the app when a site "doesn’t load" that is really a DNS resolution or propagation problem.', 'সাইট "লোড হয় না" হলে অ্যাপকে দোষ দেওয়া যা আসলে DNS রেজলিউশন বা প্রোপাগেশন সমস্যা।'],
  ['cn-http', 'cn-application', 'HTTP & the request/response model', 'HTTP ও রিকোয়েস্ট/রেসপন্স মডেল', 'Beginner', 16, 'net-request',
    'HTTP is the request/response protocol of the web: a client asks with a method and path, the server answers with a status and body.', 'HTTP হলো ওয়েবের রিকোয়েস্ট/রেসপন্স প্রোটোকল: ক্লায়েন্ট একটি মেথড ও পাথ দিয়ে চায়, সার্ভার স্ট্যাটাস ও বডি দিয়ে উত্তর দেয়।',
    'Ordering at a counter: you state what you want (GET /menu); they hand it back with a receipt code (200 OK).', 'কাউন্টারে অর্ডার: কী চান বলুন (GET /menu); তারা রসিদ কোডসহ (200 OK) ফেরত দেয়।',
    'Use the right method (GET read, POST create, PUT/PATCH update, DELETE) and read status codes to diagnose.', 'সঠিক মেথড ব্যবহার করুন (GET পড়া, POST তৈরি, PUT/PATCH আপডেট, DELETE) এবং নির্ণয়ে স্ট্যাটাস কোড পড়ুন।',
    'HTTP is simple and stateless, which scales well, but statelessness means sessions need cookies or tokens.', 'HTTP সরল ও স্টেটলেস, যা ভালো স্কেল করে, তবে স্টেটলেসনেসের অর্থ সেশনে কুকি বা টোকেন লাগে।',
    'Using GET to change data or POST to just read—breaking caching, safety, and idempotency expectations.', 'ডেটা বদলাতে GET বা শুধু পড়তে POST ব্যবহার—ক্যাশিং, নিরাপত্তা ও আইডেম্পোটেন্সি প্রত্যাশা ভাঙা।'],
  ['cn-https-tls', 'cn-application', 'HTTPS & TLS', 'HTTPS ও TLS', 'Intermediate', 16, 'net-handshake',
    'HTTPS is HTTP over TLS: TLS encrypts the traffic and verifies the server’s identity with a certificate.', 'HTTPS হলো TLS-এর ওপর HTTP: TLS ট্রাফিক এনক্রিপ্ট করে ও সার্টিফিকেট দিয়ে সার্ভারের পরিচয় যাচাই করে।',
    'A sealed, tamper-evident envelope from a sender whose ID has been checked by a trusted authority.', 'একটি সিল করা, কারচুপি-প্রকাশক খাম, যার প্রেরকের পরিচয় বিশ্বস্ত কর্তৃপক্ষ যাচাই করেছে।',
    'Serve everything over HTTPS; let the TLS handshake negotiate keys before any real data is sent.', 'সবকিছু HTTPS-এ পরিবেশন করুন; আসল ডেটার আগে TLS হ্যান্ডশেককে কী নেগোশিয়েট করতে দিন।',
    'TLS gives privacy and authenticity, but adds a handshake round trip and certificate management overhead.', 'TLS গোপনীয়তা ও সত্যতা দেয়, তবে একটি হ্যান্ডশেক রাউন্ড ট্রিপ ও সার্টিফিকেট ব্যবস্থাপনার ওভারহেড যোগ করে।',
    'Serving login or payment pages over plain HTTP, exposing credentials to anyone on the path.', 'লগইন বা পেমেন্ট পেজ সাধারণ HTTP-তে পরিবেশন, পথের যে কারো কাছে ক্রেডেনশিয়াল ফাঁস।'],
  ['cn-dhcp', 'cn-application', 'DHCP: automatic addressing', 'DHCP: স্বয়ংক্রিয় ঠিকানা', 'Beginner', 12, 'net-request',
    'DHCP automatically assigns a device its IP address, subnet mask, gateway, and DNS servers when it joins a network.', 'DHCP একটি ডিভাইস নেটওয়ার্কে যোগ দিলে স্বয়ংক্রিয়ভাবে তার IP ঠিকানা, সাবনেট মাস্ক, গেটওয়ে ও DNS সার্ভার বরাদ্দ করে।',
    'A hotel front desk handing you a room key and a map the moment you check in.', 'চেক-ইনের মুহূর্তে একটি হোটেল ফ্রন্ট ডেস্ক আপনাকে রুম কী ও ম্যাপ দেয়।',
    'Let DHCP handle addressing for clients; reserve static IPs only for servers and infrastructure.', 'ক্লায়েন্টের ঠিকানা DHCP সামলাতে দিন; শুধু সার্ভার ও অবকাঠামোর জন্য স্ট্যাটিক IP রাখুন।',
    'DHCP removes manual setup and errors, but a DHCP outage can stop new devices from getting on the network.', 'DHCP ম্যানুয়াল সেটআপ ও ভুল সরায়, তবে DHCP আউটেজ নতুন ডিভাইসকে নেটওয়ার্কে ওঠা থামাতে পারে।',
    'Running two DHCP servers on one network, handing out conflicting addresses.', 'এক নেটওয়ার্কে দুটি DHCP সার্ভার চালানো, সাংঘর্ষিক ঠিকানা বিতরণ।'],
  ['cn-websocket', 'cn-application', 'WebSockets & real-time', 'WebSocket ও রিয়েল-টাইম', 'Intermediate', 14, 'net-request',
    'WebSockets upgrade an HTTP connection into a persistent, two-way channel for real-time messages.', 'WebSocket একটি HTTP সংযোগকে রিয়েল-টাইম বার্তার জন্য স্থায়ী, দ্বিমুখী চ্যানেলে আপগ্রেড করে।',
    'Switching from mailing letters back and forth to keeping an open phone line both can talk on.', 'চিঠি আদান-প্রদান থেকে একটি খোলা ফোন লাইন রাখায় বদল, যাতে দুজনই কথা বলতে পারে।',
    'Use WebSockets for live updates (chat, notifications, dashboards) where polling would be wasteful.', 'লাইভ আপডেটে (চ্যাট, নোটিফিকেশন, ড্যাশবোর্ড) WebSocket ব্যবহার করুন, যেখানে পোলিং অপচয়।',
    'WebSockets remove polling overhead and give instant push, but long-lived connections are harder to scale and load-balance.', 'WebSocket পোলিং ওভারহেড সরায় ও তাৎক্ষণিক পুশ দেয়, তবে দীর্ঘস্থায়ী সংযোগ স্কেল ও লোড-ব্যালান্স করা কঠিন।',
    'Opening a WebSocket for data that changes rarely, where a simple request would do.', 'কদাচিৎ বদলানো ডেটার জন্য WebSocket খোলা, যেখানে একটি সাধারণ রিকোয়েস্টই যথেষ্ট।'],

  // ── Infrastructure & delivery ─────────────────────────────────────────────
  ['cn-loadbalancer', 'cn-infra', 'Load balancers', 'লোড ব্যালান্সার', 'Intermediate', 15, 'net-request',
    'A load balancer spreads incoming requests across many servers so no single one is overwhelmed.', 'লোড ব্যালান্সার আসা রিকোয়েস্ট অনেক সার্ভারে ছড়ায় যাতে কোনো একটি অতিরিক্ত চাপে না পড়ে।',
    'A host at a busy restaurant seating guests evenly so no waiter is swamped.', 'একটি ব্যস্ত রেস্তোরাঁর হোস্ট অতিথিদের সমানভাবে বসায় যাতে কোনো ওয়েটার চাপে না পড়ে।',
    'Put a load balancer in front of your servers; use health checks so it skips unhealthy instances.', 'সার্ভারের সামনে একটি লোড ব্যালান্সার রাখুন; হেলথ চেক ব্যবহার করুন যাতে এটি অসুস্থ ইনস্ট্যান্স এড়ায়।',
    'Load balancers add scalability and failover, but become a critical component that itself needs redundancy.', 'লোড ব্যালান্সার স্কেলেবিলিটি ও ফেলওভার যোগ করে, তবে নিজেই একটি সংকটপূর্ণ উপাদান হয় যার রিডানডেন্সি দরকার।',
    'Treating the load balancer as a single point of failure with no backup.', 'লোড ব্যালান্সারকে ব্যাকআপ ছাড়া একক ব্যর্থতা-বিন্দু হিসেবে রাখা।'],
  ['cn-cdn', 'cn-infra', 'CDNs & edge caching', 'CDN ও এজ ক্যাশিং', 'Intermediate', 15, 'net-request',
    'A CDN caches copies of your static content at edge locations near users, cutting latency and origin load.', 'CDN আপনার স্ট্যাটিক কন্টেন্টের কপি ব্যবহারকারীর কাছের এজ লোকেশনে ক্যাশ করে, লেটেন্সি ও অরিজিন লোড কমায়।',
    'Local warehouses stocking popular goods so customers get next-day delivery instead of shipping from one factory.', 'জনপ্রিয় পণ্য মজুত করা লোকাল গুদাম, যাতে গ্রাহক এক কারখানা থেকে না পাঠিয়ে পরদিন ডেলিভারি পায়।',
    'Serve images, scripts, and video from a CDN; set cache headers so the edge can hold content longer.', 'ছবি, স্ক্রিপ্ট ও ভিডিও CDN থেকে পরিবেশন করুন; ক্যাশ হেডার সেট করুন যাতে এজ কন্টেন্ট বেশিক্ষণ রাখে।',
    'CDNs make delivery fast and resilient, but cached content can go stale and needs careful invalidation.', 'CDN ডেলিভারি দ্রুত ও স্থিতিস্থাপক করে, তবে ক্যাশড কন্টেন্ট পুরনো হতে পারে ও সতর্ক ইনভ্যালিডেশন লাগে।',
    'Caching dynamic, user-specific pages on a CDN and serving one user’s data to another.', 'ডাইনামিক, ব্যবহারকারী-নির্দিষ্ট পেজ CDN-এ ক্যাশ করে এক ব্যবহারকারীর ডেটা অন্যকে দেওয়া।'],
  ['cn-proxy', 'cn-infra', 'Proxies & reverse proxies', 'প্রক্সি ও রিভার্স প্রক্সি', 'Intermediate', 14, 'net-request',
    'A proxy sits between clients and servers; a forward proxy fronts clients, a reverse proxy fronts servers.', 'প্রক্সি ক্লায়েন্ট ও সার্ভারের মধ্যে বসে; ফরওয়ার্ড প্রক্সি ক্লায়েন্টের সামনে, রিভার্স প্রক্সি সার্ভারের সামনে থাকে।',
    'A receptionist who takes all requests, then decides which office handles each and returns the answer.', 'একজন রিসেপশনিস্ট যিনি সব অনুরোধ নেন, তারপর কোন অফিস কোনটি সামলাবে ঠিক করে উত্তর ফেরত দেন।',
    'Use a reverse proxy for TLS termination, routing, caching, and hiding your backend topology.', 'TLS টার্মিনেশন, রাউটিং, ক্যাশিং ও ব্যাকএন্ড টপোলজি লুকাতে রিভার্স প্রক্সি ব্যবহার করুন।',
    'A reverse proxy centralizes cross-cutting concerns, but adds a hop and another component to operate.', 'রিভার্স প্রক্সি ক্রস-কাটিং বিষয় কেন্দ্রীভূত করে, তবে একটি হপ ও পরিচালনার আরেকটি উপাদান যোগ করে।',
    'Confusing a forward proxy (represents clients) with a reverse proxy (represents servers).', 'ফরওয়ার্ড প্রক্সি (ক্লায়েন্টের প্রতিনিধি) ও রিভার্স প্রক্সি (সার্ভারের প্রতিনিধি) গুলিয়ে ফেলা।'],
  ['cn-firewall', 'cn-infra', 'Firewalls & security groups', 'ফায়ারওয়াল ও সিকিউরিটি গ্রুপ', 'Intermediate', 14, 'net-hops',
    'A firewall filters traffic against rules, allowing or blocking packets by IP, port, and protocol.', 'ফায়ারওয়াল নিয়মের বিপরীতে ট্রাফিক ফিল্টার করে, IP, পোর্ট ও প্রোটোকল দিয়ে প্যাকেট অনুমোদন বা ব্লক করে।',
    'A building’s security desk that checks each visitor against a guest list before letting them in.', 'একটি ভবনের নিরাপত্তা ডেস্ক যা প্রতিটি দর্শককে ভেতরে ঢোকানোর আগে অতিথি-তালিকার সঙ্গে মেলায়।',
    'Default-deny inbound, allow only the ports you need, and restrict sources to trusted ranges.', 'ইনবাউন্ড ডিফল্ট-ডিনাই করুন, শুধু দরকারি পোর্ট খুলুন, ও সোর্স বিশ্বস্ত রেঞ্জে সীমিত রাখুন।',
    'Tight firewall rules shrink the attack surface, but overly strict rules can block legitimate traffic and are easy to misconfigure.', 'কঠোর ফায়ারওয়াল নিয়ম আক্রমণ-পৃষ্ঠ ছোট করে, তবে অতি-কঠোর নিয়ম বৈধ ট্রাফিক ব্লক করতে পারে ও সহজে ভুল কনফিগার হয়।',
    'Opening a port to the whole internet when only a few sources ever need it.', 'শুধু কয়েকটি সোর্সের দরকার হলেও একটি পোর্ট পুরো ইন্টারনেটে খোলা।'],
  ['cn-vpn', 'cn-infra', 'VPNs & tunnels', 'VPN ও টানেল', 'Intermediate', 14, 'net-hops',
    'A VPN builds an encrypted tunnel across a public network, making remote devices act as if on a private LAN.', 'VPN একটি পাবলিক নেটওয়ার্ক জুড়ে এনক্রিপ্টেড টানেল বানায়, দূরের ডিভাইসকে যেন প্রাইভেট LAN-এ থাকার মতো করে।',
    'A private, armored courier lane running through public roads—outsiders see traffic but not its contents.', 'পাবলিক রাস্তা দিয়ে চলা একটি ব্যক্তিগত, সাঁজোয়া কুরিয়ার লেন—বাইরের লোক ট্রাফিক দেখে কিন্তু ভেতরের বিষয়বস্তু নয়।',
    'Use a VPN to securely reach internal resources or protect traffic on untrusted networks.', 'অভ্যন্তরীণ রিসোর্সে নিরাপদে পৌঁছাতে বা অবিশ্বস্ত নেটওয়ার্কে ট্রাফিক রক্ষা করতে VPN ব্যবহার করুন।',
    'A VPN adds privacy and access, but the tunnel adds latency and the VPN server becomes a chokepoint and trust anchor.', 'VPN গোপনীয়তা ও অ্যাক্সেস যোগ করে, তবে টানেল লেটেন্সি যোগ করে ও VPN সার্ভার একটি চোকপয়েন্ট ও বিশ্বাসের ভিত্তি হয়।',
    'Trusting a VPN to make you anonymous, when it only shifts trust to the VPN provider.', 'VPN আপনাকে বেনামি করবে বিশ্বাস করা, যখন এটি শুধু বিশ্বাস VPN প্রদানকারীর কাছে সরায়।'],

  // ── Security & operations ─────────────────────────────────────────────────
  ['cn-pki', 'cn-ops', 'TLS certificates & PKI', 'TLS সার্টিফিকেট ও PKI', 'Advanced', 16, 'net-handshake',
    'Public-key infrastructure lets a certificate authority vouch for a server’s identity, so browsers trust its TLS certificate.', 'পাবলিক-কী ইনফ্রাস্ট্রাকচার একটি সার্টিফিকেট অথরিটিকে সার্ভারের পরিচয়ের জামিন হতে দেয়, যাতে ব্রাউজার তার TLS সার্টিফিকেট বিশ্বাস করে।',
    'A passport: you trust it because a recognized authority issued and signed it, not the holder alone.', 'একটি পাসপোর্ট: আপনি বিশ্বাস করেন কারণ একটি স্বীকৃত কর্তৃপক্ষ তা জারি ও সই করেছে, শুধু ধারক নয়।',
    'Use certificates from a trusted CA, keep private keys secret, and automate renewal before expiry.', 'বিশ্বস্ত CA থেকে সার্টিফিকেট নিন, প্রাইভেট কী গোপন রাখুন, ও মেয়াদ শেষের আগে নবায়ন অটোমেট করুন।',
    'PKI enables trust at internet scale, but the whole chain breaks if a private key leaks or a CA is compromised.', 'PKI ইন্টারনেট স্কেলে বিশ্বাস সম্ভব করে, তবে প্রাইভেট কী ফাঁস বা CA আপস হলে পুরো চেইন ভাঙে।',
    'Letting a certificate expire, breaking HTTPS for every visitor at once.', 'একটি সার্টিফিকেট মেয়াদ শেষ হতে দেওয়া, একসঙ্গে প্রতিটি দর্শকের জন্য HTTPS ভাঙা।'],
  ['cn-attacks', 'cn-ops', 'Common network attacks', 'সাধারণ নেটওয়ার্ক আক্রমণ', 'Advanced', 15, 'net-hops',
    'Common network attacks include DDoS (flooding), man-in-the-middle (intercepting), and spoofing (faking identity).', 'সাধারণ নেটওয়ার্ক আক্রমণে আছে DDoS (প্লাবন), ম্যান-ইন-দ্য-মিডল (আটকানো) ও স্পুফিং (পরিচয় নকল)।',
    'Jamming a phone line with calls (DDoS), tapping the wire (MITM), or forging the caller ID (spoofing).', 'কল দিয়ে ফোন লাইন জ্যাম (DDoS), তার ট্যাপ করা (MITM), বা কলার আইডি জাল করা (স্পুফিং)।',
    'Defend in depth: encrypt with TLS, validate inputs and identities, rate-limit, and use DDoS protection.', 'গভীর প্রতিরক্ষা: TLS দিয়ে এনক্রিপ্ট, ইনপুট ও পরিচয় যাচাই, রেট-লিমিট ও DDoS সুরক্ষা ব্যবহার করুন।',
    'No single control stops every attack; layered defenses add cost and complexity but leave no single point of failure.', 'কোনো একটি নিয়ন্ত্রণ প্রতিটি আক্রমণ থামায় না; স্তরিত প্রতিরক্ষা খরচ ও জটিলতা যোগ করে তবে একক ব্যর্থতা-বিন্দু রাখে না।',
    'Relying on "no one knows our address" (security by obscurity) instead of real encryption and authentication.', 'আসল এনক্রিপশন ও অথেন্টিকেশনের বদলে "আমাদের ঠিকানা কেউ জানে না" (obscurity দিয়ে নিরাপত্তা)-তে নির্ভর করা।'],
  ['cn-tools', 'cn-ops', 'Troubleshooting tools', 'ট্রাবলশুটিং টুল', 'Intermediate', 14, 'net-hops',
    'Diagnostic tools reveal where a problem lives: ping tests reachability, traceroute shows the path, dig queries DNS, curl inspects HTTP.', 'ডায়াগনস্টিক টুল দেখায় সমস্যা কোথায়: ping পৌঁছানো, traceroute পথ, dig DNS কুয়েরি, curl HTTP পরিদর্শন করে।',
    'A mechanic’s toolkit—each instrument checks one system so you isolate the fault fast.', 'একজন মেকানিকের টুলকিট—প্রতিটি যন্ত্র একটি সিস্টেম যাচাই করে যাতে দ্রুত ত্রুটি আলাদা করা যায়।',
    'Work up the layers: is the host reachable (ping), the path healthy (traceroute), the name resolving (dig), the service answering (curl)?', 'স্তর ধরে এগোন: হোস্ট পৌঁছানো (ping), পথ সুস্থ (traceroute), নাম রিজলভ (dig), সার্ভিস উত্তর দেয় (curl)?',
    'These tools quickly localize faults, but their output can mislead when ICMP is blocked or DNS is cached.', 'এই টুল দ্রুত ত্রুটি স্থানীয় করে, তবে ICMP ব্লক বা DNS ক্যাশড হলে এদের আউটপুট বিভ্রান্ত করতে পারে।',
    'Guessing at fixes instead of using tools to isolate which layer actually fails first.', 'কোন স্তর আসলে আগে ব্যর্থ হয় তা টুল দিয়ে আলাদা না করে অনুমানে ঠিক করার চেষ্টা।'],
  ['cn-observability', 'cn-ops', 'Monitoring & observability', 'মনিটরিং ও অবজার্ভেবিলিটি', 'Intermediate', 13, 'net-request',
    'Network observability means capturing metrics, logs, and packet traces so you can see and explain what the network is doing.', 'নেটওয়ার্ক অবজার্ভেবিলিটি মানে মেট্রিক, লগ ও প্যাকেট ট্রেস ধরা, যাতে নেটওয়ার্ক কী করছে তা দেখা ও ব্যাখ্যা করা যায়।',
    'Dashboard gauges and a black-box recorder in a plane—you cannot fix what you cannot see.', 'একটি বিমানের ড্যাশবোর্ড গজ ও ব্ল্যাক-বক্স রেকর্ডার—যা দেখতে পান না তা ঠিক করতে পারেন না।',
    'Track latency, error rates, and throughput; keep packet captures for the hard, intermittent problems.', 'লেটেন্সি, এরর রেট ও থ্রুপুট ট্র্যাক করুন; কঠিন, মাঝেমধ্যের সমস্যার জন্য প্যাকেট ক্যাপচার রাখুন।',
    'More telemetry speeds diagnosis, but capturing everything costs storage, processing, and can raise privacy concerns.', 'বেশি টেলিমেট্রি নির্ণয় দ্রুত করে, তবে সবকিছু ধরা স্টোরেজ, প্রসেসিং খরচ করে ও গোপনীয়তার উদ্বেগ বাড়াতে পারে।',
    'Only adding monitoring after an outage, so the one incident you needed to see went unrecorded.', 'আউটেজের পরই শুধু মনিটরিং যোগ করা, ফলে যে ঘটনাটি দেখা দরকার ছিল তা রেকর্ড হয়নি।'],
]

// Quick-reference tables (op = concept, value = fact) shown as an extra lesson section.
const reference = {
  'cn-layers': [['Layer 7', 'লেয়ার ৭', 'Application'], ['Layer 4', 'লেয়ার ৪', 'Transport'], ['Layer 3', 'লেয়ার ৩', 'Network'], ['Layer 2', 'লেয়ার ২', 'Data link'], ['Layer 1', 'লেয়ার ১', 'Physical']],
  'cn-ip': [['Private class A', 'প্রাইভেট ক্লাস A', '10.0.0.0/8'], ['Private class B', 'প্রাইভেট ক্লাস B', '172.16.0.0/12'], ['Private class C', 'প্রাইভেট ক্লাস C', '192.168.0.0/16'], ['Loopback', 'লুপব্যাক', '127.0.0.1']],
  'cn-subnetting': [['/24 usable hosts', '/24 ব্যবহারযোগ্য হোস্ট', '254'], ['/25 usable hosts', '/25 ব্যবহারযোগ্য হোস্ট', '126'], ['/26 usable hosts', '/26 ব্যবহারযোগ্য হোস্ট', '62'], ['/30 usable hosts', '/30 ব্যবহারযোগ্য হোস্ট', '2']],
  'cn-ports': [['HTTP', 'HTTP', '80'], ['HTTPS', 'HTTPS', '443'], ['DNS', 'DNS', '53'], ['SSH', 'SSH', '22'], ['SMTP', 'SMTP', '25']],
  'cn-dns': [['Name → IPv4', 'নাম → IPv4', 'A'], ['Name → IPv6', 'নাম → IPv6', 'AAAA'], ['Alias to another name', 'অন্য নামের উপনাম', 'CNAME'], ['Mail server', 'মেইল সার্ভার', 'MX'], ['Name server', 'নেম সার্ভার', 'NS']],
  'cn-http': [['Read a resource', 'রিসোর্স পড়া', 'GET'], ['Create a resource', 'রিসোর্স তৈরি', 'POST'], ['Replace a resource', 'রিসোর্স প্রতিস্থাপন', 'PUT'], ['Delete a resource', 'রিসোর্স মুছুন', 'DELETE'], ['Partial update', 'আংশিক আপডেট', 'PATCH']],
  'cn-tools': [['Test reachability', 'পৌঁছানো যাচাই', 'ping'], ['Trace the path', 'পথ ট্রেস', 'traceroute'], ['Look up DNS', 'DNS লুকআপ', 'dig'], ['Make an HTTP request', 'HTTP রিকোয়েস্ট', 'curl'], ['List connections', 'সংযোগ তালিকা', 'netstat']],
}

// Networking-flavoured distractors for generated exams (each is a clearly wrong idea).
const distractors = [
  l('Send raw bytes with no protocol and hope the other side understands.', 'কোনো প্রোটোকল ছাড়া কাঁচা বাইট পাঠান এবং আশা করুন অন্য পাশ বুঝবে।'),
  l('Assume every network is fast, reliable, and never drops a packet.', 'ধরে নিন প্রতিটি নেটওয়ার্ক দ্রুত, নির্ভরযোগ্য এবং কখনো প্যাকেট হারায় না।'),
  l('Trust any server without verifying its identity or encrypting traffic.', 'পরিচয় যাচাই বা ট্রাফিক এনক্রিপ্ট না করে যেকোনো সার্ভার বিশ্বাস করুন।'),
  l('Ignore latency and round trips because the demo felt fast enough.', 'ডেমো যথেষ্ট দ্রুত লেগেছে বলে লেটেন্সি ও রাউন্ড ট্রিপ উপেক্ষা করুন।'),
  l('Hard-code IP addresses and never use DNS names.', 'IP ঠিকানা হার্ড-কোড করুন এবং কখনো DNS নাম ব্যবহার করবেন না।'),
  l('Retry forever with no timeout when a request stalls.', 'অনুরোধ আটকে গেলে টাইমআউট ছাড়াই চিরকাল রিট্রাই করুন।'),
  l('Send passwords and tokens over plain, unencrypted HTTP.', 'সাধারণ, এনক্রিপ্ট-না-করা HTTP-তে পাসওয়ার্ড ও টোকেন পাঠান।'),
  l('Treat every layer as one blob instead of separate responsibilities.', 'প্রতিটি স্তরকে আলাদা দায়িত্ব না ভেবে এক তাল হিসেবে ধরুন।'),
]

export const netTopics = rawTopics.map((row, index) => {
  const [id, moduleId, en, bn, difficulty, minutes, diagram, insightEn, insightBn, analogyEn, analogyBn, actionEn, actionBn, tradeoffEn, tradeoffBn, mistakeEn, mistakeBn] = row
  const topic = {
    id, order: index + 1, moduleId, title: l(en, bn), difficulty, minutes, diagram, deepDive: null,
    insight: l(insightEn, insightBn), analogy: l(analogyEn, analogyBn), action: l(actionEn, actionBn), tradeoff: l(tradeoffEn, tradeoffBn), mistake: l(mistakeEn, mistakeBn),
    complexity: (reference[id] || []).map(([opEn, opBn, value]) => ({ op: l(opEn, opBn), value })),
    objectives: [
      l(`Explain ${en} in plain language.`, `সহজ ভাষায় ${bn} ব্যাখ্যা করতে পারবেন।`),
      l('Place it in the right network layer and know when it applies.', 'এটিকে সঠিক নেটওয়ার্ক স্তরে বসাতে ও কখন প্রযোজ্য তা জানতে পারবেন।'),
      l('State its most important trade-off and a common failure mode.', 'এর সবচেয়ে গুরুত্বপূর্ণ ট্রেড-অফ ও একটি সাধারণ ব্যর্থতা বলতে পারবেন।'),
    ],
    advantages: l(`Understanding ${en.toLowerCase()} lets you reason about how real traffic actually flows and fails.`, `${bn} বোঝা আপনাকে বাস্তব ট্রাফিক আসলে কীভাবে চলে ও ব্যর্থ হয় তা নিয়ে ভাবতে দেয়।`),
    interview: l(`Name the layer and protocol for ${en.toLowerCase()}, explain when it is the right choice, and state its cost.`, `${bn}-এর স্তর ও প্রোটোকল বলুন, কখন এটি সঠিক পছন্দ ব্যাখ্যা করুন, ও এর খরচ বলুন।`),
    glossary: [
      { term: l('Protocol', 'প্রোটোকল'), definition: l('An agreed set of rules for how two parties communicate.', 'দুই পক্ষ কীভাবে যোগাযোগ করবে তার সম্মত নিয়ম।') },
      { term: l('Latency', 'লেটেন্সি'), definition: l('The time it takes for one packet to travel from source to destination.', 'একটি প্যাকেট সোর্স থেকে গন্তব্যে যেতে যে সময় নেয়।') },
    ],
  }
  topic.exam = buildExam(topic, { distractors, subject: 'networking' })
  return topic
})

// ── Guided labs (bilingual) ─────────────────────────────────────────────────
export const netLabs = [
  {
    id: 'cn-request-lab', icon: '⇄', title: l('Trace a Web Request', 'ওয়েব রিকোয়েস্ট ট্রেস ল্যাব'), subtitle: l('Order what happens when you open an HTTPS URL.', 'একটি HTTPS URL খুললে কী ঘটে তা সাজান।'),
    stages: [
      ['Find the server', 'সার্ভার খুঁজুন', 'You type a URL. What must happen first to find the server?', 'আপনি একটি URL টাইপ করেন। সার্ভার খুঁজতে প্রথমে কী করতে হবে?', ['Resolve the name with DNS', 'Send the HTTP request immediately'], ['DNS দিয়ে নাম রিজলভ করুন', 'সঙ্গে সঙ্গে HTTP রিকোয়েস্ট পাঠান'], 0, 'DNS turns the name into an IP address before any connection can be made.', 'সংযোগের আগে DNS নামকে একটি IP ঠিকানায় পরিণত করে।'],
      ['Open the connection', 'সংযোগ খুলুন', 'You have the IP. How does TCP start the connection?', 'আপনার কাছে IP আছে। TCP কীভাবে সংযোগ শুরু করে?', ['A three-way handshake', 'Just send data and hope'], ['তিন-ধাপ হ্যান্ডশেক', 'শুধু ডেটা পাঠিয়ে আশা করা'], 0, 'TCP does a SYN, SYN-ACK, ACK handshake before any data.', 'ডেটার আগে TCP SYN, SYN-ACK, ACK হ্যান্ডশেক করে।'],
      ['Secure it', 'নিরাপদ করুন', 'It is HTTPS. What secures the connection before data flows?', 'এটি HTTPS। ডেটা যাওয়ার আগে কী সংযোগ নিরাপদ করে?', ['A TLS handshake', 'Nothing — HTTP is already safe'], ['একটি TLS হ্যান্ডশেক', 'কিছুই না — HTTP এমনিতেই নিরাপদ'], 0, 'TLS negotiates encryption and verifies the certificate first.', 'TLS আগে এনক্রিপশন নেগোশিয়েট ও সার্টিফিকেট যাচাই করে।'],
      ['Ask for the page', 'পেজ চান', 'The secure connection is ready. What does the browser send?', 'নিরাপদ সংযোগ প্রস্তুত। ব্রাউজার কী পাঠায়?', ['An HTTP request (GET /)', 'A DNS query'], ['একটি HTTP রিকোয়েস্ট (GET /)', 'একটি DNS কুয়েরি'], 0, 'Now the browser sends the actual HTTP request for the page.', 'এখন ব্রাউজার পেজের জন্য আসল HTTP রিকোয়েস্ট পাঠায়।'],
      ['Get the answer', 'উত্তর পান', 'The server processes it. What comes back?', 'সার্ভার এটি প্রসেস করে। কী ফেরত আসে?', ['An HTTP response with a status and body', 'A SYN packet'], ['স্ট্যাটাস ও বডিসহ একটি HTTP রেসপন্স', 'একটি SYN প্যাকেট'], 0, 'The server returns a status code (like 200) and the page body.', 'সার্ভার একটি স্ট্যাটাস কোড (যেমন 200) ও পেজ বডি ফেরত দেয়।'],
    ],
  },
  {
    id: 'cn-protocol-lab', icon: '◇', title: l('Pick the Protocol', 'প্রোটোকল বাছাই ল্যাব'), subtitle: l('Match each need to the right protocol.', 'প্রতিটি প্রয়োজনে সঠিক প্রোটোকল মেলান।'),
    stages: [
      ['Reliable transfer', 'নির্ভরযোগ্য ট্রান্সফার', 'You need reliable, ordered file transfer. Which transport?', 'আপনার নির্ভরযোগ্য, ক্রমিক ফাইল ট্রান্সফার দরকার। কোন ট্রান্সপোর্ট?', ['TCP', 'UDP'], ['TCP', 'UDP'], 0, 'TCP guarantees order and re-sends lost data.', 'TCP ক্রম নিশ্চিত করে ও হারানো ডেটা পুনরায় পাঠায়।'],
      ['Live call', 'লাইভ কল', 'A live video call values speed over perfection. Which transport?', 'একটি লাইভ ভিডিও কল নিখুঁততার চেয়ে গতিকে মূল্য দেয়। কোন ট্রান্সপোর্ট?', ['UDP', 'TCP'], ['UDP', 'TCP'], 0, 'UDP is low-overhead; a late packet is useless for live media.', 'UDP কম-ওভারহেড; লাইভ মিডিয়ায় দেরিতে-আসা প্যাকেট অকেজো।'],
      ['Name to address', 'নাম থেকে ঠিকানা', 'You must turn a domain name into an IP. Which protocol?', 'আপনাকে একটি ডোমেইন নাম IP-তে পরিণত করতে হবে। কোন প্রোটোকল?', ['DNS', 'ARP'], ['DNS', 'ARP'], 0, 'DNS maps names to IPs; ARP maps IPs to MACs locally.', 'DNS নামকে IP-তে; ARP লোকালি IP-কে MAC-এ মেলায়।'],
      ['Auto addressing', 'স্বয়ংক্রিয় ঠিকানা', 'A new device must get an IP automatically. Which protocol?', 'একটি নতুন ডিভাইসকে স্বয়ংক্রিয়ভাবে IP পেতে হবে। কোন প্রোটোকল?', ['DHCP', 'NAT'], ['DHCP', 'NAT'], 0, 'DHCP leases addresses; NAT shares one public IP.', 'DHCP ঠিকানা লিজ দেয়; NAT একটি পাবলিক IP শেয়ার করে।'],
      ['Encrypt the web', 'ওয়েব এনক্রিপ্ট', 'You must encrypt and authenticate web traffic. Which?', 'আপনাকে ওয়েব ট্রাফিক এনক্রিপ্ট ও অথেন্টিকেট করতে হবে। কোনটি?', ['TLS (HTTPS)', 'Plain HTTP'], ['TLS (HTTPS)', 'সাধারণ HTTP'], 0, 'TLS encrypts traffic and verifies identity; plain HTTP does neither.', 'TLS ট্রাফিক এনক্রিপ্ট ও পরিচয় যাচাই করে; সাধারণ HTTP কোনোটিই নয়।'],
    ],
  },
  {
    id: 'cn-address-lab', icon: '⊞', title: l('Address & Subnet', 'ঠিকানা ও সাবনেট ল্যাব'), subtitle: l('Reason about IP addressing and routing.', 'IP ঠিকানা ও রাউটিং নিয়ে ভাবুন।'),
    stages: [
      ['Private or public', 'প্রাইভেট না পাবলিক', 'Which address is private (not routable on the internet)?', 'কোন ঠিকানা প্রাইভেট (ইন্টারনেটে রাউটেবল নয়)?', ['192.168.1.10', '8.8.8.8'], ['192.168.1.10', '8.8.8.8'], 0, '192.168.x.x is a private range; 8.8.8.8 is public.', '192.168.x.x একটি প্রাইভেট রেঞ্জ; 8.8.8.8 পাবলিক।'],
      ['Count the hosts', 'হোস্ট গুনুন', 'A /24 subnet gives how many usable host addresses?', 'একটি /24 সাবনেট কতটি ব্যবহারযোগ্য হোস্ট ঠিকানা দেয়?', ['254', '256'], ['254', '256'], 0, '256 total minus the network and broadcast addresses leaves 254.', 'মোট 256 থেকে নেটওয়ার্ক ও ব্রডকাস্ট বাদ দিলে 254 থাকে।'],
      ['Leave the network', 'নেটওয়ার্ক ছাড়ুন', 'Your host and the server are on different networks. Who forwards the packet?', 'আপনার হোস্ট ও সার্ভার ভিন্ন নেটওয়ার্কে। কে প্যাকেট ফরওয়ার্ড করে?', ['The default gateway (router)', 'The DNS server'], ['ডিফল্ট গেটওয়ে (রাউটার)', 'DNS সার্ভার'], 0, 'Off-network traffic goes to the default gateway to be routed.', 'অফ-নেটওয়ার্ক ট্রাফিক রাউট হতে ডিফল্ট গেটওয়েতে যায়।'],
      ['Share one IP', 'এক IP শেয়ার', 'Many home devices share one public IP. What makes that work?', 'অনেক হোম ডিভাইস একটি পাবলিক IP শেয়ার করে। কী এটি সম্ভব করে?', ['NAT', 'ARP'], ['NAT', 'ARP'], 0, 'NAT rewrites addresses and ports so many devices share one public IP.', 'NAT ঠিকানা ও পোর্ট পুনর্লিখন করে যাতে অনেক ডিভাইস এক পাবলিক IP শেয়ার করে।'],
    ],
  },
  {
    id: 'cn-infra-lab', icon: '⛨', title: l('Secure & Scale', 'নিরাপদ ও স্কেল ল্যাব'), subtitle: l('Choose the right infrastructure for each goal.', 'প্রতিটি লক্ষ্যে সঠিক অবকাঠামো বাছুন।'),
    stages: [
      ['Spread the load', 'লোড ছড়ান', 'Traffic spikes across many servers. What spreads it evenly?', 'অনেক সার্ভারে ট্রাফিক স্পাইক করে। কী এটি সমানভাবে ছড়ায়?', ['A load balancer', 'One bigger server'], ['একটি লোড ব্যালান্সার', 'একটি বড় সার্ভার'], 0, 'A load balancer distributes requests and skips unhealthy servers.', 'লোড ব্যালান্সার রিকোয়েস্ট বণ্টন করে ও অসুস্থ সার্ভার এড়ায়।'],
      ['Fast worldwide', 'বিশ্বজুড়ে দ্রুত', 'Users worldwide need fast static assets. What helps most?', 'বিশ্বজুড়ে ব্যবহারকারীর দ্রুত স্ট্যাটিক অ্যাসেট দরকার। কী সবচেয়ে সাহায্য করে?', ['A CDN', 'One origin server'], ['একটি CDN', 'একটি অরিজিন সার্ভার'], 0, 'A CDN caches content at edges near users to cut latency.', 'CDN ব্যবহারকারীর কাছের এজে কন্টেন্ট ক্যাশ করে লেটেন্সি কমায়।'],
      ['Prove identity', 'পরিচয় প্রমাণ', 'You must verify a site’s identity and encrypt traffic. What proves identity?', 'আপনাকে একটি সাইটের পরিচয় যাচাই ও ট্রাফিক এনক্রিপ্ট করতে হবে। কী পরিচয় প্রমাণ করে?', ['A TLS certificate', 'A firewall rule'], ['একটি TLS সার্টিফিকেট', 'একটি ফায়ারওয়াল নিয়ম'], 0, 'A CA-signed TLS certificate proves the server’s identity.', 'CA-সাইনড TLS সার্টিফিকেট সার্ভারের পরিচয় প্রমাণ করে।'],
      ['Block bad traffic', 'খারাপ ট্রাফিক ব্লক', 'You must block unwanted inbound traffic by port and IP. What do you use?', 'আপনাকে পোর্ট ও IP দিয়ে অবাঞ্ছিত ইনবাউন্ড ট্রাফিক ব্লক করতে হবে। কী ব্যবহার করবেন?', ['A firewall', 'A load balancer'], ['একটি ফায়ারওয়াল', 'একটি লোড ব্যালান্সার'], 0, 'A firewall allows or blocks traffic by IP, port, and protocol.', 'ফায়ারওয়াল IP, পোর্ট ও প্রোটোকল দিয়ে ট্রাফিক অনুমোদন বা ব্লক করে।'],
    ],
  },
].map((lab) => ({ ...lab, stages: lab.stages.map((s, i) => ({ id: `${lab.id}-${i}`, title: l(s[0], s[1]), question: l(s[2], s[3]), options: s[4].map((en, x) => l(en, s[5][x])), correct: s[6], feedback: l(s[7], s[8]) })) }))
