import { allFlagshipContent } from './flagship-content.js'
import { flagshipExams } from './flagship-exams.js'

export const l = (en, bn) => ({ en, bn })

export const modules = [
  { id: 'foundations', number: '01', title: l('Foundations', 'ভিত্তি'), description: l('Learn the language and measurements behind every reliable design.', 'প্রতিটি নির্ভরযোগ্য ডিজাইনের ভাষা ও পরিমাপ শিখুন।'), color: '#6c5ce7' },
  { id: 'components', number: '02', title: l('Core components', 'মূল কম্পোনেন্ট'), description: l('Understand the building blocks used to serve, store, and move data.', 'ডেটা পরিবেশন, সংরক্ষণ ও স্থানান্তরের মূল উপাদানগুলো বুঝুন।'), color: '#0284c7' },
  { id: 'distributed', number: '03', title: l('Distributed systems', 'ডিস্ট্রিবিউটেড সিস্টেম'), description: l('Reason about coordination, consistency, and failure across machines.', 'একাধিক মেশিনে সমন্বয়, সামঞ্জস্য ও ব্যর্থতা নিয়ে ভাবতে শিখুন।'), color: '#0f9f78' },
  { id: 'production', number: '04', title: l('Production architecture', 'প্রোডাকশন আর্কিটেকচার'), description: l('Make systems observable, secure, and resilient in the real world.', 'বাস্তব জগতে সিস্টেমকে পর্যবেক্ষণযোগ্য, নিরাপদ ও সহনশীল করুন।'), color: '#d97706' },
  { id: 'practical', number: '05', title: l('Practical systems', 'ব্যবহারিক সিস্টেম'), description: l('Combine the pieces in interview-ready architecture case studies.', 'ইন্টারভিউ-উপযোগী আর্কিটেকচার কেস স্টাডিতে সব অংশ একত্র করুন।'), color: '#e34b87' },
  { id: 'mastery', number: '06', title: l('Architecture mastery', 'আর্কিটেকচার মাস্টারি'), description: l('Master specialized patterns and high-stakes production case studies.', 'বিশেষায়িত প্যাটার্ন ও গুরুত্বপূর্ণ প্রোডাকশন কেস স্টাডি আয়ত্ত করুন।'), color: '#7c3aed' },
]

const rawTopics = [
  ['system-design', 'foundations', 'What is system design?', 'সিস্টেম ডিজাইন কী?', 'Beginner', 12, 'request',
    'System design turns product goals and constraints into components, data flows, and explicit trade-offs.', 'সিস্টেম ডিজাইন পণ্যের লক্ষ্য ও সীমাবদ্ধতাকে কম্পোনেন্ট, ডেটা প্রবাহ ও স্পষ্ট ট্রেড-অফে রূপ দেয়।',
    'Think of planning a city: roads, utilities, and emergency routes must work together.', 'একটি শহর পরিকল্পনার কথা ভাবুন—রাস্তা, পরিষেবা ও জরুরি পথ একসঙ্গে কাজ করতে হয়।',
    'Start with requirements and scale before choosing technology.', 'প্রযুক্তি বাছাইয়ের আগে রিকোয়ারমেন্ট ও স্কেল নির্ধারণ করুন।',
    'A design that optimizes one quality often spends cost or complexity elsewhere.', 'একটি গুণ উন্নত করতে গেলে প্রায়ই অন্যদিকে খরচ বা জটিলতা বাড়ে।',
    'Jumping directly to microservices without defining the problem.', 'সমস্যা নির্ধারণ না করেই সরাসরি মাইক্রোসার্ভিস বেছে নেওয়া।'],
  ['request-lifecycle', 'foundations', 'Client-server & request lifecycle', 'ক্লায়েন্ট-সার্ভার ও রিকোয়েস্ট লাইফসাইকেল', 'Beginner', 15, 'request',
    'A request crosses DNS, networks, servers, and storage before a response reaches the client.', 'একটি রিকোয়েস্ট ক্লায়েন্টে উত্তর ফেরার আগে DNS, নেটওয়ার্ক, সার্ভার ও স্টোরেজ অতিক্রম করে।',
    'It is like a parcel moving through address lookup, sorting centers, and delivery.', 'এটি ঠিকানা খোঁজা, বাছাই কেন্দ্র ও ডেলিভারির মধ্য দিয়ে যাওয়া পার্সেলের মতো।',
    'Trace every hop and budget latency across the complete path.', 'প্রতিটি ধাপ চিহ্নিত করুন এবং পুরো পথে লেটেন্সির বাজেট করুন।',
    'Extra hops improve separation but add latency and failure points.', 'অতিরিক্ত ধাপ পৃথকীকরণ বাড়ায়, তবে লেটেন্সি ও ব্যর্থতার স্থানও বাড়ায়।',
    'Measuring only application time while ignoring network and database time.', 'নেটওয়ার্ক ও ডেটাবেস সময় বাদ দিয়ে শুধু অ্যাপ্লিকেশন সময় মাপা।'],
  ['requirements', 'foundations', 'Functional & non-functional requirements', 'ফাংশনাল ও নন-ফাংশনাল রিকোয়ারমেন্ট', 'Beginner', 14, 'request',
    'Functional requirements define behavior; non-functional requirements define how well it must work.', 'ফাংশনাল রিকোয়ারমেন্ট আচরণ নির্ধারণ করে; নন-ফাংশনাল রিকোয়ারমেন্ট সেটি কত ভালো কাজ করবে তা বলে।',
    'A restaurant needs a menu, but also acceptable wait time, safety, and capacity.', 'একটি রেস্তোরাঁর মেনুর পাশাপাশি গ্রহণযোগ্য অপেক্ষার সময়, নিরাপত্তা ও ধারণক্ষমতা দরকার।',
    'Convert vague words such as “fast” and “reliable” into measurable targets.', '“দ্রুত” ও “নির্ভরযোগ্য”-এর মতো অস্পষ্ট শব্দকে পরিমাপযোগ্য লক্ষ্যে রূপ দিন।',
    'Stricter targets increase infrastructure and engineering cost.', 'কঠোর লক্ষ্য অবকাঠামো ও প্রকৌশল খরচ বাড়ায়।',
    'Treating every possible feature as an MVP requirement.', 'সম্ভাব্য প্রতিটি ফিচারকে MVP রিকোয়ারমেন্ট ধরা।'],
  ['estimation', 'foundations', 'Back-of-the-envelope estimation', 'ব্যাক-অফ-দ্য-এনভেলপ হিসাব', 'Beginner', 18, 'database',
    'Quick estimates expose whether traffic, storage, or bandwidth will dominate the architecture.', 'দ্রুত হিসাব দেখায় ট্রাফিক, স্টোরেজ নাকি ব্যান্ডউইথ আর্কিটেকচারকে সবচেয়ে বেশি প্রভাবিত করবে।',
    'It is like estimating food for a wedding before choosing pot sizes.', 'হাঁড়ির আকার বাছাইয়ের আগে বিয়ের খাবারের পরিমাণ অনুমান করার মতো।',
    'State assumptions, calculate orders of magnitude, and revisit the largest number.', 'অনুমান লিখুন, মোটামুটি মাত্রা হিসাব করুন এবং সবচেয়ে বড় সংখ্যাটি পুনরায় যাচাই করুন।',
    'Estimates trade precision for speed and directional confidence.', 'হিসাব গতি ও দিকনির্দেশের জন্য নিখুঁততা কিছুটা ছাড় দেয়।',
    'Using daily traffic directly as peak requests per second.', 'দৈনিক ট্রাফিককেই সরাসরি পিক রিকোয়েস্ট-প্রতি-সেকেন্ড হিসেবে ব্যবহার করা।'],
  ['performance', 'foundations', 'Latency, throughput & concurrency', 'লেটেন্সি, থ্রুপুট ও কনকারেন্সি', 'Beginner', 16, 'loadbalancer',
    'Latency measures one operation, throughput measures rate, and concurrency measures simultaneous work.', 'লেটেন্সি একটি অপারেশনের সময়, থ্রুপুট কাজের হার এবং কনকারেন্সি একসঙ্গে চলা কাজ মাপে।',
    'A toll booth has per-car delay, cars per minute, and cars currently in lanes.', 'টোল বুথে প্রতি গাড়ির বিলম্ব, প্রতি মিনিটে গাড়ি এবং বর্তমানে লাইনে থাকা গাড়ি থাকে।',
    'Measure percentiles and saturation instead of relying only on averages.', 'শুধু গড়ের বদলে পার্সেন্টাইল ও স্যাচুরেশন পরিমাপ করুন।',
    'Batching can improve throughput while increasing individual latency.', 'ব্যাচিং থ্রুপুট বাড়াতে পারে, তবে ব্যক্তিগত লেটেন্সি বাড়ায়।',
    'Reporting average latency while hiding slow tail requests.', 'ধীর টেইল রিকোয়েস্ট লুকিয়ে শুধু গড় লেটেন্সি দেখানো।'],
  ['reliability', 'foundations', 'Scale, availability & fault tolerance', 'স্কেল, অ্যাভেইলেবিলিটি ও ফল্ট টলারেন্স', 'Intermediate', 18, 'loadbalancer',
    'Scale handles growth; redundancy and isolation keep service available during failure.', 'স্কেল বৃদ্ধি সামলায়; রিডানডেন্সি ও আইসোলেশন ব্যর্থতার সময় সেবা চালু রাখে।',
    'A bridge adds lanes for traffic and alternate routes for closures.', 'একটি সেতু ট্রাফিকের জন্য লেন এবং বন্ধ হলে বিকল্প পথ যোগ করে।',
    'Remove single points of failure and test failover regularly.', 'সিঙ্গেল পয়েন্ট অব ফেইলিউর দূর করুন এবং নিয়মিত ফেইলওভার পরীক্ষা করুন।',
    'Redundancy improves availability but costs money and coordination.', 'রিডানডেন্সি অ্যাভেইলেবিলিটি বাড়ায়, তবে খরচ ও সমন্বয় বাড়ায়।',
    'Adding replicas that still share one database or availability zone.', 'একই ডেটাবেস বা অ্যাভেইলেবিলিটি জোন ব্যবহার করা রেপ্লিকা যোগ করা।'],

  ['dns-proxy', 'components', 'DNS, proxies & reverse proxies', 'DNS, প্রক্সি ও রিভার্স প্রক্সি', 'Beginner', 17, 'request',
    'DNS finds an address; proxies mediate traffic and can hide either clients or servers.', 'DNS ঠিকানা খুঁজে দেয়; প্রক্সি ট্রাফিক মধ্যস্থতা করে এবং ক্লায়েন্ট বা সার্ভারকে আড়াল করতে পারে।',
    'DNS is a phone book, while a reception desk routes visitors inside a building.', 'DNS ফোনবুকের মতো, আর রিসেপশন ডেস্ক ভবনের ভেতরে দর্শনার্থী পাঠায়।',
    'Use TTLs deliberately and terminate TLS at a controlled edge.', 'TTL সচেতনভাবে নির্ধারণ করুন এবং নিয়ন্ত্রিত এজে TLS শেষ করুন।',
    'Caching DNS is fast but delays propagation of address changes.', 'DNS ক্যাশ দ্রুত, তবে ঠিকানা পরিবর্তন ছড়াতে দেরি করে।',
    'Assuming a DNS change is instantaneous everywhere.', 'DNS পরিবর্তন সর্বত্র তাৎক্ষণিক হবে ধরে নেওয়া।'],
  ['load-balancing', 'components', 'Load balancing & service discovery', 'লোড ব্যালান্সিং ও সার্ভিস ডিসকভারি', 'Intermediate', 18, 'loadbalancer',
    'A load balancer distributes healthy traffic; discovery tracks where service instances live.', 'লোড ব্যালান্সার সুস্থ সার্ভারে ট্রাফিক ভাগ করে; ডিসকভারি সার্ভিস ইনস্ট্যান্সের অবস্থান জানে।',
    'A traffic officer needs both routing rules and a current list of open roads.', 'ট্রাফিক পুলিশের রাউটিং নিয়ম ও খোলা রাস্তার বর্তমান তালিকা—দুটিই দরকার।',
    'Combine health checks, sensible algorithms, and connection draining.', 'হেলথ চেক, উপযুক্ত অ্যালগরিদম ও কানেকশন ড্রেইনিং একত্র করুন।',
    'Sticky sessions simplify state but weaken even distribution and failover.', 'স্টিকি সেশন স্টেট সহজ করে, তবে সমবণ্টন ও ফেইলওভার দুর্বল করে।',
    'Sending traffic to an unhealthy instance because health checks are too shallow.', 'অগভীর হেলথ চেকের কারণে অসুস্থ ইনস্ট্যান্সে ট্রাফিক পাঠানো।'],
  ['cdn', 'components', 'CDN & edge delivery', 'CDN ও এজ ডেলিভারি', 'Intermediate', 15, 'cdn',
    'A CDN serves cacheable content near users and shields the origin from repeated work.', 'CDN ব্যবহারকারীর কাছে ক্যাশযোগ্য কনটেন্ট দেয় এবং অরিজিনকে পুনরাবৃত্ত কাজ থেকে রক্ষা করে।',
    'It is like stocking popular products in neighborhood shops instead of one distant warehouse.', 'একটি দূরের গুদামের বদলে এলাকার দোকানে জনপ্রিয় পণ্য রাখার মতো।',
    'Choose cache keys, TTLs, and invalidation rules before caching dynamic content.', 'ডাইনামিক কনটেন্ট ক্যাশ করার আগে ক্যাশ কী, TTL ও ইনভ্যালিডেশন নিয়ম ঠিক করুন।',
    'Long TTLs increase hit rate but risk serving stale content.', 'দীর্ঘ TTL হিট রেট বাড়ায়, তবে পুরোনো কনটেন্ট দেখানোর ঝুঁকি থাকে।',
    'Including personalized headers in a shared cache key incorrectly.', 'শেয়ার্ড ক্যাশ কী-তে ব্যক্তিগত হেডার ভুলভাবে অন্তর্ভুক্ত করা।'],
  ['api-protocols', 'components', 'REST, GraphQL, gRPC & WebSockets', 'REST, GraphQL, gRPC ও WebSockets', 'Intermediate', 22, 'request',
    'Choose a communication style from interaction shape, consumers, latency, and compatibility needs.', 'ইন্টারঅ্যাকশনের ধরন, ব্যবহারকারী, লেটেন্সি ও সামঞ্জস্যের প্রয়োজন থেকে যোগাযোগ পদ্ধতি বাছুন।',
    'Letters, custom order forms, phone calls, and open radio channels suit different conversations.', 'চিঠি, কাস্টম ফর্ম, ফোনকল ও খোলা রেডিও চ্যানেল ভিন্ন কথোপকথনের জন্য উপযুক্ত।',
    'Define contracts, timeouts, errors, pagination, and evolution rules explicitly.', 'কনট্র্যাক্ট, টাইমআউট, এরর, পেজিনেশন ও পরিবর্তনের নিয়ম স্পষ্ট করুন।',
    'Efficient binary protocols improve performance but reduce browser friendliness.', 'দক্ষ বাইনারি প্রোটোকল পারফরম্যান্স বাড়ায়, তবে ব্রাউজার-সুবিধা কমায়।',
    'Choosing WebSockets for data that changes only a few times per day.', 'দিনে কয়েকবার বদলানো ডেটার জন্য WebSocket বেছে নেওয়া।'],
  ['caching', 'components', 'Caching strategies', 'ক্যাশিং কৌশল', 'Intermediate', 20, 'cache',
    'Caching saves repeated work by serving reusable data from a faster layer.', 'ক্যাশিং দ্রুত স্তর থেকে পুনঃব্যবহারযোগ্য ডেটা দিয়ে পুনরাবৃত্ত কাজ বাঁচায়।',
    'Keep frequently used ingredients on the kitchen counter instead of the pantry.', 'বারবার ব্যবহৃত উপকরণ প্যান্ট্রির বদলে রান্নাঘরের কাউন্টারে রাখার মতো।',
    'Pick cache-aside, write-through, or write-back from freshness and write needs.', 'ফ্রেশনেস ও রাইটের প্রয়োজন অনুযায়ী cache-aside, write-through বা write-back বাছুন।',
    'Caching reduces latency and load but creates invalidation and consistency work.', 'ক্যাশ লেটেন্সি ও লোড কমায়, তবে ইনভ্যালিডেশন ও কনসিস্টেন্সির কাজ বাড়ায়।',
    'Letting many expired keys trigger the same expensive database query.', 'অনেক মেয়াদোত্তীর্ণ কী দিয়ে একই ব্যয়বহুল ডেটাবেস কুয়েরি চালানো।'],
  ['sql-nosql', 'components', 'SQL versus NoSQL', 'SQL বনাম NoSQL', 'Intermediate', 20, 'database',
    'Select storage from access patterns, relationships, transaction needs, and scale—not fashion.', 'প্রচলন নয়—অ্যাক্সেস প্যাটার্ন, সম্পর্ক, ট্রানজ্যাকশন ও স্কেলের ভিত্তিতে স্টোরেজ বাছুন।',
    'Choose a filing system based on what you retrieve, not the cabinet color.', 'ক্যাবিনেটের রং নয়, কী খুঁজবেন তার ভিত্তিতে ফাইলিং সিস্টেম বাছুন।',
    'Write the dominant queries and consistency rules before choosing a database.', 'ডেটাবেস বাছার আগে প্রধান কুয়েরি ও কনসিস্টেন্সি নিয়ম লিখুন।',
    'Flexible schemas scale some workloads well but move guarantees into application logic.', 'ফ্লেক্সিবল স্কিমা কিছু ওয়ার্কলোড ভালো স্কেল করে, তবে গ্যারান্টি অ্যাপ্লিকেশন লজিকে যায়।',
    'Using NoSQL as a synonym for automatically scalable.', 'NoSQL-কে স্বয়ংক্রিয়ভাবে স্কেলযোগ্য ধরে নেওয়া।'],
  ['model-index', 'components', 'Data modeling & indexing', 'ডেটা মডেলিং ও ইনডেক্সিং', 'Intermediate', 22, 'database',
    'Model data around invariants and access patterns; indexes exchange write cost and space for faster reads.', 'ইনভ্যারিয়েন্ট ও অ্যাক্সেস প্যাটার্ন ঘিরে ডেটা মডেল করুন; ইনডেক্স দ্রুত রিডের জন্য রাইট খরচ ও জায়গা ব্যবহার করে।',
    'A library catalog speeds lookup but every new book must update the catalog.', 'লাইব্রেরির ক্যাটালগ খোঁজা দ্রুত করে, কিন্তু নতুন বই এলে ক্যাটালগও বদলাতে হয়।',
    'Inspect query plans and build the smallest useful composite indexes.', 'কুয়েরি প্ল্যান দেখুন এবং সবচেয়ে ছোট কার্যকর কম্পোজিট ইনডেক্স বানান।',
    'Denormalization speeds reads but duplicates data and complicates updates.', 'ডিনরমালাইজেশন রিড দ্রুত করে, তবে ডেটা নকল ও আপডেট জটিল করে।',
    'Adding an index for every column without checking real queries.', 'বাস্তব কুয়েরি না দেখে প্রতিটি কলামে ইনডেক্স যোগ করা।'],
  ['replication-sharding', 'components', 'Replication, partitioning & sharding', 'রেপ্লিকেশন, পার্টিশনিং ও শার্ডিং', 'Advanced', 24, 'database',
    'Replication copies data for availability; sharding divides data to expand capacity.', 'রেপ্লিকেশন অ্যাভেইলেবিলিটির জন্য ডেটা কপি করে; শার্ডিং ধারণক্ষমতা বাড়াতে ডেটা ভাগ করে।',
    'Photocopying a book differs from splitting an encyclopedia across shelves.', 'বই ফটোকপি করা আর বিশ্বকোষ বিভিন্ন তাকে ভাগ করা এক বিষয় নয়।',
    'Choose a shard key with even distribution and queries that stay local.', 'সমবণ্টন ও লোকাল কুয়েরি নিশ্চিত করে এমন শার্ড কী বাছুন।',
    'Replication lag enables scale but can return stale reads.', 'রেপ্লিকেশন ল্যাগ স্কেল সম্ভব করে, তবে পুরোনো রিড দিতে পারে।',
    'Sharding early before one well-tuned primary reaches its limits.', 'একটি ভালোভাবে টিউন করা প্রাইমারি সীমায় যাওয়ার আগেই শার্ডিং করা।'],

  ['messaging', 'distributed', 'Queues, Pub/Sub & event streaming', 'কিউ, পাব/সাব ও ইভেন্ট স্ট্রিমিং', 'Intermediate', 21, 'queue',
    'Asynchronous messaging separates producers from consumers and absorbs uneven traffic.', 'অ্যাসিঙ্ক্রোনাস মেসেজিং প্রোডিউসার ও কনজিউমারকে আলাদা করে এবং অসম ট্রাফিক শোষণ করে।',
    'A ticket counter lets arrivals continue while workers process a controlled line.', 'টিকিট কাউন্টার আগমন চালু রাখে, আর কর্মীরা নিয়ন্ত্রিত লাইন প্রক্রিয়া করে।',
    'Define delivery semantics, ordering scope, retries, and dead-letter handling.', 'ডেলিভারি সেমান্টিক্স, অর্ডারিং সীমা, রিট্রাই ও ডেড-লেটার হ্যান্ডলিং নির্ধারণ করুন।',
    'Async work improves resilience but delays results and complicates debugging.', 'অ্যাসিঙ্ক কাজ সহনশীলতা বাড়ায়, তবে ফল দেরি করে ও ডিবাগিং জটিল করে।',
    'Assuming a message will be delivered exactly once end-to-end.', 'একটি মেসেজ পুরো পথে ঠিক একবারই পৌঁছাবে ধরে নেওয়া।'],
  ['cap-consistency', 'distributed', 'CAP theorem & consistency models', 'CAP থিওরেম ও কনসিস্টেন্সি মডেল', 'Advanced', 23, 'database',
    'During a network partition, a distributed system must choose between immediate consistency and availability.', 'নেটওয়ার্ক পার্টিশনের সময় ডিস্ট্রিবিউটেড সিস্টেমকে তাৎক্ষণিক কনসিস্টেন্সি ও অ্যাভেইলেবিলিটির মধ্যে বাছতে হয়।',
    'Two shop branches disconnected by a storm must either pause sales or risk different stock counts.', 'ঝড়ে বিচ্ছিন্ন দুই দোকানকে বিক্রি থামাতে হবে, নইলে স্টকের হিসাব ভিন্ন হতে পারে।',
    'Choose consistency per operation from the business cost of stale or rejected work.', 'পুরোনো বা প্রত্যাখ্যাত কাজের ব্যবসায়িক খরচ থেকে প্রতিটি অপারেশনের কনসিস্টেন্সি বাছুন।',
    'Stronger consistency simplifies reasoning but can increase latency and reject work.', 'শক্ত কনসিস্টেন্সি বোঝা সহজ করে, তবে লেটেন্সি ও প্রত্যাখ্যান বাড়াতে পারে।',
    'Describing CAP as choosing any two properties during normal operation.', 'স্বাভাবিক অবস্থায় CAP-কে যেকোনো দুটি গুণ বাছাই বলা।'],
  ['quorums', 'distributed', 'Quorums & eventual consistency', 'কোরাম ও ইভেনচুয়াল কনসিস্টেন্সি', 'Advanced', 20, 'database',
    'Read and write quorums overlap replicas to tune freshness, availability, and latency.', 'রিড ও রাইট কোরাম রেপ্লিকার ওভারল্যাপ ব্যবহার করে ফ্রেশনেস, অ্যাভেইলেবিলিটি ও লেটেন্সি সামঞ্জস্য করে।',
    'A committee decision needs enough overlapping voters to carry current information.', 'কমিটির সিদ্ধান্তে বর্তমান তথ্য বহন করার জন্য যথেষ্ট ওভারল্যাপ করা ভোটার দরকার।',
    'Select N, R, and W with failure tolerance and repair behavior in mind.', 'ব্যর্থতা সহ্যক্ষমতা ও রিপেয়ার আচরণ মাথায় রেখে N, R ও W বাছুন।',
    'Larger quorums improve confidence but contact more nodes and reduce availability.', 'বড় কোরাম আস্থা বাড়ায়, তবে বেশি নোডে যায় ও অ্যাভেইলেবিলিটি কমায়।',
    'Assuming R + W > N removes every source of stale data.', 'R + W > N হলে পুরোনো ডেটার সব উৎস দূর হয় ধরে নেওয়া।'],
  ['consistent-hashing', 'distributed', 'Consistent hashing', 'কনসিস্টেন্ট হ্যাশিং', 'Advanced', 19, 'sharding',
    'Consistent hashing limits key movement when nodes join or leave a distributed ring.', 'কনসিস্টেন্ট হ্যাশিং ডিস্ট্রিবিউটেড রিংয়ে নোড যোগ বা বাদ হলে কী স্থানান্তর সীমিত করে।',
    'Adding a new librarian should move only nearby shelves, not reorganize the whole library.', 'নতুন লাইব্রেরিয়ান এলে শুধু কাছের তাক বদলাবে, পুরো লাইব্রেরি নয়।',
    'Use virtual nodes and capacity-aware placement for balanced ownership.', 'সুষম মালিকানার জন্য ভার্চুয়াল নোড ও ক্ষমতা-সচেতন প্লেসমেন্ট ব্যবহার করুন।',
    'Minimal movement does not automatically guarantee even load.', 'কম স্থানান্তর স্বয়ংক্রিয়ভাবে সমান লোড নিশ্চিত করে না।',
    'Using one token per physical node and creating hot ranges.', 'প্রতি ফিজিক্যাল নোডে একটি টোকেন দিয়ে হট রেঞ্জ তৈরি করা।'],
  ['leader-election', 'distributed', 'Leader election & coordination', 'লিডার নির্বাচন ও সমন্বয়', 'Advanced', 22, 'queue',
    'Leader election gives one valid coordinator authority while leases and terms prevent stale leaders.', 'লিডার নির্বাচন একজন বৈধ কোঅর্ডিনেটরকে ক্ষমতা দেয়; লিজ ও টার্ম পুরোনো লিডার ঠেকায়।',
    'A team appoints one shift lead, but the badge must expire when the shift ends.', 'একটি দল একজন শিফট লিড দেয়, তবে শিফট শেষে ব্যাজের মেয়াদ শেষ হতে হয়।',
    'Use a proven consensus service and fence work from expired leaders.', 'প্রমাণিত কনসেনসাস সার্ভিস ব্যবহার করুন এবং মেয়াদোত্তীর্ণ লিডারের কাজ আটকান।',
    'Coordination creates clear ownership but adds latency and a critical dependency.', 'সমন্বয় স্পষ্ট মালিকানা দেয়, তবে লেটেন্সি ও গুরুত্বপূর্ণ নির্ভরতা যোগ করে।',
    'Believing a heartbeat timeout proves the old leader has stopped.', 'হার্টবিট টাইমআউট মানেই পুরোনো লিডার থেমেছে ধরে নেওয়া।'],
  ['rate-limit', 'distributed', 'Rate limiting & backpressure', 'রেট লিমিটিং ও ব্যাকপ্রেশার', 'Intermediate', 18, 'loadbalancer',
    'Rate limits protect fairness and capacity; backpressure slows producers when consumers fall behind.', 'রেট লিমিট ন্যায্যতা ও ক্ষমতা রক্ষা করে; কনজিউমার পিছিয়ে পড়লে ব্যাকপ্রেশার প্রোডিউসারকে ধীর করে।',
    'A venue controls entry when people arrive faster than they can be seated.', 'মানুষ বসার চেয়ে দ্রুত এলে একটি ভেন্যু প্রবেশ নিয়ন্ত্রণ করে।',
    'Apply limits by meaningful identity and return clear retry information.', 'অর্থপূর্ণ পরিচয়ের ভিত্তিতে সীমা দিন এবং স্পষ্ট রিট্রাই তথ্য ফেরত দিন।',
    'Strict global limits are accurate but require coordination on every request.', 'কঠোর গ্লোবাল সীমা নির্ভুল, তবে প্রতিটি রিকোয়েস্টে সমন্বয় দরকার।',
    'Returning generic server errors instead of a retryable rate-limit response.', 'রিট্রাইযোগ্য রেট-লিমিট উত্তরের বদলে সাধারণ সার্ভার এরর দেওয়া।'],
  ['idempotency', 'distributed', 'Idempotency, retries & deduplication', 'আইডেমপোটেন্সি, রিট্রাই ও ডিডুপ্লিকেশন', 'Advanced', 20, 'request',
    'An idempotency key makes repeated delivery produce one logical effect.', 'আইডেমপোটেন্সি কী বারবার ডেলিভারিতেও একটি যৌক্তিক ফল নিশ্চিত করে।',
    'Pressing an elevator button repeatedly should still request one elevator.', 'লিফটের বোতাম বারবার চাপলেও একটি লিফটই আসা উচিত।',
    'Persist the operation key and result within a defined deduplication window.', 'নির্ধারিত ডিডুপ্লিকেশন সময়ে অপারেশন কী ও ফল সংরক্ষণ করুন।',
    'Deduplication prevents repeats but consumes storage and needs expiry rules.', 'ডিডুপ্লিকেশন পুনরাবৃত্তি ঠেকায়, তবে স্টোরেজ ও মেয়াদ নিয়ম দরকার।',
    'Retrying non-idempotent payment requests without a stable key.', 'স্থায়ী কী ছাড়া নন-আইডেমপোটেন্ট পেমেন্ট রিকোয়েস্ট রিট্রাই করা।'],
  ['sagas', 'distributed', 'Distributed transactions & Sagas', 'ডিস্ট্রিবিউটেড ট্রানজ্যাকশন ও সাগা', 'Advanced', 25, 'queue',
    'A Saga coordinates local transactions and compensating actions instead of one global lock.', 'সাগা একটি গ্লোবাল লকের বদলে লোকাল ট্রানজ্যাকশন ও ক্ষতিপূরণমূলক কাজ সমন্বয় করে।',
    'A travel booking confirms flight and hotel separately, then cancels earlier steps if later ones fail.', 'ভ্রমণ বুকিং ফ্লাইট ও হোটেল আলাদাভাবে নিশ্চিত করে; পরে ব্যর্থ হলে আগের ধাপ বাতিল করে।',
    'Model every step, durable state transition, retry, and compensation explicitly.', 'প্রতিটি ধাপ, টেকসই স্টেট পরিবর্তন, রিট্রাই ও ক্ষতিপূরণ স্পষ্টভাবে মডেল করুন।',
    'Sagas improve autonomy but expose temporary inconsistency and complex recovery.', 'সাগা স্বাধীনতা বাড়ায়, তবে সাময়িক অসামঞ্জস্য ও জটিল রিকভারি তৈরি করে।',
    'Assuming every real-world action has a perfect inverse operation.', 'প্রতিটি বাস্তব কাজের নিখুঁত বিপরীত অপারেশন আছে ধরে নেওয়া।'],

  ['resilience', 'production', 'Timeouts, circuit breakers & degradation', 'টাইমআউট, সার্কিট ব্রেকার ও ডিগ্রেডেশন', 'Advanced', 22, 'loadbalancer',
    'Bounded waiting, failure isolation, and fallbacks stop one dependency from exhausting the system.', 'সীমিত অপেক্ষা, ব্যর্থতা আলাদা রাখা ও ফলব্যাক একটি নির্ভরতাকে পুরো সিস্টেম নিঃশেষ করতে বাধা দেয়।',
    'An electrical breaker cuts a faulty circuit before the whole building overheats.', 'বৈদ্যুতিক ব্রেকার পুরো ভবন গরম হওয়ার আগে ত্রুটিপূর্ণ সার্কিট বন্ধ করে।',
    'Set deadlines from a latency budget and test degraded behavior deliberately.', 'লেটেন্সি বাজেট থেকে ডেডলাইন ঠিক করুন এবং ডিগ্রেডেড আচরণ সচেতনভাবে পরীক্ষা করুন।',
    'Fast failure protects capacity but may reject work during a brief recovery.', 'দ্রুত ব্যর্থতা ক্ষমতা রক্ষা করে, তবে স্বল্প রিকভারির সময় কাজ প্রত্যাখ্যান করতে পারে।',
    'Stacking independent retries at every service layer.', 'প্রতিটি সার্ভিস স্তরে স্বাধীন রিট্রাই স্তূপ করা।'],
  ['observability', 'production', 'Logs, metrics, traces & alerts', 'লগ, মেট্রিক, ট্রেস ও অ্যালার্ট', 'Intermediate', 20, 'request',
    'Observability connects events, trends, and request paths so operators can explain system behavior.', 'অবজারভেবিলিটি ইভেন্ট, প্রবণতা ও রিকোয়েস্ট পথ যুক্ত করে যাতে অপারেটর সিস্টেমের আচরণ ব্যাখ্যা করতে পারে।',
    'A doctor combines notes, vital signs, and scans instead of trusting one measurement.', 'একজন চিকিৎসক একটি মাপের বদলে নোট, ভাইটাল সাইন ও স্ক্যান একত্র করেন।',
    'Correlate structured logs, service metrics, and traces with shared identifiers.', 'শেয়ার্ড আইডি দিয়ে স্ট্রাকচার্ড লগ, সার্ভিস মেট্রিক ও ট্রেস যুক্ত করুন।',
    'More telemetry improves diagnosis but increases cost and privacy risk.', 'বেশি টেলিমেট্রি নির্ণয় উন্নত করে, তবে খরচ ও গোপনীয়তার ঝুঁকি বাড়ায়।',
    'Alerting on every error instead of user-visible symptoms and SLO burn.', 'ব্যবহারকারী-দৃশ্যমান লক্ষণ ও SLO বার্নের বদলে প্রতিটি এররে অ্যালার্ট করা।'],
  ['security', 'production', 'Authentication, authorization & security', 'অথেন্টিকেশন, অথরাইজেশন ও নিরাপত্তা', 'Intermediate', 24, 'request',
    'Authentication proves identity; authorization limits actions; layered controls reduce blast radius.', 'অথেন্টিকেশন পরিচয় প্রমাণ করে; অথরাইজেশন কাজ সীমিত করে; স্তরভিত্তিক নিয়ন্ত্রণ ক্ষতির পরিধি কমায়।',
    'A building checks your ID at entry and your permission again at a restricted room.', 'একটি ভবন প্রবেশে পরিচয় এবং সীমিত কক্ষে আবার অনুমতি যাচাই করে।',
    'Use least privilege, secure defaults, encryption, validation, and audit trails.', 'লিস্ট প্রিভিলেজ, নিরাপদ ডিফল্ট, এনক্রিপশন, ভ্যালিডেশন ও অডিট ট্রেইল ব্যবহার করুন।',
    'Extra checks add friction and latency but protect valuable boundaries.', 'অতিরিক্ত পরীক্ষা ঘর্ষণ ও লেটেন্সি বাড়ায়, তবে মূল্যবান সীমা রক্ষা করে।',
    'Checking permissions only in the browser interface.', 'শুধু ব্রাউজার ইন্টারফেসে অনুমতি পরীক্ষা করা।'],
  ['microservices', 'production', 'Microservices & event-driven architecture', 'মাইক্রোসার্ভিস ও ইভেন্ট-ড্রিভেন আর্কিটেকচার', 'Advanced', 25, 'queue',
    'Service boundaries should follow business ownership; events decouple reactions from the initiating action.', 'সার্ভিস সীমা ব্যবসায়িক মালিকানা অনুসরণ করা উচিত; ইভেন্ট মূল কাজ থেকে প্রতিক্রিয়াকে আলাদা করে।',
    'A market has independent stalls, shared rules, and announcements for common events.', 'একটি বাজারে স্বাধীন দোকান, শেয়ার্ড নিয়ম ও সাধারণ ঘটনার ঘোষণা থাকে।',
    'Split only around stable domains with independent ownership and operational need.', 'স্বাধীন মালিকানা ও অপারেশনাল প্রয়োজনসহ স্থিতিশীল ডোমেইনের চারপাশেই ভাগ করুন।',
    'Independent deployment improves autonomy but moves complexity into networks and operations.', 'স্বাধীন ডিপ্লয়মেন্ট স্বায়ত্তশাসন বাড়ায়, তবে জটিলতা নেটওয়ার্ক ও অপারেশনে যায়।',
    'Creating one microservice per database table.', 'প্রতি ডেটাবেস টেবিলের জন্য একটি মাইক্রোসার্ভিস তৈরি করা।'],

  ['url-shortener', 'practical', 'Design a URL shortener', 'URL শর্টেনার ডিজাইন', 'Case study', 30, 'url',
    'A URL shortener maps compact unique keys to long URLs and redirects with very low read latency.', 'URL শর্টেনার ছোট ইউনিক কীকে দীর্ঘ URL-এর সঙ্গে ম্যাপ করে এবং খুব কম রিড লেটেন্সিতে রিডাইরেক্ট করে।',
    'It is a numbered coat-check ticket that retrieves a much larger item.', 'এটি নম্বরযুক্ত ক্লোকরুম টিকিটের মতো, যা অনেক বড় জিনিস ফেরত দেয়।',
    'Estimate read-heavy traffic, generate collision-safe keys, cache hot redirects, and partition by key.', 'রিড-হেভি ট্রাফিক হিসাব করুন, সংঘর্ষ-নিরাপদ কী বানান, জনপ্রিয় রিডাইরেক্ট ক্যাশ করুন এবং কী দিয়ে পার্টিশন করুন।',
    'Random keys avoid coordination but need collision checks or enough entropy.', 'র‍্যান্ডম কী সমন্বয় এড়ায়, তবে কলিশন চেক বা যথেষ্ট এনট্রপি দরকার।',
    'Using sequential identifiers that expose volume and are easy to enumerate.', 'ক্রমিক আইডি ব্যবহার করে ভলিউম প্রকাশ ও সহজে অনুমানযোগ্য করে তোলা।'],
  ['chat', 'practical', 'Design chat & notifications', 'চ্যাট ও নোটিফিকেশন ডিজাইন', 'Case study', 32, 'chat',
    'Realtime chat combines persistent connections, ordered conversations, durable messages, presence, and offline delivery.', 'রিয়েলটাইম চ্যাট স্থায়ী কানেকশন, কথোপকথনের ক্রম, টেকসই মেসেজ, প্রেজেন্স ও অফলাইন ডেলিভারি একত্র করে।',
    'A postal service keeps letters durable while a phone line signals who is currently present.', 'ডাকসেবা চিঠি টেকসই রাখে, আর ফোনলাইন কে এখন উপস্থিত তা জানায়।',
    'Partition by conversation, assign server-side sequence numbers, and fan out through durable queues.', 'কনভারসেশন দিয়ে পার্টিশন করুন, সার্ভার-সাইড সিকোয়েন্স দিন এবং টেকসই কিউ দিয়ে ফ্যান-আউট করুন।',
    'Strict global ordering is expensive; per-conversation ordering is usually sufficient.', 'কঠোর গ্লোবাল অর্ডারিং ব্যয়বহুল; সাধারণত প্রতি কনভারসেশন অর্ডারিং যথেষ্ট।',
    'Treating online presence as permanently accurate state.', 'অনলাইন প্রেজেন্সকে স্থায়ীভাবে নির্ভুল স্টেট ধরে নেওয়া।'],
  ['news-feed', 'practical', 'Design a social news feed', 'সোশ্যাল নিউজ ফিড ডিজাইন', 'Case study', 32, 'feed',
    'A feed gathers candidate posts, ranks them, and serves a stable page under highly uneven fan-out.', 'ফিড সম্ভাব্য পোস্ট সংগ্রহ, র‍্যাঙ্ক এবং অসম ফ্যান-আউটের মধ্যেও স্থিতিশীল পেজ দেয়।',
    'A personalized newspaper selects and orders stories for each reader.', 'ব্যক্তিগত সংবাদপত্র প্রতিটি পাঠকের জন্য খবর বেছে ও সাজায়।',
    'Use hybrid fan-out: precompute ordinary users and fetch celebrity posts at read time.', 'হাইব্রিড ফ্যান-আউট ব্যবহার করুন—সাধারণ ব্যবহারকারীর জন্য আগে তৈরি, সেলিব্রিটির পোস্ট রিডের সময় নিন।',
    'Fan-out-on-write makes reads fast but makes celebrity writes extremely expensive.', 'ফ্যান-আউট-অন-রাইট রিড দ্রুত করে, তবে সেলিব্রিটি রাইট অত্যন্ত ব্যয়বহুল করে।',
    'Paginating a changing ranked feed with simple numeric offsets.', 'পরিবর্তনশীল র‍্যাঙ্কড ফিডকে সাধারণ সংখ্যার অফসেট দিয়ে পেজিনেট করা।'],
  ['media-search', 'practical', 'Design storage, video & search', 'স্টোরেজ, ভিডিও ও সার্চ ডিজাইন', 'Case study', 35, 'video',
    'Large media systems separate metadata from blobs, process asynchronously, deliver through a CDN, and index searchable text.', 'বড় মিডিয়া সিস্টেম মেটাডেটা ও ব্লব আলাদা করে, অ্যাসিঙ্কভাবে প্রসেস করে, CDN দিয়ে ডেলিভার করে এবং সার্চযোগ্য টেক্সট ইনডেক্স করে।',
    'A warehouse stores boxes, a workshop transforms them, and a catalog helps people find them.', 'গুদাম বাক্স রাখে, ওয়ার্কশপ রূপান্তর করে এবং ক্যাটালগ মানুষকে খুঁজতে সাহায্য করে।',
    'Upload directly to object storage, queue processing, generate renditions, and update the search index asynchronously.', 'সরাসরি অবজেক্ট স্টোরেজে আপলোড, প্রসেসিং কিউ, রেন্ডিশন তৈরি এবং অ্যাসিঙ্কভাবে সার্চ ইনডেক্স আপডেট করুন।',
    'Async processing scales heavy work but exposes temporary processing and indexing states.', 'অ্যাসিঙ্ক প্রসেসিং ভারী কাজ স্কেল করে, তবে সাময়িক প্রসেসিং ও ইনডেক্সিং স্টেট দেখায়।',
    'Sending large uploads through application servers and keeping users waiting for transcoding.', 'বড় আপলোড অ্যাপ সার্ভারের মধ্য দিয়ে পাঠানো এবং ট্রান্সকোডিংয়ের জন্য ব্যবহারকারীকে অপেক্ষা করানো।'],
  ['locks-clocks', 'mastery', 'Distributed locks, leases & clocks', 'ডিস্ট্রিবিউটেড লক, লিজ ও ক্লক', 'Advanced', 24, 'queue',
    'Locks coordinate exclusive work, leases bound ownership in time, and logical clocks order events without trusting wall time.', 'লক একক কাজ সমন্বয় করে, লিজ সময়সীমায় মালিকানা বাঁধে এবং লজিক্যাল ক্লক দেয়ালঘড়ি বিশ্বাস না করে ইভেন্ট সাজায়।',
    'A meeting-room key must expire and carry a newer stamp before its holder can act.', 'মিটিং রুমের চাবির মেয়াদ থাকতে হবে এবং কাজের আগে নতুন স্ট্যাম্প বহন করতে হবে।',
    'Prefer idempotency or partitioned ownership; when locking is unavoidable, use leases plus fencing tokens.', 'সম্ভব হলে আইডেমপোটেন্সি বা পার্টিশনড মালিকানা নিন; লক দরকার হলে লিজ ও ফেন্সিং টোকেন ব্যবহার করুন।',
    'Coordination protects exclusivity but adds latency, availability risk, and stale-owner hazards.', 'সমন্বয় একক মালিকানা রক্ষা করে, তবে লেটেন্সি, অ্যাভেইলেবিলিটি ঝুঁকি ও পুরোনো মালিকের বিপদ বাড়ায়।',
    'Assuming a client that lost its lease immediately stopped executing.', 'লিজ হারানো ক্লায়েন্ট তাৎক্ষণিকভাবে কাজ বন্ধ করেছে ধরে নেওয়া।'],
  ['probabilistic', 'mastery', 'Bloom filters & probabilistic structures', 'ব্লুম ফিল্টার ও প্রোবাবিলিস্টিক স্ট্রাকচার', 'Advanced', 20, 'cache',
    'Probabilistic structures answer membership or frequency questions with tiny memory and a controlled error rate.', 'প্রোবাবিলিস্টিক স্ট্রাকচার অল্প মেমরিতে নিয়ন্ত্রিত ভুলের হারে সদস্যতা বা ফ্রিকোয়েন্সির উত্তর দেয়।',
    'A quick guest-list screen can say “definitely absent” or “possibly present” before a full lookup.', 'দ্রুত অতিথি তালিকা পূর্ণ খোঁজের আগে “নিশ্চিত অনুপস্থিত” বা “সম্ভবত উপস্থিত” বলতে পারে।',
    'Place a Bloom filter before expensive negative lookups and size it from item count and acceptable false positives.', 'ব্যয়বহুল নেগেটিভ লুকআপের আগে ব্লুম ফিল্টার রাখুন এবং আইটেম সংখ্যা ও গ্রহণযোগ্য ফলস পজিটিভ থেকে আকার ঠিক করুন।',
    'Memory savings come with false positives and limited deletion semantics.', 'মেমরি সাশ্রয়ের বিনিময়ে ফলস পজিটিভ ও সীমিত ডিলিশন সেমান্টিক্স আসে।',
    'Treating “possibly present” as proof that the record exists.', '“সম্ভবত উপস্থিত”-কে রেকর্ড থাকার প্রমাণ ধরা।'],
  ['search-system', 'mastery', 'Design search & autocomplete', 'সার্চ ও অটোকমপ্লিট ডিজাইন', 'Case study', 30, 'request',
    'Search separates source-of-truth writes from inverted indexes, ranking, suggestions, and freshness pipelines.', 'সার্চ সোর্স-অফ-ট্রুথ রাইটকে ইনভার্টেড ইনডেক্স, র‍্যাঙ্কিং, সাজেশন ও ফ্রেশনেস পাইপলাইন থেকে আলাদা করে।',
    'A library catalog transforms book contents into terms, shelves, and popularity signals.', 'লাইব্রেরি ক্যাটালগ বইয়ের বিষয়কে শব্দ, তাক ও জনপ্রিয়তার সংকেতে রূপ দেয়।',
    'Index changes asynchronously, shard by document or term, and serve prefixes from tries or precomputed top queries.', 'পরিবর্তন অ্যাসিঙ্কভাবে ইনডেক্স করুন, ডকুমেন্ট বা টার্ম দিয়ে শার্ড করুন এবং trie বা প্রিকম্পিউটেড কুয়েরি থেকে প্রিফিক্স দিন।',
    'Fresh indexing improves relevance but consumes compute and can destabilize serving.', 'দ্রুত ইনডেক্সিং প্রাসঙ্গিকতা বাড়ায়, তবে কম্পিউট খরচ ও সার্ভিং অস্থিতিশীল করতে পারে।',
    'Running wildcard database scans for every autocomplete keystroke.', 'প্রতিটি অটোকমপ্লিট কীস্ট্রোকে ডেটাবেস ওয়াইল্ডকার্ড স্ক্যান করা।'],
  ['object-storage', 'mastery', 'Design cloud file storage & sync', 'ক্লাউড ফাইল স্টোরেজ ও সিঙ্ক ডিজাইন', 'Case study', 32, 'video',
    'File sync separates immutable chunks from metadata, versions, permissions, and a change-notification stream.', 'ফাইল সিঙ্ক অপরিবর্তনীয় চাঙ্ককে মেটাডেটা, ভার্সন, অনুমতি ও পরিবর্তন নোটিফিকেশন স্ট্রিম থেকে আলাদা করে।',
    'A moving company labels boxes, keeps an inventory, and only resends boxes that changed.', 'মুভিং কোম্পানি বাক্সে লেবেল দেয়, তালিকা রাখে এবং শুধু বদলানো বাক্স আবার পাঠায়।',
    'Upload chunks directly, hash for deduplication, commit metadata atomically, and resolve concurrent versions explicitly.', 'চাঙ্ক সরাসরি আপলোড, হ্যাশ দিয়ে ডিডুপ্লিকেট, মেটাডেটা অ্যাটমিক কমিট এবং কনকারেন্ট ভার্সন স্পষ্টভাবে সমাধান করুন।',
    'Chunking saves bandwidth but increases metadata, assembly, and garbage-collection work.', 'চাঙ্কিং ব্যান্ডউইডথ বাঁচায়, তবে মেটাডেটা, অ্যাসেম্বলি ও গারবেজ কালেকশন বাড়ায়।',
    'Overwriting concurrent edits silently without version vectors or conflict copies.', 'ভার্সন ভেক্টর বা কনফ্লিক্ট কপি ছাড়া কনকারেন্ট এডিট নীরবে ওভাররাইট করা।'],
  ['video-streaming', 'mastery', 'Design a video streaming platform', 'ভিডিও স্ট্রিমিং প্ল্যাটফর্ম ডিজাইন', 'Case study', 34, 'video',
    'Video platforms ingest once, transcode many renditions asynchronously, and deliver adaptive segments through a CDN.', 'ভিডিও প্ল্যাটফর্ম একবার ইনজেস্ট করে, অ্যাসিঙ্কভাবে অনেক রেন্ডিশন বানায় এবং CDN দিয়ে অ্যাডাপটিভ সেগমেন্ট দেয়।',
    'A kitchen prepares several portion sizes while neighborhood counters serve the closest match.', 'একটি রান্নাঘর নানা আকারের পরিবেশন বানায়, আর এলাকার কাউন্টার উপযুক্তটি দেয়।',
    'Use direct multipart upload, durable processing workflows, segmented manifests, and adaptive bitrate playback.', 'ডাইরেক্ট মাল্টিপার্ট আপলোড, টেকসই প্রসেসিং ওয়ার্কফ্লো, সেগমেন্টেড ম্যানিফেস্ট ও অ্যাডাপটিভ বিটরেট ব্যবহার করুন।',
    'More renditions improve playback but multiply compute and storage cost.', 'বেশি রেন্ডিশন প্লেব্যাক উন্নত করে, তবে কম্পিউট ও স্টোরেজ খরচ বাড়ায়।',
    'Keeping the upload request open until every video rendition finishes.', 'সব ভিডিও রেন্ডিশন শেষ না হওয়া পর্যন্ত আপলোড রিকোয়েস্ট খোলা রাখা।'],
  ['notification-platform', 'mastery', 'Design a notification platform', 'নোটিফিকেশন প্ল্যাটফর্ম ডিজাইন', 'Case study', 28, 'queue',
    'A notification platform applies preferences, templates, scheduling, provider routing, retries, and deduplication across channels.', 'নোটিফিকেশন প্ল্যাটফর্ম বিভিন্ন চ্যানেলে পছন্দ, টেমপ্লেট, সময়, প্রোভাইডার রাউটিং, রিট্রাই ও ডিডুপ্লিকেশন প্রয়োগ করে।',
    'A dispatch desk chooses the right message, time, courier, and backup courier for each recipient.', 'ডিসপ্যাচ ডেস্ক প্রতিটি গ্রাহকের জন্য সঠিক বার্তা, সময়, কুরিয়ার ও বিকল্প কুরিয়ার বেছে নেয়।',
    'Queue by channel, enforce user preferences and quiet hours, track provider receipts, and cap retries.', 'চ্যানেল দিয়ে কিউ করুন, ব্যবহারকারীর পছন্দ ও নীরব সময় মানুন, প্রোভাইডার রিসিট ট্র্যাক ও রিট্রাই সীমিত করুন।',
    'Retries increase delivery but can create duplicates and provider storms.', 'রিট্রাই ডেলিভারি বাড়ায়, তবে ডুপ্লিকেট ও প্রোভাইডার স্টর্ম তৈরি করতে পারে।',
    'Sending synchronously from the product request without preference checks.', 'পছন্দ পরীক্ষা ছাড়া প্রোডাক্ট রিকোয়েস্ট থেকে সিঙ্ক্রোনাসভাবে পাঠানো।'],
  ['geo-ride', 'mastery', 'Design ride sharing & geospatial search', 'রাইড শেয়ারিং ও জিওস্পেশাল সার্চ ডিজাইন', 'Case study', 35, 'sharding',
    'Ride matching combines rapidly changing locations, spatial indexing, candidate search, pricing, and trip state machines.', 'রাইড ম্যাচিং দ্রুত বদলানো লোকেশন, স্পেশাল ইনডেক্স, ক্যান্ডিডেট সার্চ, মূল্য ও ট্রিপ স্টেট মেশিন একত্র করে।',
    'A dispatcher continually groups nearby drivers into map cells before offering a trip.', 'ডিসপ্যাচার ট্রিপ দেওয়ার আগে কাছের ড্রাইভারদের ম্যাপ সেলে নিয়মিত ভাগ করে।',
    'Index active drivers with geohashes, expand nearby cells gradually, and serialize each accepted trip transition.', 'সক্রিয় ড্রাইভারকে জিওহ্যাশে ইনডেক্স, ধীরে কাছের সেল বাড়ান এবং গৃহীত ট্রিপের প্রতিটি পরিবর্তন সিরিয়ালাইজ করুন।',
    'Smaller geo cells improve precision but increase boundary searches and index churn.', 'ছোট জিও সেল নির্ভুলতা বাড়ায়, তবে সীমানা সার্চ ও ইনডেক্স পরিবর্তন বাড়ায়।',
    'Persisting every GPS update through the transactional trip database.', 'প্রতিটি GPS আপডেট ট্রানজ্যাকশনাল ট্রিপ ডেটাবেসে সংরক্ষণ করা।'],
  ['payments-orders', 'mastery', 'Design payments & order workflows', 'পেমেন্ট ও অর্ডার ওয়ার্কফ্লো ডিজাইন', 'Case study', 36, 'queue',
    'Payment systems use immutable ledgers, idempotent commands, reconciliation, and explicit order state transitions.', 'পেমেন্ট সিস্টেম অপরিবর্তনীয় লেজার, আইডেমপোটেন্ট কমান্ড, রিকনসিলিয়েশন ও স্পষ্ট অর্ডার স্টেট ব্যবহার করে।',
    'A bank keeps an append-only journal and balances it against external receipts.', 'ব্যাংক অ্যাপেন্ড-অনলি জার্নাল রাখে এবং বাহ্যিক রিসিটের সঙ্গে মিলায়।',
    'Separate authorization from capture, record every monetary movement, and reconcile provider events.', 'অথরাইজেশন ও ক্যাপচার আলাদা করুন, প্রতিটি অর্থ চলাচল লিখুন এবং প্রোভাইডার ইভেন্ট মিলিয়ে নিন।',
    'Strong correctness reduces ambiguity but requires slower, carefully audited workflows.', 'শক্ত কারেক্টনেস অস্পষ্টতা কমায়, তবে ধীর ও সতর্কভাবে অডিট করা ওয়ার্কফ্লো চায়।',
    'Updating a mutable balance without an immutable transaction history.', 'অপরিবর্তনীয় ট্রানজ্যাকশন ইতিহাস ছাড়া পরিবর্তনযোগ্য ব্যালেন্স আপডেট করা।'],
  ['multi-region', 'mastery', 'Multi-region architecture & disaster recovery', 'মাল্টি-রিজিয়ন আর্কিটেকচার ও ডিজাস্টার রিকভারি', 'Advanced', 30, 'database',
    'Multi-region design balances user latency, failure independence, data residency, consistency, RPO, and RTO.', 'মাল্টি-রিজিয়ন ডিজাইন ব্যবহারকারীর লেটেন্সি, স্বাধীন ব্যর্থতা, ডেটা রেসিডেন্সি, কনসিস্টেন্সি, RPO ও RTO সামঞ্জস্য করে।',
    'Independent emergency shelters need current supplies, practiced routes, and rules for who leads.', 'স্বাধীন জরুরি আশ্রয়ে বর্তমান সরবরাহ, অনুশীলিত পথ ও কে নেতৃত্ব দেবে তার নিয়ম দরকার।',
    'Choose active-passive or active-active per workload, replicate intentionally, and rehearse regional evacuation.', 'ওয়ার্কলোড অনুযায়ী active-passive বা active-active বাছুন, সচেতনভাবে রেপ্লিকেট এবং আঞ্চলিক সরিয়ে নেওয়া অনুশীলন করুন।',
    'Lower RPO and RTO improve recovery but sharply increase cost and coordination.', 'কম RPO ও RTO রিকভারি উন্নত করে, তবে খরচ ও সমন্বয় দ্রুত বাড়ায়।',
    'Claiming disaster recovery without regularly restoring data and shifting traffic.', 'নিয়মিত ডেটা রিস্টোর ও ট্রাফিক সরানো ছাড়াই ডিজাস্টার রিকভারি দাবি করা।'],
  ['cost-capacity', 'mastery', 'Capacity planning, cost & sustainability', 'ক্যাপাসিটি প্ল্যানিং, খরচ ও সাসটেইনেবিলিটি', 'Advanced', 24, 'loadbalancer',
    'Production architecture must connect demand forecasts, headroom, unit economics, scaling signals, and resource efficiency.', 'প্রোডাকশন আর্কিটেকচারে চাহিদার পূর্বাভাস, হেডরুম, ইউনিট ইকোনমিক্স, স্কেলিং সিগন্যাল ও সম্পদ দক্ষতা যুক্ত করতে হয়।',
    'A hotel plans rooms for normal nights, festivals, maintenance, and the cost of empty beds.', 'হোটেল সাধারণ রাত, উৎসব, রক্ষণাবেক্ষণ ও খালি বিছানার খরচ ধরে রুম পরিকল্পনা করে।',
    'Measure cost per useful request, keep tested headroom, right-size continuously, and separate baseline from burst capacity.', 'প্রতি কার্যকর রিকোয়েস্টের খরচ মাপুন, পরীক্ষিত হেডরুম রাখুন, নিয়মিত রাইট-সাইজ এবং বেসলাইন ও বার্স্ট ক্ষমতা আলাদা করুন।',
    'Large safety margins reduce incidents but waste money and energy.', 'বড় সেফটি মার্জিন ঘটনা কমায়, তবে অর্থ ও শক্তি অপচয় করে।',
    'Autoscaling on CPU alone without queue depth, latency, or startup time.', 'কিউ ডেপথ, লেটেন্সি বা স্টার্টআপ সময় ছাড়া শুধু CPU দিয়ে অটোস্কেল করা।'],
]

const distractors = [
  l('Choose the newest tool before measuring the problem.', 'সমস্যা মাপার আগে সবচেয়ে নতুন টুল বেছে নিন।'),
  l('Put every responsibility in one server and remove monitoring.', 'সব দায়িত্ব একটি সার্ভারে রাখুন এবং মনিটরিং বাদ দিন।'),
  l('Assume failures and traffic spikes will not happen.', 'ধরে নিন ব্যর্থতা ও ট্রাফিক স্পাইক হবে না।'),
]

function makeExam(topic) {
  const correct = {
    purpose: l(topic.insight.en, topic.insight.bn),
    action: l(topic.action.en, topic.action.bn),
    tradeoff: l(topic.tradeoff.en, topic.tradeoff.bn),
    mistake: l(topic.mistake.en, topic.mistake.bn),
  }
  const optionSet = (answer, offset = 0) => {
    const answerIndex = offset % 4
    const values = [...distractors]
    values.splice(answerIndex, 0, answer)
    return {
      options: values.map((text, index) => ({ id: String.fromCharCode(97 + index), text })),
      correct: [String.fromCharCode(97 + answerIndex)],
    }
  }
  const purpose = optionSet(correct.purpose, topic.order)
  const action = optionSet(correct.action, topic.order + 1)
  const mistake = optionSet(correct.mistake, topic.order + 2)
  const interview = optionSet(l(`The goal, the chosen approach, and this trade-off: ${topic.tradeoff.en}`, `লক্ষ্য, নির্বাচিত পদ্ধতি এবং এই ট্রেড-অফ: ${topic.tradeoff.bn}`), topic.order + 3)

  return [
    { id: 'q1', type: 'single', concept: topic.title, prompt: l(`What is the central idea of ${topic.title.en}?`, `${topic.title.bn}-এর মূল ধারণা কী?`), ...purpose, explanation: correct.purpose },
    { id: 'q2', type: 'single', concept: topic.title, prompt: l('Which approach is the strongest starting decision?', 'কোন পদ্ধতিটি সবচেয়ে শক্তিশালী শুরুর সিদ্ধান্ত?'), ...action, explanation: correct.action },
    { id: 'q3', type: 'multi', concept: topic.title, prompt: l('Select both statements that show sound system-design reasoning.', 'সঠিক সিস্টেম ডিজাইন চিন্তা দেখায়—এমন দুটি বক্তব্য বাছুন।'), options: [
      { id: 'a', text: correct.purpose }, { id: 'b', text: distractors[0] }, { id: 'c', text: correct.tradeoff }, { id: 'd', text: distractors[2] },
    ], correct: ['a', 'c'], explanation: l(`A sound answer states both the mechanism and its trade-off: ${topic.tradeoff.en}`, `সঠিক উত্তরে প্রক্রিয়া ও ট্রেড-অফ দুটিই থাকে: ${topic.tradeoff.bn}`) },
    { id: 'q4', type: 'single', concept: topic.title, prompt: l('Which choice is a common design mistake?', 'কোনটি সাধারণ ডিজাইন ভুল?'), ...mistake, explanation: l(`Avoid this mistake: ${topic.mistake.en}`, `এই ভুল এড়িয়ে চলুন: ${topic.mistake.bn}`) },
    { id: 'q5', type: 'single', concept: topic.title, prompt: l('What should a strong interview answer include?', 'একটি ভালো ইন্টারভিউ উত্তরে কী থাকা উচিত?'), ...interview, explanation: l('Interviewers value explicit assumptions, decisions, and trade-offs more than a memorized diagram.', 'ইন্টারভিউয়ার মুখস্থ ডায়াগ্রামের চেয়ে স্পষ্ট অনুমান, সিদ্ধান্ত ও ট্রেড-অফকে বেশি মূল্য দেন।') },
  ]
}

export const topics = rawTopics.map((row, index) => {
  const [id, moduleId, en, bn, difficulty, minutes, diagram, insightEn, insightBn, analogyEn, analogyBn, actionEn, actionBn, tradeoffEn, tradeoffBn, mistakeEn, mistakeBn] = row
  const topic = {
    id, order: index + 1, moduleId, title: l(en, bn), difficulty, minutes, diagram, deepDive: allFlagshipContent[id] || null,
    insight: l(insightEn, insightBn), analogy: l(analogyEn, analogyBn), action: l(actionEn, actionBn), tradeoff: l(tradeoffEn, tradeoffBn), mistake: l(mistakeEn, mistakeBn),
    objectives: [
      l(`Explain ${en} in plain language.`, `সহজ ভাষায় ${bn} ব্যাখ্যা করতে পারবেন।`),
      l('Recognize when this pattern is useful.', 'কখন এই প্যাটার্ন কার্যকর তা বুঝতে পারবেন।'),
      l('Discuss its most important trade-off.', 'এর সবচেয়ে গুরুত্বপূর্ণ ট্রেড-অফ আলোচনা করতে পারবেন।'),
    ],
    advantages: l(`It creates a clear way to reason about ${en.toLowerCase()} and its role in a larger architecture.`, `এটি ${bn} এবং বড় আর্কিটেকচারে এর ভূমিকা বোঝার স্পষ্ট উপায় দেয়।`),
    interview: l(`State assumptions first, draw the simplest ${en.toLowerCase()} flow, then explain what changes at 10× scale.`, `আগে অনুমান বলুন, ${bn}-এর সবচেয়ে সহজ ফ্লো আঁকুন, তারপর ১০ গুণ স্কেলে কী বদলাবে ব্যাখ্যা করুন।`),
    glossary: [
      { term: l('Constraint', 'সীমাবদ্ধতা'), definition: l('A limit the design must respect.', 'ডিজাইনকে যে সীমা মানতে হয়।') },
      { term: l('Trade-off', 'ট্রেড-অফ'), definition: l('Improving one quality by accepting a cost elsewhere.', 'অন্যদিকে খরচ মেনে একটি গুণ উন্নত করা।') },
    ],
  }
  topic.exam = (flagshipExams[id] || makeExam(topic)).map((question) => ({ ...question, concept: topic.title }))
  return topic
})

export const labs = [
  {
    id: 'url-lab', icon: '↗', title: l('URL Shortener Lab', 'URL শর্টেনার ল্যাব'), subtitle: l('Design a read-heavy redirect service.', 'রিড-হেভি রিডাইরেক্ট সার্ভিস ডিজাইন করুন।'),
    stages: [
      ['Requirements', 'রিকোয়ারমেন্ট', 'Which capability belongs in the MVP?', 'MVP-তে কোন সক্ষমতা থাকা উচিত?', ['Create and redirect short links', 'Add a social news feed'], ['শর্ট লিংক তৈরি ও রিডাইরেক্ট', 'সোশ্যাল নিউজ ফিড যোগ করা'], 0, 'Keep the core contract tiny: create a mapping and resolve it quickly.', 'মূল কনট্র্যাক্ট ছোট রাখুন: ম্যাপিং তৈরি ও দ্রুত সমাধান।'],
      ['Scale', 'স্কেল', 'What traffic shape should drive the design?', 'কোন ট্রাফিক ধরন ডিজাইনকে চালাবে?', ['Many more redirects than creates', 'Exactly equal reads and writes'], ['তৈরির চেয়ে অনেক বেশি রিডাইরেক্ট', 'রিড ও রাইট ঠিক সমান'], 0, 'A shortener is usually read-heavy, making caching valuable.', 'শর্টেনার সাধারণত রিড-হেভি, তাই ক্যাশিং মূল্যবান।'],
      ['Keys', 'কী', 'How should keys be generated?', 'কী কীভাবে তৈরি হবে?', ['Random/Base62 keys with enough entropy', 'Expose sequential database IDs'], ['যথেষ্ট এনট্রপিসহ র‍্যান্ডম/Base62 কী', 'ক্রমিক ডেটাবেস ID প্রকাশ'], 0, 'Opaque keys resist enumeration and distribute well.', 'অস্বচ্ছ কী অনুমান ঠেকায় ও ভালোভাবে বণ্টিত হয়।'],
      ['Architecture', 'আর্কিটেকচার', 'Where should hot redirects be served?', 'জনপ্রিয় রিডাইরেক্ট কোথা থেকে দেওয়া উচিত?', ['A distributed cache before storage', 'Always from the primary database'], ['স্টোরেজের আগে ডিস্ট্রিবিউটেড ক্যাশ', 'সবসময় প্রাইমারি ডেটাবেস'], 0, 'Cache-aside removes repeated reads from durable storage.', 'ক্যাশ-অ্যাসাইড টেকসই স্টোরেজ থেকে পুনরাবৃত্ত রিড কমায়।'],
      ['Capacity', 'ধারণক্ষমতা', 'What should storage estimates include?', 'স্টোরেজের হিসাবে কী থাকা উচিত?', ['Mappings, metadata, replication, and growth headroom', 'Only today’s short keys'], ['ম্যাপিং, মেটাডেটা, রেপ্লিকেশন ও বৃদ্ধির জায়গা', 'শুধু আজকের শর্ট কী'], 0, 'A useful estimate accounts for retained bytes and safety margin, not only key length.', 'কার্যকর হিসাবে শুধু কী নয়, সংরক্ষিত বাইট ও নিরাপত্তা মার্জিনও থাকে।'],
      ['API safety', 'API নিরাপত্তা', 'How should a retried create request behave?', 'পুনরায় পাঠানো create রিকোয়েস্ট কীভাবে আচরণ করবে?', ['Reuse an idempotency key and return the original mapping', 'Create a new link on every retry'], ['আইডেমপোটেন্সি কী দিয়ে আগের ম্যাপিং ফেরত', 'প্রতি রিট্রাইয়ে নতুন লিংক'], 0, 'Idempotency prevents client timeouts from producing duplicate links.', 'আইডেমপোটেন্সি ক্লায়েন্ট টাইমআউটে ডুপ্লিকেট লিংক তৈরি ঠেকায়।'],
      ['Abuse', 'অপব্যবহার', 'What belongs on the redirect safety path?', 'রিডাইরেক্ট নিরাপত্তা পথে কী থাকা উচিত?', ['Rate limits and asynchronous malicious-URL scanning', 'Trust every submitted destination forever'], ['রেট লিমিট ও অ্যাসিঙ্ক ক্ষতিকর URL স্ক্যান', 'সব গন্তব্যকে চিরকাল বিশ্বাস'], 0, 'Fast checks plus background classification limit abuse without making every redirect slow.', 'দ্রুত চেক ও ব্যাকগ্রাউন্ড শ্রেণিবিন্যাস রিডাইরেক্ট ধীর না করে অপব্যবহার কমায়।'],
      ['Failure', 'ব্যর্থতা', 'What should happen during an analytics outage?', 'অ্যানালিটিক্স আউটেজে কী হওয়া উচিত?', ['Keep redirects available and buffer or sample click events', 'Fail every redirect'], ['রিডাইরেক্ট চালু রেখে ক্লিক ইভেন্ট বাফার বা স্যাম্পল', 'সব রিডাইরেক্ট ব্যর্থ'], 0, 'Click analytics is valuable, but redirect availability is the primary contract.', 'ক্লিক অ্যানালিটিক্স মূল্যবান, তবে রিডাইরেক্ট সচল থাকাই মূল কনট্র্যাক্ট।'],
    ],
  },
  {
    id: 'chat-lab', icon: '⌁', title: l('Realtime Chat Lab', 'রিয়েলটাইম চ্যাট ল্যাব'), subtitle: l('Balance live delivery with durable history.', 'লাইভ ডেলিভারি ও টেকসই ইতিহাস সামঞ্জস্য করুন।'),
    stages: [
      ['Connection', 'কানেকশন', 'How should active clients receive messages?', 'সক্রিয় ক্লায়েন্ট কীভাবে মেসেজ পাবে?', ['Persistent WebSocket connections', 'Refresh the page manually'], ['স্থায়ী WebSocket কানেকশন', 'ম্যানুয়ালি পেজ রিফ্রেশ'], 0, 'A persistent channel enables low-latency bidirectional delivery.', 'স্থায়ী চ্যানেল কম-লেটেন্সির দ্বিমুখী ডেলিভারি দেয়।'],
      ['Ordering', 'অর্ডারিং', 'What ordering scope is practical?', 'কোন অর্ডারিং সীমা ব্যবহারিক?', ['Per conversation', 'Global across every user'], ['প্রতি কনভারসেশন', 'সব ব্যবহারকারীর জন্য গ্লোবাল'], 0, 'Conversation ordering matches user expectations without global coordination.', 'কনভারসেশন অর্ডারিং গ্লোবাল সমন্বয় ছাড়াই প্রত্যাশা পূরণ করে।'],
      ['Durability', 'স্থায়িত্ব', 'When is a message acknowledged?', 'মেসেজ কখন স্বীকৃত হবে?', ['After durable storage accepts it', 'Before the server receives it'], ['টেকসই স্টোরেজ গ্রহণের পরে', 'সার্ভার পাওয়ার আগে'], 0, 'Durable acceptance prevents acknowledged messages from disappearing.', 'টেকসই গ্রহণ স্বীকৃত মেসেজ হারানো ঠেকায়।'],
      ['Offline', 'অফলাইন', 'How should offline users be handled?', 'অফলাইন ব্যবহারকারী কীভাবে সামলাবেন?', ['Queue notifications and sync history later', 'Discard every message'], ['নোটিফিকেশন কিউ ও পরে ইতিহাস সিঙ্ক', 'সব মেসেজ বাদ'], 0, 'Durable history separates message truth from current presence.', 'টেকসই ইতিহাস বর্তমান উপস্থিতি থেকে মেসেজের সত্য আলাদা করে।'],
      ['Gateway scale', 'গেটওয়ে স্কেল', 'What metric sizes the realtime gateway tier?', 'রিয়েলটাইম গেটওয়ে টিয়ার কোন মেট্রিকে সাইজ হবে?', ['Concurrent connections plus messages per second', 'Daily sign-ups alone'], ['একযোগে কানেকশন ও প্রতি সেকেন্ডে মেসেজ', 'শুধু দৈনিক সাইন-আপ'], 0, 'Connection count governs memory while message rate governs processing and bandwidth.', 'কানেকশন সংখ্যা মেমোরি এবং মেসেজ হার প্রসেসিং ও ব্যান্ডউইডথ নির্ধারণ করে।'],
      ['Partitioning', 'পার্টিশনিং', 'How should conversation events be partitioned?', 'কনভারসেশন ইভেন্ট কীভাবে পার্টিশন হবে?', ['By conversation ID to preserve local order', 'Randomly for each message'], ['লোকাল অর্ডারের জন্য conversation ID দিয়ে', 'প্রতি মেসেজে র‍্যান্ডম'], 0, 'A stable conversation key keeps related events ordered on one partition.', 'স্থায়ী conversation key সম্পর্কিত ইভেন্টকে এক পার্টিশনে ক্রমে রাখে।'],
      ['Reconnect', 'পুনঃসংযোগ', 'How should a client recover after disconnecting?', 'সংযোগ বিচ্ছিন্ন হলে ক্লায়েন্ট কীভাবে ফিরবে?', ['Send its last acknowledged sequence and fetch the gap', 'Assume nothing was missed'], ['শেষ স্বীকৃত sequence পাঠিয়ে ফাঁক সংগ্রহ', 'কিছুই মিস হয়নি ধরে নেওয়া'], 0, 'A resumable cursor makes reconnect deterministic and limits duplicate delivery.', 'রিজিউমযোগ্য কার্সর পুনঃসংযোগ নির্ভরযোগ্য করে ও ডুপ্লিকেট কমায়।'],
      ['Overload', 'অতিরিক্ত চাপ', 'What should happen when a slow client cannot consume messages?', 'ধীর ক্লায়েন্ট মেসেজ নিতে না পারলে কী হবে?', ['Bound its buffer, signal backpressure, then reconnect if needed', 'Grow memory without limit'], ['বাফার সীমিত, ব্যাকপ্রেশার, প্রয়োজনে পুনঃসংযোগ', 'সীমাহীন মেমোরি বাড়ানো'], 0, 'Bounded buffers prevent one slow socket from exhausting a gateway.', 'সীমিত বাফার একটি ধীর সকেটকে গেটওয়ের মেমোরি শেষ করতে দেয় না।'],
    ],
  },
  {
    id: 'feed-lab', icon: '≋', title: l('News Feed Lab', 'নিউজ ফিড ল্যাব'), subtitle: l('Choose a fan-out strategy for uneven audiences.', 'অসম অডিয়েন্সের জন্য ফ্যান-আউট কৌশল বাছুন।'),
    stages: [
      ['Candidates', 'ক্যান্ডিডেট', 'Where do candidate posts come from?', 'সম্ভাব্য পোস্ট কোথা থেকে আসে?', ['Followed accounts plus ranking signals', 'One random global table scan'], ['ফলো করা অ্যাকাউন্ট ও র‍্যাঙ্কিং সিগন্যাল', 'একটি র‍্যান্ডম গ্লোবাল টেবিল স্ক্যান'], 0, 'Bounded candidate sources make ranking affordable.', 'সীমিত ক্যান্ডিডেট উৎস র‍্যাঙ্কিংকে সাশ্রয়ী করে।'],
      ['Fan-out', 'ফ্যান-আউট', 'How should ordinary users be served?', 'সাধারণ ব্যবহারকারীকে কীভাবে পরিবেশন করবেন?', ['Precompute inboxes on write', 'Rebuild all history on every read'], ['রাইটের সময় ইনবক্স আগে তৈরি', 'প্রতি রিডে সব ইতিহাস পুনর্নির্মাণ'], 0, 'Precomputation makes the common read path fast.', 'প্রিকম্পিউটেশন সাধারণ রিড পথ দ্রুত করে।'],
      ['Celebrities', 'সেলিব্রিটি', 'What changes for huge follower counts?', 'বিশাল ফলোয়ার সংখ্যায় কী বদলাবে?', ['Merge celebrity posts at read time', 'Write millions of inbox rows synchronously'], ['রিডের সময় সেলিব্রিটি পোস্ট মার্জ', 'সিঙ্ক্রোনাসভাবে লক্ষ ইনবক্স রো লেখা'], 0, 'Hybrid fan-out prevents celebrity write explosions.', 'হাইব্রিড ফ্যান-আউট সেলিব্রিটি রাইট বিস্ফোরণ ঠেকায়।'],
      ['Pagination', 'পেজিনেশন', 'How should a changing feed paginate?', 'পরিবর্তনশীল ফিড কীভাবে পেজিনেট হবে?', ['Stable cursor based on rank/time', 'Numeric offset only'], ['র‍্যাঙ্ক/সময়ভিত্তিক স্থিতিশীল কার্সর', 'শুধু সংখ্যার অফসেট'], 0, 'Cursors reduce duplicates and gaps as the feed changes.', 'ফিড বদলালে কার্সর ডুপ্লিকেট ও ফাঁক কমায়।'],
      ['Traffic', 'ট্রাফিক', 'Which estimate exposes fan-out write amplification?', 'কোন হিসাব fan-out write amplification দেখায়?', ['Posts per second multiplied by average followers', 'Only the number of profile pages'], ['প্রতি সেকেন্ডের পোস্ট × গড় ফলোয়ার', 'শুধু প্রোফাইল পেজের সংখ্যা'], 0, 'The multiplication reveals the inbox writes created by each published post.', 'গুণফলটি প্রতি প্রকাশিত পোস্টের ইনবক্স রাইট দেখায়।'],
      ['Ranking', 'র‍্যাঙ্কিং', 'Where should ranking features be computed?', 'র‍্যাঙ্কিং ফিচার কোথায় হিসাব হবে?', ['Split stable offline features from fresh online signals', 'Run an unbounded query for every candidate'], ['স্থিতিশীল অফলাইন ফিচার ও নতুন অনলাইন সিগন্যাল আলাদা', 'প্রতি ক্যান্ডিডেটে সীমাহীন কুয়েরি'], 0, 'Precomputation controls latency while fresh signals retain relevance.', 'প্রিকম্পিউটেশন লেটেন্সি নিয়ন্ত্রণ করে, নতুন সিগন্যাল প্রাসঙ্গিকতা রাখে।'],
      ['Cache', 'ক্যাশ', 'How should a deleted post leave cached feeds?', 'ডিলিট করা পোস্ট ক্যাশড ফিড থেকে কীভাবে সরবে?', ['Tombstone it and filter immediately while invalidation propagates', 'Wait for every cache to expire'], ['tombstone করে সঙ্গে সঙ্গে ফিল্টার, পরে invalidation', 'সব ক্যাশ মেয়াদ শেষ হওয়া পর্যন্ত অপেক্ষা'], 0, 'A tombstone closes the correctness gap during asynchronous invalidation.', 'অ্যাসিঙ্ক invalidation চলাকালে tombstone শুদ্ধতার ফাঁক বন্ধ করে।'],
      ['Degradation', 'অবনতি', 'What is a useful fallback when the ranking service fails?', 'র‍্যাঙ্কিং সার্ভিস ব্যর্থ হলে ভালো ফলব্যাক কী?', ['Serve a recent chronological feed with a visible freshness rule', 'Return a blank screen'], ['সাম্প্রতিক সময়ক্রমিক ফিড ও স্পষ্ট freshness নিয়ম', 'ফাঁকা স্ক্রিন'], 0, 'A simpler deterministic feed preserves the core reading experience.', 'সহজ নির্ধারিত ফিড মূল পড়ার অভিজ্ঞতা সচল রাখে।'],
    ],
  },
  {
    id: 'notification-lab', icon: '◉', title: l('Notification Platform Lab', 'নোটিফিকেশন প্ল্যাটফর্ম ল্যাব'), subtitle: l('Deliver across push, email, and SMS safely.', 'পুশ, ইমেইল ও SMS নিরাপদে পাঠান।'),
    stages: [
      ['Intake', 'ইনটেক', 'How should product services request a notification?', 'প্রোডাক্ট সার্ভিস কীভাবে নোটিফিকেশন চাইবে?', ['Publish a durable notification command', 'Call every provider synchronously'], ['টেকসই নোটিফিকেশন কমান্ড প্রকাশ', 'সব প্রোভাইডারকে সিঙ্ক্রোনাস কল'], 0, 'A durable command absorbs spikes and isolates product latency.', 'টেকসই কমান্ড স্পাইক শোষণ করে ও প্রোডাক্ট লেটেন্সি আলাদা রাখে।'],
      ['Preferences', 'পছন্দ', 'When should preferences and quiet hours be applied?', 'পছন্দ ও নীরব সময় কখন প্রয়োগ হবে?', ['Before channel delivery is queued', 'After every provider has sent'], ['চ্যানেল ডেলিভারি কিউ করার আগে', 'সব প্রোভাইডার পাঠানোর পরে'], 0, 'Filtering early prevents unwanted and costly sends.', 'আগে ফিল্টার করলে অনাকাঙ্ক্ষিত ও ব্যয়বহুল পাঠানো ঠেকে।'],
      ['Providers', 'প্রোভাইডার', 'How should a provider outage be handled?', 'প্রোভাইডার আউটেজ কীভাবে সামলাবেন?', ['Circuit breaker, bounded retry, then fallback', 'Retry forever without delay'], ['সার্কিট ব্রেকার, সীমিত রিট্রাই, তারপর ফলব্যাক', 'বিরতি ছাড়া অনন্ত রিট্রাই'], 0, 'Bounded recovery protects the queue and alternative providers.', 'সীমিত রিকভারি কিউ ও বিকল্প প্রোভাইডার রক্ষা করে।'],
      ['Duplicates', 'ডুপ্লিকেট', 'How do you prevent duplicate user messages?', 'ডুপ্লিকেট বার্তা কীভাবে ঠেকাবেন?', ['Stable idempotency key per logical send', 'Trust network delivery to be exactly once'], ['প্রতি যৌক্তিক সেন্ডে স্থায়ী আইডেমপোটেন্সি কী', 'নেটওয়ার্ক ঠিক একবার দেবে বিশ্বাস'], 0, 'Deduplication turns repeated delivery into one user-visible effect.', 'ডিডুপ্লিকেশন বারবার ডেলিভারিকে একটি দৃশ্যমান ফলে রূপ দেয়।'],
    ],
  },
  {
    id: 'rate-limiter-lab', icon: '⏱', title: l('Rate Limiter Lab', 'রেট লিমিটার ল্যাব'), subtitle: l('Protect an API without punishing good users.', 'ভালো ব্যবহারকারীকে শাস্তি না দিয়ে API রক্ষা করুন।'),
    stages: [
      ['Identity', 'পরিচয়', 'What should a user limit be keyed by?', 'ইউজার সীমা কোন কী দিয়ে হবে?', ['Authenticated account with IP fallback', 'One global counter for everyone'], ['অথেন্টিকেটেড অ্যাকাউন্ট, IP ফলব্যাকসহ', 'সবার জন্য একটি গ্লোবাল কাউন্টার'], 0, 'Meaningful identity improves fairness and abuse resistance.', 'অর্থপূর্ণ পরিচয় ন্যায্যতা ও অপব্যবহার প্রতিরোধ বাড়ায়।'],
      ['Algorithm', 'অ্যালগরিদম', 'Which algorithm permits controlled bursts?', 'কোন অ্যালগরিদম নিয়ন্ত্রিত বার্স্ট দেয়?', ['Token bucket', 'Delete random requests'], ['টোকেন বাকেট', 'র‍্যান্ডম রিকোয়েস্ট মুছে ফেলা'], 0, 'Tokens model a refill rate plus an explicit burst budget.', 'টোকেন রিফিল হার ও স্পষ্ট বার্স্ট বাজেট মডেল করে।'],
      ['Distribution', 'বণ্টন', 'Where should distributed counters live?', 'ডিস্ট্রিবিউটেড কাউন্টার কোথায় থাকবে?', ['Low-latency shared store with atomic updates', 'Inside one random app process'], ['অ্যাটমিক আপডেটসহ কম-লেটেন্সি শেয়ার্ড স্টোর', 'একটি র‍্যান্ডম অ্যাপ প্রসেসে'], 0, 'Shared atomic state gives replicas a consistent enforcement point.', 'শেয়ার্ড অ্যাটমিক স্টেট রেপ্লিকাকে একক প্রয়োগ পয়েন্ট দেয়।'],
      ['Response', 'উত্তর', 'What should a limited client receive?', 'সীমিত ক্লায়েন্ট কী পাবে?', ['HTTP 429 with retry guidance', 'A generic HTTP 500'], ['রিট্রাই নির্দেশনাসহ HTTP 429', 'সাধারণ HTTP 500'], 0, 'Explicit feedback lets well-behaved clients back off.', 'স্পষ্ট ফিডব্যাক ভালো ক্লায়েন্টকে ব্যাকঅফ করতে দেয়।'],
    ],
  },
  {
    id: 'video-lab', icon: '▶', title: l('Video Streaming Lab', 'ভিডিও স্ট্রিমিং ল্যাব'), subtitle: l('Build upload, transcoding, and global playback.', 'আপলোড, ট্রান্সকোডিং ও গ্লোবাল প্লেব্যাক তৈরি করুন।'),
    stages: [
      ['Upload', 'আপলোড', 'Where should large uploads go first?', 'বড় আপলোড প্রথমে কোথায় যাবে?', ['Direct multipart object storage upload', 'Through one application server'], ['ডাইরেক্ট মাল্টিপার্ট অবজেক্ট স্টোরেজ', 'একটি অ্যাপ সার্ভারের মধ্য দিয়ে'], 0, 'Direct uploads keep application bandwidth free.', 'ডাইরেক্ট আপলোড অ্যাপ্লিকেশন ব্যান্ডউইডথ মুক্ত রাখে।'],
      ['Processing', 'প্রসেসিং', 'How should transcoding start?', 'ট্রান্সকোডিং কীভাবে শুরু হবে?', ['Durable workflow after upload completion', 'Inside the user request'], ['আপলোড শেষে টেকসই ওয়ার্কফ্লো', 'ইউজার রিকোয়েস্টের ভেতরে'], 0, 'Async workflows retry heavy processing without blocking users.', 'অ্যাসিঙ্ক ওয়ার্কফ্লো ব্যবহারকারীকে না থামিয়ে ভারী কাজ রিট্রাই করে।'],
      ['Playback', 'প্লেব্যাক', 'How should varying network quality be supported?', 'ভিন্ন নেটওয়ার্ক মান কীভাবে সামলাবেন?', ['Segmented adaptive bitrate renditions', 'One maximum-quality file only'], ['সেগমেন্টেড অ্যাডাপটিভ বিটরেট', 'শুধু সর্বোচ্চ মানের একটি ফাইল'], 0, 'Adaptive segments let players switch quality smoothly.', 'অ্যাডাপটিভ সেগমেন্ট প্লেয়ারকে সহজে মান বদলাতে দেয়।'],
      ['Delivery', 'ডেলিভারি', 'Where should popular segments be served?', 'জনপ্রিয় সেগমেন্ট কোথা থেকে দেওয়া উচিত?', ['A globally distributed CDN', 'The transcoding worker'], ['গ্লোবাল CDN', 'ট্রান্সকোডিং ওয়ার্কার'], 0, 'CDN edges reduce startup latency and origin traffic.', 'CDN এজ স্টার্টআপ লেটেন্সি ও অরিজিন ট্রাফিক কমায়।'],
      ['Capacity', 'ধারণক্ষমতা', 'Which input dominates delivery bandwidth?', 'কোন ইনপুট ডেলিভারি ব্যান্ডউইডথকে সবচেয়ে বেশি প্রভাবিত করে?', ['Concurrent viewers multiplied by average bitrate', 'Number of video titles alone'], ['একযোগে দর্শক × গড় বিটরেট', 'শুধু ভিডিও শিরোনামের সংখ্যা'], 0, 'Playback bandwidth scales with simultaneous streams and selected rendition bitrate.', 'প্লেব্যাক ব্যান্ডউইডথ একযোগে স্ট্রিম ও নির্বাচিত বিটরেটের সঙ্গে বাড়ে।'],
      ['Metadata', 'মেটাডেটা', 'Where should playback metadata and video bytes live?', 'প্লেব্যাক মেটাডেটা ও ভিডিও বাইট কোথায় থাকবে?', ['Metadata database plus object storage for immutable media', 'Both inside application memory'], ['মেটাডেটা ডেটাবেস ও অপরিবর্তনীয় মিডিয়ার জন্য অবজেক্ট স্টোরেজ', 'দুটিই অ্যাপ মেমোরিতে'], 0, 'Separating queryable state from large blobs fits each workload.', 'কুয়েরিযোগ্য স্টেটকে বড় blob থেকে আলাদা করলে প্রতিটি কাজ উপযুক্ত স্টোরেজ পায়।'],
      ['Retry', 'রিট্রাই', 'How should a failed rendition be retried?', 'ব্যর্থ rendition কীভাবে রিট্রাই হবে?', ['Idempotent jobs with bounded attempts and a dead-letter queue', 'Restart the whole platform'], ['আইডেমপোটেন্ট job, সীমিত চেষ্টা ও dead-letter queue', 'পুরো প্ল্যাটফর্ম রিস্টার্ট'], 0, 'Per-rendition jobs isolate failure and make recovery observable.', 'প্রতি rendition job ব্যর্থতা আলাদা করে ও রিকভারি পর্যবেক্ষণযোগ্য করে।'],
      ['Quality', 'গুণমান', 'Which metrics reveal playback experience?', 'কোন মেট্রিক প্লেব্যাক অভিজ্ঞতা দেখায়?', ['Startup delay, rebuffer ratio, errors, and bitrate switches', 'CPU temperature alone'], ['স্টার্টআপ বিলম্ব, rebuffer অনুপাত, error ও bitrate switch', 'শুধু CPU তাপমাত্রা'], 0, 'Quality-of-experience signals connect architecture decisions to viewers.', 'অভিজ্ঞতার মেট্রিক আর্কিটেকচার সিদ্ধান্তকে দর্শকের ফলাফলের সঙ্গে যুক্ত করে।'],
    ],
  },
  {
    id: 'search-lab', icon: '⌕', title: l('Search & Autocomplete Lab', 'সার্চ ও অটোকমপ্লিট ল্যাব'), subtitle: l('Index, rank, and suggest at interactive speed.', 'ইন্টারঅ্যাক্টিভ গতিতে ইনডেক্স, র‍্যাঙ্ক ও সাজেস্ট করুন।'),
    stages: [
      ['Index', 'ইনডেক্স', 'Which structure powers full-text lookup?', 'ফুল-টেক্সট লুকআপ কোন স্ট্রাকচার চালায়?', ['An inverted index', 'A video segment manifest'], ['ইনভার্টেড ইনডেক্স', 'ভিডিও সেগমেন্ট ম্যানিফেস্ট'], 0, 'An inverted index maps terms to matching documents.', 'ইনভার্টেড ইনডেক্স টার্মকে মিলে যাওয়া ডকুমেন্টে ম্যাপ করে।'],
      ['Freshness', 'ফ্রেশনেস', 'How should source changes reach search?', 'সোর্স পরিবর্তন সার্চে কীভাবে যাবে?', ['A durable change/event pipeline', 'Manual weekly copy'], ['টেকসই চেঞ্জ/ইভেন্ট পাইপলাইন', 'সাপ্তাহিক ম্যানুয়াল কপি'], 0, 'Events decouple source writes from index work and retries.', 'ইভেন্ট সোর্স রাইটকে ইনডেক্স কাজ ও রিট্রাই থেকে আলাদা করে।'],
      ['Autocomplete', 'অটোকমপ্লিট', 'What should serve popular prefixes?', 'জনপ্রিয় প্রিফিক্স কী পরিবেশন করবে?', ['Trie or precomputed top suggestions', 'Wildcard database scan per key'], ['Trie বা প্রিকম্পিউটেড টপ সাজেশন', 'প্রতি কী-তে ডেটাবেস ওয়াইল্ডকার্ড স্ক্যান'], 0, 'Prefix structures make keystroke latency predictable.', 'প্রিফিক্স স্ট্রাকচার কীস্ট্রোক লেটেন্সি পূর্বানুমানযোগ্য করে।'],
      ['Ranking', 'র‍্যাঙ্কিং', 'How should ranking evolve safely?', 'র‍্যাঙ্কিং নিরাপদে কীভাবে বদলাবে?', ['Versioned features with offline and A/B evaluation', 'Change production weights blindly'], ['ভার্সনড ফিচার, অফলাইন ও A/B মূল্যায়ন', 'অন্ধভাবে প্রোডাকশন ওজন বদল'], 0, 'Measured rollout protects relevance and user trust.', 'পরিমাপ করা রোলআউট প্রাসঙ্গিকতা ও আস্থা রক্ষা করে।'],
    ],
  },
  {
    id: 'payments-lab', icon: '৳', title: l('Payments Workflow Lab', 'পেমেন্ট ওয়ার্কফ্লো ল্যাব'), subtitle: l('Design money movement that can be audited.', 'অডিটযোগ্য অর্থ চলাচল ডিজাইন করুন।'),
    stages: [
      ['Command', 'কমান্ড', 'How should duplicate checkout requests behave?', 'ডুপ্লিকেট চেকআউট কীভাবে আচরণ করবে?', ['Return the same result using an idempotency key', 'Charge again every time'], ['আইডেমপোটেন্সি কী দিয়ে একই ফল', 'প্রতিবার আবার চার্জ'], 0, 'A stable key creates one logical payment attempt.', 'স্থায়ী কী একটি যৌক্তিক পেমেন্ট চেষ্টা তৈরি করে।'],
      ['Ledger', 'লেজার', 'How should monetary history be stored?', 'অর্থের ইতিহাস কীভাবে সংরক্ষণ হবে?', ['Immutable double-entry ledger records', 'Only overwrite the current balance'], ['অপরিবর্তনীয় ডাবল-এন্ট্রি লেজার', 'শুধু বর্তমান ব্যালেন্স ওভাররাইট'], 0, 'Immutable entries preserve audit and reconstruction.', 'অপরিবর্তনীয় এন্ট্রি অডিট ও পুনর্গঠন রক্ষা করে।'],
      ['Provider', 'প্রোভাইডার', 'How are delayed provider events handled?', 'দেরি করা প্রোভাইডার ইভেন্ট কীভাবে সামলাবেন?', ['Durable webhook inbox plus reconciliation', 'Ignore anything after the request'], ['টেকসই ওয়েবহুক ইনবক্স ও রিকনসিলিয়েশন', 'রিকোয়েস্টের পর সব উপেক্ষা'], 0, 'Reconciliation resolves lost, duplicated, and reordered events.', 'রিকনসিলিয়েশন হারানো, ডুপ্লিকেট ও উল্টো ক্রমের ইভেন্ট মেলায়।'],
      ['Workflow', 'ওয়ার্কফ্লো', 'How should order and payment state coordinate?', 'অর্ডার ও পেমেন্ট স্টেট কীভাবে সমন্বয় হবে?', ['Explicit state machine with compensations', 'One hidden boolean flag'], ['ক্ষতিপূরণসহ স্পষ্ট স্টেট মেশিন', 'একটি লুকানো বুলিয়ান ফ্ল্যাগ'], 0, 'Explicit transitions make failures and recovery auditable.', 'স্পষ্ট ট্রানজিশন ব্যর্থতা ও রিকভারি অডিটযোগ্য করে।'],
      ['Requirements', 'রিকোয়ারমেন্ট', 'Which guarantee is more important than a fast success screen?', 'দ্রুত সফলতার স্ক্রিনের চেয়ে কোন নিশ্চয়তা বেশি গুরুত্বপূর্ণ?', ['Never silently charge twice and keep an auditable outcome', 'Always respond in one millisecond'], ['নীরবে দুইবার চার্জ নয় এবং অডিটযোগ্য ফল', 'সবসময় এক মিলিসেকেন্ডে উত্তর'], 0, 'Money movement prioritizes correctness, traceability, and explicit pending states.', 'অর্থ চলাচলে শুদ্ধতা, অনুসরণযোগ্যতা ও স্পষ্ট pending state অগ্রাধিকার পায়।'],
      ['Authorization', 'অনুমোদন', 'When should capture be separated from authorization?', 'authorization থেকে capture কখন আলাদা হবে?', ['When inventory or fulfillment must be confirmed first', 'Never, because all payments are identical'], ['ইনভেন্টরি বা fulfillment আগে নিশ্চিত হলে', 'কখনো নয়, সব পেমেন্ট একই'], 0, 'Authorize-then-capture avoids collecting funds before the order can be fulfilled.', 'authorize-then-capture অর্ডার পূরণ নিশ্চিত হওয়ার আগে অর্থ নেওয়া এড়ায়।'],
      ['Timeout', 'টাইমআউট', 'A provider times out after receiving a charge. What next?', 'চার্জ পাওয়ার পর provider timeout হলে কী করবেন?', ['Mark pending and query/reconcile by idempotency key', 'Immediately issue an unrelated new charge'], ['pending করে idempotency key দিয়ে query/reconcile', 'সঙ্গে সঙ্গে নতুন আলাদা চার্জ'], 0, 'A timeout is an unknown outcome, not proof that no charge occurred.', 'টাইমআউট অজানা ফল; চার্জ হয়নি তার প্রমাণ নয়।'],
      ['Operations', 'অপারেশন', 'What closes gaps between the ledger and provider?', 'লেজার ও provider-এর ফাঁক কীভাবে বন্ধ হবে?', ['Scheduled reconciliation with alerts and repair workflow', 'Delete mismatched records'], ['নির্ধারিত reconciliation, alert ও repair workflow', 'অমিল রেকর্ড মুছে ফেলা'], 0, 'Reconciliation turns external drift into visible, recoverable work.', 'reconciliation বাইরের অমিলকে দৃশ্যমান ও পুনরুদ্ধারযোগ্য কাজে রূপ দেয়।'],
    ],
  },
].map((lab) => ({ ...lab, stages: lab.stages.map((s, i) => ({ id: `${lab.id}-${i}`, title: l(s[0], s[1]), question: l(s[2], s[3]), options: s[4].map((en, x) => l(en, s[5][x])), correct: s[6], feedback: l(s[7], s[8]) })) }))

export const ui = {
  brand: l('System Design Path', 'সিস্টেম ডিজাইন পথ'),
  dashboard: l('Dashboard', 'ড্যাশবোর্ড'), learn: l('Learn', 'শিখুন'), labs: l('Design labs', 'ডিজাইন ল্যাব'), simulator: l('Simulator', 'সিমুলেটর'),
}
