const L = (en, bn) => ({ en, bn })
const ids = ['a', 'b', 'c', 'd']

function Q(id, promptEn, promptBn, choices, correct, explanationEn, explanationBn) {
  const correctIndexes = Array.isArray(correct) ? correct : [correct]
  return {
    id,
    type: correctIndexes.length > 1 ? 'multi' : 'single',
    prompt: L(promptEn, promptBn),
    options: choices.map(([en, bn], index) => ({ id: ids[index], text: L(en, bn) })),
    correct: correctIndexes.map((index) => ids[index]),
    explanation: L(explanationEn, explanationBn),
    authored: true,
  }
}

export const flagshipExams = {
  'system-design': [
    Q('s1', 'You are asked to design a flash-sale platform. What should you clarify before drawing services?', 'ফ্ল্যাশ-সেল প্ল্যাটফর্ম ডিজাইন করতে বলা হলো। সার্ভিস আঁকার আগে কী পরিষ্কার করবেন?', [['Peak demand, inventory correctness, and acceptable degradation', 'পিক চাহিদা, ইনভেন্টরি কারেক্টনেস ও গ্রহণযোগ্য ডিগ্রেডেশন'], ['Which cloud logo the interviewer prefers', 'ইন্টারভিউয়ার কোন ক্লাউড লোগো পছন্দ করেন'], ['The names of every future microservice', 'ভবিষ্যতের প্রতিটি মাইক্রোসার্ভিসের নাম']], 0, 'Requirements and constraints determine the architecture. Technology names are downstream decisions.', 'রিকোয়ারমেন্ট ও সীমাবদ্ধতা আর্কিটেকচার নির্ধারণ করে। প্রযুক্তির নাম পরবর্তী সিদ্ধান্ত।'),
    Q('s2', 'Only 100,000 tickets exist, but 10 million buyers may click at once. Which design protects correctness and capacity?', '১ লক্ষ টিকিট, কিন্তু ১ কোটি ক্রেতা একসঙ্গে ক্লিক করতে পারে। কোন ডিজাইন কারেক্টনেস ও ক্ষমতা রক্ষা করে?', [['Add more frontend animations', 'আরও ফ্রন্টএন্ড অ্যানিমেশন যোগ করুন'], ['Use admission control plus transactional inventory holds', 'অ্যাডমিশন কন্ট্রোল ও ট্রানজ্যাকশনাল ইনভেন্টরি হোল্ড ব্যবহার করুন'], ['Cache successful purchases for one day', 'সফল কেনাকাটা একদিন ক্যাশ করুন']], 1, 'Admission control limits work entering the critical path; transactional holds prevent overselling.', 'অ্যাডমিশন কন্ট্রোল ক্রিটিক্যাল পথে কাজ সীমিত করে; ট্রানজ্যাকশনাল হোল্ড অতিরিক্ত বিক্রি ঠেকায়।'),
    Q('s3', 'Which operations belong off the synchronous ticket-purchase path?', 'কোন কাজগুলো সিঙ্ক্রোনাস টিকিট কেনার পথের বাইরে থাকা উচিত?', [['Inventory reservation and payment authorization', 'ইনভেন্টরি রিজার্ভেশন ও পেমেন্ট অথরাইজেশন'], ['Email receipt and analytics event', 'ইমেইল রিসিট ও অ্যানালিটিক্স ইভেন্ট'], ['Idempotency validation and order commit', 'আইডেমপোটেন্সি যাচাই ও অর্ডার কমিট']], 1, 'Email and analytics can run from durable events; reservation, payment decision, and order durability determine the user result.', 'ইমেইল ও অ্যানালিটিক্স টেকসই ইভেন্ট থেকে চলতে পারে; রিজার্ভেশন, পেমেন্ট সিদ্ধান্ত ও অর্ডার টেকসই হওয়া ব্যবহারকারীর ফল নির্ধারণ করে।'),
    Q('s4', 'The system needs 50 instances normally across three zones and must survive one zone loss. What is the safer capacity plan?', 'স্বাভাবিকভাবে তিন জোনে ৫০ ইনস্ট্যান্স দরকার এবং এক জোন লস সহ্য করতে হবে। নিরাপদ ক্ষমতা পরিকল্পনা কোনটি?', [['About 75 instances, 25 per zone', 'প্রায় ৭৫ ইনস্ট্যান্স, প্রতি জোনে ২৫'], ['Exactly 50 instances, evenly split', 'ঠিক ৫০ ইনস্ট্যান্স, সমান ভাগে'], ['One instance with a larger disk', 'বড় ডিস্কসহ একটি ইনস্ট্যান্স']], 0, 'With 75 total, the two surviving zones retain 50 instances of capacity. Fifty total would leave only about 33.', 'মোট ৭৫ হলে বাকি দুই জোনে ৫০ ইনস্ট্যান্স ক্ষমতা থাকে। মোট ৫০ হলে প্রায় ৩৩টি থাকে।'),
    Q('s5', 'Select the two signals of a strong system-design interview answer.', 'শক্তিশালী সিস্টেম-ডিজাইন ইন্টারভিউ উত্তরের দুটি লক্ষণ বাছুন।', [['It states scale assumptions before choosing components.', 'কম্পোনেন্ট বাছার আগে স্কেল অনুমান বলে।'], ['It explains overload and failure behavior.', 'ওভারলোড ও ব্যর্থতার আচরণ ব্যাখ্যা করে।'], ['It uses the maximum possible number of technologies.', 'সর্বোচ্চ সংখ্যক প্রযুক্তি ব্যবহার করে।'], ['It avoids discussing trade-offs.', 'ট্রেড-অফ আলোচনা এড়ায়।']], [0, 1], 'A strong answer connects assumptions to decisions and covers failure. More technology without justification weakens the design.', 'শক্ত উত্তর অনুমানকে সিদ্ধান্তের সঙ্গে যুক্ত করে এবং ব্যর্থতা কভার করে। কারণ ছাড়া বেশি প্রযুক্তি ডিজাইন দুর্বল করে।'),
  ],
  requirements: [
    Q('r1', '“Customers can place an order” and “99.9% of orders succeed within two seconds” are what kinds of requirements?', '“গ্রাহক অর্ডার দিতে পারবেন” এবং “৯৯.৯% অর্ডার দুই সেকেন্ডে সফল হবে”—এগুলো কী ধরনের রিকোয়ারমেন্ট?', [['Both are functional', 'দুটিই ফাংশনাল'], ['Functional, then non-functional', 'প্রথমটি ফাংশনাল, দ্বিতীয়টি নন-ফাংশনাল'], ['Non-functional, then functional', 'প্রথমটি নন-ফাংশনাল, দ্বিতীয়টি ফাংশনাল']], 1, 'The first defines behavior; the second defines a measurable quality target.', 'প্রথমটি আচরণ বলে; দ্বিতীয়টি পরিমাপযোগ্য গুণগত লক্ষ্য বলে।'),
    Q('r2', 'A delivery app has 300,000 orders/day. What is a reasonable first peak-order estimate?', 'ডেলিভারি অ্যাপে দিনে ৩ লক্ষ অর্ডার। প্রথম পিক-অর্ডার অনুমান কোনটি যুক্তিযুক্ত?', [['About 3.5 orders/s with no peak factor', 'পিক ফ্যাক্টর ছাড়া প্রায় ৩.৫ অর্ডার/সেকেন্ড'], ['About 35 orders/s using a 10× peak factor', '১০ গুণ পিক ধরে প্রায় ৩৫ অর্ডার/সেকেন্ড'], ['300,000 orders/s', '৩,০০,০০০ অর্ডার/সেকেন্ড']], 1, 'Average is roughly 3.5/s. A stated 10× factor gives a defensible early peak estimate of about 35/s.', 'গড় প্রায় ৩.৫/সেকেন্ড। ঘোষিত ১০ গুণ ফ্যাক্টর প্রায় ৩৫/সেকেন্ডের যুক্তিযুক্ত প্রাথমিক পিক দেয়।'),
    Q('r3', 'Which requirement should be strongest for an acknowledged food order?', 'স্বীকৃত ফুড অর্ডারের জন্য কোন রিকোয়ারমেন্ট সবচেয়ে শক্ত হওয়া উচিত?', [['It must never be lost after acknowledgement.', 'স্বীকৃতির পর এটি কখনও হারানো যাবে না।'], ['Its courier dot must update every millisecond.', 'কুরিয়ার ডট প্রতি মিলিসেকেন্ডে বদলাতে হবে।'], ['Its menu image must always be uncompressed.', 'মেনু ছবি সবসময় আনকমপ্রেসড হতে হবে।']], 0, 'Order durability is a business invariant. Location and media freshness can usually accept weaker guarantees.', 'অর্ডার টেকসই থাকা ব্যবসায়িক ইনভ্যারিয়েন্ট। লোকেশন ও মিডিয়া ফ্রেশনেস সাধারণত দুর্বল গ্যারান্টি নিতে পারে।'),
    Q('r4', 'Courier locations arrive out of order. Which requirement prevents the map moving backward?', 'কুরিয়ার লোকেশন উল্টো ক্রমে আসে। কোন রিকোয়ারমেন্ট ম্যাপকে পেছনে যাওয়া থেকে রক্ষা করে?', [['Store only the largest payload', 'শুধু সবচেয়ে বড় পেলোড রাখুন'], ['Each update carries a sequence or event time; older updates are ignored.', 'প্রতি আপডেটে সিকোয়েন্স বা ইভেন্ট সময় থাকবে; পুরোনো আপডেট বাদ যাবে।'], ['Use a global transaction for every GPS point.', 'প্রতি GPS পয়েন্টে গ্লোবাল ট্রানজ্যাকশন নিন।']], 1, 'Ordering metadata lets consumers reject stale location updates without putting GPS traffic through the order database.', 'অর্ডারিং মেটাডেটা কনজিউমারকে পুরোনো লোকেশন বাদ দিতে দেয়, GPS ট্রাফিক অর্ডার DB-তে না দিয়েই।'),
    Q('r5', 'For a six-week MVP, which items are sensible to mark out of scope?', 'ছয় সপ্তাহের MVP-তে কোন আইটেমগুলো আউট-অফ-স্কোপ রাখা যুক্তিযুক্ত?', [['Place and track a basic order', 'মৌলিক অর্ডার ও ট্র্যাকিং'], ['Reviews, complex promotions, and scheduled group orders', 'রিভিউ, জটিল প্রোমোশন ও শিডিউলড গ্রুপ অর্ডার'], ['Durable order creation and payment reconciliation', 'টেকসই অর্ডার তৈরি ও পেমেন্ট রিকনসিলিয়েশন']], 1, 'Secondary growth features can wait; the core order and money path cannot.', 'দ্বিতীয়িক গ্রোথ ফিচার অপেক্ষা করতে পারে; মূল অর্ডার ও অর্থের পথ পারে না।'),
  ],
  estimation: [
    Q('e1', 'Ten million requests arrive uniformly per day. Which average RPS is closest?', 'দিনে ১ কোটি রিকোয়েস্ট সমানভাবে আসে। কোন গড় RPS সবচেয়ে কাছাকাছি?', [['116 RPS', '১১৬ RPS'], ['1,000 RPS', '১,০০০ RPS'], ['10,000 RPS', '১০,০০০ RPS']], 0, '10,000,000 ÷ 86,400 is about 116. Peak capacity still needs an explicit multiplier.', '১,০০,০০০০০ ÷ ৮৬,৪০০ প্রায় ১১৬। পিক ক্ষমতার জন্য এখনও স্পষ্ট গুণক দরকার।'),
    Q('e2', 'Forty million 3 MB photos are uploaded daily. What is the raw daily storage?', 'প্রতিদিন ৪ কোটি ৩ MB ছবি আপলোড হয়। কাঁচা দৈনিক স্টোরেজ কত?', [['12 TB', '১২ TB'], ['120 TB', '১২০ TB'], ['1.2 PB', '১.২ PB']], 1, '40 million × 3 MB = 120 million MB, approximately 120 TB before variants and replication.', '৪ কোটি × ৩ MB = ১২ কোটি MB, ভ্যারিয়েন্ট ও রেপ্লিকেশনের আগে প্রায় ১২০ TB।'),
    Q('e3', 'Average upload traffic is 463 RPS. What should you say before planning for 2,315 RPS?', 'গড় আপলোড ট্রাফিক ৪৬৩ RPS। ২,৩১৫ RPS পরিকল্পনার আগে কী বলবেন?', [['“I assume a 5× peak-to-average factor.”', '“আমি ৫ গুণ পিক-টু-অ্যাভারেজ ফ্যাক্টর ধরছি।”'], ['“The database automatically multiplies traffic.”', '“ডেটাবেস স্বয়ংক্রিয়ভাবে ট্রাফিক গুণ করে।”'], ['“463 and 2,315 are equivalent.”', '“৪৬৩ ও ২,৩১৫ সমান।”']], 0, 'The multiplier is an assumption, not a fact. Stating it makes the estimate reviewable.', 'গুণকটি অনুমান, তথ্য নয়। এটি বললে হিসাব যাচাইযোগ্য হয়।'),
    Q('e4', 'Photo views require roughly 11.6 GB/s of average delivery bandwidth. Which component becomes economically essential?', 'ফটো ভিউতে গড়ে প্রায় ১১.৬ GB/s ডেলিভারি ব্যান্ডউইডথ দরকার। কোন কম্পোনেন্ট অর্থনৈতিকভাবে জরুরি?', [['A CDN near users', 'ব্যবহারকারীর কাছে CDN'], ['A larger application log file', 'বড় অ্যাপ্লিকেশন লগ ফাইল'], ['A synchronous email worker', 'সিঙ্ক্রোনাস ইমেইল ওয়ার্কার']], 0, 'A CDN absorbs repeated delivery, lowers latency, and protects origin bandwidth.', 'CDN পুনরাবৃত্ত ডেলিভারি শোষণ করে, লেটেন্সি কমায় এবং অরিজিন ব্যান্ডউইডথ রক্ষা করে।'),
    Q('e5', 'Select two good estimation habits.', 'দুটি ভালো এস্টিমেশন অভ্যাস বাছুন।', [['Keep units beside every number.', 'প্রতি সংখ্যার পাশে ইউনিট রাখুন।'], ['Separate average traffic from peak traffic.', 'গড় ও পিক ট্রাফিক আলাদা করুন।'], ['Hide assumptions to sound precise.', 'নিখুঁত শোনাতে অনুমান লুকান।'], ['Ignore replicas and indexes in storage.', 'স্টোরেজে রেপ্লিকা ও ইনডেক্স বাদ দিন।']], [0, 1], 'Units prevent dimensional mistakes; separating average and peak prevents under-provisioning.', 'ইউনিট ডাইমেনশন ভুল ঠেকায়; গড় ও পিক আলাদা করা কম ক্ষমতা পরিকল্পনা ঠেকায়।'),
  ],
  'load-balancing': [
    Q('lb1', 'An instance process is alive but cannot reach its required database. Which endpoint should fail?', 'ইনস্ট্যান্স প্রসেস জীবিত, কিন্তু প্রয়োজনীয় DB-তে পৌঁছাতে পারে না। কোন এন্ডপয়েন্ট ব্যর্থ হবে?', [['Liveness only', 'শুধু লাইভনেস'], ['Readiness, while liveness may remain healthy', 'রেডিনেস; লাইভনেস সুস্থ থাকতে পারে'], ['Neither endpoint', 'কোনোটিই নয়']], 1, 'Liveness decides whether to restart the process; readiness decides whether it can receive traffic.', 'লাইভনেস প্রসেস রিস্টার্ট নির্ধারণ করে; রেডিনেস ট্রাফিক নিতে পারবে কি না বলে।'),
    Q('lb2', 'Why is 75 instances safer than 50 for a 50-instance workload across three zones?', 'তিন জোনে ৫০-ইনস্ট্যান্স ওয়ার্কলোডে ৫০-এর চেয়ে ৭৫ কেন নিরাপদ?', [['Two surviving zones retain 50 instances after one zone fails.', 'এক জোন ব্যর্থ হলে দুই জোনে ৫০ ইনস্ট্যান্স থাকে।'], ['It removes the need for health checks.', 'এটি হেলথ চেকের দরকার সরায়।'], ['It guarantees zero latency.', 'এটি শূন্য লেটেন্সি নিশ্চিত করে।']], 0, 'N-1 capacity means the surviving failure domains can still serve the normal workload.', 'N-1 ক্ষমতা মানে বাকি ফেইলিউর ডোমেইন স্বাভাবিক ওয়ার্কলোড চালাতে পারে।'),
    Q('lb3', 'A deployment terminates instances while long requests are active. What is missing?', 'দীর্ঘ রিকোয়েস্ট চলার সময় ডিপ্লয়মেন্ট ইনস্ট্যান্স বন্ধ করে। কী অনুপস্থিত?', [['Connection draining before termination', 'টার্মিনেশনের আগে কানেকশন ড্রেইনিং'], ['A random sticky cookie', 'র‍্যান্ডম স্টিকি কুকি'], ['A second DNS name for each user', 'প্রতি ব্যবহারকারীর জন্য দ্বিতীয় DNS নাম']], 0, 'Stop new traffic, wait for bounded active work, then terminate.', 'নতুন ট্রাফিক বন্ধ করুন, সীমিত সক্রিয় কাজ শেষ হতে দিন, তারপর বন্ধ করুন।'),
    Q('lb4', 'Some instances handle twice the traffic of others. Which strategy fits best?', 'কিছু ইনস্ট্যান্স অন্যদের দ্বিগুণ ট্রাফিক সামলায়। কোন কৌশল ভালো?', [['Unweighted round robin forever', 'চিরকাল আনওয়েটেড রাউন্ড রবিন'], ['Capacity-aware weighted least load', 'ক্ষমতা-সচেতন ওয়েটেড লিস্ট লোড'], ['Send all requests to the newest instance', 'সব রিকোয়েস্ট নতুন ইনস্ট্যান্সে']], 1, 'Weights and measured load align traffic share with unequal capacity.', 'ওয়েট ও পরিমাপ করা লোড অসম ক্ষমতার সঙ্গে ট্রাফিক ভাগ মেলায়।'),
    Q('lb5', 'Why should session state move outside application instances?', 'সেশন স্টেট অ্যাপ ইনস্ট্যান্সের বাইরে কেন রাখা উচিত?', [['To avoid sticky-session imbalance and make failover safe', 'স্টিকি-সেশন অসমতা এড়াতে ও ফেইলওভার নিরাপদ করতে'], ['To increase HTML file size', 'HTML ফাইল বড় করতে'], ['To disable horizontal scaling', 'হরাইজন্টাল স্কেলিং বন্ধ করতে']], 0, 'Stateless instances can receive any request, drain cleanly, and fail without losing session ownership.', 'স্টেটলেস ইনস্ট্যান্স যেকোনো রিকোয়েস্ট নিতে, পরিষ্কারভাবে ড্রেইন ও সেশন না হারিয়ে ব্যর্থ হতে পারে।'),
  ],
  caching: [
    Q('c1', 'At 20,000 reads/s and a 95% hit rate, approximately how many reads/s reach the database?', '২০,০০০ রিড/সেকেন্ড ও ৯৫% হিট রেটে DB-তে প্রায় কত রিড/সেকেন্ড যায়?', [['1,000', '১,০০০'], ['19,000', '১৯,০০০'], ['20,000', '২০,০০০']], 0, 'Only the 5% misses reach storage: 20,000 × 0.05 = 1,000.', 'শুধু ৫% মিস স্টোরেজে যায়: ২০,০০০ × ০.০৫ = ১,০০০।'),
    Q('c2', 'Thousands of requests miss the same hot key immediately after expiry. What is this, and what helps?', 'মেয়াদ শেষে একই হট কী হাজার রিকোয়েস্ট মিস করে। এটি কী এবং কী সাহায্য করে?', [['Cache stampede; TTL jitter and single-flight loading', 'ক্যাশ স্ট্যাম্পিড; TTL জিটার ও সিঙ্গেল-ফ্লাইট লোডিং'], ['Replication lag; remove every cache', 'রেপ্লিকেশন ল্যাগ; সব ক্যাশ সরান'], ['Deadlock; retry without limit', 'ডেডলক; সীমাহীন রিট্রাই']], 0, 'Jitter avoids synchronized expiry; single-flight lets one request refill while others wait or receive stale data.', 'জিটার একসঙ্গে মেয়াদ শেষ হওয়া ঠেকায়; সিঙ্গেল-ফ্লাইটে এক রিকোয়েস্ট রিফিল করে।'),
    Q('c3', 'A slow cache fill writes an old product after a price invalidation. Which protection is strongest?', 'ধীর ক্যাশ ফিল মূল্য ইনভ্যালিডেশনের পর পুরোনো পণ্য লেখে। কোন সুরক্ষা শক্ত?', [['Source-version comparison before cache write', 'ক্যাশ রাইটের আগে সোর্স-ভার্সন তুলনা'], ['A longer random URL', 'দীর্ঘ র‍্যান্ডম URL'], ['Disable database constraints', 'DB কনস্ট্রেইন্ট বন্ধ']], 0, 'A version check prevents an older fill from overwriting a newer source state.', 'ভার্সন চেক পুরোনো ফিলকে নতুন সোর্স স্টেট ওভাররাইট করতে দেয় না।'),
    Q('c4', 'The cache cluster fails and the database cannot absorb all misses. What should the application do?', 'ক্যাশ ক্লাস্টার ব্যর্থ এবং DB সব মিস নিতে পারে না। অ্যাপ কী করবে?', [['Allow unlimited fallthrough', 'সীমাহীন ফলথ্রু দিন'], ['Bound database fallthrough, serve safe stale data, and recover gradually', 'DB ফলথ্রু সীমিত, নিরাপদ পুরোনো ডেটা সার্ভ ও ধীরে রিকভার'], ['Retry every miss in all service layers', 'সব সার্ভিস স্তরে প্রতিটি মিস রিট্রাই']], 1, 'The recovery design must protect the source of truth from a cascading miss storm.', 'রিকভারি ডিজাইনকে সোর্স অব ট্রুথকে ক্যাসকেডিং মিস স্টর্ম থেকে রক্ষা করতে হবে।'),
    Q('c5', 'A read-heavy catalog tolerates five seconds of staleness. Which starting strategy is simplest?', 'রিড-হেভি ক্যাটালগ পাঁচ সেকেন্ড পুরোনো ডেটা মেনে নেয়। সহজ শুরুর কৌশল কোনটি?', [['Cache-aside with TTL and explicit invalidation', 'TTL ও স্পষ্ট ইনভ্যালিডেশনসহ ক্যাশ-অ্যাসাইড'], ['Write-back for payment balances', 'পেমেন্ট ব্যালেন্সে রাইট-ব্যাক'], ['No source-of-truth database', 'সোর্স-অফ-ট্রুথ DB নেই']], 0, 'Cache-aside keeps clear ownership while lazy fills and invalidation meet the read-heavy workload.', 'ক্যাশ-অ্যাসাইড স্পষ্ট মালিকানা রাখে; লেজি ফিল ও ইনভ্যালিডেশন রিড-হেভি ওয়ার্কলোড মেটায়।'),
  ],
  'sql-nosql': [
    Q('db1', 'Which store best protects order totals, payments, and inventory invariants?', 'অর্ডার টোটাল, পেমেন্ট ও ইনভেন্টরি ইনভ্যারিয়েন্ট কোন স্টোর ভালো রক্ষা করে?', [['A relational database with transactions and constraints', 'ট্রানজ্যাকশন ও কনস্ট্রেইন্টসহ রিলেশনাল DB'], ['An unindexed text file per request', 'প্রতি রিকোয়েস্টে আনইনডেক্সড টেক্সট ফাইল'], ['A browser cache as the only source of truth', 'একমাত্র সোর্স অব ট্রুথ হিসেবে ব্রাউজার ক্যাশ']], 0, 'Relational constraints and transactions make monetary invariants explicit and durable.', 'রিলেশনাল কনস্ট্রেইন্ট ও ট্রানজ্যাকশন অর্থের ইনভ্যারিয়েন্ট স্পষ্ট ও টেকসই করে।'),
    Q('db2', 'Product categories have very different optional attributes and are read as complete aggregates. Which model fits?', 'পণ্য ক্যাটাগরিতে ভিন্ন ঐচ্ছিক বৈশিষ্ট্য এবং সম্পূর্ণ অ্যাগ্রিগেট হিসেবে রিড হয়। কোন মডেল মানায়?', [['Document model', 'ডকুমেন্ট মডেল'], ['One global SQL lock for every read', 'প্রতি রিডে এক গ্লোবাল SQL লক'], ['Time-series metrics only', 'শুধু টাইম-সিরিজ মেট্রিক']], 0, 'A document model matches aggregate reads and variable category-specific fields.', 'ডকুমেন্ট মডেল অ্যাগ্রিগেট রিড ও পরিবর্তনশীল ক্যাটাগরি ফিল্ডের সঙ্গে মেলে।'),
    Q('db3', 'Five hundred thousand immutable click events arrive each second. Where should they enter?', 'প্রতি সেকেন্ডে ৫ লক্ষ অপরিবর্তনীয় ক্লিক ইভেন্ট আসে। কোথায় ঢুকবে?', [['Directly into the order transaction', 'সরাসরি অর্ডার ট্রানজ্যাকশনে'], ['A durable log/stream feeding an analytical store', 'অ্যানালিটিক্যাল স্টোরে যাওয়া টেকসই লগ/স্ট্রিম'], ['The product image cache', 'প্রোডাক্ট ইমেজ ক্যাশ']], 1, 'A log separates high-volume ingestion from later analytical queries and order correctness.', 'লগ উচ্চ-ভলিউম ইনজেশনকে পরবর্তী অ্যানালিটিক্যাল কুয়েরি ও অর্ডার কারেক্টনেস থেকে আলাদা করে।'),
    Q('db4', 'What is the safest reason to add a second database technology?', 'দ্বিতীয় DB প্রযুক্তি যোগ করার নিরাপদ কারণ কী?', [['A measured access pattern that the current store cannot serve well, with clear ownership', 'মাপা অ্যাক্সেস প্যাটার্ন যা বর্তমান স্টোর ভালো দিতে পারে না, স্পষ্ট মালিকানাসহ'], ['A social-media post calls it modern', 'সোশ্যাল মিডিয়া এটিকে আধুনিক বলেছে'], ['Every table must use a different database', 'প্রতি টেবিলে ভিন্ন DB লাগবে']], 0, 'Polyglot storage is justified by measured workload needs and operational ownership, not novelty.', 'পলিগ্লট স্টোরেজ মাপা ওয়ার্কলোড ও অপারেশনাল মালিকানায় যুক্তিযুক্ত, নতুনত্বে নয়।'),
    Q('db5', 'Before choosing SQL or NoSQL, which two artifacts should you write?', 'SQL বা NoSQL বাছার আগে কোন দুটি বিষয় লিখবেন?', [['Dominant access patterns', 'প্রধান অ্যাক্সেস প্যাটার্ন'], ['Business invariants and consistency needs', 'ব্যবসায়িক ইনভ্যারিয়েন্ট ও কনসিস্টেন্সি প্রয়োজন'], ['Preferred database logo color', 'পছন্দের DB লোগোর রং'], ['Number of developer laptops', 'ডেভেলপার ল্যাপটপের সংখ্যা']], [0, 1], 'Queries and invariants reveal the required data model and guarantees.', 'কুয়েরি ও ইনভ্যারিয়েন্ট প্রয়োজনীয় ডেটা মডেল ও গ্যারান্টি দেখায়।'),
  ],
  'replication-sharding': [
    Q('rs1', 'What does replication primarily add?', 'রেপ্লিকেশন প্রধানত কী যোগ করে?', [['Read capacity and failover copies', 'রিড ক্ষমতা ও ফেইলওভার কপি'], ['Unlimited write capacity to one row', 'এক রো-তে সীমাহীন রাইট ক্ষমতা'], ['Automatic elimination of stale reads', 'পুরোনো রিড স্বয়ংক্রিয়ভাবে দূর']], 0, 'Replication creates copies for reads and availability; it does not divide ownership or remove lag.', 'রেপ্লিকেশন রিড ও অ্যাভেইলেবিলিটির কপি তৈরি করে; মালিকানা ভাগ বা ল্যাগ দূর করে না।'),
    Q('rs2', 'When is sharding justified?', 'শার্ডিং কখন যুক্তিযুক্ত?', [['Before measuring one primary', 'এক প্রাইমারি মাপার আগে'], ['When dataset or write load exceeds one well-tuned primary', 'ডেটাসেট বা রাইট লোড একটি ভালো-টিউনড প্রাইমারি ছাড়ালে'], ['Whenever reads increase slightly', 'রিড সামান্য বাড়লেই']], 1, 'Sharding divides data and writes but adds routing, resharding, and cross-shard complexity.', 'শার্ডিং ডেটা ও রাইট ভাগ করে, তবে রাউটিং, রিশার্ডিং ও ক্রস-শার্ড জটিলতা যোগ করে।'),
    Q('rs3', 'Which profile shard key is generally strongest?', 'প্রোফাইলের কোন শার্ড কী সাধারণত শক্তিশালী?', [['A stable high-cardinality hash of user_id', 'user_id-এর স্থায়ী উচ্চ-কার্ডিনালিটি হ্যাশ'], ['A boolean is_premium field', 'বুলিয়ান is_premium ফিল্ড'], ['The current weekday', 'বর্তমান সপ্তাহের দিন']], 0, 'Hashed stable IDs distribute ownership while keeping user-local queries on one shard.', 'হ্যাশ করা স্থায়ী ID মালিকানা বণ্টন করে এবং ইউজার-লোকাল কুয়েরি এক শার্ডে রাখে।'),
    Q('rs4', 'A user updates a profile and immediately reads an old replica value. Which solution preserves read-your-write?', 'ব্যবহারকারী প্রোফাইল আপডেট করে সঙ্গে সঙ্গে পুরোনো রেপ্লিকা মান পড়ে। কোন সমাধান read-your-write রাখে?', [['Route the session to leader or require a minimum version', 'সেশনকে লিডারে রাউট বা মিনিমাম ভার্সন চাওয়া'], ['Increase replica lag deliberately', 'ইচ্ছাকৃতভাবে রেপ্লিকা ল্যাগ বাড়ানো'], ['Remove the profile version', 'প্রোফাইল ভার্সন সরানো']], 0, 'Leader/session routing or a minimum source version avoids replicas behind the client’s acknowledged write.', 'লিডার/সেশন রাউটিং বা মিনিমাম সোর্স ভার্সন ক্লায়েন্টের স্বীকৃত রাইটের পেছনের রেপ্লিকা এড়ায়।'),
    Q('rs5', 'Why use many logical shards mapped onto fewer physical servers?', 'কম ফিজিক্যাল সার্ভারে বেশি লজিক্যাল শার্ড কেন ব্যবহার করবেন?', [['To move smaller ownership units during online resharding', 'অনলাইন রিশার্ডিংয়ে ছোট মালিকানা ইউনিট সরাতে'], ['To guarantee every query scans all servers', 'প্রতি কুয়েরি সব সার্ভার স্ক্যান নিশ্চিত করতে'], ['To prevent adding future capacity', 'ভবিষ্যৎ ক্ষমতা যোগ ঠেকাতে']], 0, 'Logical shards decouple ownership from machines and make gradual movement practical.', 'লজিক্যাল শার্ড মালিকানাকে মেশিন থেকে আলাদা করে এবং ধীরে স্থানান্তর ব্যবহারিক করে।'),
  ],
  messaging: [
    Q('m1', 'An order commits, but the broker publish fails. Which pattern prevents the event from disappearing?', 'অর্ডার কমিট হয়, কিন্তু ব্রোকার পাবলিশ ব্যর্থ। কোন প্যাটার্ন ইভেন্ট হারানো ঠেকায়?', [['Transactional outbox', 'ট্রানজ্যাকশনাল আউটবক্স'], ['Longer frontend timeout', 'দীর্ঘ ফ্রন্টএন্ড টাইমআউট'], ['Random queue deletion', 'র‍্যান্ডম কিউ ডিলিশন']], 0, 'The order and outbox row commit atomically; a relay retries broker publication.', 'অর্ডার ও আউটবক্স রো অ্যাটমিকভাবে কমিট হয়; রিলে ব্রোকার পাবলিশ রিট্রাই করে।'),
    Q('m2', 'A consumer processes an event, but its acknowledgement is lost. What delivery should it expect?', 'কনজিউমার ইভেন্ট প্রসেস করে, কিন্তু অ্যাকনলেজমেন্ট হারায়। কোন ডেলিভারি আশা করবে?', [['At-least-once, so processing must be idempotent', 'At-least-once, তাই প্রসেসিং আইডেমপোটেন্ট হবে'], ['Guaranteed exactly once across every side effect', 'প্রতি সাইড ইফেক্টে নিশ্চিত exactly-once'], ['The event can never reappear', 'ইভেন্ট আর কখনও আসবে না']], 0, 'The broker may redeliver after acknowledgement loss. Deduplicate by event ID around the side effect.', 'অ্যাকনলেজমেন্ট হারালে ব্রোকার আবার দিতে পারে। সাইড ইফেক্টে event ID দিয়ে ডিডুপ করুন।'),
    Q('m3', 'One malformed event retries forever and blocks its partition. What should happen?', 'একটি ম্যালফর্মড ইভেন্ট অনন্ত রিট্রাই করে পার্টিশন আটকায়। কী করা উচিত?', [['Bound retries, send to a dead-letter queue, alert, and continue', 'রিট্রাই সীমিত, ডেড-লেটার কিউ, অ্যালার্ট ও চালিয়ে যাওয়া'], ['Increase retry speed without limit', 'সীমাহীন রিট্রাই গতি বাড়ানো'], ['Delete the whole topic', 'পুরো টপিক ডিলিট']], 0, 'A DLQ isolates non-retryable events while preserving them for diagnosis and replay.', 'DLQ নন-রিট্রাইযোগ্য ইভেন্ট আলাদা করে, নির্ণয় ও রিপ্লের জন্য রাখে।'),
    Q('m4', 'Messages for one order must remain ordered, but different orders can process in parallel. What partition key fits?', 'এক অর্ডারের মেসেজ ক্রমে থাকবে, ভিন্ন অর্ডার সমান্তরালে চলবে। কোন পার্টিশন কী মানায়?', [['order_id', 'order_id'], ['event timestamp modulo two', 'ইভেন্ট টাইমস্ট্যাম্প modulo দুই'], ['One global partition for the company', 'কোম্পানির জন্য একটি গ্লোবাল পার্টিশন']], 0, 'Partitioning by order keeps that aggregate ordered while distributing different orders.', 'অর্ডার দিয়ে পার্টিশন করলে সেই অ্যাগ্রিগেট ক্রমে থাকে এবং ভিন্ন অর্ডার বণ্টিত হয়।'),
    Q('m5', 'A backlog grows by 3,000 events/s and contains 3.6 million events. If production stops growing, how long to drain?', 'ব্যাকলগ ৩,০০০ ইভেন্ট/সেকেন্ড হারে কমতে পারে এবং ৩৬ লক্ষ ইভেন্ট আছে। নতুন বৃদ্ধি থামলে কত সময় লাগবে?', [['20 minutes', '২০ মিনিট'], ['2 minutes', '২ মিনিট'], ['200 hours', '২০০ ঘণ্টা']], 0, '3,600,000 ÷ 3,000 = 1,200 seconds, or 20 minutes.', '৩৬,০০,০০০ ÷ ৩,০০০ = ১,২০০ সেকেন্ড, অর্থাৎ ২০ মিনিট।'),
  ],
  'cap-consistency': [
    Q('cap1', 'What choice does CAP force specifically during a network partition?', 'CAP বিশেষভাবে নেটওয়ার্ক পার্টিশনের সময় কোন পছন্দ বাধ্য করে?', [['Immediate consistency versus availability', 'তাৎক্ষণিক কনসিস্টেন্সি বনাম অ্যাভেইলেবিলিটি'], ['SQL versus NoSQL', 'SQL বনাম NoSQL'], ['Caching versus indexing', 'ক্যাশিং বনাম ইনডেক্সিং']], 0, 'When nodes cannot communicate, a request must be rejected/delayed for consistency or accepted with possible divergence.', 'নোড যোগাযোগ না করলে কনসিস্টেন্সির জন্য রিকোয়েস্ট রিজেক্ট/দেরি হবে, অথবা বিচ্যুতির ঝুঁকিতে গ্রহণ হবে।'),
    Q('cap2', 'A social feed can show posts 30 seconds late during a regional partition. Which behavior fits?', 'আঞ্চলিক পার্টিশনে সোশ্যাল ফিড ৩০ সেকেন্ড পুরোনো পোস্ট দেখাতে পারে। কোন আচরণ মানায়?', [['Serve region-local available reads with eventual consistency', 'ইভেনচুয়াল কনসিস্টেন্সিতে রিজিয়ন-লোকাল অ্যাভেইলেবল রিড'], ['Reject every feed read worldwide', 'বিশ্বব্যাপী প্রতিটি ফিড রিড রিজেক্ট'], ['Synchronously lock every user', 'প্রতি ব্যবহারকারী সিঙ্ক্রোনাস লক']], 0, 'The product accepts staleness, so availability can be prioritized for this operation.', 'পণ্য পুরোনো ডেটা মেনে নেয়, তাই এই অপারেশনে অ্যাভেইলেবিলিটি অগ্রাধিকার পেতে পারে।'),
    Q('cap3', 'Two regions must never independently spend the same account balance. Which direction is safest?', 'দুই অঞ্চল একই অ্যাকাউন্ট ব্যালেন্স স্বাধীনভাবে খরচ করতে পারবে না। কোন দিক নিরাপদ?', [['One consistent authority or quorum that may reject during partition', 'এক কনসিস্টেন্ট অথরিটি বা কোরাম, যা পার্টিশনে রিজেক্ট করতে পারে'], ['Accept both writes and merge money later', 'দুই রাইট গ্রহণ করে পরে অর্থ মার্জ'], ['Use last-write-wins on the balance', 'ব্যালেন্সে লাস্ট-রাইট-উইনস']], 0, 'Money cannot safely fork; delaying or rejecting is preferable to duplicate spending.', 'অর্থ নিরাপদে ভাগ হতে পারে না; ডুপ্লিকেট খরচের চেয়ে দেরি বা রিজেক্ট ভালো।'),
    Q('cap4', 'Two regions concurrently add different items to a cart. What resolution preserves both intentions?', 'দুই অঞ্চল একই সময়ে কার্টে ভিন্ন আইটেম যোগ করে। কোন সমাধান দুই ইনটেন্ট রাখে?', [['Merge operation-based item additions', 'অপারেশন-ভিত্তিক আইটেম অ্যাড মার্জ'], ['Keep only the write with the latest wall-clock millisecond', 'শুধু সর্বশেষ দেয়ালঘড়ির রাইট রাখা'], ['Delete the cart after recovery', 'রিকভারির পর কার্ট ডিলিট']], 0, 'Mergeable operations preserve concurrent additions better than replacing the entire cart state.', 'পুরো কার্ট স্টেট বদলের চেয়ে মার্জযোগ্য অপারেশন কনকারেন্ট অ্যাড ভালো রাখে।'),
    Q('cap5', 'Why is “our company chooses AP” usually an incomplete statement?', '“আমাদের কোম্পানি AP বেছে নিয়েছে” সাধারণত অসম্পূর্ণ কেন?', [['Consistency requirements differ by operation and invariant.', 'প্রতি অপারেশন ও ইনভ্যারিয়েন্টে কনসিস্টেন্সি প্রয়োজন ভিন্ন।'], ['CAP applies only to CSS.', 'CAP শুধু CSS-এ প্রযোজ্য।'], ['Every operation has identical business cost.', 'প্রতি অপারেশনের ব্যবসায়িক খরচ একই।']], 0, 'Feeds, carts, inventory, and payments can rationally make different partition-time choices.', 'ফিড, কার্ট, ইনভেন্টরি ও পেমেন্ট পার্টিশনে যুক্তিযুক্তভাবে ভিন্ন পছন্দ করতে পারে।'),
  ],
  'url-shortener': [
    Q('u1', 'Why is a seven-character Base62 code usually sufficient for 100 million new links/month?', 'মাসে ১০ কোটি নতুন লিংকের জন্য সাত-অক্ষরের Base62 কোড সাধারণত কেন যথেষ্ট?', [['It provides roughly 3.5 trillion combinations.', 'এটি প্রায় ৩.৫ ট্রিলিয়ন কম্বিনেশন দেয়।'], ['It guarantees no collision without a unique constraint.', 'ইউনিক কনস্ট্রেইন্ট ছাড়াই কলিশন না হওয়া নিশ্চিত করে।'], ['It stores the full URL inside seven characters.', 'সাত অক্ষরের ভেতর পূর্ণ URL রাখে।']], 0, 'The keyspace provides large headroom, but creation still needs a unique claim and collision retry.', 'কীস্পেস বড় হেডরুম দেয়, তবে ক্রিয়েশনে ইউনিক ক্লেইম ও কলিশন রিট্রাই দরকার।'),
    Q('u2', 'A destination can be edited and click measurement must remain under service control. Which redirect is safer?', 'গন্তব্য এডিটযোগ্য এবং ক্লিক মাপ সার্ভিস নিয়ন্ত্রণে থাকবে। কোন রিডাইরেক্ট নিরাপদ?', [['302 or 307', '302 বা 307'], ['Permanent 301 cached indefinitely by clients', 'ক্লায়েন্টে অনির্দিষ্টকাল ক্যাশ হওয়া 301'], ['HTTP 500', 'HTTP 500']], 0, 'Temporary redirects keep clients returning to the service; permanent redirects may be cached beyond your control.', 'টেম্পোরারি রিডাইরেক্ট ক্লায়েন্টকে সার্ভিসে ফেরায়; পার্মানেন্ট রিডাইরেক্ট নিয়ন্ত্রণের বাইরে ক্যাশ হতে পারে।'),
    Q('u3', 'One celebrity short link receives a million redirects per minute. What protects origin storage?', 'এক সেলিব্রিটি শর্ট লিংক মিনিটে দশ লক্ষ রিডাইরেক্ট পায়। অরিজিন স্টোরেজ কীভাবে রক্ষা করবেন?', [['Layer edge and distributed caches around the code lookup', 'কোড লুকআপে এজ ও ডিস্ট্রিবিউটেড ক্যাশ স্তর'], ['Write every click synchronously before redirecting', 'রিডাইরেক্টের আগে প্রতিটি ক্লিক সিঙ্ক্রোনাস লিখুন'], ['Move the URL to one larger row', 'URL-কে একটি বড় রোতে নিন']], 0, 'The mapping is highly reusable; caches absorb hot reads while click events can be asynchronous.', 'ম্যাপিং অত্যন্ত পুনঃব্যবহারযোগ্য; ক্যাশ হট রিড নেয়, ক্লিক ইভেন্ট অ্যাসিঙ্ক হতে পারে।'),
    Q('u4', 'Two creators request the same custom alias concurrently. What guarantees one owner?', 'দুই নির্মাতা একই কাস্টম এলিয়াস একসঙ্গে চায়। কী একজন মালিক নিশ্চিত করে?', [['A conditional insert backed by a unique constraint', 'ইউনিক কনস্ট্রেইন্টসহ কন্ডিশনাল ইনসার্ট'], ['Checking in the browser before submit', 'সাবমিটের আগে ব্রাউজারে চেক'], ['Sleeping for one second in both requests', 'দুই রিকোয়েস্টে এক সেকেন্ড স্লিপ']], 0, 'Only an atomic storage claim closes the race between check and create.', 'শুধু অ্যাটমিক স্টোরেজ ক্লেইম চেক ও ক্রিয়েটের রেস বন্ধ করে।'),
    Q('u5', 'Where should click analytics run to preserve redirect latency?', 'রিডাইরেক্ট লেটেন্সি রাখতে ক্লিক অ্যানালিটিক্স কোথায় চলবে?', [['Publish a lightweight event and aggregate asynchronously', 'হালকা ইভেন্ট প্রকাশ ও অ্যাসিঙ্ক অ্যাগ্রিগেশন'], ['Block the redirect until every dashboard aggregate updates', 'সব ড্যাশবোর্ড অ্যাগ্রিগেট আপডেট না হওয়া পর্যন্ত ব্লক'], ['Store analytics in the user browser only', 'শুধু ইউজার ব্রাউজারে অ্যানালিটিক্স রাখা']], 0, 'The redirect critical path needs the mapping and safety decision; analytics is a durable asynchronous side effect.', 'রিডাইরেক্ট ক্রিটিক্যাল পথে ম্যাপিং ও নিরাপত্তা সিদ্ধান্ত দরকার; অ্যানালিটিক্স টেকসই অ্যাসিঙ্ক সাইড ইফেক্ট।'),
  ],
}
