const L = (en, bn) => ({ en, bn })

const calc = (labelEn, labelBn, formula, result, meaningEn, meaningBn) => ({ label: L(labelEn, labelBn), formula, result, meaning: L(meaningEn, meaningBn) })
const api = (method, path, purposeEn, purposeBn) => ({ method, path, purpose: L(purposeEn, purposeBn) })
const field = (name, type, noteEn, noteBn) => ({ name, type, note: L(noteEn, noteBn) })
const failure = (signalEn, signalBn, causeEn, causeBn, mitigationEn, mitigationBn) => ({ signal: L(signalEn, signalBn), cause: L(causeEn, causeBn), mitigation: L(mitigationEn, mitigationBn) })
const decision = (whenEn, whenBn, chooseEn, chooseBn, reasonEn, reasonBn) => ({ when: L(whenEn, whenBn), choose: L(chooseEn, chooseBn), reason: L(reasonEn, reasonBn) })

export const flagshipContent = {
  'system-design': {
    scenario: { title: L('Flash-sale ticket platform', 'ফ্ল্যাশ-সেল টিকিট প্ল্যাটফর্ম'), context: L('Ten million users may arrive for 100,000 tickets. The design must remain responsive, prevent overselling, and degrade safely when demand exceeds supply.', '১ লক্ষ টিকিটের জন্য ১ কোটি ব্যবহারকারী আসতে পারে। ডিজাইনকে দ্রুত থাকতে হবে, অতিরিক্ত বিক্রি ঠেকাতে হবে এবং চাহিদা ক্ষমতা ছাড়ালে নিরাপদে ডিগ্রেড করতে হবে।'), assumptions: [L('Peak: 50,000 requests/second', 'পিক: ৫০,০০০ রিকোয়েস্ট/সেকেন্ড'), L('Inventory correctness is stronger than browsing freshness', 'ব্রাউজিং ফ্রেশনেসের চেয়ে ইনভেন্টরি কারেক্টনেস গুরুত্বপূর্ণ'), L('Target: 99.95% purchase availability', 'লক্ষ্য: ৯৯.৯৫% পারচেজ অ্যাভেইলেবিলিটি')] },
    calculations: [calc('Peak capacity', 'পিক ক্ষমতা', '50,000 RPS ÷ 500 RPS/server', '100 servers', 'Add at least 30% tested headroom.', 'অন্তত ৩০% পরীক্ষিত হেডরুম যোগ করুন।'), calc('Inventory pressure', 'ইনভেন্টরি চাপ', '100,000 tickets ÷ 50,000 attempts/s', '2 seconds', 'Admission control is mandatory; scaling checkout alone is insufficient.', 'অ্যাডমিশন কন্ট্রোল বাধ্যতামূলক; শুধু চেকআউট স্কেল যথেষ্ট নয়।'), calc('Availability budget', 'অ্যাভেইলেবিলিটি বাজেট', '30 days × 0.05%', '21.6 minutes', 'Every dependency must fit inside the shared downtime budget.', 'প্রতিটি নির্ভরতাকে যৌথ ডাউনটাইম বাজেটের মধ্যে থাকতে হবে।')],
    apis: [api('GET', '/events/{id}', 'Serve cacheable event and availability information.', 'ক্যাশযোগ্য ইভেন্ট ও অ্যাভেইলেবিলিটি তথ্য দিন।'), api('POST', '/reservations', 'Create a short inventory hold using an idempotency key.', 'আইডেমপোটেন্সি কী দিয়ে স্বল্পমেয়াদি ইনভেন্টরি হোল্ড তৈরি করুন।'), api('POST', '/orders', 'Convert a valid reservation into one durable order.', 'বৈধ রিজার্ভেশনকে একটি টেকসই অর্ডারে রূপ দিন।')],
    schema: [field('reservation_id', 'UUID', 'Stable key for retries and auditing.', 'রিট্রাই ও অডিটের স্থায়ী কী।'), field('ticket_id', 'BIGINT', 'Inventory item protected by one state transition.', 'একটি স্টেট ট্রানজিশনে সুরক্ষিত ইনভেন্টরি আইটেম।'), field('status', 'ENUM', 'HELD, CONFIRMED, EXPIRED.', 'HELD, CONFIRMED, EXPIRED।'), field('expires_at', 'TIMESTAMP', 'Allows abandoned holds to return safely.', 'পরিত্যক্ত হোল্ড নিরাপদে ফেরত দেয়।')],
    failures: [failure('Checkout latency spikes', 'চেকআউট লেটেন্সি স্পাইক', 'Unbounded admission overwhelms inventory storage.', 'সীমাহীন প্রবেশ ইনভেন্টরি স্টোরেজকে চাপে ফেলে।', 'Virtual waiting room, bounded queues, and load shedding.', 'ভার্চুয়াল ওয়েটিং রুম, সীমিত কিউ ও লোড শেডিং।'), failure('Duplicate orders', 'ডুপ্লিকেট অর্ডার', 'Client retries after a timed-out response.', 'টাইমআউট উত্তরের পর ক্লায়েন্ট রিট্রাই করে।', 'Persist idempotency key and original result atomically.', 'আইডেমপোটেন্সি কী ও মূল ফল অ্যাটমিকভাবে রাখুন।'), failure('Inventory appears available but purchase fails', 'ইনভেন্টরি দেখা যায় কিন্তু কেনা ব্যর্থ', 'Browse cache is fresher than reservation capacity.', 'ব্রাউজ ক্যাশ রিজার্ভেশন ক্ষমতার সঙ্গে মেলে না।', 'Label availability as approximate and validate at reservation.', 'অ্যাভেইলেবিলিটিকে আনুমানিক বলুন এবং রিজার্ভেশনে যাচাই করুন।')],
    decisions: [decision('Early product with one team', 'এক দলসহ প্রাথমিক পণ্য', 'Modular monolith', 'মডিউলার মনোলিথ', 'Fast delivery without distributed operational cost.', 'ডিস্ট্রিবিউটেড অপারেশনাল খরচ ছাড়া দ্রুত ডেলিভারি।'), decision('Inventory correctness path', 'ইনভেন্টরি কারেক্টনেস পথ', 'Synchronous transaction', 'সিঙ্ক্রোনাস ট্রানজ্যাকশন', 'The user must know whether the hold succeeded.', 'হোল্ড সফল হয়েছে কি না ব্যবহারকারীকে জানতে হবে।'), decision('Email and analytics side effects', 'ইমেইল ও অ্যানালিটিক্স সাইড ইফেক্ট', 'Durable asynchronous events', 'টেকসই অ্যাসিঙ্ক ইভেন্ট', 'They should not extend purchase latency.', 'এগুলো পারচেজ লেটেন্সি বাড়ানো উচিত নয়।')],
    checklist: [L('State requirements and peak scale before drawing.', 'আঁকার আগে রিকোয়ারমেন্ট ও পিক স্কেল বলুন।'), L('Mark the source of truth and every cache.', 'সোর্স অব ট্রুথ ও প্রতিটি ক্যাশ চিহ্নিত করুন।'), L('Explain overload behavior, not only normal traffic.', 'শুধু স্বাভাবিক ট্রাফিক নয়, ওভারলোড আচরণ ব্যাখ্যা করুন।')],
  },
  requirements: {
    scenario: { title: L('Food-delivery checkout', 'ফুড-ডেলিভারি চেকআউট'), context: L('Customers browse menus, place orders, pay, and track delivery. Restaurants can reject unavailable items and couriers update location frequently.', 'গ্রাহক মেনু দেখেন, অর্ডার ও পেমেন্ট করেন এবং ডেলিভারি ট্র্যাক করেন। রেস্তোরাঁ অনুপস্থিত আইটেম বাতিল করতে পারে এবং কুরিয়ার ঘনঘন লোকেশন আপডেট করে।'), assumptions: [L('Launch in one city', 'এক শহরে লঞ্চ'), L('10,000 peak concurrent customers', 'পিকে ১০,০০০ সমসাময়িক গ্রাহক'), L('Order loss is unacceptable', 'অর্ডার হারানো গ্রহণযোগ্য নয়')] },
    calculations: [calc('Order traffic', 'অর্ডার ট্রাফিক', '300,000 orders/day ÷ 86,400', '3.5 average OPS', 'Plan peak at 10× average: roughly 35 orders/s.', 'গড়ের ১০ গুণ পিক ধরুন: প্রায় ৩৫ অর্ডার/সেকেন্ড।'), calc('Location updates', 'লোকেশন আপডেট', '5,000 couriers ÷ 5 seconds', '1,000 updates/s', 'Location traffic needs a separate write path from orders.', 'লোকেশন ট্রাফিকের জন্য অর্ডার থেকে আলাদা রাইট পথ দরকার।'), calc('Reliability target', 'রিলায়েবিলিটি লক্ষ্য', '99.9% monthly', '43.2 min downtime', 'Define which order states can continue during provider failure.', 'প্রোভাইডার ব্যর্থতায় কোন অর্ডার স্টেট চলবে তা নির্ধারণ করুন।')],
    apis: [api('GET', '/restaurants?lat=&lng=', 'Find serviceable restaurants near a customer.', 'গ্রাহকের কাছে সেবা দেওয়া রেস্তোরাঁ খুঁজুন।'), api('POST', '/orders', 'Submit items, address, and payment token.', 'আইটেম, ঠিকানা ও পেমেন্ট টোকেন সাবমিট করুন।'), api('PATCH', '/orders/{id}/status', 'Apply an authorized order-state transition.', 'অনুমোদিত অর্ডার স্টেট পরিবর্তন প্রয়োগ করুন।')],
    schema: [field('order_id', 'UUID', 'Public order identifier.', 'পাবলিক অর্ডার আইডি।'), field('restaurant_id', 'UUID', 'Ownership and routing boundary.', 'মালিকানা ও রাউটিং সীমা।'), field('status', 'ENUM', 'Explicit state machine, never a single boolean.', 'স্পষ্ট স্টেট মেশিন, একটি বুলিয়ান নয়।'), field('version', 'INTEGER', 'Optimistic concurrency for competing updates.', 'প্রতিযোগী আপডেটের জন্য অপটিমিস্টিক কনকারেন্সি।')],
    failures: [failure('Paid order missing', 'পেমেন্ট হয়েছে, অর্ডার নেই', 'Payment succeeds before order durability.', 'অর্ডার টেকসই হওয়ার আগে পেমেন্ট সফল।', 'Persist intent first and reconcile provider events.', 'আগে ইনটেন্ট রাখুন এবং প্রোভাইডার ইভেন্ট রিকনসাইল করুন।'), failure('Courier marker jumps backward', 'কুরিয়ার মার্কার পেছনে যায়', 'Out-of-order location updates.', 'আউট-অফ-অর্ডার লোকেশন আপডেট।', 'Include sequence/time and ignore older updates.', 'সিকোয়েন্স/সময় দিন এবং পুরোনো আপডেট বাদ দিন।'), failure('Restaurant accepts unavailable item', 'অনুপস্থিত আইটেম গ্রহণ', 'Menu cache is stale.', 'মেনু ক্যাশ পুরোনো।', 'Revalidate availability when accepting the order.', 'অর্ডার গ্রহণের সময় অ্যাভেইলেবিলিটি যাচাই করুন।')],
    decisions: [decision('Must launch in six weeks', 'ছয় সপ্তাহে লঞ্চ', 'Narrow MVP requirements', 'সীমিত MVP রিকোয়ারমেন্ট', 'Exclude reviews, promotions, and scheduled orders initially.', 'প্রথমে রিভিউ, প্রোমোশন ও শিডিউলড অর্ডার বাদ দিন।'), decision('Order placement', 'অর্ডার প্লেসমেন্ট', 'Strong durable acknowledgement', 'শক্ত টেকসই স্বীকৃতি', 'Users must not lose acknowledged orders.', 'স্বীকৃত অর্ডার হারানো যাবে না।'), decision('Courier location', 'কুরিয়ার লোকেশন', 'Eventually consistent stream', 'ইভেনচুয়ালি কনসিস্টেন্ট স্ট্রিম', 'Fresh approximate position matters more than full history.', 'সম্পূর্ণ ইতিহাসের চেয়ে নতুন আনুমানিক অবস্থান জরুরি।')],
    checklist: [L('Separate functional scope from measurable SLOs.', 'ফাংশনাল স্কোপ ও পরিমাপযোগ্য SLO আলাদা করুন।'), L('Name the consistency requirement per operation.', 'প্রতি অপারেশনের কনসিস্টেন্সি বলুন।'), L('Write explicit out-of-scope items.', 'স্পষ্ট আউট-অফ-স্কোপ আইটেম লিখুন।')],
  },
  estimation: {
    scenario: { title: L('Photo-sharing application', 'ফটো-শেয়ারিং অ্যাপ'), context: L('Estimate traffic, storage, and delivery bandwidth before selecting storage or CDN architecture.', 'স্টোরেজ বা CDN আর্কিটেকচার বাছার আগে ট্রাফিক, স্টোরেজ ও ডেলিভারি ব্যান্ডউইডথ হিসাব করুন।'), assumptions: [L('20 million daily active users', '২ কোটি দৈনিক সক্রিয় ব্যবহারকারী'), L('2 uploads/user/day; 3 MB average', 'প্রতি ব্যবহারকারী ২ আপলোড/দিন; গড় ৩ MB'), L('100 photo views/user/day', 'প্রতি ব্যবহারকারী ১০০ ফটো ভিউ/দিন')] },
    calculations: [calc('Upload RPS', 'আপলোড RPS', '40M uploads ÷ 86,400', '463 average RPS', 'Use a 5× peak factor: about 2,315 upload RPS.', '৫ গুণ পিক ধরুন: প্রায় ২,৩১৫ আপলোড RPS।'), calc('New storage', 'নতুন স্টোরেজ', '40M × 3 MB', '120 TB/day', 'Renditions and replication can multiply this by 2–4×.', 'রেন্ডিশন ও রেপ্লিকেশন এটি ২–৪ গুণ করতে পারে।'), calc('View bandwidth', 'ভিউ ব্যান্ডউইডথ', '2B views × 500 KB ÷ 86,400', '≈11.6 GB/s', 'A CDN is an economic requirement, not decoration.', 'CDN অর্থনৈতিক প্রয়োজন, শুধু সাজসজ্জা নয়।')],
    apis: [api('POST', '/uploads', 'Create an upload session and signed object-store parts.', 'আপলোড সেশন ও সাইনড অবজেক্ট-স্টোর পার্ট তৈরি করুন।'), api('POST', '/uploads/{id}/complete', 'Commit metadata after all parts exist.', 'সব পার্ট থাকার পর মেটাডেটা কমিট করুন।'), api('GET', '/photos/{id}', 'Return metadata and CDN rendition URLs.', 'মেটাডেটা ও CDN রেন্ডিশন URL দিন।')],
    schema: [field('photo_id', 'UUID', 'Stable metadata identifier.', 'স্থায়ী মেটাডেটা আইডি।'), field('object_key', 'TEXT', 'Pointer to immutable original bytes.', 'অপরিবর্তনীয় মূল বাইটের পয়েন্টার।'), field('variants', 'JSONB', 'Dimensions and keys for generated renditions.', 'তৈরি রেন্ডিশনের ডাইমেনশন ও কী।'), field('status', 'ENUM', 'UPLOADING, PROCESSING, READY, FAILED.', 'UPLOADING, PROCESSING, READY, FAILED।')],
    failures: [failure('Storage bill grows unexpectedly', 'স্টোরেজ বিল অপ্রত্যাশিত বাড়ে', 'Originals, variants, and replication were counted once.', 'অরিজিনাল, ভ্যারিয়েন্ট ও রেপ্লিকেশন একবার গোনা হয়েছে।', 'Show every multiplier and retention assumption.', 'প্রতিটি গুণক ও রিটেনশন অনুমান দেখান।'), failure('Peak uploads time out', 'পিক আপলোড টাইমআউট', 'Average RPS was used as capacity.', 'গড় RPS ক্ষমতা হিসেবে ব্যবহৃত।', 'Use peak factor and direct multipart uploads.', 'পিক ফ্যাক্টর ও ডাইরেক্ট মাল্টিপার্ট আপলোড নিন।'), failure('CDN origin overload', 'CDN অরিজিন ওভারলোড', 'Miss traffic and egress were not estimated.', 'মিস ট্রাফিক ও ইগ্রেস হিসাব হয়নি।', 'Estimate hit rate and origin bandwidth separately.', 'হিট রেট ও অরিজিন ব্যান্ডউইডথ আলাদা হিসাব করুন।')],
    decisions: [decision('Early estimate', 'প্রাথমিক হিসাব', 'Round numbers', 'রাউন্ড সংখ্যা', 'Direction matters more than false precision.', 'মিথ্যা নিখুঁততার চেয়ে দিক গুরুত্বপূর্ণ।'), decision('Unknown peak ratio', 'অজানা পিক অনুপাত', 'State a 5–10× assumption', '৫–১০ গুণ অনুমান', 'Makes capacity risk visible and revisable.', 'ক্ষমতার ঝুঁকি দৃশ্যমান ও পরিবর্তনযোগ্য করে।'), decision('Largest number is bandwidth', 'সবচেয়ে বড় সংখ্যা ব্যান্ডউইডথ', 'Prioritize CDN and compression', 'CDN ও কম্প্রেশন অগ্রাধিকার', 'Architecture should follow the dominant cost.', 'আর্কিটেকচার প্রধান খরচ অনুসরণ করবে।')],
    checklist: [L('Write units beside every number.', 'প্রতিটি সংখ্যার পাশে ইউনিট লিখুন।'), L('Separate average from peak.', 'গড় ও পিক আলাদা করুন।'), L('Run a sanity check from a second direction.', 'অন্য দিক থেকে স্যানিটি চেক করুন।')],
  },
  'load-balancing': {
    scenario: { title: L('Global API tier', 'গ্লোবাল API স্তর'), context: L('A stateless API runs across three zones. Deployments, slow instances, and zone loss must not interrupt active users.', 'স্টেটলেস API তিন জোনে চলে। ডিপ্লয়মেন্ট, ধীর ইনস্ট্যান্স ও জোন লস সক্রিয় ব্যবহারকারীকে থামাতে পারবে না।'), assumptions: [L('30,000 peak RPS', 'পিকে ৩০,০০০ RPS'), L('600 healthy RPS per instance', 'প্রতি সুস্থ ইনস্ট্যান্সে ৬০০ RPS'), L('One-zone failure must be tolerated', 'এক জোন ব্যর্থতা সহ্য করতে হবে')] },
    calculations: [calc('Baseline instances', 'বেসলাইন ইনস্ট্যান্স', '30,000 ÷ 600', '50 instances', 'This has no failure headroom.', 'এতে ব্যর্থতার হেডরুম নেই।'), calc('Zone-safe capacity', 'জোন-নিরাপদ ক্ষমতা', '50 ÷ 2 surviving zones × 3', '75 instances', '25 per zone survives the loss of one zone.', 'প্রতি জোনে ২৫টি হলে এক জোন লস সহ্য হয়।'), calc('Connection drain', 'কানেকশন ড্রেইন', 'p99 request 2s × safety 3', '6 seconds minimum', 'Long streams require separate handling.', 'দীর্ঘ স্ট্রিমের আলাদা হ্যান্ডলিং দরকার।')],
    apis: [api('GET', '/health/live', 'Confirm the process is alive without dependencies.', 'নির্ভরতা ছাড়া প্রসেস জীবিত কি না দেখুন।'), api('GET', '/health/ready', 'Confirm the instance can safely receive traffic.', 'ইনস্ট্যান্স নিরাপদে ট্রাফিক নিতে পারে কি না দেখুন।'), api('POST', '/drain', 'Stop new traffic while active requests finish.', 'সক্রিয় রিকোয়েস্ট শেষ হওয়ার সময় নতুন ট্রাফিক বন্ধ করুন।')],
    schema: [field('instance_id', 'TEXT', 'Unique service-discovery member.', 'ইউনিক সার্ভিস-ডিসকভারি সদস্য।'), field('zone', 'TEXT', 'Failure-domain placement.', 'ফেইলিউর-ডোমেইন প্লেসমেন্ট।'), field('weight', 'INTEGER', 'Capacity-aware traffic share.', 'ক্ষমতা-সচেতন ট্রাফিক ভাগ।'), field('state', 'ENUM', 'WARMING, READY, DRAINING, UNHEALTHY.', 'WARMING, READY, DRAINING, UNHEALTHY।')],
    failures: [failure('Healthy endpoint but real requests fail', 'হেলদি এন্ডপয়েন্ট, বাস্তব রিকোয়েস্ট ব্যর্থ', 'Health check tests only the process.', 'হেলথ চেক শুধু প্রসেস পরীক্ষা করে।', 'Separate liveness and readiness; include critical dependencies carefully.', 'লাইভনেস ও রেডিনেস আলাদা করুন; গুরুত্বপূর্ণ নির্ভরতা সতর্কভাবে নিন।'), failure('All users reconnect during deploy', 'ডিপ্লয়ে সব ব্যবহারকারী রিকানেক্ট', 'Instances terminate without draining.', 'ড্রেইন ছাড়া ইনস্ট্যান্স বন্ধ।', 'Remove from discovery, drain, then terminate.', 'ডিসকভারি থেকে সরিয়ে ড্রেইন, তারপর বন্ধ করুন।'), failure('Zone loss overloads survivors', 'জোন লসে বাকি অংশ ওভারলোড', 'Capacity planned only for normal traffic.', 'শুধু স্বাভাবিক ট্রাফিকের ক্ষমতা পরিকল্পিত।', 'Provision and regularly test N-1 capacity.', 'N-1 ক্ষমতা প্রভিশন ও নিয়মিত পরীক্ষা করুন।')],
    decisions: [decision('Uniform short requests', 'সমান ছোট রিকোয়েস্ট', 'Least connections or round robin', 'লিস্ট কানেকশন বা রাউন্ড রবিন', 'Both distribute stateless work simply.', 'দুটিই স্টেটলেস কাজ সহজে ভাগ করে।'), decision('Instances have different capacity', 'ইনস্ট্যান্স ক্ষমতা ভিন্ন', 'Weighted least load', 'ওয়েটেড লিস্ট লোড', 'Traffic share should match measured capacity.', 'ট্রাফিক ভাগ পরিমাপ করা ক্ষমতার সঙ্গে মিলবে।'), decision('Session data exists', 'সেশন ডেটা আছে', 'Externalize session state', 'সেশন স্টেট বাইরে রাখুন', 'Avoid sticky-session failover and imbalance.', 'স্টিকি-সেশন ফেইলওভার ও অসমতা এড়ান।')],
    checklist: [L('Name L4 versus L7 responsibilities.', 'L4 ও L7 দায়িত্ব বলুন।'), L('Show health, draining, and zone failure.', 'হেলথ, ড্রেইনিং ও জোন ব্যর্থতা দেখান।'), L('Calculate N-1 capacity.', 'N-1 ক্ষমতা হিসাব করুন।')],
  },
  caching: {
    scenario: { title: L('Product catalog cache', 'প্রোডাক্ট ক্যাটালগ ক্যাশ'), context: L('A catalog serves millions of reads while price and stock changes must become visible within seconds.', 'ক্যাটালগ লক্ষ লক্ষ রিড দেয়, তবে মূল্য ও স্টক পরিবর্তন কয়েক সেকেন্ডে দৃশ্যমান হতে হবে।'), assumptions: [L('20,000 peak reads/s', 'পিকে ২০,০০০ রিড/সেকেন্ড'), L('500 writes/s', '৫০০ রাইট/সেকেন্ড'), L('Price staleness ≤ 5 seconds', 'মূল্যের পুরোনো থাকা ≤ ৫ সেকেন্ড')] },
    calculations: [calc('Database reads', 'ডেটাবেস রিড', '20,000 × (1 − 0.95 hit rate)', '1,000 reads/s', 'A 95% hit rate removes 19,000 reads/s.', '৯৫% হিট রেট ১৯,০০০ রিড/সেকেন্ড সরায়।'), calc('Cache memory', 'ক্যাশ মেমরি', '5M hot items × 2 KB × 1.3 overhead', '≈13 GB', 'Plan replication and eviction above raw value size.', 'কাঁচা ভ্যালু সাইজের ওপর রেপ্লিকেশন ও ইভিকশন ধরুন।'), calc('Stampede risk', 'স্ট্যাম্পিড ঝুঁকি', '10k simultaneous misses × 8 ms query', '80 DB-seconds', 'One expired hot key can saturate storage.', 'একটি মেয়াদোত্তীর্ণ হট কী স্টোরেজ স্যাচুরেট করতে পারে।')],
    apis: [api('GET', '/products/{id}', 'Read through cache using product ID and version.', 'প্রোডাক্ট ID ও ভার্সন দিয়ে ক্যাশ থেকে পড়ুন।'), api('PATCH', '/products/{id}/price', 'Commit source-of-truth update and publish invalidation.', 'সোর্স-অফ-ট্রুথ আপডেট ও ইনভ্যালিডেশন প্রকাশ করুন।'), api('POST', '/cache/invalidate', 'Internal idempotent invalidation event.', 'অভ্যন্তরীণ আইডেমপোটেন্ট ইনভ্যালিডেশন ইভেন্ট।')],
    schema: [field('cache_key', 'TEXT', 'Include entity ID and representation version.', 'এনটিটি ID ও রিপ্রেজেন্টেশন ভার্সন রাখুন।'), field('payload', 'BINARY', 'Compact serialized product response.', 'কমপ্যাক্ট সিরিয়ালাইজড প্রোডাক্ট উত্তর।'), field('source_version', 'BIGINT', 'Reject older invalidations and fills.', 'পুরোনো ইনভ্যালিডেশন ও ফিল বাতিল করুন।'), field('expires_at', 'TIMESTAMP', 'Backstop when invalidation is missed.', 'ইনভ্যালিডেশন মিস হলে ব্যাকস্টপ।')],
    failures: [failure('Database spike at the top of each hour', 'প্রতি ঘণ্টার শুরুতে DB স্পাইক', 'Many keys share one TTL boundary.', 'অনেক কী একই TTL সীমা ভাগ করে।', 'Add TTL jitter and single-flight request coalescing.', 'TTL জিটার ও সিঙ্গেল-ফ্লাইট রিকোয়েস্ট কোয়ালেসিং দিন।'), failure('Old value returns after update', 'আপডেটের পর পুরোনো মান ফেরে', 'Slow cache fill races with invalidation.', 'ধীর ক্যাশ ফিল ইনভ্যালিডেশনের সঙ্গে রেস করে।', 'Use version checks or delete after database commit.', 'ভার্সন চেক বা DB কমিটের পর ডিলিট করুন।'), failure('Cache outage becomes site outage', 'ক্যাশ আউটেজে সাইট আউটেজ', 'Database cannot absorb miss traffic.', 'ডেটাবেস মিস ট্রাফিক নিতে পারে না।', 'Rate-limit fallthrough, serve stale data, and recover gradually.', 'ফলথ্রু রেট-লিমিট, পুরোনো ডেটা সার্ভ ও ধীরে রিকভার করুন।')],
    decisions: [decision('Read-heavy, tolerates brief staleness', 'রিড-হেভি, সামান্য পুরোনো মান চলে', 'Cache-aside', 'ক্যাশ-অ্যাসাইড', 'Simple ownership and lazy population.', 'সহজ মালিকানা ও লেজি পপুলেশন।'), decision('Every write must update cache', 'প্রতি রাইটে ক্যাশ আপডেট', 'Write-through', 'রাইট-থ্রু', 'Predictable cache contents at higher write latency.', 'বেশি রাইট লেটেন্সিতে পূর্বানুমানযোগ্য ক্যাশ।'), decision('Cache is unavailable', 'ক্যাশ অনুপস্থিত', 'Bounded fallback plus stale serving', 'সীমিত ফলব্যাক ও পুরোনো সার্ভিং', 'Protect the database from a cascading miss storm.', 'ক্যাসকেডিং মিস স্টর্ম থেকে DB রক্ষা করুন।')],
    checklist: [L('State cache key, value, TTL, and owner.', 'ক্যাশ কী, ভ্যালু, TTL ও মালিক বলুন।'), L('Design invalidation before claiming the latency win.', 'লেটেন্সি লাভের আগে ইনভ্যালিডেশন ডিজাইন করুন।'), L('Explain stampede and cache-outage behavior.', 'স্ট্যাম্পিড ও ক্যাশ-আউটেজ আচরণ ব্যাখ্যা করুন।')],
  },
}

// Additional flagship records are kept separate so lesson rendering stays data-driven.
export const flagshipContentPartTwo = {
  'sql-nosql': {
    scenario: { title: L('Commerce data platform', 'কমার্স ডেটা প্ল্যাটফর্ম'), context: L('Orders need transactions and auditability; product attributes vary; click events arrive at high volume.', 'অর্ডারে ট্রানজ্যাকশন ও অডিট দরকার; পণ্যের বৈশিষ্ট্য ভিন্ন; ক্লিক ইভেন্ট উচ্চ ভলিউমে আসে।'), assumptions: [L('2,000 order writes/s peak', 'পিকে ২,০০০ অর্ডার রাইট/সেকেন্ড'), L('50,000 catalog reads/s', '৫০,০০০ ক্যাটালগ রিড/সেকেন্ড'), L('500,000 click events/s', '৫,০০,০০০ ক্লিক ইভেন্ট/সেকেন্ড')] },
    calculations: [calc('Order storage', 'অর্ডার স্টোরেজ', '10M orders/month × 4 KB', '40 GB/month', 'Indexes and replicas commonly add 2–4×.', 'ইনডেক্স ও রেপ্লিকা সাধারণত ২–৪ গুণ যোগ করে।'), calc('Event volume', 'ইভেন্ট ভলিউম', '500k/s × 300 B', '150 MB/s', 'Do not force analytics events through the order database.', 'অ্যানালিটিক্স ইভেন্ট অর্ডার ডেটাবেসে দেবেন না।'), calc('Catalog partition', 'ক্যাটালগ পার্টিশন', '100M products ÷ 20 shards', '5M products/shard', 'Validate distribution against seller and category queries.', 'বিক্রেতা ও ক্যাটাগরি কুয়েরির সঙ্গে বণ্টন যাচাই করুন।')],
    apis: [api('POST', '/orders', 'Transactional creation of order and line items.', 'অর্ডার ও লাইন আইটেমের ট্রানজ্যাকশনাল তৈরি।'), api('GET', '/products/{id}', 'Flexible catalog document read.', 'ফ্লেক্সিবল ক্যাটালগ ডকুমেন্ট রিড।'), api('POST', '/events/batch', 'Append immutable behavioral events.', 'অপরিবর্তনীয় আচরণগত ইভেন্ট ব্যাচ যোগ করুন।')],
    schema: [field('orders', 'RELATIONAL', 'Constraints, transactions, and joins protect money.', 'কনস্ট্রেইন্ট, ট্রানজ্যাকশন ও জয়েন অর্থ রক্ষা করে।'), field('products', 'DOCUMENT', 'Variable category-specific attributes.', 'ভিন্ন ক্যাটাগরি-নির্দিষ্ট বৈশিষ্ট্য।'), field('events', 'LOG/COLUMNAR', 'Append-heavy analytics and scans.', 'অ্যাপেন্ড-হেভি অ্যানালিটিক্স ও স্ক্যান।'), field('search', 'INVERTED INDEX', 'Text retrieval and relevance ranking.', 'টেক্সট রিট্রিভাল ও প্রাসঙ্গিকতা র‍্যাঙ্কিং।')],
    failures: [failure('Order total disagrees with line items', 'অর্ডার টোটাল ও লাইন আইটেম মেলে না', 'Invariant lives only in application code.', 'ইনভ্যারিয়েন্ট শুধু অ্যাপ কোডে।', 'Use database constraints and one transaction.', 'DB কনস্ট্রেইন্ট ও একটি ট্রানজ্যাকশন নিন।'), failure('Catalog query scans every document', 'ক্যাটালগ কুয়েরি সব ডকুমেন্ট স্ক্যান', 'Database chosen before access patterns.', 'অ্যাক্সেস প্যাটার্নের আগে DB বাছা।', 'List top queries and build purpose-specific indexes.', 'প্রধান কুয়েরি লিখে উদ্দেশ্যভিত্তিক ইনডেক্স বানান।'), failure('One database becomes every workload', 'এক DB সব ওয়ার্কলোড', 'Operational simplicity was mistaken for universal fit.', 'অপারেশনাল সরলতাকে সর্বজনীন উপযোগ ধরা।', 'Keep the transactional core; add stores only for measured needs.', 'ট্রানজ্যাকশনাল কোর রাখুন; মাপা প্রয়োজনে স্টোর যোগ করুন।')],
    decisions: [decision('Money and inventory invariants', 'অর্থ ও ইনভেন্টরি ইনভ্যারিয়েন্ট', 'Relational SQL', 'রিলেশনাল SQL', 'Transactions and constraints are first-class.', 'ট্রানজ্যাকশন ও কনস্ট্রেইন্ট প্রথম শ্রেণির।'), decision('Variable product attributes', 'পরিবর্তনশীল পণ্য বৈশিষ্ট্য', 'Document model', 'ডকুমেন্ট মডেল', 'Aggregate-shaped reads and flexible fields fit.', 'অ্যাগ্রিগেট-আকৃতির রিড ও ফ্লেক্সিবল ফিল্ড মানায়।'), decision('High-volume immutable events', 'উচ্চ-ভলিউম অপরিবর্তনীয় ইভেন্ট', 'Log then analytical store', 'লগ, তারপর অ্যানালিটিক্যাল স্টোর', 'Separate ingestion from later queries.', 'ইনজেশন ও পরবর্তী কুয়েরি আলাদা করুন।')],
    checklist: [L('Start with access patterns and invariants.', 'অ্যাক্সেস প্যাটার্ন ও ইনভ্যারিয়েন্ট দিয়ে শুরু করুন।'), L('Use polyglot storage only with operational ownership.', 'অপারেশনাল মালিকানা থাকলেই পলিগ্লট স্টোরেজ নিন।'), L('Explain migration and source-of-truth boundaries.', 'মাইগ্রেশন ও সোর্স-অফ-ট্রুথ সীমা বলুন।')],
  },
  'replication-sharding': {
    scenario: { title: L('Global customer profiles', 'গ্লোবাল কাস্টমার প্রোফাইল'), context: L('Profiles must survive node failure and scale beyond one database while preserving user-local reads.', 'প্রোফাইলকে নোড ব্যর্থতা সহ্য ও এক DB-এর বাইরে স্কেল করতে হবে, সঙ্গে ব্যবহারকারী-লোকাল রিড রাখতে হবে।'), assumptions: [L('500 million profiles', '৫০ কোটি প্রোফাইল'), L('8 KB average profile', 'গড় প্রোফাইল ৮ KB'), L('95% reads; users access their own profile', '৯৫% রিড; ব্যবহারকারী নিজের প্রোফাইল দেখেন')] },
    calculations: [calc('Raw data', 'কাঁচা ডেটা', '500M × 8 KB', '4 TB', 'Three replicas plus indexes can exceed 15 TB.', 'তিন রেপ্লিকা ও ইনডেক্স ১৫ TB ছাড়াতে পারে।'), calc('Shard count', 'শার্ড সংখ্যা', '4 TB ÷ 250 GB target', '16 shards minimum', 'Use 32–64 logical shards for growth and movement.', 'বৃদ্ধি ও স্থানান্তরের জন্য ৩২–৬৪ লজিক্যাল শার্ড নিন।'), calc('Replica lag exposure', 'রেপ্লিকা ল্যাগ এক্সপোজার', '2 seconds × 10k writes/s', '20k pending writes', 'Read-your-write routing matters after profile updates.', 'প্রোফাইল আপডেটের পর read-your-write রাউটিং জরুরি।')],
    apis: [api('GET', '/profiles/{userId}', 'Route by stable user shard key.', 'স্থায়ী ইউজার শার্ড কী দিয়ে রাউট করুন।'), api('PATCH', '/profiles/{userId}', 'Write to leader and return source version.', 'লিডারে লিখে সোর্স ভার্সন দিন।'), api('GET', '/profiles/{userId}?minVersion=', 'Avoid a replica older than the client write.', 'ক্লায়েন্ট রাইটের চেয়ে পুরোনো রেপ্লিকা এড়ান।')],
    schema: [field('user_id', 'UUID', 'High-cardinality stable shard key.', 'উচ্চ-কার্ডিনালিটি স্থায়ী শার্ড কী।'), field('profile_blob', 'JSONB', 'User-owned aggregate.', 'ব্যবহারকারী-মালিকানাধীন অ্যাগ্রিগেট।'), field('version', 'BIGINT', 'Monotonic conflict and freshness marker.', 'মনোটনিক কনফ্লিক্ট ও ফ্রেশনেস মার্কার।'), field('home_region', 'TEXT', 'Placement and residency hint.', 'প্লেসমেন্ট ও রেসিডেন্সি হিন্ট।')],
    failures: [failure('User cannot find recent update', 'সাম্প্রতিক আপডেট দেখা যায় না', 'Immediate read went to a lagging replica.', 'তাৎক্ষণিক রিড ল্যাগিং রেপ্লিকায় গেছে।', 'Use leader read, session stickiness, or minimum version.', 'লিডার রিড, সেশন স্টিকিনেস বা মিনিমাম ভার্সন নিন।'), failure('One shard is much larger', 'এক শার্ড অনেক বড়', 'Shard key correlates with a hot tenant or geography.', 'শার্ড কী হট টেন্যান্ট বা ভূগোলের সঙ্গে সম্পর্কিত।', 'Hash stable IDs and isolate exceptional tenants.', 'স্থায়ী ID হ্যাশ ও ব্যতিক্রমী টেন্যান্ট আলাদা করুন।'), failure('Resharding blocks writes', 'রিশার্ডিং রাইট বন্ধ করে', 'Physical placement equals logical shard identity.', 'ফিজিক্যাল প্লেসমেন্টই লজিক্যাল শার্ড পরিচয়।', 'Use logical shards and online dual-read/cutover.', 'লজিক্যাল শার্ড ও অনলাইন ডুয়াল-রিড/কাটওভার নিন।')],
    decisions: [decision('Need read scale and availability', 'রিড স্কেল ও অ্যাভেইলেবিলিটি দরকার', 'Replication', 'রেপ্লিকেশন', 'Copies improve reads and failover, not write capacity.', 'কপি রিড ও ফেইলওভার বাড়ায়, রাইট ক্ষমতা নয়।'), decision('Dataset/write load exceeds one primary', 'ডেটাসেট/রাইট এক প্রাইমারি ছাড়ায়', 'Sharding', 'শার্ডিং', 'Divide ownership and write capacity.', 'মালিকানা ও রাইট ক্ষমতা ভাগ করুন।'), decision('Cross-user query is common', 'ক্রস-ইউজার কুয়েরি সাধারণ', 'Separate index/aggregation path', 'আলাদা ইনডেক্স/অ্যাগ্রিগেশন পথ', 'Avoid scatter-gather across every shard.', 'সব শার্ডে স্ক্যাটার-গ্যাদার এড়ান।')],
    checklist: [L('Say whether you need copies or division.', 'কপি নাকি বিভাজন দরকার বলুন।'), L('Prove the shard key distributes and localizes queries.', 'শার্ড কী বণ্টন ও লোকাল কুয়েরি প্রমাণ করুন।'), L('Describe lag, failover, and resharding.', 'ল্যাগ, ফেইলওভার ও রিশার্ডিং বলুন।')],
  },
  messaging: {
    scenario: { title: L('Checkout event pipeline', 'চেকআউট ইভেন্ট পাইপলাইন'), context: L('Order placement must trigger inventory, email, fraud, analytics, and fulfillment without coupling checkout latency to every consumer.', 'অর্ডার প্লেসমেন্ট ইনভেন্টরি, ইমেইল, ফ্রড, অ্যানালিটিক্স ও ফুলফিলমেন্ট চালাবে—চেকআউট লেটেন্সি সব কনজিউমারের সঙ্গে বাঁধা যাবে না।'), assumptions: [L('5,000 orders/s peak', 'পিকে ৫,০০০ অর্ডার/সেকেন্ড'), L('Five independent consumers', 'পাঁচ স্বাধীন কনজিউমার'), L('No acknowledged order event may be lost', 'স্বীকৃত অর্ডার ইভেন্ট হারানো যাবে না')] },
    calculations: [calc('Event ingress', 'ইভেন্ট ইনগ্রেস', '5,000 × 2 KB', '10 MB/s', 'Replication and retention determine broker disk.', 'রেপ্লিকেশন ও রিটেনশন ব্রোকার ডিস্ক নির্ধারণ করে।'), calc('Backlog recovery', 'ব্যাকলগ রিকভারি', '3.6M events ÷ (8k consume − 5k produce)', '20 minutes', 'Consumer capacity must exceed producer rate after recovery.', 'রিকভারির পর কনজিউমার ক্ষমতা প্রোডিউসার হারের বেশি হবে।'), calc('Partition count', 'পার্টিশন সংখ্যা', '5,000/s ÷ 500/s per consumer lane', '10+ partitions', 'Add headroom and choose an ordering key.', 'হেডরুম ও অর্ডারিং কী যোগ করুন।')],
    apis: [api('POST', '/orders', 'Commit order and outbox record atomically.', 'অর্ডার ও আউটবক্স রেকর্ড অ্যাটমিকভাবে কমিট করুন।'), api('EVENT', 'order.created.v1', 'Versioned immutable fact for consumers.', 'কনজিউমারের জন্য ভার্সনড অপরিবর্তনীয় ফ্যাক্ট।'), api('POST', '/consumers/{name}/replay', 'Controlled replay from a durable offset.', 'টেকসই অফসেট থেকে নিয়ন্ত্রিত রিপ্লে।')],
    schema: [field('event_id', 'UUID', 'Deduplication and tracing identity.', 'ডিডুপ্লিকেশন ও ট্রেসিং পরিচয়।'), field('aggregate_id', 'UUID', 'Order key for partition-local ordering.', 'পার্টিশন-লোকাল অর্ডারিংয়ের অর্ডার কী।'), field('event_type', 'TEXT', 'Stable versioned contract name.', 'স্থায়ী ভার্সনড কনট্র্যাক্ট নাম।'), field('payload', 'JSON', 'Immutable event data, not current mutable state.', 'বর্তমান পরিবর্তনশীল স্টেট নয়, অপরিবর্তনীয় ইভেন্ট ডেটা।')],
    failures: [failure('Order exists but no event', 'অর্ডার আছে, ইভেন্ট নেই', 'Database commit and broker publish are separate.', 'DB কমিট ও ব্রোকার পাবলিশ আলাদা।', 'Transactional outbox plus relay.', 'ট্রানজ্যাকশনাল আউটবক্স ও রিলে।'), failure('Consumer applies side effect twice', 'কনজিউমার দুবার সাইড ইফেক্ট দেয়', 'At-least-once delivery after acknowledgement loss.', 'অ্যাকনলেজমেন্ট হারিয়ে at-least-once ডেলিভারি।', 'Inbox/dedup table keyed by event ID.', 'ইভেন্ট ID-ভিত্তিক ইনবক্স/ডিডুপ টেবিল।'), failure('Poison event blocks a partition', 'পয়জন ইভেন্ট পার্টিশন আটকায়', 'Infinite retry on non-retryable data.', 'নন-রিট্রাইযোগ্য ডেটায় অনন্ত রিট্রাই।', 'Bound retries, dead-letter with alert, and replay tools.', 'রিট্রাই সীমা, অ্যালার্টসহ ডেড-লেটার ও রিপ্লে টুল।')],
    decisions: [decision('Exactly one worker should process a job', 'এক ওয়ার্কার কাজ করবে', 'Work queue', 'ওয়ার্ক কিউ', 'Competing consumers divide tasks.', 'প্রতিযোগী কনজিউমার কাজ ভাগ করে।'), decision('Many services react independently', 'অনেক সার্ভিস স্বাধীনভাবে প্রতিক্রিয়া দেয়', 'Pub/Sub or stream', 'পাব/সাব বা স্ট্রিম', 'Each consumer gets its own durable position.', 'প্রতি কনজিউমার নিজস্ব টেকসই অবস্থান পায়।'), decision('Replay and ordered history matter', 'রিপ্লে ও অর্ডারড ইতিহাস জরুরি', 'Partitioned event log', 'পার্টিশনড ইভেন্ট লগ', 'Retention and offsets preserve history.', 'রিটেনশন ও অফসেট ইতিহাস রাখে।')],
    checklist: [L('Define delivery and ordering scope.', 'ডেলিভারি ও অর্ডারিং সীমা বলুন।'), L('Show outbox, idempotent consumer, and DLQ.', 'আউটবক্স, আইডেমপোটেন্ট কনজিউমার ও DLQ দেখান।'), L('Calculate backlog recovery time.', 'ব্যাকলগ রিকভারি সময় হিসাব করুন।')],
  },
  'cap-consistency': {
    scenario: { title: L('Cart, feed, and payment under partition', 'পার্টিশনে কার্ট, ফিড ও পেমেন্ট'), context: L('Different operations in one product need different behavior when regions cannot communicate.', 'এক পণ্যের ভিন্ন অপারেশনে অঞ্চল যোগাযোগ না করলে ভিন্ন আচরণ দরকার।'), assumptions: [L('Two active regions', 'দুই সক্রিয় অঞ্চল'), L('Partitions are rare but unavoidable', 'পার্টিশন বিরল কিন্তু অনিবার্য'), L('Business impact differs per operation', 'প্রতি অপারেশনে ব্যবসায়িক প্রভাব ভিন্ন')] },
    calculations: [calc('Partition window', 'পার্টিশন সময়', '8 minutes × 2,000 cart writes/s', '960k writes', 'Conflict handling must be a designed workflow.', 'কনফ্লিক্ট হ্যান্ডলিং ডিজাইন করা ওয়ার্কফ্লো হতে হবে।'), calc('Payment risk', 'পেমেন্ট ঝুঁকি', '0.1% duplicate × 100k payments', '100 incidents', 'Small inconsistency rates can be unacceptable for money.', 'অর্থে ছোট অসামঞ্জস্য হারও অগ্রহণযোগ্য।'), calc('Feed freshness', 'ফিড ফ্রেশনেস', '30-second replication lag', 'Acceptable by product', 'Availability can win when stale data has low cost.', 'পুরোনো ডেটার খরচ কম হলে অ্যাভেইলেবিলিটি জিততে পারে।')],
    apis: [api('PUT', '/carts/{id}/items/{sku}', 'Mergeable quantity update with operation ID.', 'অপারেশন ID-সহ মার্জযোগ্য পরিমাণ আপডেট।'), api('GET', '/feeds/{userId}', 'Serve region-local eventually consistent feed.', 'রিজিয়ন-লোকাল ইভেনচুয়ালি কনসিস্টেন্ট ফিড।'), api('POST', '/payments', 'Route to one authoritative ledger region.', 'এক অথরিটেটিভ লেজার অঞ্চলে রাউট করুন।')],
    schema: [field('operation_id', 'UUID', 'Deduplicate repeated client intent.', 'পুনরাবৃত্ত ক্লায়েন্ট ইনটেন্ট ডিডুপ করুন।'), field('logical_version', 'VECTOR/HLC', 'Detect concurrent updates without wall-clock trust.', 'দেয়ালঘড়ি ছাড়া কনকারেন্ট আপডেট ধরুন।'), field('home_region', 'TEXT', 'Authority and routing boundary.', 'অথরিটি ও রাউটিং সীমা।'), field('conflict_state', 'JSON', 'Preserve information when automatic merge is unsafe.', 'অটো মার্জ অনিরাপদ হলে তথ্য রাখুন।')],
    failures: [failure('Cart item disappears after recovery', 'রিকভারির পর কার্ট আইটেম হারায়', 'Last-write-wins discarded a concurrent add.', 'লাস্ট-রাইট-উইনস কনকারেন্ট অ্যাড বাদ দিয়েছে।', 'Use operation-based merge or CRDT-style set semantics.', 'অপারেশন-ভিত্তিক মার্জ বা CRDT-স্টাইল সেট নিন।'), failure('Payment accepted twice in two regions', 'দুই অঞ্চলে পেমেন্ট দুবার গ্রহণ', 'Both sides remained writable without one authority.', 'এক অথরিটি ছাড়া দুই পাশ রাইটযোগ্য ছিল।', 'Single-writer routing or quorum rejection.', 'সিঙ্গেল-রাইটার রাউটিং বা কোরাম রিজেকশন।'), failure('System rejects harmless feed reads', 'সিস্টেম নিরীহ ফিড রিড প্রত্যাখ্যান করে', 'One global consistency policy was applied everywhere.', 'এক গ্লোবাল কনসিস্টেন্সি নীতি সর্বত্র।', 'Choose consistency per operation and business invariant.', 'প্রতি অপারেশন ও ব্যবসায়িক ইনভ্যারিয়েন্টে নীতি বাছুন।')],
    decisions: [decision('Stale feed is acceptable', 'পুরোনো ফিড গ্রহণযোগ্য', 'Available local reads', 'অ্যাভেইলেবল লোকাল রিড', 'The business cost of staleness is low.', 'পুরোনো থাকার ব্যবসায়িক খরচ কম।'), decision('Cart additions should survive', 'কার্ট অ্যাড টিকে থাকবে', 'Mergeable operations', 'মার্জযোগ্য অপারেশন', 'Preserve both concurrent intents.', 'দুই কনকারেন্ট ইনটেন্টই রাখুন।'), decision('Money cannot fork', 'অর্থ ভাগ হতে পারবে না', 'Consistent authority', 'কনসিস্টেন্ট অথরিটি', 'Reject or delay rather than create duplicate value.', 'ডুপ্লিকেট মূল্য তৈরির চেয়ে রিজেক্ট বা দেরি করুন।')],
    checklist: [L('CAP choices happen during partition, not every normal request.', 'CAP পছন্দ পার্টিশনের সময়, প্রতিটি স্বাভাবিক রিকোয়েস্টে নয়।'), L('Choose per operation, not per company.', 'কোম্পানি নয়, প্রতি অপারেশনে বাছুন।'), L('Explain conflict detection and resolution.', 'কনফ্লিক্ট শনাক্ত ও সমাধান বলুন।')],
  },
  'url-shortener': {
    scenario: { title: L('Global short-link service', 'গ্লোবাল শর্ট-লিংক সার্ভিস'), context: L('Create compact links and redirect globally with low latency, abuse controls, expiration, and click analytics.', 'ছোট লিংক তৈরি ও কম লেটেন্সিতে বিশ্বব্যাপী রিডাইরেক্ট করুন, সঙ্গে অপব্যবহার নিয়ন্ত্রণ, মেয়াদ ও ক্লিক অ্যানালিটিক্স।'), assumptions: [L('100M new links/month', 'মাসে ১০ কোটি নতুন লিংক'), L('10B redirects/month', 'মাসে ১,০০০ কোটি রিডাইরেক্ট'), L('p99 redirect < 80 ms', 'p99 রিডাইরেক্ট < ৮০ ms')] },
    calculations: [calc('Create RPS', 'ক্রিয়েট RPS', '100M ÷ 2.6M seconds', '≈39 average RPS', 'Even a 10× peak is modest.', '১০ গুণ পিকও মাঝারি।'), calc('Redirect RPS', 'রিডাইরেক্ট RPS', '10B ÷ 2.6M seconds', '≈3,850 average RPS', 'Plan 10× peak and edge-cache hot keys.', '১০ গুণ পিক ও এজ-ক্যাশ হট কী ধরুন।'), calc('Key space', 'কী স্পেস', 'Base62^7', '≈3.5 trillion keys', 'Seven characters provide comfortable headroom.', 'সাত অক্ষর যথেষ্ট হেডরুম দেয়।')],
    apis: [api('POST', '/v1/links', 'Create a random or custom short code idempotently.', 'র‍্যান্ডম বা কাস্টম শর্ট কোড আইডেমপোটেন্টভাবে তৈরি করুন।'), api('GET', '/{code}', 'Return 301/302 redirect after cache and safety checks.', 'ক্যাশ ও নিরাপত্তা পরীক্ষার পর 301/302 রিডাইরেক্ট দিন।'), api('DELETE', '/v1/links/{code}', 'Disable an owned link and invalidate caches.', 'মালিকানাধীন লিংক বন্ধ ও ক্যাশ ইনভ্যালিডেট করুন।')],
    schema: [field('short_code', 'VARCHAR(10)', 'Primary lookup and partition key.', 'প্রধান লুকআপ ও পার্টিশন কী।'), field('long_url', 'TEXT', 'Validated destination with scheme policy.', 'স্কিম নীতিসহ যাচাইকৃত গন্তব্য।'), field('owner_id', 'UUID?', 'Optional ownership and quota boundary.', 'ঐচ্ছিক মালিকানা ও কোটা সীমা।'), field('expires_at', 'TIMESTAMP?', 'Cleanup and redirect policy.', 'ক্লিনআপ ও রিডাইরেক্ট নীতি।')],
    failures: [failure('Two links receive one code', 'দুই লিংকে এক কোড', 'Insufficient entropy or non-atomic custom alias claim.', 'কম এনট্রপি বা নন-অ্যাটমিক কাস্টম এলিয়াস ক্লেইম।', 'Unique constraint plus retry; conditional create for aliases.', 'ইউনিক কনস্ট্রেইন্ট ও রিট্রাই; এলিয়াসে কন্ডিশনাল ক্রিয়েট।'), failure('Disabled malicious link still works', 'বন্ধ ক্ষতিকর লিংক এখনও চলে', 'Long edge-cache TTL without revocation path.', 'রিভোকেশন ছাড়া দীর্ঘ এজ-ক্যাশ TTL।', 'Push invalidation and maintain short negative deny cache.', 'ইনভ্যালিডেশন পুশ ও ছোট নেগেটিভ ডিনাই ক্যাশ রাখুন।'), failure('Popular link overloads one shard', 'জনপ্রিয় লিংক এক শার্ড ওভারলোড করে', 'Every redirect reaches origin storage.', 'প্রতি রিডাইরেক্ট অরিজিন স্টোরেজে যায়।', 'Layer browser/edge/distributed caches; async click events.', 'ব্রাউজার/এজ/ডিস্ট্রিবিউটেড ক্যাশ স্তর; অ্যাসিঙ্ক ক্লিক ইভেন্ট।')],
    decisions: [decision('Opaque public links', 'অস্বচ্ছ পাবলিক লিংক', 'Random Base62 code', 'র‍্যান্ডম Base62 কোড', 'Avoid central counters and easy enumeration.', 'কেন্দ্রীয় কাউন্টার ও সহজ অনুমান এড়ান।'), decision('Permanent canonical mapping', 'স্থায়ী ক্যানোনিক্যাল ম্যাপিং', '301 with careful cache policy', 'সতর্ক ক্যাশ নীতিসহ 301', 'Clients may cache it beyond your control.', 'ক্লায়েন্ট আপনার নিয়ন্ত্রণের বাইরে ক্যাশ করতে পারে।'), decision('Editable or measurable destination', 'এডিটযোগ্য বা পরিমাপযোগ্য গন্তব্য', '302/307', '302/307', 'Keeps redirect control at the service.', 'রিডাইরেক্ট নিয়ন্ত্রণ সার্ভিসে রাখে।')],
    checklist: [L('Estimate create and redirect traffic separately.', 'ক্রিয়েট ও রিডাইরেক্ট ট্রাফিক আলাদা হিসাব করুন।'), L('Show key generation, collision handling, and abuse controls.', 'কী তৈরি, কলিশন ও অপব্যবহার নিয়ন্ত্রণ দেখান।'), L('Move click analytics off the redirect path.', 'ক্লিক অ্যানালিটিক্স রিডাইরেক্ট পথ থেকে সরান।')],
  },
}

export const allFlagshipContent = { ...flagshipContent, ...flagshipContentPartTwo }
